### ISSUE TITLE
A webworkify equivalent with Rollup

### ISSUE THREAD

**Issue by mourner** [rollup/rollup#1029]
I've been exploring the possibility of switching from CommonJS + Browserify to ES6 Modules + Rollup in [Mapbox GL JS](https://github.com/mapbox/mapbox-gl-js), a big and complex WebGL-powered mapping library. The only major thing I see no equivalent of in a Rollup setup is [Webworkify](https://github.com/substack/webworkify/), a way to launch a web worker at runtime that contains a part of the final bundle. This is needed to achieve these requirements:
- A single JavaScript bundle for both the main thread and the worker instead of two separate bundles, making it easier to set up and use for users.
- No code duplication.
- Only running the required parts instead of the full bundle on the worker side, reducing library initialization time.

The way it works in the Browserify case is figuring out all module dependencies of a worker entry point (they're exposed at runtime), then stringifying corresponding module wrapper functions and concatenating them into a `Blob` that can then be instantiated with a worker.

Due to the fact that Rollup doesn't wrap modules with functions while exposing the dependency tree at runtime, doing something equivalent is very tricky. So far the only potentially viable approach I could come up with is the following:

``` js
// worker.js
if (typeof self !== 'undefined') {
    self.onmessage = ...
    ...
}

// make up some kind of marker like this and make sure it's not tree-shaken or minified
'=== WORKER ENDS HERE ===';

// main.js
import './worker'; // Import worker code first!!! 

function fnThatUsesWorker() {
    global.myWorker.postMessage(...);
}
```

Then I would add a custom prelude instead of UMD that stringifies the factory function that wraps the whole bundle, splits it around the worker marker (`WORKER ENDS HERE`) into two parts, and creates a blob worker from the first part as `global.myWorker`.

This needs to assumptions:
- That all the code worker.js needs will come first in the bundle if you import it first. Can you rely on dependency ordering like this?
- Coming up with some code chunk that's not tree shaken and can be used as a splitting point.

This setup is of course pretty crazy and may be considered too hacky to use. @Rich-Harris do you have any ideas/tips on possible approaches to this problem?

**Comment by Rich-Harris** [comment]
I spent some time digging into this very issue after https://github.com/mapbox/mapbox-gl-js/issues/2658 and reached the same conclusion as you did – it's difficult! 😀  

I don't have any good answers off the top of my head, but it's something I'm motivated to look into since we're no longer able to use Mapbox GL on theguardian.com due to CSP restrictions. (*Slightly* orthogonal, I know, but I'm operating on the assumption that a Webworkify alternative would address the CSP issue at the same time.)

The approach you've outlined seems as good as any. Ideally most of the extra logic required could live in a plugin, though I don't yet know the extent to which that's possible. I have a hunch that code-splitting logic (#372) would help, if we get round to implementing that. Will think on it.

**Comment by mourner** [comment]
@Rich-Harris I guess the only way around CSP Blob restriction is to have a separate worker bundle file — any kind of dynamic solution is bound to use blobs... But a separate file would require things like this in all user code that uses bundling (browserify, webpack, rollup):

```js
mapboxgl.workerPath = '/path/to/mapbox-gl-worker.js`;
```

**Comment by Rich-Harris** [comment]
Are data URIs out of the question? If length is a concern, could maybe have a small worker that then evals the actual code. Though that might have CSP issues of its own...

**Comment by andyearnshaw** [comment]
I started [rollup-plugin-bundle-worker](https://github.com/andyearnshaw/rollup-plugin-bundle-worker) a while ago to bundle and shim simple workers.  It won't handle worker dependencies, but you could have multiple build steps where you build the worker files first and the final thing after.

Different approaches are needed in different browsers.  IE 11/Edge 12 (not sure about newer) won't allow blobs, the helper code bundled by the plugin will detect this and create a sync worker shim instead.  It's possible to work around the issue using an interim worker script that evals a posted message body, but I didn't have a strong enough use case.

It should be possible to use some Rollupception to rollup worker code before returning it in the plugin too (with the unfortunate side-effect of duplication).

Just posting here in case it's useful as a starting-off point.  I'd also gladly accept any improvements as pull requests.

**Comment by puzrin** [comment]
@andyearnshaw IMHO without dependency handling that will not be useful.

> IE 11/Edge 12 (not sure about newer) won't allow blobs, the helper code bundled by the plugin will detect this and create a sync worker shim instead.

I think it's not bundler responsibility to emulate webworker API. The only thing, expected from such plugin is to autogenerate data URL and eliminate need to provide a separate script for worker source. Browserify + webworkify work such way.

**Comment by stereobooster** [comment]
> A single JavaScript bundle for both the main thread and the worker instead of two separate bundles, making it easier to set up and use for users.

What if we would have  "convention over configuration", for example treat all `*.webworker.js` as webworker code? If this convention would be adapted by bundlers (like CRA, next.js etc) it would make it a breath for users to setup (it will work out of the box).

Pros: potentially no CSP restriction. Cons: potential code duplication.

**Comment by andyearnshaw** [comment]
@puzrin I disagree.

> I think it's not bundler responsibility to emulate webworker API.

How do you suggest that Rollup should handle IE 11/Edge then?  Falling back to a URL for the Worker would be non-trivial since you don't know where the JS file is located relative to the page your code is running on (`document.currentScript` is not available in IE 11).

> The only thing, expected from such plugin is to autogenerate data URL and eliminate need to provide a separate script for worker source. Browserify + webworkify work such way.

The only thing _I would expect_ is for it to work with minimal hassle.  You haven't eliminated the need to provide a separate script for Worker source because you don't have full compatibility.  To me, falling back to a "same-thread Worker" should at least be the default option in that case.

**Comment by puzrin** [comment]
> How do you suggest that Rollup should handle IE 11/Edge then?

Rollup should not handle IE 11/Edge or any other browser. It should allow to get source string for webworker from existing code, as webworkify does. That's a minimal required feature. Everything else is optional.

> You haven't eliminated the need to provide a separate script for Worker source because you don't have full compatibility.

I described how things work in real world, without separate ww scripts. Both topic author, me, and other people use browserify + webworkify exactly to have no separate script for ww.

**Comment by stereobooster** [comment]
Side note: [Webworkers will support ES6 modules](https://html.spec.whatwg.org/multipage/workers.html#module-worker-example) `let worker = new Worker("worker.js", { type: "module" });`

**Comment by mourner** [comment]
Closing this as not actionable — can't come up with a good way forward with this. However, as described in https://github.com/mapbox/mapbox-gl-js/issues/5939, Rollup offers benefits that may significantly outweigh the cost of bigger worker bundle (in case we use the same bundle for main thread and worker instead of dynamically building a smaller one). I'll share more concrete findings after we migrate the huge Mapbox GL JS codebase to Rollup.

**Comment by anandthakker** [comment]
The (really impressive!) new code-splitting functionality opens up some interesting new possibilities here.  I'm currently exploring this for mapbox/mapbox-gl-js#5939

**Comment by guybedford** [comment]
@anandthakker if you're interested, there may be some ways we can handle the `new Worker` rewriting to point to the entry point file correctly in Rollup whilst supporting code splitting. ES modules won't work due to module workers not being implemented yet, but the System or AMD output would be a potential way to get this running with chunks shared between the main thread and workers, so that inlining the `new Worker` call to a special wrapper module containing either an AMD or System loader that then loads the entry point again would be an approach. The remaining issue there is handling the async boundary on startup while the module tree of the worker is loading, which may require the worker loader entry point wrapper to buffer any incoming messages while the modules are loading, then pass them fire them again somehow once the modules are finished loading.

Reading through your issue on this it sounds like your bottleneck is parse / compile time not necessarily network time needing code splitting. If there's anything we can do there to help happy to discuss too.

**Comment by anandthakker** [comment]
Thanks @guybedford !

> but the System or AMD output would be a potential way to get this running with chunks shared between the main thread and workers, so that inlining the new Worker call to a special wrapper module containing either an AMD or System loader that then loads the entry point again would be an approach

Yeah, I think this would work very nicely in an application setting.  Since we're working on a library and don't want to impose module/script-loading constraints on users, our approach is to package the entire web worker code into a `blob:` URL and load the web worker using that, all from within the (single) main bundle.

I think code splitting could still help with this -- I'm experimenting with using the three outputs of a `['main.js', 'worker.js]` code-split build as an intermediate step towards a single bundle that works as described above.   An appealing idea is that, if we can get this working, we could offer users both options: either a single bundle that does the `blob:` trick, or a three-part distribution that can use a dynamic loading strategy.

**Comment by guybedford** [comment]
@anandthakker blob inlining will likely be the best way to handle workers actually with es modules too, to get around some of those constraints I mention without incurring unnecessary files. So if there's ways we might introduce a worker hook with a blog return, kind of like we do for the dynamic import hook, that could be something we could look at if it helps.

**Comment by anandthakker** [comment]
@guybedford I agree that sounds is elegant and ideal for cases where code can be distributed via separate files.  While we could offer a build of Mapbox GL JS that worked this way, we definitely _also_ have to be able to ship it as a single bundle as well.

That said, it's totally possible to do this just by recombining the code-splitting chunks with some specialized glue code to accomplish a strategy like the one described in https://github.com/rollup/rollup/issues/1029#issuecomment-367374520.  In https://github.com/mapbox/mapbox-gl-js/pull/6196, I'm currently doing that in a hacky way--using rollup a second time to bundle the chunks that were produced by the first pass.

**Comment by guybedford** [comment]
@anandthakker right, so you would effectively do two Rollup builds - one for the worker, and then another for the main bundle, which inlines the worker using whatever technique you're after.

Perhaps `inlineWorker(specifier: string | node, parentId: string): string | void | Promise<string | void>` where a string output replaces the entire `new Worker(x)` source with a custom source string in the `x` position? Then a void output would indicate running the Rollup default behaviour which in the future can do the automatic code splitting workflow stuff?

If you wanted to dynamically generate a blob, you'd then do something like:

```js
inlineWorker (specifier, parentId) {
  if (specifier === './myworker.js') {
    return `createObjectURL(new Blob(['worker source'], {type : 'application/javascript'}))`;
  }
}
```

Let me know how that sounds?

**Comment by anandthakker** [comment]
@guybedford yeah, I think something like `inlineWorker` will be one ingredient.  Another will be a project-specific plugin that wraps each chunk in a wrapper 'factory' function like in https://github.com/rollup/rollup/issues/1029#issuecomment-367374520 (necessary for dynamically creating the blob).  I think `inlineWorker` could simply be a plugin, already doable via the existing `transform` hook, right?

**Comment by guybedford** [comment]
@anandthakker the major benefit is reliable transforming of the ast without re-parsing, but yes a simple replace could do the same thing :) Although in future it would offer workflow for opting out of the automatic support for a more custom workflow.

Maybe you could walk me through your code example in https://github.com/rollup/rollup/issues/1029#issuecomment-367374520 as I wasn't able to follow this. Specifically how dependency sharing could work in that fashion over direct string embedding.

**Comment by guybedford** [comment]
(that is, I am currently imagining that this work would require running a Rollup sub-process in the rollup plugin itself or something similar...)

**Comment by anandthakker** [comment]
@guybedford here's a small, working example of the approach: https://gist.github.com/anandthakker/ae7955882d7d9f300eaf9bd894742ef9 . Happy to walk through it in more detail any time!

**Comment by guybedford** [comment]
Nice, I can't quite tell how `shared` and `worker` are being populated with the right sources in your example without an explicit function toString call going on there but I get the gist of it I think.

It would be amazing if we could simplify the approach and bring it to more libraries... let me know if you think of anything at all further here!

**Comment by anandthakker** [comment]
>  I can't quite tell how shared and worker are being populated with the right sources in your example without an explicit function toString call going on

Ah, the `.toString()` is implicitly invoked for string concatenation.

> It would be amazing if we could simplify the approach and bring it to more libraries... let me know if you think of anything at all further here!

I've been mulling on whether there could be some plugin hook that would allow this to happen more simply and systematically, but haven't come up with any good/clear ideas on that front yet.
