### ISSUE TITLE
[Bug]  Rollup issue with web-animations-js eval

### ISSUE THREAD

**Issue by Luchillo** [rollup/rollup#1043]
Importing `web-animations-js` with Rollup seems to complain about `eval` sentence:

```sh
[14:56:15]  rollup: Use of `eval` (in 
/home/carlos/Carlos/OSGroup/startApp/node_modules/web-animations-js/web-animations.min.js)
is strongly discouraged, as it poses security risks and may cause issues with minification.
See https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval for more details
```

Related issues:
https://github.com/driftyco/ionic-app-scripts/issues/129
https://github.com/web-animations/web-animations-js/issues/90

**Comment by marvinhagemeister** [comment]
That is an issue with `web-animation-js` not with rollup. Like the warning says: you shouldn't use `eval` in your code if you care about security.

Duplicate of (includes previous discussion) https://github.com/rollup/rollup/issues/1034

**Comment by Luchillo** [comment]
I do understand the issue about eval, however that seems to break a whole lot of libaries making very hard for anyone to use Rollup, for example Webpack didn't break because of it, i think that should be a warning, not an error.

**Comment by Rich-Harris** [comment]
It *is* a warning and not an error. Is it failing to build?

**Comment by Luchillo** [comment]
Hmm, i think not, i used webpack and now i have to use Rollup, just started yesterday so i don't know the difference, i think not, the error shows up in the browser according [this](https://github.com/driftyco/ionic-app-scripts/issues/129#issuecomment-253027979) comment in the related issue.

Since webpack worked ok with it i, think it has to be Rollup doing something, maybe it's minifying an already minified file?

**Comment by Rich-Harris** [comment]
The error you're seeing is unrelated to `eval`.

I've done some investigating, and the cause is that `web-animations-js` cannot be used in strict environments – if you take the contents of `web-animations.min.js` and wrap it like so...

```js
(function () {
'use strict';
/* contents of web-animations.min.js */
}());
```

...you get the very same error, without involving Rollup at all.

Rollup is an ES6 module bundler. ES6 modules are *always* in strict mode. As such, there isn't really a 'proper' way to use sloppy-mode modules in a Rollup bundle. You could hack it like this...

```js
// rollup.config.js
export default {
  // ...
  plugins: [
    // other plugins...
    removeUseStrict()
  ]
};

function removeUseStrict () {
  return {
    transformBundle: code => {
      return {
        code: code.replace( `'use strict';`, '' ),
        map: { mappings: '' }
      }
    }
  };
}
```

...and it runs, but it's a bit of a messy solution. I would recommend raising an issue on `web-animations-js` to try and understand why they only support sloppy mode, since it's frankly rather unusual in this day and age. At the same time, they could replace their direct `eval` with an indirect `eval` with no loss of functionality ([more info here](https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval)) to prevent the warning.

An alternative solution is to simply put the polyfill in a script tag before your bundle, and not bother importing it at all. In many ways this makes more sense since the polyfill isn't part of your app, it's just upgrading the environment in which your app runs.

> Since webpack worked ok with it i, think it has to be Rollup doing something

The reason Ionic moved over to Rollup is that bundles are smaller and initialise *significantly* faster. That's possible because Rollup works in a fundamentally different way to Webpack – whereas Webpack wraps each module in a function, Rollup puts all module code in a shared scope whereupon it immediately executes. We're in regular contact with the Webpack team and they're investigating adopting a similar approach in some cases, in which case they would encounter the exact same problems with `eval`. The long term solution here is for `web-animations-js` (and any other library that uses `eval` and sloppy mode) to go strict and avoid `eval`, both of which come with benefits beyond Rollup compatibility.

**Comment by Luchillo** [comment]
I see, i did read 'The cost of small modules' explaining the diference between Webpack, Rollup and Browserify.

I already have an issue in `web-animations-js` repo, i'll link your comment and see what's up.

Also i haven't see any other way of copying the pollyfil file with Rollup (damn i miss webpack) so i had to copy by hand to assets folder, however dealing with the updates will be a pain in the a$$.

Btw the `Intl` pollyfil shows an error as well, should i raise a new issue for it?

**Comment by Rich-Harris** [comment]
> Btw the Intl pollyfil shows an error as well, should i raise a new issue for it?

yes
