### ISSUE TITLE
Typescript code can not be compiled with rollup.

### ISSUE THREAD

**Issue by lygstate** [rollup/rollup#1048]
refere to : https://github.com/Microsoft/TypeScript/issues/11567
Getting the following code works:
jdenticon.ts

```
export interface JdentionStatic {
  update(element:any, hash:string, padding:number): void;
}
export declare var jdenticon: JdentionStatic;
```

user.ts

``` ts
import {jdenticon} from './jdenticon'
```

Error report by rollup:

```
[03:47:32]  bundle dev failed:  Module
C:/CI-Cor/acrop/acrop-client/src/typings.ts does not export jdenticon
(imported by
C:/CI-Cor/acrop/acrop-client/src/pages/devicelist/devicelist.ts)

[03:47:32]  Error: Module C:/CI-Cor/acrop/acrop-client/src/typings.ts does
not export jdenticon (imported by
C:/CI-Cor/acrop/acrop-client/src/pages/devicelist/devicelist.ts)
    at Module.trace
(C:\CI-Cor\acrop\acrop-client\node_modules\rollup\dist\rollup.js:7706:29)
    at ModuleScope.findDeclaration
(C:\CI-Cor\acrop\acrop-client\node_modules\rollup\dist\rollup.js:7329:22)
    at Scope.findDeclaration
(C:\CI-Cor\acrop\acrop-client\node_modules\rollup\dist\rollup.js:5349:39)
    at Scope.findDeclaration
(C:\CI-Cor\acrop\acrop-client\node_modules\rollup\dist\rollup.js:5349:39)
    at MemberExpression.bind
(C:\CI-Cor\acrop\acrop-client\node_modules\rollup\dist\rollup.js:6695:28)
    at
C:\CI-Cor\acrop\acrop-client\node_modules\rollup\dist\rollup.js:5149:50
    at CallExpression.eachChild
(C:\CI-Cor\acrop\acrop-client\node_modules\rollup\dist\rollup.js:5166:5)
    at CallExpression.bind
(C:\CI-Cor\acrop\acrop-client\node_modules\rollup\dist\rollup.js:5149:7)
    at CallExpression.bind
(C:\CI-Cor\acrop\acrop-client\node_modules\rollup\dist\rollup.js:5850:23)
    at
C:\CI-Cor\acrop\acrop-client\node_modules\rollup\dist\rollup.js:5149:50
```

**Comment by marvinhagemeister** [comment]
This has nothing to do with rollup. I guess you are confused by the difference between typings (the `*.d.ts` files) and typescript files themselves ( `*.ts`). Like the others in the provided issue at the typescript repo mentioned: The `declare` keyword must only be used inside `*.d.ts` files. Naturally typing files only contain description of the types. In your case your `jdenticon.ts` file is interpreted as a typings file which is why your code fails.

A good introduction on how the module system works with typescript can be found here: https://www.typescriptlang.org/docs/handbook/modules.html

**Comment by lygstate** [comment]
```import {jdenticon} from '../../typings.d.ts'``` is not possible.

**Comment by lygstate** [comment]
and typescript support for this, so this is the problem of rollup

**Comment by marvinhagemeister** [comment]
No, you're simply using typescript wrong. See https://github.com/rollup/rollup/issues/1049#issuecomment-253414986

@Rich-Harris please close this

**Comment by snuggs** [comment]
@lygstate @marvinhagemeister is correct. This is now a duplicate. need to close both. :-)
