### ISSUE TITLE
JSNext Badge

### ISSUE THREAD

**Issue by tusharmath** [rollup/rollup#1067]
It would be great if there was a badge that one could put in their README.md files to showcase that the project supports `jsnext:main`. 

Possible options —

![alt text](https://img.shields.io/badge/module-es6-blue.svg)
![alt text](https://img.shields.io/badge/main-es6-blue.svg)
![alt text](https://img.shields.io/badge/main-jsnext-blue.svg)

A designer badge would be even more awesome.

**Comment by snuggs** [comment]
Concur @tusharmath

**Comment by Rich-Harris** [comment]
This seems like a great idea (I'd probably suggest something like

![es2015 module](https://img.shields.io/badge/es2015-module-blue.svg)

since `module` is designed to supersede `jsnext:main`, and ES2015 is more 'correct') – though I wonder if we ought to wait until it's accepted as a standard? Am wary of more aggressively promoting `pkg.module` if there's a chance that it could change in future (which is still the case, AFAIK).

Then again, we've already been promoting it, and a lot of people are already using `pkg.module` alongside `pkg.main`.

**Comment by jhabdas** [comment]
:lipstick:

**Comment by jhabdas** [comment]
Why not simply [es|module]?

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
