### ISSUE TITLE
Cannot read property 'expression' of undefined

### ISSUE THREAD

**Issue by matthieusieben** [rollup/rollup#1081]
The following code will break with the error `Cannot read property 'expression' of undefined`.

``` js
// main.js
import incX from './test.js';
```

``` js
// test.js
export default function incX () {
    ++(this.x)
}
```

[Live example](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwaW5jWCUyMGZyb20lMjAnLiUyRnRlc3QuanMnJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0ZXN0LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRoaXMlMjBmdW5jdGlvbiUyMGdldHMlMjBpbmNsdWRlZCU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBpbmNYJTIwKCklMjAlN0IlNUNuJTVDdCUyRiUyRiUyMCUyQiUyQih0aGlzLngpJTVDbiU3RCUyMiU3RCU1RCU3RA==) (requires you to uncomment the line)

Except from the fact that that is valid JS, it was very difficult for me to figure out where this error was originating from. Could you also make errors more verbose when there is a syntax problem in a file?

```
Cannot read property 'expression' of undefined
TypeError: Cannot read property 'expression' of undefined
    at UpdateExpression.bind (DIRNAME/node_modules/rollup/src/ast/nodes/UpdateExpression.js:9:79)
    at DIRNAME/node_modules/rollup/src/ast/Node.js:6:34
    at VariableDeclarator.eachChild (DIRNAME/node_modules/rollup/src/ast/Node.js:21:5)
    at VariableDeclarator.bind (DIRNAME/node_modules/rollup/src/ast/Node.js:6:8)
    at DIRNAME/node_modules/rollup/src/ast/Node.js:6:34
    at VariableDeclaration.eachChild (DIRNAME/node_modules/rollup/src/ast/Node.js:18:20)
    at VariableDeclaration.bind (DIRNAME/node_modules/rollup/src/ast/Node.js:6:8)
    at BlockStatement.bind (DIRNAME/node_modules/rollup/src/ast/nodes/BlockStatement.js:8:9)
    at FunctionDeclaration.bind (DIRNAME/node_modules/rollup/src/ast/nodes/FunctionDeclaration.js:20:13)
    at ExportDefaultDeclaration.bind (DIRNAME/node_modules/rollup/src/ast/nodes/ExportDefaultDeclaration.js:32:20
```

**Comment by Rich-Harris** [comment]
I think this was another manifestation of https://github.com/rollup/rollup/issues/1101 – it looks like it's fixed in 0.37 ([demo](http://rollupjs.org/?version=0.37.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwaW5jWCUyMGZyb20lMjAnLiUyRnRlc3QuanMnJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0ZXN0LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRoaXMlMjBmdW5jdGlvbiUyMGdldHMlMjBpbmNsdWRlZCU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBpbmNYJTIwKCklMjAlN0IlNUNuJTVDdCUyQiUyQih0aGlzLngpJTVDbiU3RCUyMiU3RCU1RCU3RA==)), so I'll close this.

Agree re errors – have just opened https://github.com/rollup/rollup/issues/1158
