### ISSUE TITLE
async function is donot work!

### ISSUE THREAD

**Issue by ok111net** [rollup/rollup#1088]
async function f() {
    const d=await fettch();
    console.log(d);
}

if the code has async function, the rollup donot run,it report some err!

**Comment by NicolasParada** [comment]
In the rollup.config.js:
```js
  acorn: {
    ecmaVersion: 8
  }
```

**Comment by Victorystick** [comment]
Rollup only natively supports es6 at this time. You'll need to transpile `async`/`await` using a plugin (like Babel) before Rollup can bundle the code.

**Comment by snuggs** [comment]
@Victorystick acorn has support for async as of v8. Spoke to @Rich-Harris about this a couple months ago. Was when (after I wrote a ton of code) we realized just pass ecmaVersion 8 to acorn options. I shoulda checked if there were air in the tires first. :-) /cc @NicolasParada @ok111net 

ref ➡️ https://github.com/ternjs/acorn/commit/452f3d7181b82512716579a07f35d7a7ca39beeb

**Comment by Victorystick** [comment]
@snuggs I understand that Acorn supports them, but does Rollup? Or is it enough just to test them the same as any other function, meaning they're supported our of the box?

**Comment by snuggs** [comment]
out of the box by triggering v8. I've been up and down the source code @ acorn. This is the link to the implementation. https://github.com/ternjs/acorn/commit/452f3d7181b82512716579a07f35d7a7ca39beeb 
. Should just work 📦 "out of the box" 📦  as you say @Victorystick. /cc @Rich-Harris

**Comment by bathos** [comment]
Though `ecmaVersion: 8` does work, it seems(?) there might be some acorn issues anyway. It considers this an error:

```
const foo = { async: true };
```

(Pretty certain it’s not — like any other reserved word, the identifier constraint does not apply to property names.)

You can get around this with `allowReserved: true`*. But _not always_. Sometimes, instead throwing parse errors for illegal reserved words, acorn is throwing generic "unexpected token" errors for properties named `async`.

Naturally I wouldn’t use `async` as a property name myself, but this occurs in third-party modules (e.g. uiRouter 1.0).

While this seems to be an acorn rather than a rollup issue, I figured I would dump my fuzzy knowledge-so-far here since the issue is likely to come up for others who are using rollup _without_ transpiling to es5.

---

_\* This acorn option also gets you around issues with functions that use `undefined` as a parameter name, a common old-school technique to ‘lock in’ undefined-as-undefined in a closure — i.e. a solution to the imaginary problem of code redefining `undefined`, pre-es5)._
