### ISSUE TITLE
Option to return a stream instead of a promise

### ISSUE THREAD

**Issue by DonGissel** [rollup/rollup#1123]
The current method of returning a promise works fine in many cases, but usage in a task runner such as gulp becomes very difficult. So far I've used a wrapper ([rollup-stream](https://www.npmjs.com/package/rollup-stream)) which returns a stream for me to work with, but if Rollup itself had an option to return a stream (or even a buffer, using `vinyl-buffer`) directly, I could dispense with the potentially troublesome wrapper, which would be nice. And if code splitting or similar ever became a thing, having streams built-in would probably lessen the complexity for gulp-users such as myself considerably.

**Comment by Rich-Harris** [comment]
Unfortunately there's really no sensible way for Rollup to create a stream, because it can't begin generating code until it has a picture of the entire bundle in memory. There really isn't any benefit to outputting a stream once you've got the entire output to hand, other than to align more closely with Gulp's idiosyncratic view of the world, so I think it's reasonable to expect that the interop burden lies on the Gulp side of the fence.
