### ISSUE TITLE
Angular AoT and Rollup problem: Could not resolve app.module.ngfactory

### ISSUE THREAD

**Issue by Alberto2686** [rollup/rollup#1175]
Hi, as the title says I'm having problems with rollup execution.
I'm following Angular 2 official tutorial https://angular.io/docs/ts/latest/cookbook/aot-compiler.html
I can generate the ngfactories with AoT compilation but when I launch rollup -c rollup-config.js I get this message: 
**Could not resolve '../../aot/src/app/app.module.ngfactory' from [...]\src\app\main.aot.ts**

What am I doing wrong?
I prepared a minimal repro: https://github.com/Alberto2686/rollup.
After git clone and npm install do this:
1) AoT compilation with => npm run aotc
2) Rollup execution with => npm run rollup

Thanks

**Comment by Rich-Harris** [comment]
If a file extension is missing, Rollup will try adding a `.js` extension (so `./foo` and `./foo.js` are equivalent – though at some unspecified point in the future we'll probably drop support for relative paths without extensions).

The `main.aot.ts` file has the following line:

```js
import { AppModuleNgFactory } from '../../aot/src/app/app.module.ngfactory';
```

That path corresponds to a file called `aot/src/app/app/module.ngfactory.ts`, but since the `.ts` file extension is absent, Rollup doesn't find it. But even if you add the extension, it doesn't work, because Rollup doesn't know what to do with TypeScript files.

It sounds like the Angular documentation is incomplete. To be honest you might have more luck raising this on an Angular forum or issue tracker – Rollup is behaving as expected given the situation.

**Comment by ghego1** [comment]
Same problem here. @Alberto2686, have you solved the issue in the meanwhile?

**Comment by Rich-Harris** [comment]
Closing as it doesn't seem like there's anything for Rollup to do here

**Comment by coni2k** [comment]
@Alberto2686, @ghego1 I had the same problem. Apparently tutorial is missing a step, and as Alberto said, after generating `ts` files with `ngc`, these need to be compiled one more time with typescript to generate `js` files. For me the rest works (so not sure about your last comment Alberto).

I have created a Q & A on stackoverflow about this issue:
http://stackoverflow.com/a/41740546/1087768

And a quick demo app that shows the steps:
https://github.com/forCrowd/Labs-Angular-AOTConfiguration
