### ISSUE TITLE
Trouble with aliases

### ISSUE THREAD

**Issue by tschaub** [rollup/rollup#1189]
Given this `main.js`:

```js
import Foo from './foo.js'

new Foo();
```

And this `foo.js`:
```js
var Foo;

Foo = function() {
  alert('hello');
};

export default Foo;
```

I was a bit surprised to see this output (specifically the `Foo$1` part):
```js
var Foo;

Foo = function() {
  alert('hello');
};

var Foo$1 = Foo;

new Foo$1();
```

If however I change `foo.js` to put the function expression in the variable declarator:
```js
// modified foo.js module
var Foo = function() {
  alert('hello');
};

export default Foo;
```

Then I get this output from `rollup`:
```js
var Foo = function() {
  alert('hello');
};

new Foo();
```

Which is what I was hoping to get from the first example (no extra `Foo$1`).

The `Foo$1` alias is causing trouble with a bundle that I'm trying to pass to the Closure Compiler (types on `Foo$1` are not being recognized).  I can try to rework the code that I'm passing to Rollup, but I was curious if seeing the `Foo$1` alias in the output above is expected (only when I don't have an initial value in the original variable declaration).

**Comment by Rich-Harris** [comment]
This is expected, yes. The reason is that `export default` doesn't create a *live binding*, meaning that in a situation like this...

```js
var Foo;

export default Foo;

Foo = function() {
  alert('hello');
};
```

...the default export would be `undefined`. (If it was `export { Foo }` instead, the binding would be live, meaning that anything that imported `Foo` and used it would be using the function).

Because of this, Rollup creates an additional variable – `Foo$1` – which is a snapshot of the value of `Foo` at the point of export, which can then safely be used in other modules. The reason this doesn't happen when `Foo` is initialised at the point of declaration is that it's never reassigned, meaning there's no need for a snapshot.

Now, you and I can very easily see by looking at the code that in the example above, where the export declaration comes at the end instead of in the middle...

```js
var Foo;

Foo = function() {
  alert('hello');
};

export default Foo;
```

...there's no need for the snapshot. But it's a little harder to teach Rollup to come to the same conclusion. Certainly not *impossible*, but a bit finicky. So we've never bothered, since you'd assume that the resulting behaviour is identical – I hadn't considered that Closure might treat the result differently.

Your best bet is probably to avoid the reassignment if possible – since this isn't really a 'bug', fixing it will have to be a lower priority than other issues.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
