### ISSUE TITLE
Circular dependency leads to runtime failure

### ISSUE THREAD

**Issue by cowwoc** [rollup/rollup#1193]
Please see https://github.com/cowwoc/rollup-circular-dependency for a self-contained testcase showing rollup producing code that breaks at runtime due to circular dependencies.

I explain the cause of the problem and propose a solution (see README.md).

**Comment by Rich-Harris** [comment]
This isn't a Rollup issue so much as it's inherent to circular dependencies when used in this way. Rollup follows the spec when it comes to order of execution, and in this case that means that the order is `Requirements.js`, `ArrayVerifier.js`, then `RequirementVerifier.js`.

`Requirements.js` instantiates `RequirementVerifier`. That works because `RequirementVerifier` is a function, and is therefore hoisted, but `delegate` inherits from `RequirementVerifier.prototype`. On [this line](https://github.com/cowwoc/rollup-circular-dependency/blob/master/src/RequirementVerifier.js#L6) you reassign `RequirementVerifier.prototype`, meaning that any methods that are then added don't attach to `delegate`.

I don't know if this solution scales to the codebase as a whole, but you can prevent the prototype chain breaking by [removing these two lines](https://github.com/cowwoc/rollup-circular-dependency/blob/master/src/RequirementVerifier.js#L6-L7). Failing that, you would have to rearchitect the codebase, for example putting the `requireThat` implementation outside any cyclical dependencies.

All Rollup can really do here is warn that there's a problem (see https://github.com/rollup/rollup/issues/1089#issuecomment-267858411) — it can't fix it, so I'll close this issue.

**Comment by cowwoc** [comment]
Regarding your suggestion to [remove these two lines](https://github.com/cowwoc/rollup-circular-dependency/blob/master/src/RequirementVerifier.js#L6-L7), won't doing so prevent `RequirementVerifier` from acting as a class? I mean, don't I *need* these two lines?

**Comment by Rich-Harris** [comment]
@cowwoc no, they're redundant – functions are created with a prototype whose `constructor` method is the function. So those two lines are equivalent to doing this:

```js
var obj = {
  foo: {
    bar: 42
  }
};

obj.foo = Object.create( obj.foo );
obj.foo.bar = 42;
```

**Comment by cowwoc** [comment]
@Rich-Harris Okay. So are you saying that I only need these two lines in case of inheritance (where the subclass prototype points to a superclass instance)?

**Comment by Rich-Harris** [comment]
@cowwoc yep, exactly that (though typically it'd point to a superclass *prototype* rather than a superclass instance)

**Comment by cowwoc** [comment]
@Rich-Harris Interesting. Why then does https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain provide this sample?

```
B.prototype = Object.create(A.prototype, {
  varB : {
    value: null, 
    enumerable: true, 
    configurable: true, 
    writable: true 
  },
  doSomething : { 
    value: function(){ // override
      A.prototype.doSomething.apply(this, arguments); // call super
      // ...
    },
    enumerable: true,
    configurable: true, 
    writable: true
  }
});
B.prototype.constructor = B;
```

Isn't this assigning a superclass *instance* instead of the prototype? Or did I miss something?

**Comment by Rich-Harris** [comment]
It's creating an object (`B.prototype`) that inherits from `A.prototype` where `A` is the superclass, and adding additional methods to it. There's no `A` instance (i.e. `var a = new A()`) involved in that snippet.

**Comment by cowwoc** [comment]
I see. Makes sense. I was thrown off by `Object.create()`, thinking that it created a new `A` instance.
