### ISSUE TITLE
Allow entry to be a glob pattern or an array of strings

### ISSUE THREAD

**Issue by lukeapage** [rollup/rollup#120]
If I have alot of unit tests, written using the same es6 as the main application, I would rather roll them all up and stick them together, than have to use requirejs only for the tests.

**Comment by lukeapage** [comment]
hrmm maybe for this usecase its better to use a task runner to rollup each spec file individually.

Please feel free to close if you think it is out of scope.

**Comment by Rich-Harris** [comment]
also under discussion here: https://github.com/square/field-kit/pull/30#issuecomment-139397124

One thing that might work, depending on how things are set up:

```js
// entry.js
import './these-tests';
import './those-tests';
import './the-other-tests';
```

In other words, you're still using a single bundle with a single entry point, but all the test files are included and executed in the order specified.

**Comment by mstade** [comment]
Multiple entry points into one file doesn't really make much sense, does it? Multiple entry points make sense in my mind, to support the following scenario:

- You have multiple different modules that can execute on their own
- These modules import common functionality
- It's a perfect job for a computer to figure out that commonality; humans should spend their time doing better things

So the linker (i.e. rollup) could be smart about this and notice those commonalities and put them in a common bundle, exporting things using whatever symbols make sense and rewriting the different modules to import the correct symbols from the now common library. That's a multiple entry point scenario that makes sense to me, but will produce multiple files and not just the one – which is what you want with linking tests together. That's not really linking though, that's concatenation, and probably should be done by other means.

**Comment by mstade** [comment]
Also, this doesn't *just* make sense in the browser setting of page A and B and C all being separate, but using common functionality from library D and you don't want to factor that into A, B, and C since it'll increase file size and it's not really worth it to save the one request, as opposed to caching a common bundle. It also makes sense in a nodejs context, or otherwise one where you're not at the mercy of HTTP, but potentially other things like the latency of loading files from disk. That's a scenario where the file size doesn't matter as much, but factoring things out into a common bundle still make sense – particularly if that common bundle is stateful.

Multiple entry points do make sense I think, just not for concatenating tests together.

**Comment by Rich-Harris** [comment]
@mstade 

> So the linker (i.e. rollup) could be smart about this and notice those commonalities and put them in a common bundle, exporting things using whatever symbols make sense and rewriting the different modules to import the correct symbols from the now common library

Absolutely. This is definitely something I'd like Rollup to be able to do. I haven't really thought about implementation, but this would be a good place to talk about what the API might look like. 

```js
rollup.split({
  entries: [ 'foo.js', 'bar.js', 'baz.js' ]
}).then( function ( result ) {
  // code used by all three bundles
  result.common.write({
    dest: 'dist/common.js',
    format: 'umd'
  });

  result.entries.forEach( bundle => {
    bundle.write({
      dest: bundle.entry.replace( 'src', 'dist' ),
      format: 'umd'
    });
  });
});
```

Total straw man (I'd try and come up with some different examples but it's lunchtime :fork_and_knife: :doughnut:), and fairly simplistic (it doesn't allow the level of configurability of JSPM's [bundle arithmetic](https://github.com/systemjs/builder#bundle-arithmetic) or Webpack's [code splitting](https://webpack.github.io/docs/code-splitting.html), though maybe simplicity is more important anyway) – would be very interested to hear other ideas.

**Comment by mstade** [comment]
The best API, I think, is no API.

No one really *wants* to define splits, and especially not in a tooling specific way. The 80/20 applies; 80% (probably more like 99/1, honestly) only care that they are deploying a *web* app or a *server* app or a *native* app (in which case they probably use something entirely different, come to think of it) and all they care about is whatever is best for their target platform. Not their target deployment – mind you – the platform. Because as much as people probably like to say that it's very important for them to be able to define where to split and what not, it's really not. There are pretty hard and fast rules about what constitutes good bundling, and they don't really change much from project to project. It's a producer/consumer dichotomy; the producer might say it's important that they get to decide this or that, but at the end of the day the consumer just wants to buy a damn t-shirt, and they want to do it fast.

To that end, I think flexibility is less important than finding out what those sensible defaults are, and making sure they are well implemented for each target platform. Now, the target platform is known – always – unless you're building a library in which case the decision is simply deferred to whoever is building an executable. Also, the target platforms change very rarely. There are servers and desktops, and web browsers, and I suppose you could split that into mobile web browsers too, but it's not like there's a proliferation of different target platforms. There are probably commonalities between them as well.

Now, as an author, if you *really* **really** care about making sure some things end up in a specific bundle, then I think taking a cue from many other languages and dev environments might be useful: simply force people to create sort of meta or aggregate modules, that all they do is import and re-export symbols. That module then becomes an entry point, and if combined with other entry points can be optimized as well. If not combined with other entry points, it's just as any other app. It's simple, it's easily grokked, and doesn't really require any APIs or is otherwise tooling specific. Such modules are often trivial to generate on the fly as part of a build process, and tools like Make will be a much better fit than coming up with new APIs like bundle arithmetic or whatever. Those things are not good ideas, they're terrible idea. Humans should do the job of computer's.

So I suppose, if there should be an API at all, it should be one to define the target platform heuristics. Not sure what that might look like – it might just be best to kick off development on one such target, and let the API take shape from that. I do think such a function would have to operate on a lower level than the abstractions of files, it'd probably have to operate on the AST, or given some AST be able the answer to the question: where are the splits and joins? This becomes relevant for target platforms that are not-quite-production, such as when you *do* want/need a build step, but still want to take advantage of things like replacing modules at runtime. A linker like rollup should be uniquely qualified to do this proper (not the webpack sillyness) by taking advantage of the intimate knowledge of the AST, and knowing what it means to target a browser (or node for that matter, I've done some module replacement experiments there in the past and it's LOVELY!)

I guess, a very nifty thing, is if such heuristics are composable. I have no idea what that might look like though.

**Comment by lukeapage** [comment]
Not sure it has relevance to your discussion, but I raised the bug so maybe worth saying, the way I'm doing it is like so..

I'm packaging my library using rollup using umd.
I include the file in my test runner, exposing a global
I write tests using the globally exposed version
the tests use some mocks and helpers etc.. so I rollup each "-spec" file, using grunt-rollup to help me rollup all `*-spec` files.

Its not perfect, but I can get away withut using requirejs and just using rollup for packaging.

**Comment by mstade** [comment]
Yeah sorry, I think I may have hi-jacked things a bit here – apologies for the ranting!

**Comment by englercj** [comment]
Any word on this?

My use case is that I have a "core" library and many plugins. I want to use rollup to include the core and any arbitrary number of plugins I want into a single bundle. Right now the only way to do that is to bundle each module separately and concat them, which works fine for `iife` but obviously falls apart for amd/commonjs. I can hack around it, by exporting each as iife and adding my own header, but then I lose sourcemaps and other features. This feature is almost necessary for me to switch to rollup.

**Comment by Rich-Harris** [comment]
This is now supported via https://github.com/eventualbuddha/rollup-plugin-multi-entry, so I'll close this issue and open a separate one for the discussion around code splitting.
