### ISSUE TITLE
Assigning to function parameters defeats tree-shaking

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#1208]
[This](http://rollupjs.org/?version=0.39.2&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBmb28lMjAoJTIweCUyMCklMjAlN0IlNUNuJTIwJTIwaWYlMjAoJTIwIXglMjApJTIweCUyMCUzRCUyMDIlM0IlNUNuJTIwJTIwcmV0dXJuJTIweCUyMColMjAyJTNCJTVDbiU3RCU1Q24lNUNudmFyJTIwdW51c2VkJTIwJTNEJTIwZm9vKCUyMDElMjApJTNCJTIyJTdEJTVEJTdE) makes it impossible to do things like defaults:

```js
function foo ( x ) {
  if ( !x ) x = 2; // without this line, everything would be tree-shaken
  return x * 2;
}

var unused = foo( 1 );
```

**Comment by kzc** [comment]
Same issue for UpdateExpression:
```js
function foo ( x ) {
  --x;    // without this line, everything would be tree-shaken

}

var unused = foo( 1 );
```

**Comment by lukastaegert** [comment]
@Rich-Harris @kzc I am not sure I understand the issue here, could anyone please elaborate?
As I understand it, all of the code above is side-effect-free and should therefore be removed. If this is really about function parameter defaults, please include an example where the function is actually used as a parameter default so that we know when this issue can be closed. Btw., side-effects in pattern assignment defaults should already be treated correctly.

**Comment by kzc** [comment]
> all of the code above is side-effect-free and should therefore be removed

That's correct. This issue was describing a deficiency in the previous algorithm and can now be closed.
