### ISSUE TITLE
Tree shaking should be run after transformBundle hook

### ISSUE THREAD

**Issue by Pauan** [rollup/rollup#1272]
Here is an example Rollup configuration:

```js
export default {
  entry: "foo.js",
  format: "es",
  plugins: [
    {
      transformBundle: function (source) {
        return source + "function foo() {}";
      }
    }
  ]
};
```

And here is `foo.js`:

```js
console.log(1);
```

The result of running `rollup --config` is this:

```js
console.log(1);function foo() {}
```

The `foo` function is not used, so I was expecting it to be tree-shaken, but it was not.

This ties into https://github.com/rollup/rollup/issues/1271, because it doesn't make sense to do tree shaking after `format` is applied, but if `transformBundle` runs before `format`, then tree shaking can be done at that time.

**Comment by Rich-Harris** [comment]
Unfortunately it just doesn't work like that — treeshaking operates on an AST, not on a string, so in order to do this it would be necessary to transform/parse every module, analyse them (to discover imports, understand scope in order to rename variables to avoid conflicts between modules etc), sort and concatenate them, stringify the bundle, parse the result of *that*, and analyse everything all over again, which isn't realistic.

If you want to add a function that may or may not be used you're better off doing it like this:

```js
// rollup.config.js
function addFoo () {
  const pluginId = '\0my-plugin';

  return {
    name: 'my-plugin',
    resolveId (id) {
      if (id === pluginId) return pluginId;
    },
    load (id) {
      if (id === pluginId) return `export function foo () {...}`;
    },
    transform (code, id) {
      if (id === pluginId) return;
      return `import { foo } from '${pluginId}';\n${code}`;
    }
  };
}

export default {
  ...
  plugins: [
    addFoo()
  ]
};
```

This is how [rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel/blob/master/src/index.js) imports helper functions and treeshakes them.
