### ISSUE TITLE
export "modules" as well as "externalModules" in the user-facing Bundle object.

### ISSUE THREAD

**Issue by ty1824** [rollup/rollup#128]
I'm writing a plugin to perform incremental builds to multiple targets using rollup, and it'd be very handy if the "modules" property was exported along with the "externalModules" property. Currently "externalModules" is exported as "imports".

This is handy when trying to identify if a modified file will affect a specific target (i.e. is it in the dependency tree for my given target) - if so, I want to rebuild that target, but ignore unaffected targets.

I'm not sure what an appropriate name would be - internalImports/internalDependencies?

I'd be happy to make this change myself :)

**Comment by Rich-Harris** [comment]
#2 is a related issue – in order to do fast incremental rebuilds, it'd be necessary to do some level of caching, and the property on the user-facing `bundle` object you speak of is probably very similar to the thing you'd need to implement any form of caching.

I haven't spent a lot of time thinking about exactly what you'd need for each module – the module ID, certainly, but possibly also a list of dependencies and dependants, source code, AST, maybe a checksum (to see if source code has changed)?

So here's what I think makes sense: we add a new property, `bundle.modules`, which is an array of objects that only have an `id` property for now, but could in future be extended to include those other things as and when they become necessary. That should give you what you need to detect whether a given bundle is affected by a given file change.

(A simpler option would be to just pass through the internal `modules` array, but I'm against that because a) it exposes Rollup's innards, allowing people to use undocumented stuff that's likely to change in future, b) ideally `modules` should be serializable with `JSON.stringify` so that it can be dumped to disk for incremental rebuild purposes, and c) it introduces mutation-related bugs as something we'd need to worry about.)

How does that sound?

**Comment by ty1824** [comment]
I'm a fan of this approach - I actually had modified the exports to include a similar map -> module id. Exposing the module internals definitely seems too extreme.

I've definitely been thinking about caching as well - I hadn't looked closely at #2! This should work for now - I'm personally working on a relatively small project, but I wanted to have a reliable automatic build tool that used rollup - it's too awesome.

**Comment by Victorystick** [comment]
I look forward to seeing what you build, @ty1824! :smile:

**Comment by ty1824** [comment]
@Victorystick 
A rough first draft of what I've used this for :)
https://github.com/ty1824/project-rollup

Gulp-compatible (support for streams) "incremental" builds. Allows a user to specify a list of target paths or a file containing a list of target paths. It's not quite incremental, I rebundle/regenerate everything related to each target when that target is built, but it allows tracking changes so only changed targets are rebundled.
