### ISSUE TITLE
this.warn and this.error are not available in transformBundle

### ISSUE THREAD

**Issue by Pauan** [rollup/rollup#1282]
Here is an example Rollup config:

```js
export default {
  entry: "foo.js",
  format: "es",
  plugins: [
    {
      transformBundle: function (source) {
        console.log(this.warn);
        console.log(this.error);
      }
    }
  ]
};
```

And here is `foo.js`:

```js
console.log(1);
```

Both `this.warn` and `this.error` are `undefined`, but they should be defined.

**Comment by olsonpm** [comment]
per the wiki

> Inside a **transform** function, you can use this.warn(warning[, pos]) to provide feedback in a standard form.

transformBundle doesn't have a note about this.warn

**Comment by Pauan** [comment]
@olegskl I am aware. I am requesting that it be added to `transformBundle` as well.

**Comment by olsonpm** [comment]
Ah I misunderstood

**Comment by olsonpm** [comment]
Btw - I came across this issue in my plugin (wanted this.warn inside the `resolveId` function).  I looked at the warn code and it's very coupled to the `transform` function.  Because of that, the quickest solution is to just provide your own `onwarn` plugin option.

It's a workaround, not a solution - but it *worksaround* well enough for me

**Comment by guybedford** [comment]
These are now available for plugins in https://github.com/rollup/rollup/pull/2208.
