### ISSUE TITLE
unused buble generated class not dropped

### ISSUE THREAD

**Issue by kzc** [rollup/rollup#1284]
```js
// echo 'class Foo { foo(){} }' | buble
var Foo = function Foo () {};
Foo.prototype.foo = function foo () {};
```

See: https://gitlab.com/Rich-Harris/buble/issues/181

**Comment by kzc** [comment]
@lukastaegert #1582 doesn't appear to fix this one. Any thoughts?

**Comment by lukastaegert** [comment]
I do but it will take some time since I want to address other things (call handling) first, and I think this one is more difficult. I think the issue is the following:
If you wrote

```javascript
var Foo = {prototype: globalVar}
Foo.prototype.foo = function foo () {}
```

Rollup would be right to keep the code. Unfortunately there is no way for Rollup to distinguish these two cases yet. There are some
good ideas in the code that handles namespace imports I want to take a look at—and this is certainly on my list—but it is difficult to get right without writing spaghetti code.
