### ISSUE TITLE
tree shaking the tether.js module omits function extend()? 

### ISSUE THREAD

**Issue by MichaelRando** [rollup/rollup#1289]
I made a repro example for this one out of a rollup starter project. See here:
https://github.com/MichaelRando/babel-react-rollup-starter

What I did was to add reactstrap to a reactjs rollup project. reactstrap pulls in tether.js, a valid module. When the rollup build evaluates the tether.js file, the app.js ends up missing a variety of the functions exported on the TetherBase.Utils object; in particular, the extend function has been omitted or tree-shaken somehow.. 

I don't know why it would do this or how to fix it, so I'm hoping this bug generates comments leading to a fix or workaround. thx.

**Comment by olsonpm** [comment]
This seems to be a bug with tether and not rollup.

A distilled version of the problem can be seen below:

```js
// es6.js
function extend() {
  console.log('this gets tree shaken');
}

var utils = {
  extend: extend
};

global.keepUtilsAlive = utils;

var extend = 'this is kept';


// rollup.config.js
export default {
  entry: 'es6.js'
  , dest: 'es5.js'
  , format: 'cjs'
};


// es5.js after `rollup -c`
'use strict';

var utils = {
  extend: extend
};

global.keepUtilsAlive = utils;

var extend = 'this is kept';
```

The issue is the double declaration of `extend`, which is apparent in the tether.js distributable.  If you use the default eslint settings on their non-minified distributable, you'll see a number of "variable is already defined" errors, with `extend` being one of them.

Until that codebase is cleaned up, you should expect misbehavior from rollup.  The closure compiler also doesn't digest the double variable declarations well.

**Comment by MichaelRando** [comment]
Tether bug reference: https://github.com/HubSpot/tether/issues/187
