### ISSUE TITLE
Duplicate code when using symlinks.

### ISSUE THREAD

**Issue by youzi** [rollup/rollup#1292]
When using symlinks, we should use the realpath to handle/cache modules.

This is actually the origin of: https://github.com/rollup/rollup-watch/issues/32 — this fix can be removed when applied in the rollup core.

I have a quick fix on https://github.com/vigour-io/rollup/blob/master/src/Bundle.js#L344. I'm not familiar with the code and not sure if this is the best solution.

**Comment by ArthurClemens** [comment]
I am experiencing the same issue. In trying to pinpoint the situations where this occurs, this happens too when I copy the package to my node_modules (instead of symlinking), unless I remove the node_modules dir inside that package. It seems that the trigger is the nested node_modules dirs. But perhaps that is what @youzi was saying.

**Comment by Rich-Harris** [comment]
I *think* this might be fixed now, symlink support was improved a while back (see [this line](https://github.com/rollup/rollup/blob/304c0beaf6941b94affc43e8f2be7f37b1213f87/src/utils/defaults.js#L13)).

If that's not the case, any chance you could provide a [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff) so we can investigate? Thanks

**Comment by ArthurClemens** [comment]
I don't see the problems I had before, so I assume it has been fixed.
