### ISSUE TITLE
requires 800 lines of config file and 12 plugins to do anything.

### ISSUE THREAD

**Issue by laramiestreams** [rollup/rollup#1344]
No, I do not wish to define all of lodash to use your module.

**Comment by Rich-Harris** [comment]
Sounds like you're doing it wrong.

**Comment by Offirmo** [comment]
I would be interested in knowing how to do it right. Having a shot at rollup, blocked because I'm using lodash.
I'm searching on the web, wiki for 1 hounr already. Lodash is a trivial lib, it's usage should be covered in https://rollupjs.org/#faqs or in https://github.com/rollup/rollup/wiki/Troubleshooting
