### ISSUE TITLE
Tree-shaken external dependency reported as unused import

### ISSUE THREAD

**Issue by Conduitry** [rollup/rollup#1381]
**main.js**:

```javascript
import { c } from './foo.js';

console.log( c );
```

**foo.js**:

```javascript
import { a, b } from 'external';

export let c = a + 1;
export let d = b + 1;
```

This reports a warning of `'b' is imported from external module 'external' but never used` which I don't think it should. `b` *is* used, but the export that uses it is (apparently) getting removed before Rollup checks for which imports are used.

**Comment by Conduitry** [comment]
This was added in #1174 but the imported name merely not being activated doesn't seem like a strong enough condition for displaying this warning. I can't figure out what condition should be used though.

Is there a reason this check is happening at all? Unused imports from non-external modules don't display a warning.

**Comment by Rich-Harris** [comment]
Spelunking through the issue history, I think [this](https://github.com/rollup/rollup/issues/595#issuecomment-242715971) was the motivation:

> Would be great if Rollup could also notify about unused imports, so you'd know to clean up source files..

I'd argue that it *is* correct to say that `b` is unused, but that we should *also* point out that `d` is an unused export, since that's potentially useful information that the developer is unlikely to get any other way (since a linter can't know if an export is unused), unless they're using something like https://github.com/yamafaktory/shrimpit. 

Though it's certainly possible that it might be an external module that's importing and not using the binding, in which case it's just an annoying warning that you can't do much about. Perhaps it's better to err on the side of too much information than too little though?

**Comment by Conduitry** [comment]
I suppose I don't have that strong of an opinion about this. Since all (or at least many?) of the warnings have specific codes now, I was able to just ignore this one in the project it was affecting.

I will say that the custom `onwarn` feature is a little hard to use if I want to revert to the built-in behavior for most warning codes - I had to re-implement the existing behavior of only warning about each thing once by saving the warnings I'd already displayed. Not a huge deal, but slightly more annoying to use than it seems it has to be. Perhaps if the user-supplied `onwarn` function returned true or something, then Rollup can call its default `onwarn` function afterwards?

Would it even make sense to let `onwarn` be something that individual plugins can specify, instead of just one in the `rollup` invocation? Not sure how useful this would actually be.

**Comment by Rich-Harris** [comment]
It's not ideal, no. I've wondered about passing the default `onwarn` handler to any custom handlers as an argument, so that you'd do something like this:

```js
// rollup.config.js
export default {
  ...
  onwarn (warning, next) {
    if (warning.code !== 'THING_I_DONT_CARE_ABOUT') next(warning);
  }
};
```

Does that seem like a sensible solution?

Not sure what it would mean to allow individual plugins to specify `onwarn` handlers, since warnings can happen outside plugin responsibilities. FWIW a plugin can override `onwarn` if it's feeling naughty:

```js
export default myPlugin (opts) {
  return {
    name: 'my-plugin',
    options: options => {
      options.onwarn = warning => {
        doSomethingUnconventionalWith(warning);
      };
    }
  };
}
```

Not generally recommended though 😉

**Comment by Conduitry** [comment]
My idea about letting plugins each specify an `onwarn` wasn't very well-formed, and was something I thought of while writing that comment. Probably disregard :)

I do like the idea of giving some way of falling back to the default `onwarn` handling. Passing in the original handler as an additional argument sounds good to me, and is a bit more explicit than using a specific return value from the custom `onwarn` handler.

**Comment by Conduitry** [comment]
Now that 0.46 supports an easy way to fall back to the default warning handler, my desire for this change isn't as great. I would still argue that the warning given here isn't ideal, but I can live with it and/or I'm not actually sure how to fix it myself :)

**Comment by bdwain** [comment]
i agree with @Conduitry that this warning is not ideal. I'm running into it in a scenario where I have multiple rollup builds for my library (for exporting different files), and one of them uses only a small section of a file. Like I have a main.js file, which uses some portions of foo.js, and main2.js which uses other portions of foo.js (from the example in the original comment).

**Comment by bdwain** [comment]
i would also argue that finding unused imports/exports is more of a job for something like eslint than rollup. I would just expect rollup to clean them up silently (since cases like above aren't wrong). Eslint already can warn you if you are not using an import in your file. Finding unused exports may be harder with eslint, but they're not necessarily wrong, so having to ignore the warnings manually seems weird.

**Comment by guybedford** [comment]
This should be fixed in the latest version with https://github.com/rollup/rollup/pull/2124.
