### ISSUE TITLE
Feature request: es2015:main, es2016:main etc.

### ISSUE THREAD

**Issue by lohfu** [rollup/rollup#1401]
I've started outputting multiple bundles and use user agent strings to deliver es2015, es2016 and es2017 code to browsers depending on what features they support.

Judging by the increased release rate of ES iterations I am thinking it could be useful for library authors to be able to generate similar bundles, and specify entry files for different ES release in the `package.json`.

Something like:

```
{
  "es2015:main": "es2015/index.js",
  "es2016:main": "es2016/index.js",
  "es2017:main": "es2017/index.js"
}
```

Can anyone else see the usecase for this? Or am I completely off target?

**Comment by robdodson** [comment]
I've been thinking about this a lot as well. If I'm building a project that has the luxury of only needing to support modern browsers, for example an internal tool or app, then I'd like to be able to use the es2015 version of a package.

Another way of thinking about it is that at some point we'll need to transition off of transpiling down to es5 because there will be enough support for newer features. Creating separate build artifacts and indicating what common feature set they support seems like a possible path forward.

cc @justinfagnani

**Comment by bfred-it** [comment]
It's not a bad idea, but it should go through `node-eps` first — and that isn't happening.

**Comment by Rich-Harris** [comment]
This is a large and difficult question, with pros and cons that are difficult to weigh. I don't think Rollup should be in the position of adding support for things that aren't either a) standard or b) on the way to becoming standard, because it creates confusion and promotes fragmentation. So for that reason I'll close this issue.

The plugin API is designed to be flexible enough to allow this sort of thing on an ad hoc basis, but this is something where we'd really need community consensus around it.
