### ISSUE TITLE
Tree-shaking with Object.assign 

### ISSUE THREAD

**Issue by flashhawk** [rollup/rollup#1413]
This demo can be  Tree-shaking
[demo1](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGElMjAlN0QlMjBmcm9tJTIwJy4lMkZtb2R1bGUuanMnJTNCJTVDbnZhciUyMG9ial9hJTNEbmV3JTIwYSgpJTNCJTVDbmEuc2F5SGVsbG8oKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtb2R1bGUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTIwZnVuY3Rpb24lMjBhKCklMjAlN0IlNUNuJTVDbiUyMCU3RCU1Q25hLnByb3RvdHlwZS5zYXlIZWxsbyUzRGZ1bmN0aW9uKCklMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2coJTVDJTIyYSUyMGhlbGxvJTVDJTIyKSUzQiU1Q24lN0QlM0IlNUNuJTVDbmZ1bmN0aW9uJTIwYygpJTIwJTdCJTVDbiU1Q24lN0QlNUNuJTVDbmMucHJvdG90eXBlLnNheUhlbGxvJTNEZnVuY3Rpb24oKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZyglNUMlMjJjJTIwaGVsbG8lNUMlMjIpJTNCJTVDbiU3RCUzQiU1Q25leHBvcnQlMjAlN0JhJTJDYyU3RCUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

This demo cant't be Tree-shaking
[demo2](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGElMjAlN0QlMjBmcm9tJTIwJy4lMkZtb2R1bGUuanMnJTNCJTVDbnZhciUyMG9ial9hJTNEbmV3JTIwYSgpJTNCJTVDbm9ial9hLnNheUhlbGxvKCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybW9kdWxlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyMGZ1bmN0aW9uJTIwYSgpJTIwJTdCJTVDbiU1Q24lMjAlN0QlNUNuT2JqZWN0LmFzc2lnbihhLnByb3RvdHlwZSUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwc2F5SGVsbG8lM0FmdW5jdGlvbigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKCU1QyUyMmMlMjBoZWxsbyU1QyUyMiklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCU3RCklM0IlNUNuJTVDbmZ1bmN0aW9uJTIwYygpJTIwJTdCJTVDbiU1Q24lN0QlNUNuJTVDbk9iamVjdC5hc3NpZ24oYy5wcm90b3R5cGUlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMHNheUhlbGxvJTNBZnVuY3Rpb24oKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb25zb2xlLmxvZyglNUMlMjJjJTIwaGVsbG8lNUMlMjIpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlN0QpJTNCJTVDbmV4cG9ydCUyMCU3QmElMkNjJTdEJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

**Comment by P0lip** [comment]
The case you describe isn't a bug in my opinion. Since Object.assign might be monkey-patched or even not exist in older environments, Rollup makes a good assumption.
[Example](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGElMjAlN0QlMjBmcm9tJTIwJy4lMkZtb2R1bGUuanMnJTNCJTVDbnZhciUyMG9ial9hJTNEbmV3JTIwYSgpJTNCJTVDbm9ial9hLnNheUhlbGxvKCklM0IlNUNub2JqX2Euc2F5SGVsbG9UaGVyZSgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1vZHVsZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMjBmdW5jdGlvbiUyMGEoKSUyMCU3QiU1Q24lNUNuJTIwJTdEJTVDbk9iamVjdC5hc3NpZ24oYS5wcm90b3R5cGUlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMHNheUhlbGxvJTNBZnVuY3Rpb24oKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb25zb2xlLmxvZyglNUMlMjJjJTIwaGVsbG8lNUMlMjIpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlN0QpJTNCJTVDbmNvbnN0JTIwb3JpZ2luYWwlMjAlM0QlMjBPYmplY3QuYXNzaWduJTNCJTVDbk9iamVjdC5hc3NpZ24lMjAlM0QlMjBmdW5jdGlvbiUyMCh0YXJnZXQlMkMlMjBvYmoxJTJDJTIwb2JqMiklMjAlN0IlNUNuJTIwJTIwb3JpZ2luYWwoYS5wcm90b3R5cGUlMkMlMjBvYmoxKSUzQiUyMCU1Q24lN0QlNUNuJTVDbmZ1bmN0aW9uJTIwYygpJTIwJTdCJTVDbiU1Q24lN0QlNUNuJTVDbk9iamVjdC5hc3NpZ24oYy5wcm90b3R5cGUlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMHNheUhlbGxvVGhlcmUlM0FmdW5jdGlvbigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKCU1QyUyMmMlMjBoZWxsbyU1QyUyMiklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCU3RCklM0IlNUNuZXhwb3J0JTIwJTdCYSUyQ2MlN0QlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyaWlmZSUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

While it's an obvious edge case and is unlikely to occur often, I believe that adding support for such functions may lead to weird bugs.

**Comment by olsonpm** [comment]
Assuming you're content with P0lip's answer, mind closing the issue @flashhawk ?  Tree shaking simply doesn't fit user's expectations in a lot of scenarios, hence the caveat in the [wiki 'Troubleshooting' section](https://github.com/rollup/rollup/wiki/Troubleshooting#tree-shaking-doesnt-seem-to-be-working).

**Comment by NaridaL** [comment]
I don't really agree with @P0lip's argumentation...

If Object.assign doesn't exist in the environment, then it isn't going to run anyway and it doesn't matter what rollup does.

Sure, JS doesn't prevent you from doing `Object.assign = "lol"`, but I don't think anyone expects to be able to do that without breaking everything. For example, TypeScript's `tslib`, which provides helper functions for down-level transpilation also expects Object.assign to behave as defined in the standard: https://github.com/Microsoft/tslib/blob/master/tslib.js#L69

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
