### ISSUE TITLE
RFC: Eliminate `treeshake: false` option

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#1431]
I've come to believe that this was a short-sighted decision. Having two separate modes of operation adds a great deal of complexity to the codebase, gives us cover to deprioritise treeshaking bugs, and introduces new bugs into the bargain.

I'd like to remove it soon. Any objections?

**Comment by bfred-it** [comment]
Closes https://github.com/rollup/rollup/issues/1221

**Comment by lukastaegert** [comment]
With regard to upcoming improvements to the tree-shaking algorithm I would actually recommend against removing this option. It seems that bundling takes about twice as long for #1667 which is probably due to the more complex side-effect detection algorithm.

Therefore, turning tree-shaking off will give noticeable performance improvements once it is merged. It would even go further and make treeshaking=false the default for watch mode.

**Comment by kzc** [comment]
In addition to @lukastaegert's comments, `treeshake: false` is useful in debugging Rollup itself.

**Comment by guybedford** [comment]
I'm wondering if we need to start thinking about optimization levels for the project yet, like C++ compilers have the `-o` option.

A simple user-facing setting like `treeshaking: 'none' | 'basic' | 'full'` or something suitably descriptive could be useful. Or perhaps even just a number system with labels like C++ compilers.

There is definitely something to be said for development workflows requiring very different priorities to staging and then full production workflows.

Perhaps we could even label modes `dev`, `production` and `staging` describing use cases.

**Comment by guybedford** [comment]
Such an option could effectively stand in for a more complex default treeshaking options object, with the labels effectively acting like presets expanding into a full `treeshaking` object.

**Comment by mourner** [comment]
> It seems that bundling takes about twice as long for #1667 which is probably due to the more complex side-effect detection algorithm.
> Therefore, turning tree-shaking off will give noticeable performance improvements once it is merged. It would even go further and make treeshaking=false the default for watch mode.

On the other hand, eliminating treeshaking=false would force contributors to focus on improving the treeshaking performance overhead. @lukastaegert would you be up to removing the option if tree shaking gets "fast enough"?

**Comment by lukastaegert** [comment]
I kind of agree with @kzc here. However if your point is to assure tree-shaking performance receives the necessary attention I can assure it is currently very high in our (especially my) priorities. I have some plans for some fundamental improvements I want to try soon and of course your suggestions from #2050 will be taken into account as well.

**Comment by mourner** [comment]
> Having two separate modes of operation adds a great deal of complexity to the codebase

I just share Rich's love for simplicity in code — projects like this can very quickly grow out of control without a constant focused effort on reducing complexity — removing cruft, leftovers, even some features if they aren't essential.

**Comment by lukastaegert** [comment]
This is a valid point but there is actually not much of an alternative code path here.  Switching tree-shaking off means that all nodes are simply marked as included in one loop instead of including them conditionally. There is only three exceptions for conditional expressions, if statements and sequence expressions that also check for the presence of the `treeshake` option. Still, let's tackle performance first and then talk about this again as I see only small complexity reductions here.

**Comment by guybedford** [comment]
Let me know if anyone objects to closing this issue.

**Comment by mourner** [comment]
Yeah, I was wrong about this — `treeshaking: false` is useful. Let's close the issue.

**Comment by shellscape** [comment]
Closing per last comment.
