### ISSUE TITLE
Module loader in the browser

### ISSUE THREAD

**Issue by binarykitchen** [rollup/rollup#1465]
Is there a recipe how to solve the following?

```html
<html>
    <body>
        <script src="/dist/i-have-been-bundled-with-rollup-and-my-module-name-is-videomail-client.js"></script>
        <script>
            import VideomailClient from 'videomail-client' // <--- boooom
        </script>
    </body>
</html>
```

Before I were using `require` instead in conjunction with Browserify. But now migrating to Rollup, cannot use `var VideomailClient = require('videomail-client')` anymore.

What's the solution here? Thanks for any tips!

**Comment by bfred-it** [comment]
You'll be able to use exactly that syntax when ES modules land in the browsers. Until then, there's no mechanism like browserify's require.

But why not just use the global via the IIFE?

**Comment by binarykitchen** [comment]
Global via the IIFE? But isn't that bad practice to pollute global?

Is there a trick/library which could add the require fn alone until ES modules land in browsers meanwhile?

**Comment by bfred-it** [comment]
It is a bad practice, that's why many now use bundlers and not plain `script` tags 😃 

I think the trick would be to output a UMD bundle. It looks for a `module` or `export` globals, so if you set them before loading your umd bundle you can build your own loader.

Otherwise either you stick to browserify for the `require` bundle or use ES modules with some polyfill/loader. I think I've seen some article about that. I wouldn't suggest either. Bundling and real ES modules are the standard.

**Comment by binarykitchen** [comment]
hmmm, i would like to see some examples of that if you have any?

i want to stick to plain `script` tags here. this to keep all code in one file, very useful when you want to show examples, like this one https://github.com/binarykitchen/videomail-client/blob/feature/rollupjs/examples/simple.html ... handing this in bundled files would make examples very cumbersome to understand.

**Comment by bfred-it** [comment]
Yeah, if it's just for examples I don't see the issue of using globals. I don't think anyone will create a `VideoMailClient` global. 

I don't have any examples but all those options are documented.

**Comment by binarykitchen** [comment]
well, this is not just for examples. just want a final bundle every other library/framework can include, either with `import` or with `require` both if possible. looking for a recipe to achieve this.

**Comment by Rich-Harris** [comment]
The answer is `format: 'umd'`:

* if `define` is a function, and `define.amd` is true, then it assumes we're using something like RequireJS, and uses that
* if `module` and `module.exports` exist, it assumes we're in a CommonJS environment, and uses that
* otherwise, it creates a global variable.

Typically, this UMD file corresponds to the `"main"` field in your package.json file.

To make your library available as an ES module, you need to create a second file, corresponding to `"module"` in your package.json.

You can create both files with one rollup.config.js:

```js
// rollup.config.js
import pkg from './package.json';

export default {
  entry: 'src/main.js',
  ...,
  moduleName: 'VideoMailClient',
  targets: [
    { dest: pkg.main, format: 'umd' },
    { dest: pkg.module, format: 'es' }
  ]
};
```

```js
// package.json
{
  ...,
  "main": "dist/videomailclient.umd.js",
  "module": "dist/videomailclient.es.js",
  "scripts": {
    "build": "rollup -c"
  }
}
```

Closing this issue as there's nothing that needs to change in Rollup.

**Comment by binarykitchen** [comment]
ah, wonderful, thanks for the good summary. getting closer here now. think this should be documented somwhere.
