### ISSUE TITLE
Async transformBundle plugins

### ISSUE THREAD

**Issue by caccialdo** [rollup/rollup#1474]
Although the current version of rollup allows for `transform` method returning a `Promise`, the `transformBundle` is currently synchronous only.

cf. https://github.com/rollup/rollup/blob/master/src/utils/transformBundle.js#L11

I have a scenario where I need to run closure compiler (the Java version) in a custom plugin, over hundreds of different bundles. `transformBundle` needing to be synchronous, I'm calling the `.jar` file using `require("child_process").spawnSync`. It works but I cannot easily make the bundling tasks run in parallel.

Is there a reason for having limited the Promise handling to `transform` as part of https://github.com/rollup/rollup/pull/263 ?

**Comment by Rich-Harris** [comment]
Released as 0.45

**Comment by dnoyes** [comment]
After upgrading from 0.44.0 to 0.44.5, I'm now getting:

`> grunt rollup
Running "rollup:target" (rollup) task
Warning: bundle.generate(...) now returns a Promise instead of a { code, map } object Use --force to continue.

Aborted due to warnings.`

Here's the pertinent Gruntfile info:

`
   var babel = require("rollup-plugin-babel");

      rollup: {
            options: {
                format: "umd",
                moduleName: "...",
                plugins: function() {
                    return [
                        babel({
                            presets: [["env", {modules: false}]],
                            plugins: ["external-helpers"]
                        })
                    ];
                }
            },

    grunt.loadNpmTasks("grunt-rollup");
`

And my package.json
`
    "babel-cli": "^6.24.1",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-env": "^1.5.2",
    "grunt": "^1.0.1",
    "grunt-rollup": "^1.0.1",
    "rollup": "^0.44.0",
    "rollup-plugin-babel": "^2.7.1",
    "rollup-plugin-node-resolve": "^3.0.0",
`

Are there tips/instructions of what I need to change after upgrading to 0.45.0?

I'm running node 8.1.3 and npm 5.0.3

**Comment by Rich-Harris** [comment]
Unfortunately grunt-rollup will need to be updated to reflect the new API. Specifically, [this](https://github.com/chrisprice/grunt-rollup/blob/master/tasks/rollup.js#L79) would need to change to something like this:

```diff
return rollup.rollup({
  entry: entry,
  external: options.external,
  plugins: plugins,
  context: options.context,
  moduleContext: options.moduleContext,
  onwarn: options.onwarn
}).then(function(bundle) {

  var sourceMapFile = options.sourceMapFile;
  if (!sourceMapFile && options.sourceMapRelativePaths) {
    sourceMapFile = path.resolve(f.dest);
  }

-  var result = bundle.generate({
+  return bundle.generate({
    format: options.format,
    exports: options.exports,
    moduleId: options.moduleId,
    moduleName: options.moduleName,
    globals: options.globals,
    indent: options.indent,
    useStrict: options.useStrict,
    banner: options.banner,
    footer: options.footer,
    intro: options.intro,
    outro: options.outro,
    sourceMap: options.sourceMap,
    sourceMapFile: sourceMapFile
  });
+}).then(function (result) {

  var code = result.code;

  if (options.sourceMap === true) {
    var sourceMapOutPath = f.dest + '.map';
    grunt.file.write(sourceMapOutPath, result.map.toString());
    code += "\n//# sourceMappingURL=" + path.basename(sourceMapOutPath);
  } else if (options.sourceMap === "inline") {
    code += "\n//# sourceMappingURL=" + result.map.toUrl();
  }

  grunt.file.write(f.dest, code);
});
```

We recommend using Rollup directly (with a `rollup.config.js` file, rather than via Grunt/Gulp etc) for that reason — it's much easier to avoid these sorts of headaches.

**Comment by dnoyes** [comment]
Ahhh. Okay, I see.  That (needed) change makes sense. Thank you for the quick response.

**Comment by halfnibble** [comment]
So...what's the temporary solution for those of us with complex build processes already coded in Grunt?

**Comment by halfnibble** [comment]
FYI. There's a fix for `grunt-rollup` and all I had to do was modify my package.json file to use the latest version:
`"grunt-rollup": "^2.0.1",`
