### ISSUE TITLE
ES2015 classes mangled

### ISSUE THREAD

**Issue by MTCoster** [rollup/rollup#1484]
ES2015 classes are now [widely supported in browsers](http://caniuse.com/#feat=es6-class).  Unfortunately, Rollup seems to mangle them!  For example:

### in.js
```
class Socket {
    ...
}

const sock = new Socket();
```

### out.js
```
class Socket {
    ...
}

var Socket$1 = Object.freeze({
    default: Socket
});

const sock = new Socket$1();
```

Which results in a TypeError:
```
Uncaught TypeError: Socket$1 is not a constructor
```

Is there an option to disable this behaviour?

**Comment by Victorystick** [comment]
Your `in.js` example [works fine in the REPL](https://rollupjs.org/repl?version=0.44.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwU29ja2V0JTIwJTdCJTVDbiUyMCUyMCUyMCUyMCU1Q24lN0QlNUNuJTVDbmNvbnN0JTIwc29jayUyMCUzRCUyMG5ldyUyMFNvY2tldCgpJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).

I can massage the inputs a bit to generate a file like your `out.js`. You're likely just importing Socket wrong. Instead of importing the [Socket namespace](https://rollupjs.org/repl?version=0.44.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMFNvY2tldCUyMGZyb20lMjAnLiUyRnNvY2tldCclM0IlNUNuJTVDbmNvbnN0JTIwc29jayUyMCUzRCUyMG5ldyUyMFNvY2tldCgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnNvY2tldC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBTb2NrZXQlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==), import its [default export](https://rollupjs.org/repl?version=0.44.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMFNvY2tldCUyMGZyb20lMjAnLiUyRnNvY2tldCclM0IlNUNuJTVDbmNvbnN0JTIwc29jayUyMCUzRCUyMG5ldyUyMFNvY2tldCgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnNvY2tldC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBTb2NrZXQlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).

PS. Rollup doesn't mangle classes in any way.

**Comment by MTCoster** [comment]
You're right, this was entirely my mistake for using `import * as Socket from './socket'`, switching to `import Socket from './socket'` fixed the issue for me.  Sorry for wasting your time!
