### ISSUE TITLE
Use semvar for versioning. 

### ISSUE THREAD

**Issue by seanmclucas** [rollup/rollup#1485]
Repos that have rollup as a dependency may expect semvar-style versioning, e.g. grunt-rollup is fixed on any minor version, `"rollup": "^0.x"`. A breaking API change was added to 0.45.0, which breaks grunt-rollup. Semvar guidelines suggest using the MAJOR number (the first number) for breaking changes. 

http://semver.org/

**Comment by skyghis** [comment]
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

http://semver.org/#spec-item-4

**Comment by Rich-Harris** [comment]
@skyghis is right, this is valid semver. `npm install` shouldn't update to 0.45 if you were on 0.44, unless you specifically install the latest version.

For that reason I would strongly recommend against grunt-rollup using `"^0.x"`. Generally speaking we recommend that people use Rollup directly instead of via wrappers, because there are then fewer moving parts that can break like this.
