### ISSUE TITLE
"ReferenceError: jQuery is not defined" when using jQuery and jQuery UI

### ISSUE THREAD

**Issue by SpoonBytes** [rollup/rollup#1496]
When trying to use jQuery after importing jQuery UI, jQuery becomes undefined. Removing the jQuery UI import fixes this issue.

**Import statements from the main JS file**
```
import $ from "jquery";
import "jquery-ui";
```

**Rollup config**
```
import resolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";
import includePaths from 'rollup-plugin-includepaths';
import babel from "rollup-plugin-babel";
import uglify from "rollup-plugin-uglify";

export default {
	entry: "src/scripts/app.js",
	dest: "dist/assets/po.js",
	format: "iife",
	globals: {
		jquery: "jQuery"
	},
	plugins: [
		includePaths({
			paths: ["src/scripts/modules"]
		}),
		resolve(),
		commonjs({
			sourceMap: false
		}),
		babel({
			exclude: "node_modules/**"
		}),
		uglify()
	]
};
```

**Comment by Rich-Harris** [comment]
Can you create a [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff) please?

**Comment by oscarpr** [comment]
Hey @Rich-Harris please take a look at this repo https://github.com/oscarpr/a-autocomplete.git, i'm getting the same error. This is an ng4-cli project, and the rollup config is in the ng-package.json folder. Please, I really need help with this.

**Comment by lukastaegert** [comment]
Hi @oscarpr, thanks for the repo. Are you still experiencing this error or did you find a solution?

If not: As your setup is rather complex, can you describe which steps are necessary to produce an error and what is the exact error?

However it seems to me your issue is different from the issue described above as you are not using jQuery via imports but directly as a global.

@SpoonBytes Since this issue is a little older: Did you find a solution/workaround?

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.

**Comment by StoneCypher** [comment]
it's just impossible to find a working jquery solution 

they all get closed as inactive
