### ISSUE TITLE
React.js compatibility

### ISSUE THREAD

**Issue by petulla** [rollup/rollup#153]
Rich

Have you tried rollup with React?

Something basic like this doesn't compile with `rollup` due to jsx:

```
var createGrid = function() {
	var imagedata = [{"id":"1"},{"id":"2"},{"id":"3"}];

	var portrait = React.createClass({
	  render: function() {
	    return (
	    	<div className="commentBox">
	        <h1>Comments</h1>
	        <CommentList data={this.props.imagedata} />
	        <CommentForm />
	      </div>
	    );
	  }
	});
}

export function drawGrid() {
  return createGrid()
}
```

**Comment by lukeapage** [comment]
are you processing with something that understands jsx *first* ?

**Comment by petulla** [comment]
Just getting that setup now.. was hoping it could be integrated into rollup.

**Comment by lukeapage** [comment]
duplicate: https://github.com/rollup/rollup/issues/115

**Comment by Rich-Harris** [comment]
The most likely route is [rollup-babel](https://github.com/rollup/rollup-babel), as per #115 – support isn't yet first class, but it works (though I haven't actually tried it with JSX – you might need to add an `import React from 'react'` in each .jsx file), and #107 and #111 will get us the rest of the way there.

The issue is that vanilla Acorn (the parser Rollup uses) doesn't understand JSX, and rather than adding support to Rollup directly (e.g. via [acorn-jsx](https://github.com/RReverser/acorn-jsx)), it'd be better in the long term to focus solely on standard ES6 modules and have robust support for source code transformations. That way we can easily support JSX, CoffeeScript, TypeScript, and whatever else comes down the pike.
