### ISSUE TITLE
How do we specify a folder for pkg.module?

### ISSUE THREAD

**Issue by trusktr** [rollup/rollup#1593]
I want to tell Rollup (or Webpack 2+) that everything in a certain folder should be treated as an ES Module.

For example, someone might `import foo from "something/foo/bar"`

where `something` is a package on NPM, and `foo/bar.js` is located in `something/esmodule/foo/bar`

where `something`'s package.json contains `module: "esmodule"` or `module: "esmodule/index.esm.js"`.

How do we make Rollup understand to import files directly, not the package's index file, with each separate file being treated as ES modules (not just an entrypoint being treated as ES module but rather all files in some folder)?

**Comment by trusktr** [comment]
After experimenting, it seems that specifying a folder in pkg.module is working, as in `"module": "some-folder-containing-es2015-modules"`. Note, this folder has an `index.js` file, I haven't tested without an `index.js` file, so it may be possible that the `index.js` file is what Rollup can start at to traverse the dep graph, but I'm just guessing. I'll post back if I find out anything else.

**Comment by guybedford** [comment]
@RichHarris how would you feel about integrating the behaviour I'm trying
to spec for NodeJS here?

**Comment by Rich-Harris** [comment]
Yeah, we could do that. It would be a job for rollup-plugin-node-resolve, rather than Rollup core.

**Comment by trusktr** [comment]
@guybedford what behavior is that? Is it something that could prevent Node from using .mjs? I would love for Node not to use .mjs.

**Comment by guybedford** [comment]
@Rich-Harris with the Rollup commonjs and node resolver plugins, this does seem to work fine loading ES modules from within packages with a module property.

So it seems like from a strictness point of view there could be "strict modules" option that:
* Disable loading non-ES modules from packages with a module property in the package json for rollup-plugin-commonjs.
* Disables the ability to load ES modules that are JS files without a module property hint through rollup-plugin-node-resolve.

If you're interested in moving along these lines I'm more than happy to help with the grunt work, but since the core behaviour is effectively a strict subset of what rollup supports, this kind of strictness property could be added at any point.

**Comment by guybedford** [comment]
@trusktr the proposal is at https://github.com/nodejs/node-eps/pull/60 if you're interested.

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
