### ISSUE TITLE
missing documentation for targets option

### ISSUE THREAD

**Issue by marzelin** [rollup/rollup#1605]
While looking at [glamorous rollup configuration](https://github.com/paypal/glamorous/blob/master/rollup.config.js) I was suprised that it hasn't `dest` and `format` options specified but instead there's `targets` field.

I couldn't find any information about `targets` option at [rollupjs.org](https://rollupjs.org). I thought maybe it's some custom magic, but then I checked [rollup source code](https://github.com/rollup/rollup/blob/master/src/rollup/index.js). And yeah - it is a valid key.

Am I missing something or is it undocumented for some reason?

**Comment by fengxinming** [comment]
It really mess up with us about entry, input, dest, output and so on

**Comment by revelt** [comment]
I just checked, that Glamorous config is outdated, it's not following the [latest](https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32) spec. Now we're supposed to use either `targets` or array of `{ file, format, ... }` objects in `output`.

I couldn't find the `targets` in the official documentation so I guess this issue is still valid.

**Comment by guybedford** [comment]
`targets` is deprecated for `output` at this point and there should be a clear deprecation message on this when using it.
