### ISSUE TITLE
Transition to long options only

### ISSUE THREAD

**Issue by haraldrudell** [rollup/rollup#1641]
During a transitional period getopt supported both long ```--config``` and short options ```-c```

rollup does not have to suffer from this but should support only long options. This means:

- ```-c``` does not need to work but can maybe still be supported
- The option should be ```-config``` with a single hyphen
- ```--config``` can still work

The equal sign should be supported for optional arguments to work well. Equal signs may require the program rather than bash to expand ~. This is really difficult on Linux. An optional argument example where equal sign is beneficial is ```rollup --config= entryFile``` avoiding using ```entryFile``` as the config file.

**Comment by sholladay** [comment]
I generally prefer long options as well. But tons of tools have short options for convenience sake when you are hacking on the command line. Rollup is certainly not alone here. What exactly is the problem? Do you find the aliases to be ambiguous?

Obviously, using short options in scripts is always a bad idea. But having the tool enforce this by removing all short options seems heavy handed to me. Especially because, as things stand, you really have to futz with the shell to get autocomplete for CLI options. I'm not even sure if such a thing even exists for Rollup.

**Comment by guybedford** [comment]
It could definitely be worthwhile to switching to long flags in the documentation. There was something along these lines recently in https://github.com/rollup/rollupjs.org/pull/138, and further updates like that are welcome.

Re `=` handling, this is used when specifying the object form of input for code splitting cases. I'm not quite sure I follow the advantage of using it for `--config`, since an `--input` flag can cleanly disambiguate a following input.
