### ISSUE TITLE
module from require statement not included in globals

### ISSUE THREAD

**Issue by kentcdodds** [rollup/rollup#1646]
Hi, I'm dealing with this issue: https://github.com/paypal/glamorous/issues/334

The problem in my case is that I conditionally require the `prop-types` module, so I'm using a `require` statement. In the UMD build, I expect that to be a global `PropTypes`, however the `require` statement is not transpiled at all.

Here's [my reproduction](https://github.com/kentcdodds/rollup-require-global) and here's the relevant bits:

**config**

```javascript
const commonjs = require('rollup-plugin-commonjs')
const nodeResolve = require('rollup-plugin-node-resolve')

module.exports = {
  input: './input.js',
  output: [{file: './output.js', format: 'umd'}],
  exports: 'default',
  name: 'myLib',
  external: ['any-package-at-all'],
  globals: {'any-package-at-all': 'AnyPackageAtAll'},
  plugins: [
    nodeResolve(),
    // the include doesn't appear to make any difference here...
    commonjs({include: '**/*.js'})
  ],
}
```

**input.js**

```javascript
const AnyPackageAtAll = require('any-package-at-all')

export default AnyPackageAtAll
```

**output.js**

```javascript
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global.myLib = factory());
}(this, (function () { 'use strict';

const AnyPackageAtAll = require('any-package-at-all');

return AnyPackageAtAll;

})));
```

Am I missing something obvious?

**Comment by charlike** [comment]
> Am I missing something obvious?

Yes.

You should not add it to the the `external` option. It is meant exactly for that: a) mute warnings for unresolved dependencies; b) when using the `*-node-resolve` plugin to NOT resolve that dependencies that are in that array.

Remove these lines and try again

```
  external: ['any-package-at-all'],
  globals: {'any-package-at-all': 'AnyPackageAtAll'},
```

**Comment by charlike** [comment]
And @kentcdodds, feel free to ping me always & everywhere when you have some issues or wanderings about Rollup. (note that i changed my username recently, so ping @charlike and not @tunnckoCore ;d)

**Comment by kentcdodds** [comment]
> Remove these lines and try again

That didn't seem to make any difference in the output 🤔 

> feel free to ping me always & everywhere 

Thank you :) I'll keep that in mind :wink:

**Comment by revelt** [comment]
hi guys, where are we stuck with this issue? It still needs to be taken care of, doesn't it?

**Comment by lukastaegert** [comment]
Rollup now has dynamic `import(...)` statements if you enable `experimentalDynamicImports` which *could*  help with your issue (and is the "official" JavaScript way of doing this).

As for this particular example, vanilla rollup will probably never support `require` as rollup is built around ES6 modules and there is no way to translate a dynamic require statement into ES6 without some kind of runtime. That is why `rollup-plugin-commonjs` will probably not be able to help you as well even if you try to patch it.

Sorry for the bad news but maybe it is possible for you to handle your issue asynchronously and use `import().then()` or otherwise if it is running in a Node environment and 'any-package-at-all' is external, provide a small wrapper library that handles the `require` which is then imported again as an external dependency by a rollup CJS bundle.

**Comment by guybedford** [comment]
The thing to note here is that "hybrid" ES modules that are also CommonJS modules is not a supported pattern. If NodeJS were to support this, we could consider doing that as well, although it would introduce a lot of build complexity for Rollup in double linking these cases.

**Comment by arizonatribe** [comment]
@kentcdodds I ran across this same issue. I built an NPM package last year that I hadn't started using in a create-react-app scaffolded UI until a few days ago, which is when I noticed the same issue you reported.

The NPM package I have is just a couple of small files scooped up in one root `index.js`, but when the UMD build is being created those `require` statements are being left in the final output. [My rollup config](https://github.com/arizonatribe/machines/blob/master/rollup.config.js) is very similar to yours (I'm not using the `rollup-plugin-commonjs` or using `externals` though), but I based mine initially off of [the rollup config from Redux](https://github.com/reduxjs/redux/blob/master/rollup.config.js#L53). I went back to theirs to see if they're solving it any differently, but there's really not much difference (nothing that seems relevant in the `rollup.config.js` at least). Yes they are using ESNext `imports`/`exports`, but otherwise there's nothing different I could identify.

But with fingers crossed I updated from my locked-in version of `rollup` and all the plugins in my `package.json` to match the semvers specified in the Redux `package.json`, and it actually worked this time! Maybe give it a try to see if it works for you too, and if so, I guess it's something that got accidentally fixed in a version of rollup or one of the associated plugins.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
