### ISSUE TITLE
how to use worker in rollup

### ISSUE THREAD

**Issue by songguangyu** [rollup/rollup#1677]
I use Worker in rollup ，no plugin resolve it and resolve worker js dependencies , can you help me？

**Comment by songguangyu** [comment]
![image](https://user-images.githubusercontent.com/6869168/31594647-e0acb756-b1fb-11e7-9264-1e18d5e19edd.png)

worker.js like this。

**Comment by sholladay** [comment]
Hi @songguangyu, there is not enough information here for someone to help you.

Check out https://stackoverflow.com for general support and help with how to use open source projects like Rollup. The issue tracker is better for submitting bug reports. An example of a good issue would be https://github.com/rollup/rollup/issues/1685, mainly because it has links to real code and a small, reproducible example.

My best guess is that this line...

```js
import Mp4decode from '../mp4decode';
```

... needs to be ...

```js
import Mp4decode from 'mp4decode';
```

I'm guessing that because it seems like it would be the name of an external library. Though, I don't see any such library at https://npmjs.com/mp4decode and I really have no way of knowing without seeing your project. I'm happy to try to help more if you post a more detailed question on StackOverflow and provide a link on here to the question.

**Comment by guybedford** [comment]
Web worker workflows with Rollup are definitely something the project could improve and this is important to track. But we need to consider tangible proposals for how Rollup can assist with this process.

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
