### ISSUE TITLE
Namespace collision regression 

### ISSUE THREAD

**Issue by coryjones1** [rollup/rollup#1708]
There is an issue where we import from an external library in one file and import internally with the same import name in another file.  This occurs when using the transform-deorators-legacy babel plugin and babel-preset env stage-1.  Using a static class variable in the container class triggers this behavior.

https://gist.github.com/coryjones1/b790455a2f2da4b7c3ba2748e8e391cc

**Comment by coryjones1** [comment]
https://github.com/rollup/rollup/blob/8365bb1a1ddcf63ea564fb2b25d897a155ac9d72/src/ast/variables/ExternalVariable.js#L32

**Comment by coryjones1** [comment]
https://github.com/rollup/rollup/commit/8365bb1a1ddcf63ea564fb2b25d897a155ac9d72

**Comment by jsg2021** [comment]
The commit referenced by @coryjones1 is the commit that broke for us.

**Comment by lukastaegert** [comment]
Hi,
thanks for posting this issue. I am actually a little baffled as to why this causes problems for you. Especially since I did not touch the dependency resolution logic here or in any of the previous commits–there are a few fishy things going on and I wanted to finish tree-shaking first.
My strong suspicion is that this was actually broken before and only brought to light by the fix you mention.
Questions:
* Are you using the pureExternalModules flag? If so, was it working in previous versions when this flag is turned to false?
* Does it work when you set treeshaking: false in your config? (If you turn it off, the changed code will not even be executed). If it is not working: Is it working in previous versions?

**Comment by jsg2021** [comment]
The gist has the a reproduction. The babel & rollup configs are there. I don't think we have pureExternalModules... I'm not even aware of what that is?

The `<Input/>` is referencing the wrong variable. It should have been renamed.  `0.50.0` works as expected for this case.

**Comment by jsg2021** [comment]
adding `external: ['some-external']`, `pureExternalModules: true`, and toggling `treeshaking: false` has no effect... 

the output has: (0.51.2)
```js
		value: function render() {
			return React.createElement(Input, null);
		}
```
when it should have: (0.50.0)
```js
		value: function render() {
			return React.createElement(SearchProviderInput, null);
		}
```

**Comment by jsg2021** [comment]
The incorrect output starts with `0.50.1`

**Comment by jsg2021** [comment]
I will concede that the the referenced commit may not be the cause... based on the changelog that was the only code change in the release, but looking at the commits, that's not true.

**Comment by jsg2021** [comment]
The funny thing is ...if you comment out or remove the `static someStatic = 5` line, the `Input` reference is correctly renamed.
