### ISSUE TITLE
pkg.module wiki page

### ISSUE THREAD

**Issue by kamleshchandnani** [rollup/rollup#1713]
I guess this section needs to be updated as per the recent changes to browsers?
#### Wait, it just means import and export – not other future JavaScript features?
Source: https://kangax.github.io/compat-table/es6/

Can I send a PR for this?

**Comment by lukastaegert** [comment]
Though I think some things could still be updated. As far as I know, `pkg.module` is now the accepted standard and one should no longer use `jsnext:main`. On the other hand, there is a move to use `esnext` for untranspiled sources: http://2ality.com/2017/06/pkg-esnext.html. Not sure this is supported by rollup, though.

**Comment by michael-ciniawsky** [comment]
`pkg.main` (CJS) `node` NodeJS only
`pkg.module` (ESM) `node --experimental-modules && <script src=""  type="module"></script>` Both
`pkg.browser` (UMD/AMD/...)  `<script src=""></script>` Browser only

These fields are about the parsing goal (Module System), ES2015+ features etc a unrelated to these fields in particular and a separate transpilation step maybe required (e.g during 'app' bundling). `npm` could add browsers to `pkg.engines`.  `pkg.esnext` is bananas 😛

**Comment by damianobarbati** [comment]
I honestly think this statement does not make much sense:
`...you should transpile them if you want your library to work in environments that don't support those features. Otherwise, whoever uses your library will have to transpile it themselves, including configuring their transpiler to handle your code...`
And the approach of transpiling on behalf of consumer is wrong as well.

1. Publishing `transpiled sources` instead of `plain sources` forces consumer to include unnecessary code: how can a pkg publisher assume what environment the consumer will be transpiling/targeting?

2. If they're using the `module` entry thus nowadays JS/packaging features then consumer is most likely transpiling as most of web app developers. If he is not (jQuery/raw html + plugin websites) they can simply resort to the old `main` entry with the bloated js file.

So if we really want to promote `module` entry as the *future* of javascript, we should target developers and their custom environment first and not assuming "browser targets" and environment of whatever sort.

I think we're confusing "ES compatibility" (class, const, arrow syntax, async/await etc) with "browser compatibility" (localStorage, websockets, etc etc). 
Compatibility between a pkg and a browser should be dictated by the latter and not the former, since ES can be transpiled down to whatever needed specification of ECMAScript (in some cases not true but negligible) but features can not be shipped.
This last statement is also "platform" agnostic because it applies to both browsers and node.

My personal (and just personal view) on a better pkg handling:
- we need an entry for untranspiled sources destined to browser bundling (which should be `module` or `esnext`)
- we already have the `browserslist` to dictate compatible browsers (features, not ecma specs): developer can act accordingly (babel-preset-env)
- we need an entry for untranspiled (or transpiled if needed) sources destined to node usage
- we already have the `engines` to dictate compatible node versions (features and ecma specs)
- isomorphic pkgs like `momentjs` should transpile the node entry 

Just thoughts as always, keep up the good work 🤙🏻

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
