### ISSUE TITLE
[0.51.5] still get unused curried function code.

### ISSUE THREAD

**Issue by UncleBill** [rollup/rollup#1726]
Hey, thanks for this awesome tool!!
I got following issue:

## main.js
```javascript
import {foo} from './utils'
foo()
```

## utils.js
```javascript
function curry(val) {
	var cahced = window.__cached__;
	return function () {
		cahced['digit'] = val;
		console.log('given digit', val)
	}
}
export var curried = curry(1);
export function foo () {
	console.log('hello world');
}
```
## output
```javascript
function curry(val) {
	var cahced = window.__cached__;
	return function () {
		cahced['digit'] = val;
		console.log('given digit', val);
	}
}
var curried = curry(1);
function foo () {
	console.log('hello world');
}

foo();
```

## expect output
``` javascript
function foo () {
	console.log('hello world');
}

foo();
```

### repl
https://rollupjs.org/repl?version=0.51.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmZvbyU3RCUyMGZyb20lMjAnLiUyRnV0aWxzJyU1Q25mb28oKSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ1dGlscy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJmdW5jdGlvbiUyMGN1cnJ5KHZhbCklMjAlN0IlNUNuJTVDdHZhciUyMGNhaGNlZCUyMCUzRCUyMHdpbmRvdy5fX2NhY2hlZF9fJTNCJTVDbiU1Q3RyZXR1cm4lMjBmdW5jdGlvbiUyMCgpJTIwJTdCJTVDbiU1Q3QlNUN0Y2FoY2VkJTVCJ2RpZ2l0JyU1RCUyMCUzRCUyMHZhbCUzQiU1Q24lNUN0JTVDdGNvbnNvbGUubG9nKCdnaXZlbiUyMGRpZ2l0JyUyQyUyMHZhbCklNUNuJTVDdCU3RCU1Q24lN0QlNUNuZXhwb3J0JTIwdmFyJTIwY3VycmllZCUyMCUzRCUyMGN1cnJ5KDEpJTNCJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwZm9vJTIwKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCdoZWxsbyUyMHdvcmxkJyklM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by UncleBill** [comment]
updated

**Comment by anilanar** [comment]
Btw, how would rollup know whether `window.__cached__` is not a getter with side effects?

E.g. `Object.defineProperty(window, '__cached__', { get() { destroyTheWorld(); return {}; } })`

**Comment by lukastaegert** [comment]
@anilanar You are correct, this is the issue here. I plan on adding an option in the future to disable this behaviour (but then it is up to you to make sure you do not trigger any getters).

**Comment by nathancahill** [comment]
I'd love to see that option. Something like `saneGetters: true`. The other route is to use a pure annotation like UglifyJS2. I opened this proposal for a pure annotation earlier this year: #1293.

**Comment by lukastaegert** [comment]
Right now there are two things rollup guards against when determining whether object property access could have a side-effect:
* If it is possible a getter was triggered
* If it is possible an "undefined is not an object" error was triggered (i.e. you might use `try...catch` to check if a property exists)

I plan on adding an option that deactivates both of these checks at once as for most of the code, this is basically the same check. As this is not solely about getters, the option should probably have a different name. I though about something like `trackPropertyAccess: true/false` (defaults to `true`), but I am certainly open for better suggestions that reflect the above behaviour.

**Comment by kzc** [comment]
@lukastaegert Historically Rollup assumed that properties reads and unknown global variable reads are side effect free. I see the default now is to preserve property reads but the unknown globals are still dropped:
```
$ bin/rollup -v
rollup version 0.51.8
$ cat g.js
Unknown;
$ bin/rollup g.js -f es --silent | node
$ cat g.js | node
[stdin]:1
Unknown;
^
ReferenceError: Unknown is not defined
```
I'd suggest two configuration options to match the current behavior:
1. `property_read_side_effects` defaulting to `true`
2. `unknown_variable_read_side_effects` defaulting to `false`

Invalid property reads or chains of invalid property reads such as `obj.no_such_prop` or `obj.no_such_prop.no_such_prop` would be dropped if `property_read_side_effects` is `false`.

**Comment by kzc** [comment]
The proposed config options above could accept either a boolean or an array of strings for names. For example:
```
// all property reads assumed to be side-effect-free 
// except for `obj.foo` and `obj.bar`
property_read_side_effects: [ "foo", "bar" ],
```

**Comment by lukastaegert** [comment]
Yes, accessing unknown globals is no side effect. The reason is mainly that global handling is somewhat limited right now and uses solely the list of pure functions to determine what can be accessed. Since I did not want each access to `window` to be a side-effect, I decided to start access side effects for globals one layer deeper for now. I plan to refine this behaviour once I start to rework global handling.

I like `property_read_side_effects` as it is very clear to the point. I also like the other option but as stated above, this depends on a reworked global variable handling. If this is done, I would actually set the default to `true` for this option as well.

**Comment by lukastaegert** [comment]
About the array form of the attribute, I would put the actual form of the access into the array, otherwise you might add a lot of unnecessary side-effects:
```
property_read_side_effects: [ "obj.foo", "obj.bar" ]
```
What do you think?

**Comment by kzc** [comment]
> About the array form of the attribute, I would put the actual form of the access into the array, otherwise you might add a lot of unnecessary side-effects:

The impact wouldn't be as bad as you might think. One would hope that the programmer would choose unique property names for getters with side effects.

> `property_read_side_effects: [ "obj.foo", "obj.bar" ]`

I'm not in favor of this idea. Once the variables names are mangled by a minifier the notation above would be effectively useless. Property names are less commonly mangled in programs due to bugs created with keys being generated programmatically at runtime.

But your proposal is not incompatible with mine - technically the `"obj.prop"` and `"prop"` nomenclature is (mostly) non-overlapping barring variable name mangling coincidentally coming up with `obj` in large programs:
```js
property_read_side_effects: [ "fiz", "baz", "obj.foo" ],
```
Another wrinkle is how to specify a property read side effect for something like `obj["key with a space"]`. As absurd as it may be, there ought to be a way.

**Comment by lukastaegert** [comment]
I have implemented the simplest solution, i.e. no array version, in #1760 now. If there ist demand for more fine-grained control, we can always add this later.
I decided to use camel-case instead of snake-case so that it looks nicer in the config and better fits the other multi-word option, `pureExternalModules`. But of course we could also rename both options before merging this PR as I moved `pureExternalModules` anyway. Further comments please at #1760.

**Comment by lukastaegert** [comment]
Am I correct in assuming that the new `treeshake.propertyReadSideEffects` option also solves this issue?

**Comment by UncleBill** [comment]
@lukastaegert I will test it tomorrow.

**Comment by UncleBill** [comment]
I confirm that it's fixed! Thanks! 💯
