### ISSUE TITLE
Treeshaking fails for named CJS exports

### ISSUE THREAD

**Issue by digitalkaoz** [rollup/rollup#1729]
2 use cases:

```js
//a.js
module.exports = () => {console.log("a")}

//b.js
module.exports = () => {console.log("b")}

//entry.js
const a = require("./a");
const b = require("./b");

a();
```

> treeshaking works fine (no `b` is included)

but this one fails:

```js
//deps.js
module.exports.a = () => {console.log("a")}
module.exports.b = () => {console.log("b")}

//entry.js
const {a} = require("./deps");

a();
```

> treeshaking fails, (`b` is included)

so it seems that treeshaking fails for named exports with CJS modules

**Comment by kzc** [comment]
If you're going to use ES6 constructs in a given file, you may as well do this:
```js
import {a} from './deps.js';
a();
```
to produce:
```js
var a = () => {console.log("a");};
a();
```

**Comment by digitalkaoz** [comment]
@kzc but there treeshaking works as designed...

**Comment by kzc** [comment]
I thought you wanted a workaround. Fair enough.

The core issue is that `rollup@0.51.2` cannot reduce ES6 destructuring statements:

```js
$ cat d.js
const {a} = {a:1, b:2};
console.log(a);
```
```js
$ bin/rollup d.js -f es --silent
const {a} = {a:1, b:2};
console.log(a);
```

**Comment by digitalkaoz** [comment]
ah ok i think im getting into it, so:

```js
//esm.js
export foo = () => console.log("foo");
export bar = () => console.log("bar");
```

is not the same as 

```js
//cjs.js
module.exports.foo = () => {console.log("foo")}
module.exports.bar = () => {console.log("bar")}
```

? with cjs its (in reality??)

```js
const foo = () => {console.log("foo")}
const bar = () => {console.log("bar")}

module.exports = {
    foo,
    bar
}
```

?

**Comment by kzc** [comment]
The issue is not with the exports and `rollup-plugin-commonjs`, but with how the code is imported.

**Comment by digitalkaoz** [comment]
ok so its a general problem, but the code works in the end, so i guess its okish... should i leave it open for further treeshaking todos or should i close this issue?

**Comment by kzc** [comment]
Although it's unusual to use a destructuring `require()` rather than an `import`, it's valid code. I defer to the Rollup maintainers.

**Comment by lukastaegert** [comment]
This is an issue that could be solved both in rollup-plugin-commonjs and in rollup itself. I agree with @kzc that the problem is your import style. These are the two possible solutions from our side that I see:
* In rollup-plugin-commonjs: Transform `const {a} = require("./deps")` -> `import {a} from "./deps"`. I do not recommend this, however. If `a` is only exported dynamically, the plugin will not add `a` as a named export and rollup will fail even though the code is valid.
* Improve tree-shaking in rollup to trace destructuring. This is certainly possible and I hope we will implement this at some point. Note however that this is rather low priority at the moment. Nevertheless, yes, we should keep this open until we can do that.

**Comment by kzc** [comment]
>  I do not recommend this, however. If `a` is only exported dynamically, the plugin will not add a as a named export and rollup will fail even though the code is valid.

I've never seen this is the wild, but anything is possible with CommonJS.

**Comment by nathancahill** [comment]
> I do not recommend this, however. If a is only exported dynamically, the plugin will not add a as a named export and rollup will fail even though the code is valid.

In my experience, it's common in the wild. The extended answer to this is to use the `namedExports` option, ie.:

```js
namedExports: {
    './deps': ['a'],
}
```

**Comment by lukastaegert** [comment]
True. Not sure we should add a rule to rewrite certain destructuring require statements based in the presence of this option considering that the plugin's code is quite convoluted already. Though, if someone would submit a PR that implements this while cleaning up the code base so that it is MORE readable…

Still, I think we should fix this on rollup core side by improving the way destructuring is handled.

**Comment by guybedford** [comment]
Tracking destructuring in https://github.com/rollup/rollup/issues/2272.
