### ISSUE TITLE
Feature Request: per-output-file external

### ISSUE THREAD

**Issue by jasonkarns** [rollup/rollup#1755]
The `external` option is a top-level option, which means it applies to all output files. However, that's not always desirable. Scenario:

- CJS build for node with, say, lodash, as an `external` (that will be required at runtime via node `require`)
- UMD build for browser that should _bundle_ lodash

The same request exists for having plugins be per-output file as well. Some plugins, like the commonjs or node-resolve plugins would only make sense for the UMD module described above as it needs to read in lodash dep at build time, whereas those plugins do not apply to the CJS build that leaves lodash as an `external`.

**Comment by lukastaegert** [comment]
Hi @jasonkarns, I understand this makes sense from a user perspective. From an internal perspective, however, the question if dependencies are resolved or not has a profound effect on core features like Rollup’s scope hoisting and tree-shaking. Hence such a feature would probably not grant you any performance benefits as compared to the currently available feature of passing an array of configuration objects to Rollup (we have just updated the documentation to better present this feature). Note that due to the programmatic nature of Rollup’s configuration, you can already use standard JavaScript features like `Object.assign` to share information between otherwise unrelated configuration objects.

Therefore I would argue against implementing this.

**Comment by jasonkarns** [comment]
👍  I hadn't actually seen the array config option until later, but it works for me! (Well, with the exception of https://github.com/rollup/rollup-plugin-babel/issues/179

**Comment by lukastaegert** [comment]
Well, it was hard to see considering the documentation was not really up to date 😜 Thanks for the heads up!
