### ISSUE TITLE
suggestion: support object spread without babel?

### ISSUE THREAD

**Issue by DrYSG** [rollup/rollup#1757]
Now that it is widely supported, any chance of supporting format: 'es' packages that use object spread without having to use the babel plugin (the code we write is largely targeted to evergreen browsers, and we use es format).

```
let path = {...thePath}
```
gives a syntax error with the current rollup

**Comment by nathancahill** [comment]
This is a different issue than the one fixed by that PR. This applies to the compiled code vs the compiled config.

**Comment by lukastaegert** [comment]
Thanks @nathancahill, I have removed the label.

@DrYSG I understand that this is something many people are interested in but I am against enabling it as
* object rest spread is still a stage-3 JavaScript feature (official features are stage-4) and
* for that reason is not natively supported by our parser acorn

To enable it, I see two possible paths:
* Do automatic transpilation. This is not something I support. Transpilation has never been a concern of rollup. As a user, you can instead include `rollup-plugin-babel` and just do a targeted transpilation of object rest spread.
* Use a different parser. Again this is something I do not support. We might in the future find a way to allow plugins to change the parser but for rollup core, restricting ourselves to official language features seems more reasonable to me.

Once object rest spread has reached stage-4 and is supported by acorn, rollup will support it natively as well.

**Comment by DrYSG** [comment]
@nathancahill sounds good to me, I was only noticing that browser Chrome and FireFox support it. I as a clear policy approach, I think you are correct to wait.

**Comment by adrianheine** [comment]
`rollup-plugin-buble` can also transpile this and is probably much faster than babel. Also, there are acorn plugins for parsing it (for example [mine](https://github.com/adrianheine/acorn5-object-spread)), so in theory adding (pass-through) support for it in rollup wouldn't be too difficult.
