### ISSUE TITLE
JSON.parse call is stripped from the output ( Reproducible )

### ISSUE THREAD

**Issue by thetutlage** [rollup/rollup#1775]
Haven't find any existing issue for same. Sharing the REPL example, where `JSON.parse` statement has been removed from the code.

[Reproduce here](https://rollupjs.org/repl?version=0.52.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAoaW5wdXQpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHRyeSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBKU09OLnBhcnNlKGlucHV0KSU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjB0cnVlJTVDbiUyMCUyMCU3RCUyMGNhdGNoJTIwKGUpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMGZhbHNlJTVDbiUyMCUyMCU3RCU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by adrianheine** [comment]
This is wrong, but to be expected, since `JSON.parse` is marked as a pure function.

**Comment by lukastaegert** [comment]
I agree, maybe marking JSON.parse as pure was wrong since throwing errors is part of its interface. Note that this call is only removed because you are not reusing the result. Still, I think this should be changed and we should add a small test similar to your example so that this use case is not forgotten.

**Comment by adrianheine** [comment]
`JSON.stringify` throws on circular structures, so maybe that's not pure either?

**Comment by lukastaegert** [comment]
I get a feeling there is some thin line here we might cross at some point but yes, I guess you are correct. I think once we implement `/*#IMPURE*/` annotations, see #1771 , we might at the same time finally start parsing `/*#PURE*/` annotations so that people can make their JSON interactions tree-shakeable again.
