### ISSUE TITLE
Binary files become corrupted by Rollup's default load function

### ISSUE THREAD

**Issue by dfrankland** [rollup/rollup#1786]
I am working on some WebAssembly Rollup plugins which transform binary wasm files, and I stumbled upon an issue with Rollup where some binary files get their contents jumbled up a bit.

This seems to be caused by the loading of files as `utf-8`: https://github.com/rollup/rollup/blob/master/src/utils/defaults.js#L6-L8

Here's nice reproduction of the problem here: <https://github.com/dfrankland/rollup-bad-binary-issue>

My current version of Node is `v8.9.0` on macOS High Sierra 10.13.1.

**Comment by dfrankland** [comment]
It may have something to do with character encoding actually:

This is a slice of the string returned by Rollup:
```
asm�!````~```````~~`~~`~~~~`~~~~`~~~
```

And here is a slice of the string from the file:
```
asmÆ!````~```````~~`~~`~~~~`~~~~`~~~
```

**Comment by TrySound** [comment]
I believe it's related to https://github.com/rollup/rollup-plugin-wasm

**Comment by dfrankland** [comment]
@TrySound, I am not using that plugin, I am developing my own: https://github.com/dfrankland/wasm-module-preprocessors/tree/master/packages/rollup-plugin-wasm-module

This bug is caused by [Rollup's default `load` function using `utf-8`](https://github.com/rollup/rollup/blob/master/src/utils/defaults.js#L6-L8). I tried adding a `load` function to my plugin, but that causes _all_ files to load with that function due to this bit of code: https://github.com/rollup/rollup/blob/master/src/Bundle.js#L82

Ideally, some plugins would be able to receive code as binary or Buffers, and the rest would use the default `load` function that uses `utf-8`.

**Comment by TrySound** [comment]
@dfrankland PR is appreciated.

**Comment by guybedford** [comment]
We're working on a core WebAssembly approach in https://github.com/rollup/rollup/pull/2113, where we'd have a new type of WasmModule to support binary loads etc. Feedback would be welcome on the work there.

**Comment by dfrankland** [comment]
Oh cool, I'll check it out and follow along 👍

**Comment by guybedford** [comment]
If emitting binary files, the recommended approach now is through the `this.emitAsset('name.wasm', buffer)` in the plugin API. Load should always return a string.

**Comment by shellscape** [comment]
@guybedford reading through this (and not quite up to speed on core yet) a question struck me: what would the ramifications be if we asserts that load were to return a buffer rather than string, in the future?

**Comment by guybedford** [comment]
@shellscape thanks for picking up on the history here, it really helps having a chance to review and go through these things again. So we could definitely allow `load` to return a Buffer, I'm just not sure what the benefit would be for that over a string as we would just call `.toString()` anyway. For WASM support, the issue isn't really about Buffer v string, but more about working out if the source is a WASM file or a JS file. This could be done with a type flag being returned, or we could use a Buffer to represent this difference semantically though certainly, making the Buffer return specifically mean WASM, and implemented along with the WASM work. Worth considering though that other buffer formats may be needed in future (eg Binary AST), so that a flag is probably more future-proof anyway. That is, I'd actually recommend - `return { code: Buffer, type: 'wasm' }` for the WASM return in `load`.

**Comment by guybedford** [comment]
(the `emitAsset` suggestion above is about how to implement WASM plugins today, while the wasm core is still being developed)
