### ISSUE TITLE
Can't include renamed dependencies

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup#182]
This `package.json`
```json
{
  "dependencies": {
    "a": "https://git-xyz.com/user/b.git"
  }
}
```
creates the following `node_modules` directory.
```
node_modules/
  b/
```

Attempting to import `a`
```js
import a from 'a';
```
throws:
```
Could not find package a
```

An external `npm` resolver should take this into account, and import `b`.

**Comment by Victorystick** [comment]
@Rich-Harris I've been trying to look for some documentation about this. Browserify doesn't seem to handle this either. Could it be expected behaviour not to find the package?

**Comment by heavyk** [comment]
I had a similar problem (not this exact one but close enough).

 it is intended that if your package.json says `"lala": "someuser/somepkg"` then it will install not install into `node_modules/lala` but into `node_modules/[name in somepkg/package.json]`

so, say somepkg's name was really `my-module` - it would get installed to `node_modules/my-module`. always. I didn't realize this was such a big issue until I investigated, but it is. so that is expected behaviour.

for reference: https://github.com/npm/npm/issues/5499

**Comment by Flaise** [comment]
Node doesn't support that either. It looks in containing folders for modules_folders, not subfolders. It's worth noting that npm 3 flattens your dependencies as much as it can so under certain conditions Node or Browserify may find a module by accident that their algorithms are not guaranteed to support.

**Comment by Rich-Harris** [comment]
Crikey – that issue @heavyk references speaks to how complex this is. I suggest we side-step the issue entirely and promote custom resolvers as the solution to this – once we're happy with #207, it could look like this:

```js
rollup.rollup({
  entry: 'main.js',
  plugins: [
    require( 'rollup-plugin-alias' )({
      a: 'node_modules/b'
    })
  ]
}).then(...)
```

That way, any opinions that turn out to be harmful are contained to the plugin, and Rollup itself doesn't need to do anything controversial.

**Comment by heavyk** [comment]
:+1: :+1: I really like that idea a lot

**Comment by Victorystick** [comment]
Good. I'll close this then.
