### ISSUE TITLE
Treeshaking pure external functions

### ISSUE THREAD

**Issue by basav22** [rollup/rollup#1829]
Hi, I am unable to understand why is dead code (AgroButtonDefault in this case). Please help me understand 

Please find below repl -

https://rollupjs.org/repl?version=0.53.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEFncm9CdXR0b25QcmltYXJ5JTIwJTdEJTIwZnJvbSUyMCcuJTJGYnV0dG9uLmpzJyUzQiU1Q24lNUNuZXhwb3J0JTIwJTdCQWdyb0J1dHRvblByaW1hcnklN0QlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYnV0dG9uLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHN0eWxlZCUyMGZyb20lMjAlNUMlMjJzdHlsZWQtY29tcG9uZW50cyU1QyUyMiUzQiU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMCUyMGlzbid0JTIwdXNlZCUyMGFueXdoZXJlJTJDJTIwc28lNUNuJTJGJTJGJTIwUm9sbHVwJTIwc2hvdWxkJTIwZXhjbHVkZXMlMjBpdCUyMGZyb20lMjB0aGUlMjBidW5kbGUuLiUyMGJ1dCUyMGl0JTIwYnVuZGxlcyU1Q25leHBvcnQlMjBjb25zdCUyMEFncm9CdXR0b25QcmltYXJ5JTIwJTNEJTIwc3R5bGVkLmJ1dHRvbiU2MCU2MCUzQiU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMGZ1bmN0aW9uJTIwZ2V0cyUyMGluY2x1ZGVkJTVDbmV4cG9ydCUyMGNvbnN0JTIwQWdyb0J1dHRvbkRlZmF1bHQlMjAlM0QlMjBzdHlsZWQuYnV0dG9uJTYwJTYwJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

**Comment by guybedford** [comment]
@lukastaegert a `treeshake.pureExternalFunctions = [{ id: 'styled-components', name: 'button' }]` perhaps!?

**Comment by lukastaegert** [comment]
@basav22: The issue is that rollup will always assume that external functions (which includes tag functions of tagged template literals as in this example) have side-effects. Both the definitions of the "primary" and the "default" button call the function "styled.button()" - and this function is called when the module is initialised and not when the buttons are actually used.

@guybedford 's suggestion of adding an option to list pure external function sounds good to me. 

Additionally, we could start supporting UglifyJS `/*@__PURE__*/` annotations. There already is an issue for that (#1293) and it might be a good idea to implement this together with a complementary `/*@__KEEP__*/` annotation to resolve #1771 .

In any case I would classify solving this problem as an interesting enhancement. Further suggestions are always welcome.

**Comment by lukastaegert** [comment]
I have taken the liberty to slightly adjust the issue title

**Comment by acewf** [comment]
i resolved the issue by adding `{ modules: false }` on the babel loader present
```
{
   loader: 'babel-loader',
   options: {
       presets: [
            ["@babel/preset-env", { modules: false }],
            ["@babel/preset-react", { modules: false }]
       ],
   }
}
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
