### ISSUE TITLE
Unused import statement is being modified to import entire dependency

### ISSUE THREAD

**Issue by alan-agius4** [rollup/rollup#1833]
I have an unused import like such; 
```js
import { someMethod } from 'some-extrnal-deps';
```

with rollup this is converted to:
```js
import 'some-extrnal-deps';
```

Reproduction
https://rollupjs.org/repl?version=0.53.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFlvdSUyMGNhbiUyMGltcG9ydCUyMGV4dGVybmFsJTIwbW9kdWxlcyUyMGludG8lMjB5b3VyJTIwYnVuZGxlJTIwJUUyJTgwJTkzJTVDbiUyRiUyRiUyMGl0JTIwZG9lc24ndCUyMG1hdHRlciUyMGlmJTIwdGhleSdyZSUyMEVTMjAxNSUyMG9yJTIwbGVnYWN5JTVDbmltcG9ydCUyMCU3QiUyMHNvbWVNZXRob2QlMjAlN0QlMjBmcm9tJTIwJ3NvbWUtZXh0cm5hbC1kZXBzJyUzQiU1Q24lMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

While having an unused import is not correct, I don't think this is this transformation is still not correct I believe.

**Comment by lukastaegert** [comment]
This transformation is in fact correct. `import 'some-extrnal-deps'` is not importing the "entire" dependency (otherwise, there would be a `from` and variables that things are assigned to). Rather, it is just running the synchronous initialisation code of the external dependency. As we cannot be sure that the dependency does not create global variables or logs to the console etc., this is necessary to keep all possible functionality working.

The option `treeshaking.pureExternalModules` can be used to signal that external dependencies indeed do not have side-effects in their initialisation code. If you set this option, the unused import will be removed entirely.
