### ISSUE TITLE
JSON (object property) tree shaking

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#1838]
This issue is totally not in response to anything going on with other projects.

Example scenario - https://rollupjs.org/repl?version=0.53.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGJhciUyMGZyb20lMjAnLiUyRmJhci5qcyclM0IlNUNuJTVDbm1vZHVsZS5leHBvcnRzJTIwJTNEJTIwYmFyLnNvbWUlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYmFyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAlN0IlNUNuJTVDdHNvbWUlM0ElMjAndmFsdWUnJTJDJTVDbiU1Q3Rhbm90aGVyJTNBJTIwJ3ZhbHVlJyU1Q24lN0QlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by lukastaegert** [comment]
Except that you seem to be mixing module types, it seems you want something like #501? (Or, not quite unrelated, #349?) Yes, that would be really great. The main unsolved problem is how to bail out of this when
* computed properties are accessed that cannot be resolved
* the variable is exported
* the variable is passed to a global or external function that may behave differently depending on the presence of object members

Beyond that, I have marked this personally as my "holy grail of tree-shaking" that I hope to have at some point because this would finally make fluent interfaces tree-shakeable (if they are implemented correctly)! Take that, moment.js!

**Comment by guybedford** [comment]
@lukastaegert I think you've already exactly narrowed down the right bailing-out behaviour there :)

Other question is if it should be first-level only or for deeper properties too. First-level seems like it would capture the major use case though.

**Comment by lukastaegert** [comment]
In this particular case, maybe we can take some inspiration from the logic built for namespace exports.

**Comment by lukastaegert** [comment]
Experience tells me that
* doing all levels is often not much more work than doing the first level, and
* produces a cleaner solution

There is a good reason I originally refactored the tree-shaking to make everything recursive...

**Comment by guybedford** [comment]
The thing to balance though may be performance if we end up iterating deep object handling here.

**Comment by guybedford** [comment]
I like the idea of a general "object-like" handling though that can track and apply for namespaces, classes, objects, etc equally.

**Comment by kzc** [comment]
Uglify performs this particular transform on side effect free object literals.
```js
$ cat test.js
var bar = {
	some: 'value',
	another: 'value'
};

module.exports = bar.some;
```
```
$ bin/uglifyjs -V
uglify-es 3.3.4
```
```
$ bin/uglifyjs test.js --toplevel -mc
module.exports="value";
```
See also: https://github.com/facebook/react/issues/11503#issuecomment-348753282

**Comment by lukastaegert** [comment]
@guybedford Performance can often be fixed with an additional bail-out condition e.g. based on path-depth. Currently, there are bigger performance sinks in the tree-shaking elsewhere :)

@kzc In fact uglify is inlining the value, which is something that we could actually solve separately and independent of this issue.

**Comment by kzc** [comment]
Yes, uglify inlines the value from the side effect free object literal and then drops the now unused object literal. How is that different than the problem discussed?

**Comment by guybedford** [comment]
@lukastaegert sounds sensible, although "Not as bad as" arguments shoudn't be encouraged wrt performance :P I do hope we can get some standard benchmarks going soon so it becomes a top-of-mind consideration for all features.

**Comment by guybedford** [comment]
Closing as a duplicate of #501, unless you want to create a more general tracking issue.
