### ISSUE TITLE
Use "browser" field in package.json?

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#185]
Webpack, Browserify and JSPM all use `pkg.browser` to indicate where to find dependencies. I think it's a poor naming choice – bundling code is beneficial on the server too (you get faster startup times, smaller/shallower/faster installations from npm, and no nasty surprises when dependencies introduce breaking changes in spite of semver. I wish more people talked about this stuff...), but be that as it may it's a widely used convention that perhaps we should adhere to.

Having said that, it potentially gets a bit tricky in our case because Rollup only wants to know about your ES6 dependencies (for now), whereas a package author that filled out the `browser` field would presumably be pointing to CommonJS dependencies.

**Comment by Rich-Harris** [comment]
Via https://github.com/pouchdb/pouchdb/pull/4462#issuecomment-147796092

**Comment by Victorystick** [comment]
Besides pointing out CommonJS modules, the `browser` field is used to point out browser-specific _versions_ of a library. It isn't specifically designed for bundling, although it is most often use as such. Since Rollup should be used for bundling both for both browsers _and_ Node, we can't always look for the `browser` field. We'd probably need two external resolvers: `npm` and `browserify`, to handle the two use cases.

**Comment by Rich-Harris** [comment]
This is something that can now be delegated to a plugin (most likely the https://github.com/rollup/rollup-plugin-npm plugin could be extended to support `browser` fields), so I'll close this – nothing needs to change in core.
