### ISSUE TITLE
Compiler inlining optimizations

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#1904]
Here's an optimization that would greatly improve the code I'm currently building:

```js
function x () {
  console.log("side effect x");
}
if (x)
  x();
x = null;


function y () {
  if (x)
    x();
  console.log('side effect y');
}
if (y)
  y();
y = null;
```

How hard would it be to work out that this can be rewritten as:

```js
function x () {
  console.log("side effect x");
}
x();
x = null;


function y () {
  console.log('side effect y');
}
y();
y = null;
```

And therefore to:

```js
  console.log("side effect x");
  console.log('side effect y');
```

Specifically, would this type of optimization ever be within the scope of Rollup?

**Comment by guybedford** [comment]
To summarize the optimizations being applied here:
1. Scope tracking (as we have)
2. Conditional inlining - when an if statement is known to evaluate to true, we can inline its truthy branch (this is effectively dead code ellimination with simple possible value tracking)
3. Function call inlining - when a function is called once without a need for its closure, to unroll the function into its call site

**Comment by guybedford** [comment]
Note that typically compilers implement optimizations like these as pluggable passes, that can be configured with performance heuristics etc.

**Comment by lukastaegert** [comment]
I actually have some notes on how to implement some parts of this, happy to share and discuss details tomorrow.

**Comment by lukastaegert** [comment]
Some initial thoughts:
1. Inlining functions is definitely the hardest due to the need for
   * scope deconflicting
   * context handling (or a deoptimization logic that detects this)
   Difficult to get this right without too much spaghetti code
2. I would go for variable inlining first (and e.g. keeping functions as function expressions)
3. Of course one should only inline variables that are only used once to avoid code duplication so this should ideally be tied into the tree-shaking logic
4. To be able to properly inline variables and get rid of the original definitions in situations like
    ```javascript
    const a = {x: 1, y: 2};
    const x = a.x;
    const y = a.y;
    console.log(x, y); // should be simplified to console.log(1, 2);
    ```
    we should also implement object expression tree-shaking first (so that in the above example, we can confidently remove `a`)

I have notes for algorithms to achieve 2-4. The only unsolved point here is how to render nodes across module boundaries. I.e. if A imports B then if we want to inline variables in A that are defined in B, `render` methods in A need to be able to render nodes from B into their own code. `magic-string` might have some tools to help us here (and get proper source maps in the process) but it's still difficult and needs some expansion of our current rendering logic.

In any case I would go for point 4 first which does not rely on this.

**Comment by lukastaegert** [comment]
Other things to note:
* We cannot evaluate `if` statements in that way yet. A lot would be possible here but only if variables are not reassigned
* We cannot track multiple values of variables (in this case `x`) and especially not the temporal order of reassignments. The current logic would give `x` an unknown value due to it being assigned a function and `null`. Changing this would require a lot of internal refactorings that honestly I do not think are worth the effort (our current logic is quite fast and "good enough"  in many real-life use cases)

**Comment by guybedford** [comment]
@lukastaegert I should have known you'd have a detailed response to hand here :)

A couple of points worth mentioning here:

* Can you clarify the conditional inlining issues - is this due to the "scope merging" issue? Alternatively the branch could be left as a "block statement", just without the conditional, in the code output?

* In particular it's worth considering that the "critical code path" is the primary optimization concern for application load time. That is, there is a top-level evaluation underlying any particular build. Apart from this top-level evaluation, functions are exported that then open up to other runtime evaluation paths on the code, but that top-level evaluation is the most critical one to optimize down to the absolute minimum. That's the evaluation path to follow first and foremost for optimization, where function inlining, dead code ellimination, and other more advanced optimizations can make a huge difference. Tools that can cut down that top-level path the most will provide the best runtime production performance through bringing down that code load time.

* About the rendering, as mentioned before I have been thinking it would be good to separate the rendering and analysis phases at a code level completely. Perhaps simply `render(node)` over `node.render` would provide this adequately. We'd lose the nice ability to have `node.render` to hand, but there would be a performance benefit to a flat loop here over the stack so it might pay off.... perhaps a simple performance investigation would be a good start. In addition a conceptual model of "cutting and pasting" Nodes through their magic string insertions shouldn't be too tricky to implement actually, but would be worth putting some thought to. That could allow Node cloning for inlining cases etc possibly. Perhaps we can start to discuss some architecture considerations here.

**Comment by lukastaegert** [comment]
**Conditional inlining:** Should actually not be too difficult, it just needs to be done :) The scoping is already handled properly in simple cases: https://rollupjs.org/repl?version=0.55.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmlmJTIwKHRydWUpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZygnSGVsbG8nKSUzQiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

We already have the `getValue` function which currently only returns literal values (as far as I know). This could probably be enhanced
1. handle non-reassigned variables: Should not be too difficult, would prove very powerful with little effort
2. to `getValueAtPath` to handle things like `if (x.y) ...`
3. to handle non-literal types. This, however, requires some thought as you would have to rethink how e.g. binary expressions are handled

**Rendering**: Would be interesting to explore this path (and do measurements).

**Comment by guybedford** [comment]
Moving this discussion to #2152.
