### ISSUE TITLE
Automatically calculate `--external` based on external packages without `jsnext:main`

### ISSUE THREAD

**Issue by nhunzaker** [rollup/rollup#192]
Just a thought. What if an entry in `--external` was automatically added for packages without a `jsnext:main` field instead of bailing out with `package x (imported by y) does not have a jsnext:main field`.

**Comment by Victorystick** [comment]
Doing so makes it unclear if a bundle has any unresolved dependencies or not. By making all external packages explicit, the user will always be sure of what packages are needed to make the bundle work.

**Comment by nhunzaker** [comment]
Fair enough.

**Comment by nhunzaker** [comment]
I guess I was unclear on the role of Rollup in the overall process. It sounds like it is not a replacement for Webpack or Browserify, but something lower level.

**Comment by Victorystick** [comment]
@Rich-Harris What's your take on it?

**Comment by Rich-Harris** [comment]
I'm sympathetic... the more permissive approach was definitely a source of frustration with Esperanto (Rollup's predecessor), which is why I initially took a hard line with Rollup. But having to explicitly state external dependencies (or generate it programmatically by inspecting `pkg.dependencies` and querying for `jsnext:main`) does get old pretty quickly.

There is a crucial difference between Rollup and Esperanto – with Esperanto, you could specify a project `base`, (e.g. `src`), and a non-relative import would be resolved against that first (e.g. `import 'foo'` looked for `src/foo.js`). That turned out to be a huge mistake – relative paths are far more robust (if a little finicky when you end up with `../../../../`), so Rollup is able to assume that a non-relative path is *always* for an external package. That makes it possible for us to say '`x` is an external package with `jsnext:main`, `y` is an external package without `jsnext:main`.

So we *could* fix this issue. If it reduces friction, it's probably a good thing.

@nhunzaker Rollup is designed to be a replacement for Browserify and Webpack... one day! Interop with CommonJS is the sticking point.

**Comment by nhunzaker** [comment]
Thanks for the awesome reply. If it were to be a replacement for Browserify or Webpack, I'd give this a huge :+1:. Running some trials on a few projects, this was consistently the friction point. Something a user would bump into every time they added a new CommonJS-only module to their project.

All the same, I am super excited about this project; it is extremely alluring.

**Comment by Victorystick** [comment]
As long as it is clear to users that a bundle has external dependencies, I'm for implementing it. Could we put it behind a flag, like: `--auto-externals` or `--permissive-externals`?
