### ISSUE TITLE
rollup doesn't strip const with comma operator

### ISSUE THREAD

**Issue by yuqianma** [rollup/rollup#1937]
[Check here: repl](https://rollupjs.org/repl?version=0.55.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwRk9OVF9ISU5HRV9TSVpFJTIwJTNEJTIwMC4wNyUzQiU1Q25jb25zdCUyMEJBQ0tfSElOR0VfU0laRSUyMCUzRCUyMDAuMTYlM0IlNUNuJTVDbmZ1bmN0aW9uJTIwUG9pbnRlckdhdWdlJTIwKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjBiYWNrSGluZ2UlMjAlM0QlMjBCQUNLX0hJTkdFX1NJWkUlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwZm9udEhpbmdlJTIwJTNEJTIwRk9OVF9ISU5HRV9TSVpFJTNCJTVDbiU1Q3QlNUNuJTVDdHJldHVybiUyMCU1QiU1Q24lNUN0JTVDdCUyRiUyRmJhY2tIaW5nZSUyQyU1Q24lNUN0JTVDdGZvbnRIaW5nZSU1Q24lNUN0JTVEJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMFBvaW50ZXJHYXVnZSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

I encounterd a problem and reproduce this minimal version.
You can see the line `backHinge = BACK_HINGE_SIZE` should be stripped but not. This leads to the "not defined error".

However if I write them in two line version, e.i.:
```
const backHinge = BACK_HINGE_SIZE;
const fontHinge = FONT_HINGE_SIZE;
```
Everything runs perfect.

Does it mean const & comma syntax is not supported? But since it's verbose to write multiple const, this feature is useful.

Anyway, thanks for your awesome work!

**Comment by lukastaegert** [comment]
Hi @yuqianma,
thanks for filing this issue! To answer your question:
Yes, your use case should be handled properly by rollup and this is a bug.

Incidentally I am refactoring some core parts of the statement rendering logic at the moment where fixing this issue would fit in nicely. So there is a good chance this will be fixed in the near future :) Until then, though, you will need to split this specific constant.

For reference, I am quite sure this is related to #1831.

**Comment by yuqianma** [comment]
Hi @lukastaegert 

Thanks! It's great to know you guys are striving for a better rollup. Can't wait to see the new version!
