### ISSUE TITLE
Items logged on stderr that aren't errors?

### ISSUE THREAD

**Issue by adamreisnz** [rollup/rollup#1955]
I am needing to integrate a front-end build process with a Java environment that is built with Maven. This is all working great and Rollup is bundling our assets just fine, but I've noticed that some of it's log output is being reported by the Maven build as ERRORs, while in reality they aren't, e.g.:

```
[INFO] $ rollup -c
[ERROR] 
[ERROR] app/index.js → dist/foo.min.js...
[ERROR] created dist/foo.min.js in 14.3s
```

According to [several](https://github.com/eirslett/frontend-maven-plugin/issues/628) [issues](https://github.com/eirslett/frontend-maven-plugin/issues/680) opened at the relevant Maven plugin that runs these commands, that plugin just logs anything that's outputted to `stderr` as an `ERROR` and to `stdout` as `INFO`, so the problem seems to lie possibly with Rollup not outputting to the correct channel.

Would you please be able to double check this, as I am worried the backend developers will panic by seeing these "errors" show up 😄

**Comment by adamreisnz** [comment]
Looks like this was an issue with usage of `&&` in script calls!

**Comment by adamreisnz** [comment]
I don't want actual errors to get swallowed though

**Comment by kzc** [comment]
```
$ node_modules/.bin/rollup blahblah.js -f es --silent
[!] Error: Could not resolve entry (blahblah.js)
```

**Comment by adamreisnz** [comment]
Thanks, it does silence the logs, but still doesn't explain how regular log output ended up in `stderr` or with a non zero exist code. I'll take it though, up to you if you want to investigate that further :)

**Comment by kzc** [comment]
No mystery. Code output defaults to stdout and all messages (info, warn, error) go to stderr. Only errors result in an error exit code.

**Comment by adamreisnz** [comment]
Gotcha, thanks

**Comment by matthiasg** [comment]
The fact that output appears on stderr that are not errors is interpreted by some tools (like https://rushjs.io/)  as build warnings which cause issues.

--silent does not silence it sadly

so now I am stuck with redirecting stderr to stdout which works, but it would be nice to have --silent not emit build steps or anything on stderr that is not an error

**Comment by lukastaegert** [comment]
`--silent` should prevent all output that is not an error. If that is not the case, you should try to create a minimal reproduction (important!) and create an issue, otherwise the situation will certainly not change.

**Comment by TimvdLippe** [comment]
FWIW we found the exact same issue in our Chromium integration with the Ninja build system (https://ninja-build.org/) We ended up using `--silent`, after doing several checks that errors generated by Rollup would still fail the build (which they do). Ideally, if `processCode === 0`, then `stderr === ''`. To me, that was a universal assumption when I started integrating Rollup with our build system.

I did attempt to create a PR on this issue, but sadly I was not able to figure out why this was happening in the first place. I think the culprits are the following two lines:

https://github.com/rollup/rollup/blob/1aeb23b23ef1aafe2edcbfd5c4062dd97186f700/cli/run/build.ts#L31

and

https://github.com/rollup/rollup/blob/1aeb23b23ef1aafe2edcbfd5c4062dd97186f700/cli/run/build.ts#L68

On both these lines, I would have expected the output to be on `process.stdout`. I looked into the history of both of these lines, but they appear to have been introduced >3 years ago and it wasn't clear to me why the choice for `stderr` was made.

If the usage of `stderr` *is* intentional and not subject to change, could you maybe add code comments to these lines explaining why that is the case? That should hopefully provide enough documentation for later for people like me integrating Rollup with build systems and tripping over this bug. Thanks!

**Comment by shellscape** [comment]
> To me, that was a universal assumption when I started integrating Rollup with our build system.

I used to hold that same assumption, until I did the research for this RFC https://github.com/rollup/rollup/issues/2393 and learned more about what `stderr` and `stdout` are really for. The links to references are at the bottom of the OP of that issue. I'd highly recommending reading that and the thread that follows for that RFC. It will shed light onto how Rollup intends to log.

Never, ever assume the process return code should mean anything for output.

> If the usage of stderr is intentional and not subject to change, could you maybe add code comments to these lines explaining why that is the case?

I think that the Issues here is a wealth of knowledge that is more easily searchable and contains far more nuance.

**Comment by ziofat** [comment]
@matthiasg hi, did you manage to redirect the stderr? I am stuck with this as well and hopefully there are working solutions I can use directly...

by the way, `--silent` does not silence stderr but do omit all stdout.

**Comment by shirakaba** [comment]
Just to clarify for any users of https://rushjs.io/, the following change to our npm build script successfully got our CI build to work:

```diff
- "build": "rollup -c",
+ "build": "rollup -c --silent",
```

As a sanity check that no stderr is emitted: Again, if using rush, you'll notice in your local development environment that, having added the `--silent` flag as above, the `rush rebuild` will no longer emit a file `your-app-name-a.build.error.log` for a successful build (because there was no stderr to collect).

**Comment by sam-mfb** [comment]
For those finding this, here is a summary of how we are handling it in a rush.js monorepo situation where our CI/CD will, as we want, fail on any output to stderr.

As noted above, adding the `--silent` flag to the CLI build command will suppress all non-error output.  That is good except that that means things logged at the "warn" level are suppressed as well.  We don't want that; we like our CI/CD to fail on warnings as well as errors (otherwise people just ignore warnings).  To do that, we use the `onLog` option in the rollup config to provide our own custom log function, the sole purpose of which is to "upconvert" warnings to errors thereby leading to failures of our CI/CD on warnings (which are now errors) even when `--silent` is invoked.

The function we provide to `onLog` is pretty basic, and is in fact based on the code from the official rollup docs [here](https://rollupjs.org/configuration-options/#onlog).  It is just (in typescript for easier reading):
```typescript
const customLogHandler: LogHandlerWithDefault = (
  level,
  log,
  defaultHandler
) => {
  // convert warnings to errors
  if (level === "warn") {
    defaultHandler("error", log)
  } else {
    defaultHandler(level, log)
 }
}
```
You could also just inline this to `onLog` if you find that easier.

A few other notes:

- Setting `logLevel` to "warn" via CLI or config does not work.  You will still get some "innocent" success messages escaping to stderr when you run the CI build command
- Setting `silent` to true in a config file does not work.  You similarly still get some stuff on stderr even on success.  Only `--silent` on the CLI seems to suppress all non-error logging.
