### ISSUE TITLE
import naming conflicts in v0.55

### ISSUE THREAD

**Issue by jackmellis** [rollup/rollup#1958]
Okay so I'm having trouble with import name conflicts. Basically if I import to the same variable name in different files, rollup doesn't bother fixing the naming conflict, it just overwrites the first with the second. 

The reproduction below probably sums it up best. Note how there are 3 `reduce`s from different sources.

This only affects the es module I think (cjs is fine).

[Reproduction](https://rollupjs.org/repl?version=0.55.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZvbyUyMGZyb20lMjAnLiUyRmZvbyclM0IlNUNuaW1wb3J0JTIwYmFoJTIwZnJvbSUyMCcuJTJGYmFoJyUzQiU1Q25pbXBvcnQlMjBiYXolMjBmcm9tJTIwJy4lMkZiYXonJTNCJTVDbiU1Q25leHBvcnQlMjAlN0IlMjBmb28lMkMlMjBiYWglMkMlMjBiYXolMjAlN0QlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHJlZHVjZSUyMGZyb20lMjAncmFtZGElMkZzcmMlMkZyZWR1Y2UnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwKCklMjAlM0QlM0UlMjByZWR1Y2UoKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiYWguanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVkdWNlJTIwJTdEJTIwZnJvbSUyMCdtb3N0JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMCgpJTIwJTNEJTNFJTIwcmVkdWNlKCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYmF6LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHJlZHVjZSUyMGZyb20lMjAnbG9kYXNoLnJlZHVjZSclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjAoKSUyMCUzRCUzRSUyMHJlZHVjZSgpJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

I should also point out that when I rolled back from v0.55 to v0.54 the issue doesn't occur:

[v0.54](https://rollupjs.org/repl?version=0.54.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZvbyUyMGZyb20lMjAnLiUyRmZvbyclM0IlNUNuaW1wb3J0JTIwYmFoJTIwZnJvbSUyMCcuJTJGYmFoJyUzQiU1Q25pbXBvcnQlMjBiYXolMjBmcm9tJTIwJy4lMkZiYXonJTNCJTVDbiU1Q25leHBvcnQlMjAlN0IlMjBmb28lMkMlMjBiYWglMkMlMjBiYXolMjAlN0QlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHJlZHVjZSUyMGZyb20lMjAncmFtZGElMkZzcmMlMkZyZWR1Y2UnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwKCklMjAlM0QlM0UlMjByZWR1Y2UoKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiYWguanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVkdWNlJTIwJTdEJTIwZnJvbSUyMCdtb3N0JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMCgpJTIwJTNEJTNFJTIwcmVkdWNlKCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYmF6LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHJlZHVjZSUyMGZyb20lMjAnbG9kYXNoLnJlZHVjZSclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjAoKSUyMCUzRCUzRSUyMHJlZHVjZSgpJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by guybedford** [comment]
I just checked and it seems like this is fixed in 0.55.4 (https://rollupjs.org/repl?version=0.55.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZvbyUyMGZyb20lMjAnLiUyRmZvbyclM0IlNUNuaW1wb3J0JTIwYmFoJTIwZnJvbSUyMCcuJTJGYmFoJyUzQiU1Q25pbXBvcnQlMjBiYXolMjBmcm9tJTIwJy4lMkZiYXonJTNCJTVDbiU1Q25leHBvcnQlMjAlN0IlMjBmb28lMkMlMjBiYWglMkMlMjBiYXolMjAlN0QlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHJlZHVjZSUyMGZyb20lMjAncmFtZGElMkZzcmMlMkZyZWR1Y2UnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwKCklMjAlM0QlM0UlMjByZWR1Y2UoKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiYWguanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVkdWNlJTIwJTdEJTIwZnJvbSUyMCdtb3N0JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMCgpJTIwJTNEJTNFJTIwcmVkdWNlKCklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYmF6LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHJlZHVjZSUyMGZyb20lMjAnbG9kYXNoLnJlZHVjZSclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjAoKSUyMCUzRCUzRSUyMHJlZHVjZSgpJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).
