### ISSUE TITLE
Ensure line breaks match input source line breaks

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#1974]
Mixed `\r\n` line breaks in the input source get mixed up with `\n` added by Rollup in the output source. Ideally we should either sanitize entirely to `\n` or run a line break detection on the input source for Rollup's use.

Previous report:
~~Just doing some Windows testing now I notice the latest release replaces instances of `\r\n` with `\n` in the output.~~

~~Ideally the `\r` characters should be passed through for newline consistency.~~

**Comment by guybedford** [comment]
I'm finding this is making testing Rollup on Windows difficult now as I need to correct line endings, and it may well be affecting other projects with source-based comparison test builds on windows.

**Comment by lukastaegert** [comment]
Could you be a little more specific:
* are all occurrences of `\r\n` replaced?
* if not, in what situations are they replaced?

I did not check the code yet but I would not have expected this to happen.

**Comment by guybedford** [comment]
Here's an exact replication:

```js
var input = `// comment\r\nexport var p = 5;console.log(\'a\');/*asdf1*/ switch (test) {\r\n
\t\t// comment\r\n\tdefault:\r\n\t\t\'asdf\'; //asdf\r\n}\r\n/* asdf */\r\n`;

var output = `// comment\r\nvar p = 5;console.log(\'a\');/* asdf */\n\nexport { p };\n`;
```

There may be other cases here.

**Comment by guybedford** [comment]
In 0.55.0, the output was:

```js
var output = `// comment\r\nvar p = 5;console.log(\'a\');/*asdf1*/ \r\n/* asdf */\n\nexport {
 p };\n'`
```

So I guess this is not actually a regression... I may have misdiagnosed the original issue will look into it further.

**Comment by guybedford** [comment]
Ok I managed to track this down to the fact that a test case changed from having a double `\n` at the end to a single `\n\n`, which wasn't copying and pasting correctly so I assumed this was due to `\r` handling.

The only thing here that could possibly be improved though is detecting what line breaks are being used in the original source and ensuring those are output correctly.

I'm renaming the issue to match and removing the bug label.

**Comment by lukastaegert** [comment]
I think this is mainly problematic for the finalisers as they generate lots of new code. The only other places I could find are if-statements (when there are hoisted variables) and rendered namespace blocks.

Variable declarations used to insert line-breaks as well but this has been changed (and therefore fixed 😉) in 0.56.0.

Not sure what the best approach is here. Maybe we just take the first line-break we can find as a template or otherwise just use `\n`.

As a side note: I was under the impression that even though `\r\n` is the standard line-break on windows, a simple `\n` is always handled correctly as well. As rollup is already doing lots of transformations to the code, I am not really sure in what situations people would find value from doing source comparisons of the rollup output (except for rollup developers that is 😜). Is there a certain use case outside rollup development you have in mind, or maybe even a situation where this tripped up another line-break detection algorithm?

**Comment by guybedford** [comment]
Ah right, if it is from the finalizers, then in that case I can likely work on this.

Mostly this is just for completeness reasons!

**Comment by guybedford** [comment]
I've been thinking about this a little more, and what's made me reconsider is that typically one might build external packages where you don't control the sources, which may have different line endings.

So this is the greater source of inconsistency that anything we do.

As such, doing this in the finalisers won't bring consistency, and running a replacement over the whole source seems rather unnecessary to be honest.

So closing :)
