### ISSUE TITLE
Loophole in import alias protection

### ISSUE THREAD

**Issue by jkrems** [rollup/rollup#202]
Normally an attempt to modify the import alias is protected, e.g. the following doesn't work:

```js
import * as constants from './constants';
constants.foo = 'bar';
```

But careless use of mutating functions can still mess with the import alias - and even lead to it becoming out-of-sync with the backing variable:

```js
import * as constants from './constants';
import { λ } from './constants';
Object.assign(constants, { 'λ': 20 }); // mutates `constants`
console.log('λ === λ', constants['λ'] === λ); // false
```

Both snippets are based on the dynamic namespaces example, just replacing the `main.js` code.

**Comment by Victorystick** [comment]
I feared this might happen.

This bug is caused by an unsafe optimisation where the `* as constants` namespace import generates
```js
var constants = { λ: λ };
```
where
```js
var constants = {};
Object.defineProperties(constants, {
  λ: { value: λ }
});
```
(or sinilar) is required.

We'll look into it.

**Comment by Rich-Harris** [comment]
We'll need to add `enumerable: true`, [per the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-module-namespace-exotic-objects). I'm torn – should this be behind a `strict` option or similar? It's certainly a good deal less elegant than the looser version, and would fail in some older browsers. Or are there enough realistic scenarios in which this could cause problems that it ought to be the default? (i.e. maybe we have a `loose` mode instead of a `strict` mode)

**Comment by Victorystick** [comment]
> Module namespace objects are not extensible.

I guess we should do something about that too while we're at it.

What about:
```js
var constants = Object.freeze({ λ: λ });
```
All properties would be made constant and non-configurable but enumerable as per the spec. That's not much uglier than anything else.

**Comment by Rich-Harris** [comment]
Ah, of course. I always forget about `Object.freeze`. Would still fail in older browsers, though maybe we should cross that bridge when we come to it
