### ISSUE TITLE
Inefficient when using destructuring operator in typescript.

### ISSUE THREAD

**Issue by ohpyupi** [rollup/rollup#2029]
I am giving it a try to use rollup instead of webpack to compile my typescripts. But it is very annoying that commonjs plugin cannot always return "name-is-not-exported-by-module" error
whenever I use destructuring object operator, such as below.

    import { Router } from 'express';

The way to achieve is to manually go to the config file, and add those names to it.

    namedExports: {
      'node_modules/express/index.js': [
        'Router',
        ...
      ]
    }

I mean I can do it for several pacakges, but I don't think it will work well when our app is growing.
The main part of reasons to use a bundler is to easily import/export packages over a project. To me it looks like a very serious issue, making rollup have lower value than webpack.

Any thoughts?

**Comment by guybedford** [comment]
Can you clarify exactly what is happening in your workflow that is the issue here?

Are you saying you are getting an error / warning in your workflow that you are having to fix manually, or is the issue that this isn't providing a proper error / warning in the first place?

If there's something better we can do here, could be worth looking into it.

Personally I would advise doing `import express from 'express'` due to the fact that Node's current intention is to never support named exports for npm packages, so is a much more future-stable convention to use.

**Comment by guybedford** [comment]
Closing, but happy to continue discussion here.
