### ISSUE TITLE
Code-Splitting Features Feedback

### ISSUE THREAD

**Issue by AndyOGo** [rollup/rollup#2049]
First, thanks a lot for providing this awesome tool.

Since, you asked for help regarding code-splitting I went for it on a live project, whose PR is here:
https://github.com/axa-ch/patterns-library/pull/333

Here are my conclusions:

- **UMD** and **iife** formats aren't supported and throw:
   > Error: UMD and IIFE output formats are not supported with the experimentalCodeSplitting option.
- add `chunkName` option
- add `maxChunks` option - in my case i would like to build just a single chunk, not more.
- customising path and filename options

**Comment by guybedford** [comment]
Thanks so much @AndyOGo for the feedback here!

Custom chunk names and paths are exactly what is being worked on next here in https://github.com/rollup/rollup/issues/1995, which I'm aiming to start on tomorrow.

Creating fewer chunks is definitely something we can look into as well. I was thinking of something along the lines of a `manualChunks` option to support this:

```js
manualChunks: {
  'custom-chunk.js': ['react', 'jquery', './src/common.js']
}
```

where that custom chunk will always be used for any of its modules. Constructing a single chunk with this kind of API would be tricky though, but perhaps combined with some custom globs in the config file would work fine for most use cases. I'd really prefer this to having to do custom optimization algorithms that will likely make the wrong decisions, without bringing real load time feedback for optimization into the fray.

As for the UMD and IIFE support - this is really hard to do because the nature of code splitting is that it needs a loader to manage the registry of modules being loaded. I'd be interested to hear what the difficulties were with using an AMD or System loader here.

**Comment by AndyOGo** [comment]
@guybedford 
Sorry for my late reply.

**Background:**
Let me tell you first a bit about this project.
Basically our goal is to provide a framework and library agnostic collection of components by utilising Custom Elements V1. Unfortunately Web-Components themselves are still very young and I would say far away from being major. So we had to fix/workaround a bunch of stuff, which led to quite some additional generic code. And those helper utils we would like to provide in a separate JS file named `common.js`.

Regarding **UMD** support.
We basically have two kind of consumers:
 - The ones having a proper cutting edge build system for es modules (we have no troubles here)
 - The others who still have es5 or even es3, no magic build, etc... for them we would like to provide ready to use bundles in the form of:
   ```html
   <script type="text/javascript" src="patterns-library/common.js"></script>
   <script type="text/javascript" src="patterns-library/m-button/index.js"></script>
   ```

**Comment by guybedford** [comment]
Effectively the `common.js` that you are building here is in many ways like an internal shared library. As such, it is still worth thinking about building shared libraries as a separate build unto themselves - where you can have full control over exactly what is in that library etc. (note also a library using dynamic import can itself be built with code splitting benefits).

So rather to consider the builds as (1) a single file Rollup build of common.js and (2) another single file build of each component, with the externals of that component specifically set at the boundaries of common.js.

I think it's important to bear the distinction in mind between library and application boundaries, and how single-file builds and code splitting can work in both of those separate scenarios, but should still be applied as separate phases to both.

For example - I'd love to position Rollup in a place where npm packages are commonly built with Rollup single file or code splitting (when necessary) with externals set as other npm packages before publishing. This would create a much faster npm ecosystem.

**Comment by guybedford** [comment]
Better control over the exact chunking algorithm is definitely a requirement here - I've created https://github.com/rollup/rollup/issues/2070 to track.

@AndyOGo let me know if it sounds like the discussion here and in the new issue has covered your feedback, or if you think there may still be aspects not yet accounted for.

**Comment by AndyOGo** [comment]
@guybedford 
Thanks for your reasoned description. **Manually defined chunks** are the feature we sought for:).

I would still consider **UMD** Support, since it could be considered a superset of **AMD**, cause any UMD Module can be loaded by any AMD loader like RequireJS.

**Comment by guybedford** [comment]
Great to hear that.

The trouble with UMD is that there isn't a way to support either static or dynamic import in the global cases, which is a key feature of code splitting - and relying on the exact script order with complex chunking cases will be very tricky to communicate through the interface as chunking scenarios grow more complex.

I'll close this for now, just let me know if there's anything else you'd like to discuss further.

**Comment by AndyOGo** [comment]
Thanks for you quick response.

May I'm wrong but can't it just bundle up multiple UMD's in one file, like:

```js
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['exports', 'b'], factory);
    } else if (typeof exports === 'object' && typeof exports.nodeName !== 'string') {
        // CommonJS
        factory(exports, require('b'));
    } else {
        // Browser globals
        factory((root.commonJsStrict = {}), root.b);
    }
}(typeof self !== 'undefined' ? self : this, function (exports, b) {
    // Module A here
}));

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['exports', 'b'], factory);
    } else if (typeof exports === 'object' && typeof exports.nodeName !== 'string') {
        // CommonJS
        factory(exports, require('b'));
    } else {
        // Browser globals
        factory((root.commonJsStrict = {}), root.b);
    }
}(typeof self !== 'undefined' ? self : this, function (exports, b) {
    // Module B here
}));
```

**Comment by guybedford** [comment]
I get what you're saying about being able to easily define this common layer though through manual chunking - it definitely would be convenient.

Perhaps we could look into this after all, since the graph metadata is available from the interface to build these script tag outputs.

But I would stress that this only really makes sense when manualChunks can enable simpler chunking results (small number of chunks). As its the large numbers of chunks or uses of dynamic import that make global management here untenable.

I've created https://github.com/rollup/rollup/issues/2072 to track discussion on this further.

**Comment by AndyOGo** [comment]
@guybedford 
Thanks allot. Totally agree, it's a manual number of chunks only feature.
