### ISSUE TITLE
Use TypeScript strictNullChecks

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2051]
Supporting these compiler options in tsconfig.json may well help with performance by helping to enforce hidden class shape as part of the compilation process itself.

**Comment by guybedford** [comment]
I see strictPropertyInitialization got added in the recent PR!

**Comment by lukastaegert** [comment]
Unfortunately, strict null checks are still missing and there is a little more work to be done here. As think it is the more important one of the two, I will adjust the description and reopen it.

**Comment by edsrzf** [comment]
I'm interested in helping out on this, but not sure of the best way to approach it. There are currently 400 errors on the master branch with `strictNullChecks` enabled, so trying to fix them all in a single branch/pull request seems like a bad idea.

I could try a more gradual approach, but I worry that some of the progress will be (unintentionally) undone as others make changes.

I can think of a couple other ways:

We could add a `tsconfig.strict.json`, that enables `strictNullChecks` and only includes files that pass with that option. Note that these files can also only import other files that pass. Gradually, we'd add more files, and check against these options in CI so that things don't regress.

Another option would be to add `// @ts-ignore` comments to all errors caused by `strictNullChecks` and gradually work towards removing the comments, without allowing people to add more. However, this could potentially cover up other, unrelated errors.

**Comment by lukastaegert** [comment]
I am also somewhat unsure about this. The main problem is that some of Rollup's code very much relies on strict null checks NOT being enabled and would become noticeably less efficient if we use "proper" types and add null checks instead.

The situation is related to build steps. E.g. chunks do not have an id until after id generation has run. However as we only access chunk ids after that, there is no need to check for null when accessing ids from this code. Solving such things "properly" while preventing unnecessary checks would probably require fundamental refactorings.

I am also not too happy about `// @ts-ignore` as it would also prevent other checks. Here is what I see could work out:

1. We leave all types as they are for now.
2. We add explicit type casts for every error. This should have the same effect as a ts-ignore while being more specific to the issue at hand.
3. We merge this as soon as possible to master.

After that, we can try to start untangling these situations where it makes sense and possibly find better solutions (hopefully solutions that involve breaking down some of the larger classes floating around...).

In case a type cast does not work, I guess an ignore comment could be used as a fallback but I hope we can avoid this.

I would be happy to support any PR in that direction!

**Comment by lukastaegert** [comment]
BTW I would actually go for the full "strict" mode if possible.

**Comment by edsrzf** [comment]
Okay, that sounds like a workable solution. I'll just got for `strictNullChecks` initially, but I'll see how many additional errors full `strict` produces and either include that or do it separately, depending.
