### ISSUE TITLE
Indent-wrapper option

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2078]
If we're making --indent the default, I'd like to suggest that we combine this with a default that we don't indent within finalizer wrappers, but rather enable this through a separate option `--indent-wrapper`.

That is to output:

```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(factory());
}(this, (function () { 'use strict';

// maths.js

// This function gets included
function cube ( x ) {
	// rewrite this as `square( x ) * x`
	// and see what happens!
	return x * x * x;
}

/* TREE-SHAKING */

console.log( cube( 5 ) ); // 125

})));
```

Instead of:

```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(factory());
}(this, (function () { 'use strict';

	// maths.js

	// This function gets included
	function cube ( x ) {
		// rewrite this as `square( x ) * x`
		// and see what happens!
		return x * x * x;
	}

	/* TREE-SHAKING */

	console.log( cube( 5 ) ); // 125

})));
```

For example, in the System module format we have three indentation levels for the wrapper. I also think it's better to leave the original source alone by default.

**Comment by lukastaegert** [comment]
I'm sorry but I don't think separating these two indents is very useful. The reason is that, if I did not overlook anything, the *only*  place other than finalizers that use ident is when rendering namespace objects. Nowhere else. People who care about indent will either use both options or none.

Instead of separating these two for some kind of micro-management, we should rather make sure that indents work consistently across finalizers and probably discuss further if we want to change the default.

As library developers who may care about beautiful code are still some of our most prominent users, and beautiful code is one of the sellling points of rollup, I would vote for keeping the indent, but if the performance overhead is significant, we could change that. In any case, I think the REPL should use indenting.
