### ISSUE TITLE
ENV conditional code

### ISSUE THREAD

**Issue by aaronjensen** [rollup/rollup#208]
A common pattern is to wrap code in `if (process.env.NODE_ENV === 'production')` which, when combined w/ webpack's DefinePlugin and uglify eliminates that code. Is there an equivalent of DefinePlugin w/ rollup?

**Comment by aaronjensen** [comment]
Well, I guess there's this:

```bash
$ ./node_modules/.bin/rollupbabel lib/index.js | sed 's/process.env.NODE_ENV/"production"/g'
```

heh...

**Comment by Rich-Harris** [comment]
That plugin doesn't exist yet, but it certainly could – I can see its usefulness. We're currently debating plugin strategy over on https://github.com/rollup/rollup/pull/207.

In the meantime, this could be achieved with a transform. I've put together a simple example here: https://github.com/rollup/rollup-environment-variables-example. It's fairly basic, but could easily be adapted to support `process.env` or whatever else.

Having said that it would only get us half-way – with tree-shaking, you could avoid importing the code in the first place, eliminating the risk that UglifyJS was unable to remove the dead code (which is sometimes unavoidable due to the nature of JavaScript). So I wonder if there's value in Rollup itself being smart enough to eliminate obviously dead branches (by 'obviously', I mean recognising truthy literals, falsy literals, the `!` operator in combination with those things, and `Literal === Literal`, plus maybe one or two other common cases).

**Comment by Rich-Harris** [comment]
There's now a plugin for this: https://github.com/rollup/rollup-plugin-replace

It doesn't prevent Rollup importing stuff used in dead branches – that's a potential future optimisation. In most cases UglifyJS etc can do the rest, so nothing is lost. So I'll close this

**Comment by aaronjensen** [comment]
Great, thanks.

**Comment by mshick** [comment]
@aaronjensen I needed functionality like this for a project and wanted it nice and tidy, so I built a very simple module which you might find useful. https://github.com/mshick/rollup-plugin-env

**Comment by pastelsky** [comment]
For anyone seeing this issue now, conditional requires are now eliminated if only one uses the `rollup-plugin-replace` before `rollup-plugin-commonjs`.

**Comment by DavidWells** [comment]
Here is a demo of this I found helpful for anyone else trying to solve this issue https://github.com/eventualbuddha/rollup-316

**Comment by aminnairi** [comment]
You can even use the `--environment` argument from the [`rollup`](https://rollupjs.org/guide/en#command-line-flags) CLI to dynamically replace references of `process.env.NODE_ENV` in your code to achieve similar results compared to [`webpack.DefinePlugin()`](https://webpack.js.org/plugins/define-plugin/).

```console
$ npm install --save-dev rollup-plugin-replace
$ # or
$ yarn add --dev rollup-plugin-replace
$ vim rollup.config.js
```

```javascript
// ...
import replace from 'rollup-plugin-replace'

const { PRODUCTION } = process.env

export default {
  // ...
  plugins: [
    // ...
    replace({
      'process.env.NODE_ENV': JSON.stringify(
         PRODUCTION ? 'production' : 'development'
       )
    }),
    // ...
  ],
  // ,,,
}
```

```console
$ ./node_modules/.bin/rollup -c --environment DEVELOPMENT
$ # or
$ ./node_modules/.bin/rollup -c --environment PRODUCTION
```

**Comment by Guria** [comment]
replace is different then DefinePlugin. Define makes actual variable reference and replace works only for exact match.

**Comment by DominicTobias** [comment]
Weird it doesn't seem to work at all for me - https://github.com/rollup/rollup-plugin-replace/issues/35

**Comment by ppoulard** [comment]
I think that the ultimate solution is described here :
https://github.com/rollup/rollup/issues/487#issuecomment-485660918

**Comment by ppoulard** [comment]
> I think that the ultimate solution is described here :
> [#487 (comment)](https://github.com/rollup/rollup/issues/487#issuecomment-485660918)

...not so much : the solution works well but destroy .map files ; if you intend to debug your code in the browser and expect to have the source mapped to the transpiled code, you're done !

My definitive solution is the following : 

Create the file `process.ts` :

```
(window as any).process = {
    env: {
        NODE_ENV: '__NODE_ENV__',
        WHATEVER: '__WHATEVER__'
    }
}
```

then prepend it in `index.tsx` :

```
import './process';

import React from 'react';
import ReactDOM from 'react-dom';
```

then use the `replace` rollup plugin :

```
        replace({
            __NODE_ENV__ : build,
            __WHATEVER__ : whatever
        }),
```

Then you can use indifferently `process.env.NODE_ENV` or `process.env['NODE_ENV']`, and as a bonus, it doesn't break React's stuffs such as `if (process.env.NODE_ENV === 'production') {}` that fails with the direct Rollup substitution `replace({'process.env.NODE_ENV' ...`
Why ? Simply because the transpiler will check that 'development' === 'production' is ALWAYS false, and terminate with a semantic error.

**Comment by lukastaegert** [comment]
If you look at the linked thread, the "ultimate solution" should actually be https://github.com/rollup/rollup/issues/487#issuecomment-486229172 which also addresses the sourcemap issue.

**Comment by lukastaegert** [comment]
The advantage of the linked solution in contrast to your solution is that
* no global variable is actually created
* unless `process` is directly referenced, all references will be completely tree-shaken and conditionals will be properly simplified

**Comment by ppoulard** [comment]
Great ! This is exactly what I was looking for !
Thanks !

**Comment by lukastaegert** [comment]
Still hope that someone rolls this into a nice plugin for public use. But maybe this has already happened, but then this should probably be mentioned in #487

**Comment by ppoulard** [comment]
Hi,
Your code is now available in this plugin :
https://www.npmjs.com/package/rollup-plugin-inject-process-env
Let me know if I forgot anything.

**Comment by lukastaegert** [comment]
Awesome!

**Comment by s875515** [comment]
Hi, If you need to read an env file then the bellow work may suitable for you.
I use "@rollup/replace" and "dotenv" to read and replace what the env value you want.
[https://gist.github.com/s875515/b674c313f7e695b4e8736d77a893d4b6](https://gist.github.com/s875515/b674c313f7e695b4e8736d77a893d4b6)

**Comment by yairEO** [comment]
I didn't understand anything of this thread, after reading it carefully a few times. 

I personally have a constructor function and a large amount of *prototype* methods, and I want to conditionally include only part of those methods. 

Rollup/terser do not tree-shake (prototype) methods because it's not 100% safe to remove. How can they know without being explicitly told so? after I've done some research regarding `__PURE__` comments..they are useless/difficult to work with.

---
I also don't understand why OP edited this post saying:

> [EDITED] update from Rich — this now works. use rollup-plugin-replace, and ensure it comes before rollup-plugin-commonjs in your plugins array

1. *what exactly* "now works"?
2. "use rollup-plugin-replace" - in what way?? no example given.

---

what I experimented with is a whole different approach using the [rollup-plugin-jscc](https://github.com/aMarCruz/rollup-plugin-jscc) to wrap pieces of code that I conditionally want to be striped away. (JSCC must be the first rollup plugin defined before all others)

What I **like** about this, that it does all of the changed in build-time and no logic is actually created in the bundle especially for this conditional elimination/insertion of methods.

What I **do not like** about *JSCC* approach is that it's tedious. There many pieces of code which I want to remove in a "light" version of my bundle, some are methods, some functions calls, some whole chunks of code-flow deemed irrelevant (by me) for a "light" version.

For example, I want to remove a prototype method, so what I do (in the source-code) is:

```js
function Foo(){ ... }
Foo.prototype = {
	init(){
		//#if _FULL_BUILD
		if( something )
			return this.bar()
		//#endif
	},
	//#if _FULL_BUILD
	bar(){
		...
	},
	//#endif
	...	
}
```

The above will complete remove anything between the comments (and the comments themselves) if I use the below JSCC rollup plugin config:

```
Jscc({
  values: { _FULL_BUILD: false }
}),
``` 

So my actual build process runs Rollup twice, one with the above `_FULL_BUILD` set to `true` and one to `false`.
Not optimal at all and I am not very pleased with all of this.
