### ISSUE TITLE
Desire a way to disable warning of eval when I need to use it.

### ISSUE THREAD

**Issue by intervalia** [rollup/rollup#2082]
Using eval generates this warning: **(!) Use of eval is strongly discouraged**

I would like some way to prevent the warning when I _choose_ to use it.

Maybe a comment like this one: `// eslint-disable-line no-eval` that would ignore the fact that I did an `eval` on this line or `// eslint-disable-next-line no-eval` that would ignore the `eval` on the next line.

If I know what I am doing and wanted/needed to use `eval` in my file I don't want rollup to complain about it.

Can this be done? Can this be added?

**Comment by guybedford** [comment]
Enabling warning flag customization is a feature being discussed at https://github.com/rollup/rollup/issues/1978.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by dk00** [comment]
Warnings can be suppressed with config:

```js
{
  onwarn(warning, warn) {
    // suppress eval warnings
    if (warning.code === 'EVAL') return
    warn(warning)
  }
}
```

See #408 for details.

**Comment by codefactor** [comment]
@dk00 ,

This should be considered purely a work around and not a solution. We should be able to locally identify "safe evals" using a comment localized to the file that has introduced the dependency to eval. This is commonly achieved through comments, an example of the desired behavior might be the following:

```
// rollup-disable-warning-next-line EVAL
eval(string);
```
This would allow the developer to thoughtfully suppress the warning only after being directed to the issue at build time, rather than disabling it broadly for the project forever.

**Comment by codefactor** [comment]
@shellscape ,

Please reopen - warnings should have a way to disable warnings outside of the configuration. Warning suppression does not belong to config, to disable it globally in the configuration would be the same to say that this warning is not useful for the project, but that is not what is desired here. However, the warning is useful and will help developers identify risky behavior.

Even if you could somehow magically detect in the `onwarn` function of the config that the particular location of the eval call is "safe" and conditionally warn the eval issue, I don't believe the config.js file is where that detection belongs.

Please consider to reopen this bug - or maybe refactor the solution to https://github.com/rollup/rollup/issues/408 so that rollup can read comments to suppress warnings when a comment is present at the offending location.

**Comment by codefactor** [comment]
@shellscape ,

Is there some limitation, outside of effort required, to implement a better solution that involves inline comments to suppress warnings?

**Comment by shellscape** [comment]
I'd guess someone just needs to step up and submit a PR, and then work through it with Lukas.
