### ISSUE TITLE
Tree shaking doesn't work for dependent libraries

### ISSUE THREAD

**Issue by robhicks** [rollup/rollup#2114]
Here's the scenario (real, not contrived):

1. library 1 depends on a single exported isJson method from library 2.
2. library 2 which exports a number of methods, including the isJson method imported by library 1, and which depends on a single exported StringBuilder from library 3.
3. library 3 includes two exports, the StringBuilder class imported by library 2, and a native web component which depends on [hyperhtml](https://viperhtml.js.org/hyperhtml/documentation/) (a third party library which exports, using es2015 module exports) several functions, only one of which is used.

Rollup is is used for all 3 libraries. Library 3 identifies hyperhtml as an external. Library 2 identifies library 3 as an external. And library 1 identifies library 2 as an external.

All 3 libraries include a module property in their package.json files, which points to the rolled up file for that library without the externals.  

Two rolled up files are built for each library, one without any resolved externals, and one using rollup-plugin-node-resolve to resolve the external libraries, which are installed using npm.

The bundled build file for library 3 includes the hyperhtml dependency. 
The bundled build file for library 2 includes all of the library 3 dependencies, even though they are not used. 
The bundled build file for library 1 includes all of dependencies of libraries 2 and 3. 

This is not what I would have expected and show that tree shaking for upstream libraries does not seem to work. 

To demonstrate this, I have created the 3 libraries:
- [library 1](https://github.com/robhicks/rollup-lib-1)
- [library 2](https://github.com/robhicks/rollup-lib-2)
- [library 3](https://github.com/robhicks/rollup-lib-3)

**Comment by youcanping** [comment]
The latest version of Rollup has this problem, V0.43.0 version can be tree-shaking the library in node_modules

**Comment by lukastaegert** [comment]
I did not look at everything as the reasons for inclusions of certain code can vary but basically the main reason why rollup includes most of the code is because rollup (with a few exceptions) does not know if accessing properties of global objects can have side effects. For instance that is why the line `const G = document.defaultView;` needs to be retained, and most of the properties of `G` that are checked later. A lot of other code needs to be included to make the code valid.

Property access checks are a somewhat new concept. If you are certain there are no property accessed with side-effects, you can get the old behaviour via: `treeshake: {propertyReadSideEffects: false}`. In most cases, you can get even better results via

```json
treeshake: {
  propertyReadSideEffects: false,
  pureExternalModules: true
}
```
