### ISSUE TITLE
Is output.paths still supported?

### ISSUE THREAD

**Issue by matthewp** [rollup/rollup#2131]
It seems to be according to https://github.com/rollup/rollup/blob/4d452f6a2116465d5642ee3f68b62acada3d3dd7/src/rollup/types.d.ts#L186

However this commit removed using it: https://github.com/rollup/rollup/commit/f59e310fcedeef36f5a75506f1614e50dfeb51ee#diff-8c6f11349cc1bb370bdd557ed2bcbe7dL841

Was this feature intentionally removed? If so, is there another/better way to name the chunks?

**Comment by guybedford** [comment]
In that commit it was just moved to https://github.com/rollup/rollup/commit/f59e310fcedeef36f5a75506f1614e50dfeb51ee#diff-8c6f11349cc1bb370bdd557ed2bcbe7dR72.

Note that paths are for specifying where externals should be loaded from in the output.

See the docs at https://github.com/rollup/rollupjs.org/pull/130 for controlling the code splitting output.

**Comment by matthewp** [comment]
That function isn't in master any more. I don't see anywhere in master where options.paths is used. 

It looks like it is now done here, but doesn't call options.paths: https://github.com/rollup/rollup/blob/master/src/Chunk.ts#L1016-L1018

My reason for using this is because in `experimentalPreserveModules` it replaces import specifiers with the ids (and in that code I linked to it makes them relative). I would prefer there be a way to say not to change the module specifiers. I was using options.paths as a workaround.

**Comment by guybedford** [comment]
It was moved out to ExternalModule.ts at https://github.com/rollup/rollup/blob/master/src/ExternalModule.ts#L43.

It sounds like you want `import 'x'` not to be rewritten to say `import './node_modules/x/index.js'`? If so, perhaps you just want a preserveModules build with `x` as an external in the first place?

If you can explain what you're trying to accomplish I can offer some suggestions further.

**Comment by matthewp** [comment]
Yes, that is what I want. The problem with rewriting specifiers is that you are replacing something that is contextual, a module specifier, with something that is not contextual, an id. If it just put in the `id` that would be a little better, but it forces a relative like path.

The underlying problem is the assumption that an `id` coming from a plugin is a file path.

**Comment by guybedford** [comment]
The best I could suggest here would be to replace SOMEID with "bar" internally in "modules" before applying it in Rollup.

**Comment by matthewp** [comment]
That would only work if `bar` is unique in the graph. I would imagine there are specifiers like `./index` that are not unique in most graphs.

If paths didn't exist for this reason, would you be open to some new type of option that allows resolving ids to specifiers? It would run here: https://github.com/rollup/rollup/blob/master/src/Chunk.ts#L1016-L1018

It even makes sense as a plugin hook, `resolveSpecifier`, since it would be the opposite of `resolveId`.

**Comment by guybedford** [comment]
preserveModules implies an output folder structure based on the relative resolved id values, so that `./index` would reference the same thing for all parents (just in different subfolders for example).

It should be possible I think to map your current module space into a well-formed file-like space for the resolveId result values before applying Rollup preserveModules, in which case that would provide the output you're after.

The thing is this is very much unique to preserveModules because normal code splitting builds have their own naming system which is a new id space. So the alternative I think would be rather than outputting specifiers through a new hook to retain the old import names. But that seems somewhat of a regression as there are benefits to resolving extensions etc.

**Comment by matthewp** [comment]
Ok, sounds like rollup is not meant to be used for this purpose then. Thanks for listening.

**Comment by guybedford** [comment]
I didn't mean to shut you down here @matthewp, just trying to work out what conceptual model fits your use case and how that can fit the conceptual model of preserveModules.

The main conceptual model I think to follow for preserveModules is something like a "prettier" style approach.

But it sounds like your scenario is building multiple packages at the same time (say all the packages of a monorepo, with cross-package treeshaking in preserveModules, while retaining the plain / bare specifier names like "SOMEID".

That's certainly a valid use case... I'm just not sure currently what the best way would be to support that.

**Comment by matthewp** [comment]
No worries. Simply, my use-case is to use rollup for its full-graph analysis and DCE. Ideally I could give it a graph, it removes any dead code, and I have the same graph, just smaller. Then I'd like to be able to do bundling on my own. But it sounds like the tree-shaking and bundling capabilities are intertwined in a way that this may not be feasible.

**Comment by guybedford** [comment]
The only assumption here in code splitting that seems to be affecting your use case is that we assume each module in the optimized graph follows a logical hierarchical file structure, in order to allow the ability to write the graph to an arbitrary directory with a single input "dir" argument.

Perhaps your initial expectation of having `paths` apply to internal requires would handle this? Where:

```js
paths: {
  // continue to map external paths
  'external': '/external/path.js',
  // also support internal paths through leading "./" suffix
  './internal.js': 'internal'
}
```

So that if I had a module at `pkgA/index.js` that imports `../dep.js` and a module at `pkgB/index.js` that also imports `../dep.js`, we would pass through `./dep.js` into paths (that is the resolved internal path from the output graph root), which would be allowed to return eg "dep".

The only issue is if we'd need this to be contextual - `../dep.js` becoming `depA` in pkgA and `depB` in pkgB for example, which may cause a huge number of paths checks as we'd need to then check every single vertex of the output graph through this mechanism.

**Comment by guybedford** [comment]
I'd be interested to hear your thoughts on whether having paths apply once per module no per module import would work for you.

paths as an object and function are interchangeable as the same mechanism.

**Comment by matthewp** [comment]
Ok, rereading your comment I don't think I quite understand. I think you are saying that you need the paths to be relative internally, is this right? And your solution is to use paths configuration to allow customizing what is written into imports? If that's what you're saying, I am fine with that. I think I might be misunderstanding though.

**Comment by guybedford** [comment]
Yes using `./` before the module name would just be there to distinguish between "internal" and "external" module names for the "paths" configuration.

And are you ok with the paths running only once per internal module, and not per usage of that module?

If so, could well be worth implementing actually.

**Comment by guybedford** [comment]
Hmm actually this starts to get ugly pretty quickly... here's an example:

main1.js
```js
import "./dep"
```

main2.js
```js
import './dep/index.js';
```

Would resolve `dep` into `dep/index.js` for both, and `main1.js` and `main2.js` as just those.

We would then check `paths('./dep/index.js')`, `paths('./main1.js')`, and `paths('./main2.js')`.....

One could then have `./dep/index.js` return a paths value of `dep` to resolve as plain again.

But the issue comes with paths that return relative paths themselves.... as that would likely make very little sense....

Perhaps we need some separate concept here of an "preserve modules boundary / subset".... let me think about this a bit more actually...

**Comment by guybedford** [comment]
There's a PR along these lines at https://github.com/rollup/rollup/pull/2277.
