### ISSUE TITLE
Help Wanted: Tree shaking and scss import

### ISSUE THREAD

**Issue by ale-grosselle** [rollup/rollup#2154]
Hi, 
I have a question how to properly work with scss and rollup.
I am building an UX library, each library component has its scss style. For example:

**Modal.js**

```
import Materialize from "materialize-css";
import "vanilla/genericComponent/modal/index.scss";

export default Materialize.Modal;
```

**index.js** 

```
//@flow
import Button from "vanilla/genericComponent/button";
import Modal from "vanilla/genericComponent/table";
export {Button};
export {Modal};
```

**bundle.es.js**
```
....code and code....
var css$1 = ".th-ui .table, .th-ui .th, .th-ui .td {\n  border: none; ...css and css...\n";
styleInject(css$1);

var index$1 = {};
export { index as Button, index$1 as Table };
```

Es bundle shown above are imported in a project and then minify.
All the generated css are always included and never removed during the uglify process, even if i am using Button instead of Table.
If i am using only Button component, in the bundle I will find Table css too
 Looking the es bundle I think that the is correct behavior, because css are all included as variable 

My idea is try to add css in a variable like this:
```
export function Button (){
   let css = <import "vanilla/genericComponent/modal/index.scss";>
   applyCss(css);
}

```
But I do not know how I can do it...
Have any of you identified the way to import scss and using tree shaking?

**Comment by ale-grosselle** [comment]
Little update, I am using postcss rollup plugin. 
I'm checking if injecting the CSS by hand solved problem.

**Comment by ale-grosselle** [comment]
Ok, setting postcss.inject to false tree shaking works well!

**Comment by nathanielhunter** [comment]
@brunocramos I know it was a long time ago, but do you know if you ever figured this out? We are running into what seems to be the same issue even though it's years later.

**Comment by brunocramos** [comment]
@nathanielhunter, not really, unfortunately. At that time, the CSS was being completely injected while the components' main code were tree shake, and I decided to stick with that. (It has been almost three years tho)

**Comment by nathanielhunter** [comment]
@brunocramos I think I figured out that its an issue with the postcss plugin, it appears the plugin needs to mark the css module as having side-effects. Because it doesn't rollup doesn't include the reference. There's a draft PR that's supposed to resolve the issue, but the postcss plugin is in maintenance mode.... Haven't seen any other plugins that work properly though.

**Comment by nathanielhunter** [comment]
Another update, it looks like the resolve() plugin determines if modules have side effects or not as well as rollup, the resolve package appears to identify it incorrectly, because it relies on flags in the package.json of packages. In order to prevent treeshaking of scss you need to do this in your package.json
```
  "sideEffects": [
    "**/*.scss",
    "**/*.scss.js"
  ],
```

instead of :
`"sideEffects": false`

**Comment by tlehtimaki** [comment]
Did you @nathanielhunter maybe mean to say: "In order to allow treeshaking ..." , not prevent?
