### ISSUE TITLE
Code splitting not working with default export/import

### ISSUE THREAD

**Issue by caub** [rollup/rollup#2156]
When using [`experimentalCodeSplitting`](https://github.com/caub/color-tf/blob/a6f15062587f8b273f6ae04e0addf3ba9235b650/rollup.config.js#L25), I get this erroneous generated content: https://unpkg.com/color-tf@5.0.0-beta1/dist/cjs/index-9f2891df.js

It should be `var hsl2hsv = require('./hsl2hsv.js');` instead of just `require('./hsl2hsv.js');`

**rollup version**: 0.58.2

------

You can probably reproduce with: (I couldn't put a different config in https://rollupjs.org/repl)

rollup.config.js
```js
export default {
  input: ['main.js', 'hsl2hsv.js', 'index.js'],
  output: {
    format: 'cjs',
    dir: 'dist/cjs',
  },
  experimentalCodeSplitting: true,
};
```

main.js
```js
import * as lib from './index';
export default new Map(Object.entries(lib))
```
hsl2hsv.js
```js
export default (h, s, l) => {
  const t = s * (l < 0.5 ? l : 1 - l),
    V = l + t,
    S = l > 0 ? 2 * t / V : 0;
  return [h, S, V];
};
```

index.js
```js
export { default as hsl2hsv } from './hsl2hsv';
```

**Comment by guybedford** [comment]
Believe it or not the output is actually roughly correct in terms of how we handle these cases. There are two bugs exposed here though:

1. The file at https://unpkg.com/color-tf@5.0.0-beta1/dist/cjs/index-9f2891df.js should have `var hsl2hsv.js = require('./hsl2hsv.js')` at the top so that the bindings are properly defined.
2. The file at https://unpkg.com/color-tf@5.0.0-beta1/dist/cjs/index.js is incorrectly accessing `index.undefined`.

I'm working on a fix for both of these cases so thanks so much for providing this test case to look into that. Will post an update here when I've got a PR up.

In terms of the use case that you are after, I assume you are using code splitting to allow the individual implementations to be required on their own like `require('color-tf/dist/cjs/hsl2hsv.js')` while also supporting `require('color-tf')`? If so I'd suggest running the build with `input: ['main.js', 'hsl2hsv.js']`. Note that **input** is best thought of as the output **entry points** not the input modules, as these will be automatically traced.

If I use that input value I get just the two output files closer to what you're probably expecting.

Will aim to get those bugs fixed for you though soonest.

**Comment by caub** [comment]
@guybedford yes, thanks, I'm wanting an output a la `date-fns` or `lodash`

putting everything in `dist/`, then publishing that directory

I've added this temporary config: https://github.com/caub/color-tf/blob/master/rollup.config.debug.js
When I run it the individual files are well-generated, but it's still problematic for `proxy.js`:

dist/src/proxy.js:
```js
import './hsl2hsv.js';
import './hsl2rgb.js';
import './hsv2hsl.js';
import './hsv2hwb.js';
import './hsv2rgb.js';
import './hwb2hsv.js';
import './hwb2rgb.js';
import './rgb2hsl.js';
import './rgb2hsv.js';
import './rgb2hwb.js';

var lib = /*#__PURE__*/Object.freeze({
  hsl2hsv: hsl2hsv,
  hsl2rgb: hsl2rgb,
  hsv2hsl: hsv2hsl,
  hsv2hwb: hsv2hwb,
  hsv2rgb: hsv2rgb,
  hwb2hsv: hwb2hsv,
  hwb2rgb: hwb2rgb,
  rgb2hsl: rgb2hsl,
  rgb2hsv: rgb2hsv,
  rgb2hwb: rgb2hwb
});
```

dist/proxy.js:

```js
'use strict';

require('./hsl2hsv.js');
require('./hsl2rgb.js');
require('./hsv2hsl.js');
require('./hsv2hwb.js');
require('./hsv2rgb.js');
require('./hwb2hsv.js');
require('./hwb2rgb.js');
require('./rgb2hsl.js');
require('./rgb2hsv.js');
require('./rgb2hwb.js');



var lib = /*#__PURE__*/Object.freeze({
  hsl2hsv: hsl2hsv,
  hsl2rgb: hsl2rgb,
  hsv2hsl: hsv2hsl,
  hsv2hwb: hsv2hwb,
  hsv2rgb: hsv2rgb,
  hwb2hsv: hwb2hsv,
  hwb2rgb: hwb2rgb,
  rgb2hsl: rgb2hsl,
  rgb2hsv: rgb2hsv,
  rgb2hwb: rgb2hwb
});
```

**Comment by guybedford** [comment]
Yup, working on a fix, that's actually been a long-standing bug it seems - 

https://rollupjs.org/repl?version=0.58.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMG0lMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKE9iamVjdC5rZXlzKG0pKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAlN0IlMjB4JTIwJTdEJTIwZnJvbSUyMCdleHRlcm5hbDInJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by guybedford** [comment]
I've posted the fix at https://github.com/rollup/rollup/pull/2157.
