### ISSUE TITLE
Yet another module bundler

### ISSUE THREAD

**Issue by Sinewyk** [rollup/rollup#219]
Any reason why the concept (not importing everything from es6 modules) could not be done as a browserify transform/webpack loader ?

**Comment by Victorystick** [comment]
Importing ES6 code can indeed be done using a browserify transform or a webpack loader; such tools already exist. However, the result will not be _as efficient_ as the Rollup equivalent due to how those tools bundle the modules.

**Comment by Sinewyk** [comment]
That's my point. Wouldn't it have been more _efficient_ to dig in those codebases to implement the roll up concept code rather than trying to re-do already everything else that has already been done ?

Did you approach the browserify/webpack people to try to implement it ?

**Comment by Rich-Harris** [comment]
@Sinewyk it's a fair question, and one that we've been asked a few times, so I'll try and answer as thoroughly as possible so that this can serve as a reference.

Forget about the tree-shaking for a moment. Webpack and Browserify have their [differences](https://gist.github.com/substack/68f8d502be42d5cd4942), but fundamentally they work off the same basic concept: wrap each module in a function, then wrap all those functions in a bundle that includes a module loader (Browserify's prelude.js or Webpack's `__webpack_require__`).

Rollup, by contrast, works similarly to es6-module-transpiler and Esperanto (both now deprecated in favour of Rollup). Rather than wrapping each module in its own function, all modules share a single scope. That makes ES6 module features like [bindings](https://github.com/rollup/rollup/wiki/Bindings) and [cycles](https://github.com/rollup/rollup/wiki/Cycles) trivial to implement; it also means that you're not paying the per-module cost of wrapping and continually re-declaring imports. The end result is far more compact, even in situations where tree-shaking wouldn't help because all the code is being used. (Here is [Redux built with Webpack](https://gist.github.com/Rich-Harris/d47fcf788ce160fdefd8), here it is [built with Rollup](https://gist.github.com/Rich-Harris/d9bcf812495c3fc45923) – minified and gzipped, the Rollup version is 14.5% smaller.)

Could you do that in Browserify and Webpack? I don't know, but my hunch is that it would be rather difficult – you're basically talking about a fundamental rethink of how they work. When I started writing Rollup, it was an experiment that I wasn't certain would succeed. It would have been rather bold of us to approach the maintainers of those tools to ask whether they'd consider tearing up their designs based on a hunch, so we chose instead to build a new, simple tool, focused on ES6 modules from the ground up (rather than being CommonJS-centric and supporting ES6 modules via transforms).

## Webpack 2 will support tree-shaking

See [here](https://github.com/webpack/webpack/pull/861#issuecomment-149997270) for the details. This is really fantastic news – Webpack has a large user base, and those users now have a powerful incentive to start using ES6 modules. Developments like this are significant in terms of moving the JS community away from legacy module formats, and I'm thrilled about it.

But the idea is still basically the same – wrap modules, supply a module loader. Compare [this example of Webpack 2](https://github.com/webpack/webpack/tree/webpack-2/examples/harmony-unused#jsoutputjs) with the [equivalent Rollup example](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22iife%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20%7B%20add%20%7D%20from%20'.%2Fmath'%3B%5Cnimport%20%7B%20reexportedMultiply%20%7D%20from%20%5C%22.%2Flibrary%5C%22%3B%5Cn%5Cnadd(1%2C%202)%3B%5CnreexportedMultiply(1%2C%202)%3B%22%7D%2C%7B%22name%22%3A%22math.js%22%2C%22code%22%3A%22export%20function%20add()%20%7B%5Cn%20%20%20%20var%20sum%20%3D%200%2C%20i%20%3D%200%2C%20args%20%3D%20arguments%2C%20l%20%3D%20args.length%3B%5Cn%20%20%20%20while%20(i%20%3C%20l)%20%7B%5Cn%20%20%20%20%20%20%20%20sum%20%2B%3D%20args%5Bi%2B%2B%5D%3B%5Cn%20%20%20%20%7D%5Cn%20%20%20%20return%20sum%3B%5Cn%7D%5Cn%5Cnexport%20function%20multiply()%20%7B%5Cn%20%20%20%20var%20product%20%3D%201%2C%20i%20%3D%200%2C%20args%20%3D%20arguments%2C%20l%20%3D%20args.length%3B%5Cn%20%20%20%20while%20(i%20%3C%20l)%20%7B%5Cn%20%20%20%20%20%20%20%20product%20*%3D%20args%5Bi%2B%2B%5D%3B%5Cn%20%20%20%20%7D%5Cn%20%20%20%20return%20product%3B%5Cn%7D%5Cn%5Cnexport%20function%20list()%20%7B%5Cn%20%20%20%20return%20Array.from(arguments)%3B%5Cn%7D%22%7D%2C%7B%22name%22%3A%22library.js%22%2C%22code%22%3A%22export%20%7B%20a%2C%20b%2C%20c%20%7D%20from%20%5C%22.%2Fabc%5C%22%3B%5Cnexport%20%7B%20add%20as%20reexportedAdd%2C%20multiply%20as%20reexportedMultiply%20%7D%20from%20%5C%22.%2Fmath%5C%22%3B%22%7D%2C%7B%22name%22%3A%22abc.js%22%2C%22code%22%3A%22export%20function%20a()%20%7B%20console.log(%5C%22a%5C%22)%3B%20%7D%5Cnexport%20function%20b()%20%7B%20console.log(%5C%22b%5C%22)%3B%20%7D%5Cnexport%20function%20c()%20%7B%20console.log(%5C%22c%5C%22)%3B%20%7D%22%7D%5D%7D). 

## When should you use Webpack?

Webpack really shines if you're developing a complex application. I don't personally use it, because I'm not particularly keen on the way it encourages Webpack-specific idioms (such as overloading `require()` to sometimes mean 'load this module', sometimes mean 'have these side-effects', and sometimes mean 'generate this URL'), but that's just me – a huge number of developers are in love with it, and we've seen some incredibly cool stuff (such as hot module replacement) come from the Webpack camp. I'm glad that it exists.

It makes less sense if you're developing a library. The idea that a library should include a module loader (i.e. `__webpack_require__`) *just so it can load its own modules* is, if you think about it, rather bizarre. But that's not Webpack's fault – developers flocked to it in the absence of an alternative. Rollup aims to be one such alternative. (I say 'one such' and not 'the' because the great thing about standards is that annoying details such as which module bundler you use *fade into the background* – we can stop writing Browserify code and Webpack code and RequireJS code, and just write JavaScript.)

------

I hope this goes some way towards explaining why this exists as a separate project. It doesn't exist as a criticism of Browserify (which I still use, occasionally) or Webpack, it exists because ES6 modules encourage a completely different approach to module bundling.

I'll close this issue, but happy to continue the discussion if necessary.

**Comment by Sinewyk** [comment]
Thanks for detailed explanations. I only hope in the future we can merge some of these tools to avoid fragmenting even more the community.

I'll continue using webpack for applications (dev-server, code splitting), but I'll probably keep rollup in mind for libraries or simple applications where I don't need code splitting and can make due livereload stuff in another way.

nb: I'm only sligthly aware of webpack behavior for module bundling, I'm not proficient in saying how difficult it would be to merge both systems. Sorry if I was a condescending.

**Comment by Rich-Harris** [comment]
> nb: I'm only sligthly aware of webpack behavior for module bundling, I'm not proficient in saying how difficult it would be to merge both systems. Sorry if I was a condescending.

Not at all! It's a totally legitimate question that lots of people have asked :beers:

**Comment by sokra** [comment]
> it exists because ES6 modules encourage a completely different approach to module bundling.

It's a pretty valid reason. A static module syntax (ES6) allows a wide range to advanced optimization (see rollup), which would be difficult to integrate in a module bundler which allows mixing of ES6, CommonJS and AMD.

**Comment by Rich-Harris** [comment]
Thanks @sokra – awesome to see you here. (And thanks for [source-map-visualization](http://sokra.github.io/source-map-visualization/#custom), I use it a lot, and the other day I suddenly realised 'hey, this was made by the Webpack guy!')

**Comment by FezVrasta** [comment]
@Rich-Harris thanks for the awesome post, would you care to elaborate this sentence?

> it encourages Webpack-specific idioms (such as overloading require() to sometimes mean 'load this module', sometimes mean 'have these side-effects', and sometimes mean 'generate this URL')

I'm studying the downsides of `import` vs `require` in WebPack and yours seem like good points.

**Comment by Shyam-Chen** [comment]
Rollup writes less code than Webpack 2. (Easy to configure)
