### ISSUE TITLE
[experimentalCodeSplitting] imports left in incorrect chunks

### ISSUE THREAD

**Issue by Andarist** [rollup/rollup#2207]
[This](https://github.com/Andarist/rollup-splitting-issue/blob/fa02223bd56338b920f5dfcdc34cef205c09c413/src/base.js#L1) is the only import requesting `add` from `ramda`. However side effect import is left over [here](https://github.com/Andarist/rollup-splitting-issue/blob/fa02223bd56338b920f5dfcdc34cef205c09c413/es/index.js#L2) whereas it shouldn't appear in this chunk at all.

**Comment by lukastaegert** [comment]
This is actually a feature. And a performance optimization of sorts.

Rollup knows that in order to run `index.js`, you need to have both `base.js` and its transitive dependency `ramda` available.

Without the empty import, the runtime would parse `index.js`, discover it needs `base.js`, load `base.js`, discover it needs `ramda`, and then load `ramda`.

By injecting a "side-effect import" of the transitive dependency, the runtime can immediately load both `base.js` and `ramda` in parallel once `index.js` has been parsed thus saving a loading roundtrip and speeding up startup time.

**Comment by lukastaegert** [comment]
This does not affect execution order.

**Comment by Andarist** [comment]
Hm, seems quite reasonable, I'm only worried that it might affect some tree-shaking algorithms (webpack's maybe?) in a bad way - not sure if it does.

**Comment by lukastaegert** [comment]
It should not affect them as basically nothing is imported except the initialization code. Of course we cannot be sure but I don't think we should optimize for sub-optimal algorithms. At least in the case of external modules, I would expect Webpack to strip them out provided the library sets the`sideEffects: false` flag in its `package.json`.

And if the code is wrapped in a runtime (as does Webpack if module concatenation is not possible), the code would still only be run once.

I assume this can be closed?

**Comment by Andarist** [comment]
Yeah, until some problem arise with this approach I'm gonna close it. Thanks for the explanation!
