### ISSUE TITLE
Migration path for webpack users?

### ISSUE THREAD

**Issue by dmr** [rollup/rollup#221]
I just rediscovered this project from the webpack-2 pull request and I'd like to give it a try.
But the problem is that webpack provides many features that my project needs, mostly DefinePlugin and  ProvidePlugin and also I have many loaders that my project requires for things.

Is there a "convert webpack config" example of some documentation on how to switch to rollup?

**Comment by Rich-Harris** [comment]
Not exactly – I'd kind of prefer to leave 'migration guides' to other people, since I've discovered people get emotional if you do something that could be construed as criticism of another project, even if the intention is anything but. (The very existence of this project offends some people!)

Having said that, I can offer one example – I wrote a [Rollup build script for Redux](https://github.com/Rich-Harris/redux/blob/rollup/build.js) that mirrors the Webpack config ([1](https://github.com/rackt/redux/blob/master/webpack.config.base.js), [2](https://github.com/rackt/redux/blob/master/webpack.config.development.js), [3](https://github.com/rackt/redux/blob/master/webpack.config.production.js)). It uses version 0.20.0, which is unreleased pending review (#209), and which allows the use of plugins. In the example, we're using [rollup-plugin-replace](https://github.com/rollup/rollup-plugin-replace) to do the same job as DefinePlugin.

So far there's only a [handful of plugins](https://github.com/rollup/rollup/wiki/Plugins#list-of-plugins), which will be released to npm once 0.20.0 is released. A ProvidePlugin equivalent is definitely possible, and most loaders should be fairly straightforward to implement assuming they're just wrapping existing compilers (e.g. TypeScript, CoffeeScript etc).

My general feeling is that relying on plugins is a bit of an anti-pattern in most cases, since it means you end up writing tool-specific code which results in exactly these sorts of migration headaches. But it's definitely useful to know which plugins people commonly use so we can help minimise the pain involved.

**Comment by Rich-Harris** [comment]
FYI I cobbled together a ProvidePlugin equivalent: https://github.com/rollup/rollup-plugin-inject

**Comment by dmr** [comment]
Thank you for the detailed response.

I agree that plugins are not good to rely on but for me plugins were the reason that allowed me to transition to webpack away from requirejs in the first place. So in the long run I would say get rid of plugins but to get users started they are helpful.

Thank you also for the inject plugin, I'll have a look into that.
