### ISSUE TITLE
Handling known undefined properties

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#2222]
For cases like - 

```js
var a = {
	b: {
		c: 'd'
	}
};

if (a.b.d)
  console.log('yes');
```

surely we have all the analysis at this point to know that `a.b.d` is undefined and therefore falsy? Is this related to https://github.com/rollup/rollup/issues/2215?

**Comment by GrosSacASac** [comment]
Hi, I am curious , why does rollup need to analyze anything that is inside an if ? I thought rollup would only be concerned about finding top level import and export.

**Comment by lukastaegert** [comment]
Rollup's tree-shaking has evolved quite a bit since then. Imagine a situation like this one:

```js
import foo from 'foo.js';
import bar from 'bar.js';

function startup() {
  if (bar) foo();
}

startup();
```

Today, rollup can detect that if `bar` is always `false`, then `foo` will be tree-shaken even though its call is inside a function. It is a common misconception that tree-shaking has to do anything with top level ES module statements or ES modules at all. Incidentally, I recently held a talk explaining this: https://events.techcast.com/btd/2018/Garmisch_1130/

**Comment by GrosSacASac** [comment]
Interesting thank you very much.
