### ISSUE TITLE
Incorrect function name mangling while tree shaking dependencies

### ISSUE THREAD

**Issue by diervo** [rollup/rollup#2230]
Rollup does some incorrect mangling for function names while tree shaking. We have seen this behavior for quite a while, so not sure what exact version this was introduced.

I believe this might be a trivial bug to fix for the owners if you know the code base. Otherwise, if you don't have time to prioritize this, let me know and I will dig in.

[Repro](https://rollupjs.org/repl?version=0.59.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMF9pbmhlcml0cyUyMGZyb20lMjAlNUMlMjIuJTJGaW5oZXJpdHMlNUMlMjIlM0IlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjB0ZXN0KCklMjAlN0IlNUNuJTIwJTVDdCUyMHZhciUyMEZvbyUyMCUzRCUyMCU3QiU3RCUzQiU1Q24lMjAlMjBfaW5oZXJpdHMoJTdCJTdEJTJDJTIwRm9vKSUzQiU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyaW5oZXJpdHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwc2V0UHJvdG90eXBlT2YlMjBmcm9tJTIwJTVDJTIyLiUyRnNldFByb3RvdHlwZU9mJTVDJTIyJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBfaW5oZXJpdHMoc3ViQ2xhc3MlMkMlMjBzdXBlckNsYXNzKSUyMCU3QiU1Q24lMjAlMjBpZiUyMChzdXBlckNsYXNzKSUyMHNldFByb3RvdHlwZU9mKHN1YkNsYXNzJTJDJTIwc3VwZXJDbGFzcyklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJzZXRQcm90b3R5cGVPZi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBfc2V0UHJvdG90eXBlT2YobyUyQyUyMHApJTIwJTdCJTVDbiUyMCUyMF9zZXRQcm90b3R5cGVPZiUyMCUzRCUyME9iamVjdC5zZXRQcm90b3R5cGVPZiUyMCU3QyU3QyUyMGZ1bmN0aW9uJTIwX3NldFByb3RvdHlwZU9mKG8lMkMlMjBwKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBvLl9fcHJvdG9fXyUyMCUzRCUyMHAlM0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwbyUzQiU1Q24lMjAlMjAlN0QlM0IlNUNuJTVDbiUyMCUyMHJldHVybiUyMF9zZXRQcm90b3R5cGVPZihvJTJDJTIwcCklM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

## Code example: 
This example is a boiled down version of the use of babel helpers (latests babel 7).

main.js
```js
import _inherits from "./inherits";
export function test() {
    var Foo = {};
   _inherits({}, Foo);
}
```

inherits.js
```js
import setPrototypeOf from "./setPrototypeOf";

export default function _inherits(subClass, superClass) {
  if (superClass) setPrototypeOf(subClass, superClass);
}
```

setPrototypeOf.js

```js
export default function _setPrototypeOf(o, p) {
  _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) {
    o.__proto__ = p;
    return o;
  };

  return _setPrototypeOf(o, p);
}
```

Output:

```js
Object.defineProperty(exports, '__esModule', { value: true });

function _setPrototypeOf(o, p) {
  _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) {
    o.__proto__ = p;
    return o;
  };

  return _setPrototypeOf(o, p);
}

function _inherits(subClass, superClass) {
  // HERE: setPrototypeOf is incorrectly scoped it should be _setPrototypeOf
  if (superClass) setPrototypeOf(subClass, superClass);
}

function test() {
 	 var Foo = {};
  _inherits({}, Foo);
}

exports.test = test;
```

As you can see the `setPrototypeOf` call is named incorrectly.

**Comment by diervo** [comment]
Do add a bit more detail, I think the issue is because of the dynamic binding used in the `_setPrototypeOf` exported function.

**Comment by lukastaegert** [comment]
Seems to be a very old issue around the interplay of assigning names to default exports that have ids themselves and are reassigned. Would probably need to check how a "real" ES6 loader handles this. The issue is very specific to the use of default exports. You can avoid it effectively by using named exports.

Even simpler repro: [REPL](https://rollupjs.org/repl?version=0.59.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGIlMjBmcm9tJTIwJTVDJTIyLiUyRmElNUMlMjIlM0IlNUNuJTVDbmIoKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMGEoKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coJ2VmZmVjdCcpJTNCJTVDbiU1Q3QlNUNuJTVDdCUyRiUyRiUyMHJlbW92ZSUyMHRoaXMlMjBsaW5lJTIwdG8lMjBmaXglNUNuJTIwJTIwYSUyMCUzRCUyMHNvbWVHbG9iYWwlM0IlNUNuJTIwJTIwcmV0dXJuJTIwYSgpJTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

**Comment by diervo** [comment]
@lukastaegert I wish I could change the names, but this is babel helpers compilation. 
If we don't fix this rollup will never be compatible with babel7 when using runtime-tranform for inlining helpers.

I will try to take a look and send a PR.

**Comment by guybedford** [comment]
I'm also looking into this, but haven't found an easy fix yet either. Will post back if I make progress too.

**Comment by lukastaegert** [comment]
I'll be on a trip from tomorrow to Sunday so I'll not be able to help before next week, sorry.

**Comment by guybedford** [comment]
I've created a fix here in https://github.com/rollup/rollup/pull/2234.
