### ISSUE TITLE
Rollup overrides runtime environment function definitions in a TypeScript project

### ISSUE THREAD

**Issue by ciddan** [rollup/rollup#2249]
Adding rollup to our project (as a dependency of systemjs-builder) broke our build, since rollup redefines the signatures of some global functions, like setInterval and setTimeout, through the `@types/node` package. We're building a client-side SPA, so having runtime functions redefined for a NodeJS context is not great for us. This hasn't been an issue for us in the past, so either rollup was added as a dependency of SystemJS-Builder or @types/node was added to rollup.

How come `@types/node` is listed as a dependecy of rollup and not as a devDependency?

Reproduction available here: https://github.com/ciddan/rollup-typescript-issue

**Comment by guybedford** [comment]
It sounds like the issue here is specifically that Rollup pulls in the Node.js typing as a dependency. This has come up before as well.

I believe there should be some combination of ignores in the tsconfig.json to stop this from happening?

We could potentially look at making the Rollup typing no longer depend on the Node typing, which would involve inlining EventEmitter (https://github.com/rollup/rollup/blob/master/src/rollup/types.d.ts#L10) and possibly some others.

**Comment by ciddan** [comment]
Thanks for the tip, @guybedford. I found the types section of tsconfig:
```javascript
{
    "compilerOptions": {
        "types": []
    }
}
```
That allows you to specifically _include_ `@types` packages from `node_modules`. I'd consider this more of a work around than a fix, though.

**Comment by guybedford** [comment]
Yes, removing the Node typings altogether from Rollup would be a fix here. Perhaps that is something we can look into.

**Comment by guybedford** [comment]
I did try this again, but it's not just the EventEmitter case - things like `fs` and `Buffer` also don't work this way.

Closing as a wontfix unfortunately.
