### ISSUE TITLE
"xyz" is not exported when it IS

### ISSUE THREAD

**Issue by ksnyde** [rollup/rollup#2251]
I have a Typescript library which I'm transpiling into ES2015 module format. I then use `bili` which uses `rollup` to transpile to CJS and UMD. I use a popular npm library called "Pluralize" which I believe exports to AMD and CJS. Anyway the initial transpilation using `tsc` to ES2015 works fine but then rollup gives me the following error:

>  'plural' is not exported by 'node_modules/pluralize/pluralize.js'

Not sure this is an issue with rollup or not so hopefully it isn't too cheeky to raise this issue. I did try the Gitter channel first but got no response. Anyway, i'm desperate. Lost a day and want to start moving forward again.

[Pluralize](https://www.npmjs.com/package/pluralize), [Typings](https://www.npmjs.com/package/@types/pluralize)

**Comment by lukastaegert** [comment]
Hi @ksnyde, sorry for the issues you have. The problem is quite possibly that `pluralize` creates its named exports in a very dynamic way that the TypeScriptCompiler cannot translate to named exports. Thus you cannot `import {plural}  from 'pluralize'` but have to do something like
```js
import pluralize from 'pluralize';
const plural = pluralize.plural; // or always use it via pluralize.plural
```

Hope this helps. I know this can be confusing as it is a very technical issue.

**Comment by guybedford** [comment]
I've created https://github.com/rollup/rollup-plugin-commonjs/issues/323 to track this on the CommonJS plugin side.
