### ISSUE TITLE
using rollup --watch, I can't scroll up

### ISSUE THREAD

**Issue by luisrudge** [rollup/rollup#2252]
Issue demonstrated here:

![rollup](https://user-images.githubusercontent.com/941075/41150510-8c40bbd4-6ae4-11e8-808c-ddd35e78c84b.gif)

**Comment by EvanLovely** [comment]
Me either 😢

**Comment by assertnotnull** [comment]
This change also overwrite the console output when used with npm-run-all.
It has a lof of consequences because I can't see log ouput anymore now therefore I can't update.

**Comment by luisrudge** [comment]
any news on this? 😬

**Comment by shellscape** [comment]
@luisrudge have you tried adding the following to your config?

```js
  watch: {
    clearScreen: false
  },
```

**Comment by luisrudge** [comment]
@shellscape that works as a workaround, thanks! I still prefer when the screen is cleared, but I can live with this.

**Comment by shellscape** [comment]
The documentation can probably be clearer on this. What `clearScreen` is actually doing, is telling the terminal to use an _alternate_ screen. The code in Rollup sends a character to the terminal if `clearScreen: true`. You can read more about what that means here: https://unix.stackexchange.com/a/289055

@guybedford @lukastaegert is there an opportunity here for a documentation change? is `clearScreen` an accurate name for that option, considering the above?

**Comment by lukastaegert** [comment]
Not 100% sure what a better name would be but we could certainly do a soft deprecation/option rename with the 1.0 release. I guess `alternateScreen: false/true` would be a better fit technically but I am not sure everyone will understand that this has the effect of controlling if the screen is cleared 😉

**Comment by timdavish** [comment]
How is this not considered a bug? For example, jest seems to also use an alternate screen during watch mode, but you can scroll up just fine when the content overflows that particular screen. Is this same behavior not accomplishable for rollup watch mode?

Setting `watch: {clearScreen: false}` is definitely a workaround but does not seem like an actual solution to the problem the video demonstrates. Otherwise, it seems like `watch: {clearScreen: false}` should be a default option during watch mode, as not being able to scroll to see the full build output is not ideal behavior?

**Comment by timdavish** [comment]
@lukastaegert @shellscape 

How is this not considered a bug? For example, jest seems to also use an alternate screen during watch mode, but you can scroll up just fine when the content overflows that particular screen. Is this same behavior not accomplishable for rollup watch mode?

Setting `watch: {clearScreen: false}` is definitely a workaround but does not seem like an actual solution to the problem the video demonstrates. Otherwise, it seems like `watch: {clearScreen: false}` should be a default option during watch mode, as not being able to scroll to see the full build output is not ideal behavior?

Perhaps I am just missing something and/or need further explanation.

(Re-commented with @'s as I don't think this was going to be seen since the issue's closed.)

**Comment by lukastaegert** [comment]
Yes, this should be improved

**Comment by lukastaegert** [comment]
Note though that at least for my tests, Jest is NOT using an alternate screen (when you quit Jest, you still see the last output).

**Comment by lukastaegert** [comment]
After playing around a little more and googling a bit I feel we should just get rid of the alternate screen altogether as its utility is rather limited and just do the clear screen between runs (as Jest does), which will still allow scrolling.

**Comment by lukastaegert** [comment]
Please check out #2942. Would be very nice if people could check this against various terminals to see if it behaves as expected. My guess is that the alternate screen was one of those "it seemed like a good idea at that time" things. If nobody cries out, I will merge this soon.
