### ISSUE TITLE
Fix code coverage reporting

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#227]
IIRC, I _think_ the problem was that remap-istanbul was trying to load some files that weren't on disk (their content had been bundled, making inclusion unnecessary, but it still caused a problem even though the content existed in the sourcemap's `sourcesContent` array), but I haven't thoroughly investigated yet.

**Comment by irae** [comment]
I spent a little time on this, and it is a bit more complicated than that.

The real issue is that istanbul is not able to hook and instrument `dist/` and `bin/rollup`.

To prove that, just try:

   ./node_modules/.bin/istanbul cover --verbose --no-default-excludes --report json node_modules/.bin/_mocha -- -u exports -R spec test/test.js

Some of the lines you get are:

    Module load hook: transform [/Users/irae/code/rollup/node_modules/commander/index.js]

This happened because `--no-default-excludes` let istanbul instrument `node_modules`. Now, what we don't see there is rollup compiled files. I tried investigating stuff related to default excludes, gitignore and etc. and I still got no luck.

I have two hypothesis, but no time to check it:

  1. Because you use `readFileSync` to load some tests, istanbul is not able to hook into `require` and can't instrument those files.
  2. There might be a conflict between `--compilers js:buble/register` and istanbul. Because both are replacing nodejs require, if any of the implementations are slightly incompatible, it might result in istanbul not instrumenting the files it needs to.

Honestly, I think the second hypothesis is way more likely to be the problem, specially because `--compilers js:buble/register` is not the only hook. There is also the source map hook and the console group hook too.

**Comment by shellscape** [comment]
I started poking at this problem the other day. I switched everything to use `nyc` rather than intanbul directly, and this worked in part. It reported coverage for `src`. The problem with that approach is that the files in the bundle from `node_modules` were also being reported in coverage:

![nyc coverage](https://media.discordapp.net/attachments/466787074893283332/476848434498764810/Screen_Shot_2018-08-08_at_4.24.51_PM.png)

No combination of `exclude` nor `include` setting would resolve that.

It's my thinking after looking at this that a move to `jest`, or other test suite framework that can handle TypeScript natively, and using `src` directly rather than a rolled module in `dist` will accurately give us coverage. However, that would likely require assembling some "key" tests that would also need to run against the rolled module in `dist` as a sanity check.

**Comment by lukastaegert** [comment]
Why not have two different ways for running the same test suite? This already happens today on CI in that after a successful run of the test suite, the created bundle is used to run the test suite again as a last smoke test to see if the new version of Rollup is able to create a fully functional version of Rollup itself. We could adapt this in that the first time we use source files or a special build of Rollup with instrumentation while the second time we use a bootstrapped production build without instrumentation.

**Comment by shellscape** [comment]
Admittedly, instrumentation is not my forte´. If we could get a bundle that was instrumented properly, that'd do the trick. My attempts to make that happen weren't successful. The _only_ pain point to running the test suites twice would be double the run time. (#2390 would help with that, and we could run those extra passes parallel)

**Comment by lukastaegert** [comment]
So let's visit this again once we are fully on CircleCI?
