### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by jeffsaremi** [rollup/rollup#2332]
First off I don't even know if rollup is the tool i should be using or not.
I have a few TS files which are compiled into JS. I now want to avoid having to refer to run my code in Chrome browser. I don't care if my code runs in node.js or not.
If my assumption is correct then this is how i proceeded:

- installed rollup using npm install -g 
- did a --help and it looked like the option --format iife is what i need
- ran rollup against the entry script in a folder where only my js files resided:
`rollup test_entry.js --file bundle.js --format iife`
- referenced the resulting bundle.js in my html:
`<script src='bundle.js'></script>`
- launched the html file in chrome with the developer extension open.
- i got the above error against this line:
`Object.defineProperty(exports, "__esModule", { value: true });`

**Comment by lukastaegert** [comment]
Your approach looks sound to me. I am a little puzzled that your code contains the line `Object.defineProperty(exports, "__esModule", { value: true })` as this line should only be added for formats cjs, umd and amd.

Is this line added by rollup or is it already part of your code? Are you using rollup-plugin-typescript? Otherwise you should make sure that the TypeScript is compiled to ES6 modules, not CommonJS (compilerOptions.module = 'ES6') unless you want to add rollup-plugin-commonjs as well.

**Comment by jeffsaremi** [comment]
Lukas thanks very much for weighing on this
I went back and changed the target in typescript.json to ES2015 from CommonJS.
I also changed the format on rollup command line to "umd"
The result is now runnable with no issues in Chrome.
Just wanted to add that the simplicity of "rollup" usage is amazing!
Closing this

**Comment by abhilashdk2016** [comment]
Hi I am facing the same issue. In tsconfig target is ES2015, module is commonjs.For rollup  format is set to "umd". But still In the generated JS  is see `Object.defineProperty(exports, "__esModule", { value: true });`. 

Could you provide me the right combination of target, module and format so that I don't get the exports option in generated module.

I am using gulp-rollup in the below format:
`.pipe(rollup({
                    format: "umd",
                    moduleName: "DataStructuresAlgorithms",
                    entry: PATHS.bundleJSMainFile
                }))`

**Comment by BlackGlory** [comment]
`format: 'es'` also has the same problem.

**Comment by BlackGlory** [comment]
The key to this problem is that js files generated by TypeScript contain `Object.defineProperty(exports, "__esModule", {value: true });`, even if they do not actually have any exports (such as pure type files).
There is currently no way to improve this behavior, please subscribe to this [issue](https://github.com/microsoft/TypeScript/issues/32934).

This is my current solution:
```js
plugins: [
  replace({
    'Object.defineProperty(exports, "__esModule", { value: true });': '',
    delimiters: ['\n', '\n']
  }),
  ...
]
```

**Comment by suman-kr** [comment]
Facing the same issue. Anyone has the resolution?

**Comment by cjmyles** [comment]
@BlackGlory's fix worked for me. You'll need the [replace plugin](https://www.npmjs.com/package/@rollup/plugin-replace) for it to work.

**Comment by janniks** [comment]
_In case this helps anybody:_

For me, putting the `commonjs` plugin before the `replace` plugin fixed it.

**Comment by StoneCypher** [comment]
In general, `typescript` will emit that code when you have your `module` set to `commonjs`.  You need to manage more than just your `target`.

Change both `module` and `target` to `es2015`, and everything should be fixed.

**Comment by Babailan** [comment]
when exporting something on entry point file it keeps throwing error I realize that you shouldn't do that because it's the main file, it can only import what you need in project . am I wrong or not.

**Comment by subash-0** [comment]
Hii everyone , i just wondering with the same issue . here is my vite.config file 
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import legacy from '@vitejs/plugin-legacy';
import { babel } from '@rollup/plugin-babel';

export default defineConfig({
  plugins: [
    react(),
    babel({
      babelHelpers: 'bundled',
      extensions: ['.js', '.jsx', '.ts', '.tsx'],
      presets: [
        [
          '@babel/preset-env',
          {
            targets: {
              browsers: ['Chrome >= 49', 'Android >= 5'],
            },
            useBuiltIns: 'entry',
            corejs: 3,
          },
        ],
        '@babel/preset-react',
      ],
    }),
    legacy({
      targets: ['Chrome >= 49', 'Android >= 5'], // Explicit targets
      additionalLegacyPolyfills: ['regenerator-runtime/runtime'], // Ensure async/await works
      modernPolyfills: true, // Use modern polyfills where available
    }),
    
  ],
  esbuild: {
    target: 'es2015',
  },
  base:'/',
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
    rollupOptions: {
      output: {
        entryFileNames: 'assets/[name]-[hash].js',
        chunkFileNames: 'assets/[name]-[hash].js',
        assetFileNames: 'assets/[name]-[hash].[ext]',
      },
      external: ['react-player'], // Exclude react-player from bundling
    },
  },
  optimizeDeps: {
    include: ['react-player'],
    esbuildOptions: {
      target: 'es2015',
    },
  },
  resolve: {
    alias: {
        '@': '/src', // Optional: Alias for cleaner imports
    },
  },
});

just provide me the solution of Uncaught ReferenceError: exports is not defined

**Comment by Jabher** [comment]
> Change both `module` and `target` to `es2015`, and everything should be fixed.

Sadly, it is sometimes impossible to do that. For example, if you want to use babel - all of them have this issue. E.g.
https://unpkg.com/browse/@babel/plugin-transform-modules-systemjs@7.25.9/lib/index.js
