### ISSUE TITLE
You must specify options.format - but file and format provided

### ISSUE THREAD

**Issue by seanlandsman** [rollup/rollup#2341]
When trying a simple test case I'm encountering the following error: 

Error: You must specify output.format, which can be one of 'amd', 'cjs', 'system', 'esm', 'iife' or 'umd'

but the format has been specified in the configuration file.

My input file (main.js)  looks like this: 

`console.log("Hello World");
`
My configuration file looks as follows: 

`
export default {
    input: 'main.js',
    output: {
        file: 'rolled-up-bundle.js',
        format: 'umd'
    }
};
`

I've created a repo of the issue here: https://github.com/seanlandsman/rollup-issue

I'm using rollup version 0.63.2

thanks

**Comment by lukastaegert** [comment]
Hi @seanlandsman, I checked your repo and the issue is the way you call rollup:
```
rollup -c -silent=false rollup.config.js
```

The issue is with the second option:
1. Long options like `silent` (in contrast to e.g. `c`) need to be prefixed with two dashes `--` instead of one
2. Inverting a boolean option on the command line is done via prefixing it with `no-`. I.e. in your example, the option would be `--no-silent`. The documentation does not specify this directly but there are many examples given c.f. e.g. in this list: https://rollupjs.org/guide/en#danger-zone
3. `--no-silent` is in fact the default so you do not need to specify it :)

Hope this helps!

**Comment by seanlandsman** [comment]
@lukastaegert thanks very much!

Looking at this now I can't believe it was down to something so small - thanks very much.

Closing as clearly an issue on my side
