### ISSUE TITLE
Rolling up application that uses rolled up dependency fails with `Error: 'default' is not exported`

### ISSUE THREAD

**Issue by DianaSuvorova** [rollup/rollup#2346]
Here is the repo that repro:

[https://github.com/DianaSuvorova/rollupSquared](https://github.com/DianaSuvorova/rollupSquared)

 If I try to use rollup to bundle an app that has one of its dependencies a rolled up app it fails with `Error: 'default' is not exported by src/index_rolledUp.js`

<img width="695" alt="screen shot 2018-07-23 at 2 00 06 pm" src="https://user-images.githubusercontent.com/1284223/43102735-c9897ca0-8e80-11e8-8c3b-ece86aa0a54f.png">

**Comment by lukastaegert** [comment]
Hi @DianaSuvorova, the issue is that `index_rolledUp` is a UMD bundle which can only loaded by CJS and AMD loaders but not by vanilla Rollup which only supports the ESM format.

To consume your bundle by rollup itself, you have two options
* Add the plugin `rollup-plugin-commonjs` to `rollupSquared.config.js`. This will enable Rollup to read CJS as well. I would not recommended this in your situation as it can result in less efficient output in some cases.
* Create an ESM bundle instead of a UMD bundle in `rollup.config.js` (recommended). This will result in the best possible output.

If you also need the UMD file to be generated, you could create a "dual-mode" bundle by changing your `rollup.config.js` like this:

```json
export default {
  input: `./src/index.js`,
  output: [
    {
      file: './src/index_rolledUp.js',
      format: 'umd',
      sourcemap: 'inline',
      name: 'indexRolledUp'
    },
    {
      file: './src/index_rolledUp.mjs',
      format: 'esm',
      sourcemap: 'inline'
    },
  ],
};
```

Now you have two files with the same base name and extensions `.js` and `.mjs` and the latest versions of rollup should automatically prefer the `.mjs` file if you import without using an extension.

**Comment by DianaSuvorova** [comment]
@lukastaegert Thank you so much. That explains it and it works. 

So it sounds like recommended rollup config for libs should be including both `umd` and `esm` bundles, in case any of the dependent projects of that lib would also use Rollup as a bundler.

Thank you!
