### ISSUE TITLE
experimentalCodeSplitting with cjs format

### ISSUE THREAD

**Issue by MurakamiKennzo** [rollup/rollup#2426]
- Rollup Version: v0.65.0
- Operating System (or Browser):Mac OS 10.13.6
- Node Version: v9.10.1

### Expected Behavior

the bundle code should be execute currently.

### Actual Behavior

here is my code:

```js
// main.js

import { version } from '../package.json'

export default function(){
  console.log(version)
}

```

and: 

```js
//main2.js

export default function () {
  return import('./main.js').then(({ default: main }) => {
    main();
  });
}

```

finally:

```js
// rollup.config.js

import json from 'rollup-plugin-json'

export default {
  input: 'src/main2.js',
  output: {
    dir: 'dist',
    format: 'cjs',
  },
  plugins: [
    json(),
  ],
  experimentalCodeSplitting: true,
}

```
and when I run this shell:
```shell
  nom run rollup -- -c
```

the dist code not execute currently, 

the bundle code:

```js
// main2.js

'use strict';

function main2 () {
  return Promise.resolve(require("./main.js")).then(({ default: main }) => {
    main();
  });
}

module.exports = main2;

```

```js
// main.js

'use strict';

var version = "1.0.0";

function main$1(){
  console.log(version);
}

module.exports = main$1;

```

it seems that default is undefined in main2.js when module.exports was used in main.js.

isn't that a bug?

or someone help me please? I am greener here.

**Comment by MurakamiKennzo** [comment]
thanks for your answer, I used your config and got bundle code correctly. and since it's a bug, hoping fix it as soon as possible.

**Comment by dasa** [comment]
This Issue appears to be fixed in the latest version:
https://rollupjs.org/repl/?version=1.27.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMCgpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMGltcG9ydCgnLiUyRm1haW4yLmpzJykudGhlbigoJTdCJTIwZGVmYXVsdCUzQSUyMG1haW4lMjAlN0QpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMG1haW4oKSUzQiU1Q24lMjAlMjAlN0QpJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1haW4yLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbigpJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKCU1QyUyMnRlc3QlNUMlMjIpJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJhbWQlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by lukastaegert** [comment]
I agree, and it will adapt correctly if you make main2 an entry point as well. Feel free to reopen if there is more to fix.
