### ISSUE TITLE
Minification before optimizeChunks

### ISSUE THREAD

**Issue by manucorporat** [rollup/rollup#2439]
### Feature Use Case

Plugin hook before `optimizeChunks` runs in order to run minification. This way the `chunkGroupingSize` threshold is applied based in real final sizes. 

### Feature Proposal

Not sure about any specific implementation, I wonder if it's legit to provide some way to run minification before the `optimizeChunks` optimization.

**Comment by lukastaegert** [comment]
You could actually just minify in the `transform` hook. Paired with the `output.compact` flag, this should give you nearly the same size improvements as minifying later while giving you correct measurements. It will even be faster in most cases. As Rollup observes white-space, minified input will usually result in minified output. The (undocumented since it is somewhat experimental) `output.compact` boolean flag will take care of minifying the wrapper code added by rollup.

**Comment by manucorporat** [comment]
This is perfect @lukastaegert! Going to give it a try this afternoon. Feel free to close the issue!

https://github.com/ionic-team/stencil/commit/7e0023020d8f5db5515f79213c924c0be07553d0

We recently enabled the optimization, and as usual, incredible job from the rollup core team!

**Comment by lukastaegert** [comment]
Hope this  works for you 👍 always happy to receive feedback and thanks for the kind words!
