### ISSUE TITLE
Ability to modify or disable side effect detection behaviour

### ISSUE THREAD

**Issue by devsnek** [rollup/rollup#2506]
I'm emitting `DoExpression` AST nodes which have some interesting properties that break the current rules of side effect detection, namely that nodes that would be usually considered unused are used as part of the completion. In `(do { a })`, the `a` is used as the completion value.

Obviously this isn't really the fault of rollup, as do expressions aren't a reified part of any specification it has to deal with. However, it would be nice if I could handle this somehow.

### Expected Behavior / Situation
Emits all the nodes

### Actual Behavior / Situation
Eliminates nodes that are being used

### Modification Proposal
Ideally there could be a new API of some sort where people can tell rollup that specific ast nodes actually do need to be kept, but in the worst case adding an option to disable the entire dead code elimination system would be an acceptable solution as well.

Off the top of my head I can offer two possible systems:

1. The side effects detection system could check for a property on AST nodes, like `hasSideEffect`, which could be added by acorn plugins.

2. A function which is called on every node in the entire graph, and returns a boolean. I would imagine the signature of such a method would be `(node, path, defaultCheck)` where you could `return defaultCheck()` to skip handling the node.

**Comment by lukastaegert** [comment]
You can always disable dead-code elimination completely via `treeshake: false` ;)

As for providing a special AST API: Yes, this is definitely a very interesting idea but not without controversy. The tricky question is how to provide an API that
* is powerful enough
* does not expose too much of Rollup's internals so that we are still able to do larger refactorings without too much pain
* provides good performance

This is definitely not a short-term enhancement. Nevertheless, ideas for what such an API might look like are heartily welcome!

**Comment by devsnek** [comment]
As I've been reading through the source I've noticed something interesting...

`UnknownNode#hasEffects` always returns true without searching child nodes, so how is the body of the do expression even being searched?
