### ISSUE TITLE
[Asset emission]: Reconsider default asset filename and flexibility

### ISSUE THREAD

**Issue by wessberg** [rollup/rollup#2532]
### Feature Use Case

As described here: https://github.com/rollup/rollup/issues/2163, Rollup now supports asset emission.

This is great since plugins can now add things like CSS, images, and other static assets to a Rollup build without manually writing to disk. This is a good thing since Rollup may be invoked programmatically and the intention may not necessarily be to write these assets to disk (for example, a virtual filesystem may be used).

The asset emission API is fine as it is, but I'd like to question the default setting to emit to an `/assets` directory. Please consider the following use cases:

- (1) Generating Gzip/Brotli encoded versions of output files and emitting them alongside them
- (2) Generating Typescript/Flow declaration files and emitting them alongside files
- (3) Generating JSON metadata such as schemas or type information and emitting it alongside files

With the default Rollup options, use case (1) could lead to an output directory structure like this:

```
- index.js
- index.js.map
- /assets
     - index.js.gz
     - index.js.br
```

I think it's fair to assume that this is most often unwanted behavior. Plugin authors `could` ask plugin consumers to modify their `options.assetName` option to write to the output directory, rather than the `/asset/` directory, but I don't think that is a particularly good user experience. Also, plugins may want varying asset output directories (for example, a css plugin could write to a `/style` directory, and another one could write to a `/documentation` directory).

### Feature Proposal

For all of these use cases, including the primary one of emitting static assets, I think a better default is to emit assets alongside emitted chunks.

The plugin author can then customize this path from the output root. A simple plugin that copies static assets could then write something like:
```
emitAsset(`/assets/${myStaticFileName}`, myStaticFileContent);
```

This way, all of the above use cases, as well as the default use case of emitting static assets will be supported.

**Comment by lukastaegert** [comment]
Unfortunately I missed this one and yes, I think I see your point. Marking this as a candidate for 2.0.0. Note however there are still situations where a user could really mess up things.
- Of course if the user uses `assetFileNames`, they probably know what they do, but it may invalidate assumptions
- If `chunkFileNames` has a different directory than `entryFileNames`, placing files alongside chunks will not be possible for entry chunks. But my feeling is that the entry chunks are actually the important ones.

The longer I think about this, I am not sure if we should use the current chunk naming scheme as a default for assets but rather that both should just have similar defaults.

I wonder if it would help to add an e.g. `renderOptions` hook that works similar to the `options` hook but lets you inspect and modify output options. That way, a plugin that relies on a certain directory structure could either add the `assetFileNames` property if it is missing or issue a warning/error if it is set to an incompatible value.

**Comment by wessberg** [comment]
I agree that they should have similar defaults, exactly as you are saying. `renderOptions` could help plugin authors, sure, but I think the easiest and most flexible solution is to simply share output directory defaults. E.g. assets are emitted relative to the `dir` property of output options, and for single-file bundles, they are emitted relative to taking the directory of the `file` property of output options.

**Comment by AmySteam** [comment]
A non-breaking solution that could be implemented sooner would be to add `outputOptions.assetFileNamesMap`, an object with key/value pairs that could be used by plugin authors in the new `outputOptions` hook. 

It would follow this pattern:

```javascript
{
  assetFileNamesMap: { [assetId] : [assetFileNames pattern] },
  ...outputOptions,
}
```

This would allow plugin authors to define specific patterns for their assets.

**Comment by lukastaegert** [comment]
Hi, I keep thinking ab about this issue and my feeling is that the solution should NOT be to change the default asset path but rather recognise that there are different types of assets:
- assets that can be placed anywhere, which is what the current system can handle
- assets that need to be placed relative to (next, or in a fixed path relative to) a specific generated chunk

This is just ideas in early stages and I would love to get some feedback here:
- Do you see any type of asset that would not fall into one of those two categories?
- Maybe there should be a different way to emit assets, either via a new parameter for asset emission or via a different plugin context function to allow placing assets next to chunks
- Maybe those assets should support a name pattern so that they can have names similar to the chunk they are relative to?
- Identifying a chunk could happen by specifying a module in that chunk?
- How should we handle name conflicts? Rename, throw an error,...
- Should it be possible to reference those assets from within JS code? This would have an effect on at what stages it is possible to emit those chunks, i.e. allowing a chunk to be referenced would mean it needs to be emitted during "build" and not during "generate".
- If we do not need to reference those chunks, they could basically be emitted at (nearly) any stage, e.g. during `generateBundle` and just take all necessary information from the supplied bundle information.

**Comment by wessberg** [comment]
> Do you see any type of asset that would not fall into one of those two categories?

No, I agree with the identification of those two asset categories.

> Maybe there should be a different way to emit assets, either via a new parameter for asset emission or via a different plugin context function to allow placing assets next to chunks

I still feel that the simplest and most intuitive solution is to emit to the output directory by default and thus put the decision-making into the hands of users and plugin authors. But yes, hooks like renderChunk *could* allow returning something like "relatedFiles" or "relatedAssets" as a property from the `SourceDescription` object literal, and that would then represent assets falling into category 2.

> Maybe those assets should support a name pattern so that they can have names similar to the chunk they are relative to?

If you mean something like `[chunkFileName].gz`, I think that's OK, but since you do have access to the name of the chunk directly from the hook, I think I for one would just work with that instead.

> Identifying a chunk could happen by specifying a module in that chunk?

Not sure I'm following 100% here, but it's already pretty easy to figure out the chunk filename for a module for any `OutputChunk`.

> How should we handle name conflicts? Rename, throw an error,...

Hmm. I'm in favor of throwing, I think 😊.

> Should it be possible to reference those assets from within JS code? This would have an effect on at what stages it is possible to emit those chunks, i.e. allowing a chunk to be referenced would mean it needs to be emitted during "build" and not during "generate".

If we're talking about those assets falling into category 2 (relative assets), then I don't think it should be possible.

> If we do not need to reference those chunks, they could basically be emitted at (nearly) any stage, e.g. during generateBundle and just take all necessary information from the supplied bundle information.

That's great!

**Comment by AmySteam** [comment]
Good to see discussion on this issue! 😃

> Do you see any type of asset that would not fall into one of those two categories?

No, I think these two categories would cover it for my use cases. Right now I especially need specific paths for specific types of assets. I like the idea of a default asset pattern as a fallback. Right now, conflict between plugins seems to be a possible risk.

> How should we handle name conflicts? Rename, throw an error...

Throwing does seem to be the best alternative, since we're talking about relative paths here. Otherwise, the plugin might need to determine and modify paths other assets (imagine image paths inside stylesheets and stylesheets inside html files), which raises the complexity of developing a plugin. 

This has been a pain point for us with the current API. We're developing a plugin to derive inputs from a Chrome extension `manifest.json` file, so CSS and HTML files come up as well as JS. Some can be copied directly, but I'd rather use the Rollup API, instead of hacking together multiple approaches.

> Should it be possible to reference those assets from within JS code?

Can someone offer with a use case for this? If not, it seems like we could forgo this...

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by lukastaegert** [comment]
I think the new asset emission API now provides a better solution.
