### ISSUE TITLE
Variable collision after renamed default import

### ISSUE THREAD

**Issue by haldunanil** [rollup/rollup#2564]
- Rollup Version: `0.66.6`
- Operating System (or Browser): Mac OS 10.13
- Node Version: `v8.12.0`

### How Do We Reproduce?

I'm importing a variable from a separate library (`reactstrap`), styling it as well as adding additional characteristics and exporting. In order avoid name collisions between the `reactstrap` version of the component and mine, I'm renaming the default import of the `reactstrap` component but this is ignored when rollup compiles. My code looks like this:

```typescript
import React, { Component } from "react";
import "./Alert.scss";

import ReactstrapAlert from "reactstrap/lib/Alert";

...

export interface AlertProps extends AlertIconProps {
  canBeToggled?: boolean;
  title?: string;
  canTimeout?: boolean;
  timeout?: number;
}

export interface AlertState {
  visible: boolean;
}

class Alert extends Component<AlertProps, AlertState> {
  ...

  public render() {
    return (
      <ReactstrapAlert
        {...otherProps}
        color={color}
        data-ut="alert"
        isOpen={this.state.visible}
        toggle={canBeToggled ? this.onDismiss : null}
      >
        ...
      </ReactstrapAlert>
    );
  }
}

export default Alert;
```

However, when compiled, the renamed `ReactstrapAlert` is imported as:

```typescript
import Alert from 'reactstrap/lib/Alert';
```

which causes a collision when attempting to export my library's `Alert` component. I've also tried:

```typescript
import { default as ReactstrapAlert } from 'reactstrap/lib/Alert'; 
```

didn't work.

### Expected Behavior

When a default import is renamed when being imported, the compiler should use the renamed variable name rather than the original export name.

### Actual Behavior

See above.

**Comment by lukastaegert** [comment]
Just to clarify by "collision" you mean that one of the "Alert"s is renamed to something like `Alert$1` but the code itself is valid otherwise? I.e. this issue: https://rollupjs.org/repl?version=0.67.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmRlZmF1bHQlMjBhcyUyME90aGVyQWxlcnQlN0QlMjBmcm9tJTIwJy4lMkZsaWIuanMnJTNCJTVDbiU1Q25jbGFzcyUyMEFsZXJ0JTIwJTdCJTVDbiU1Q3Rjb25zdHJ1Y3RvcigpJTIwJTdCJTVDbiU1Q3QlMjAlMjBjb25zb2xlLmxvZygndGhpcyUyMHNob3VsZCUyMGtlZXAlMjBpdHMlMjBuYW1lJyklM0IlNUNuJTVDdCU3RCU1Q24lN0QlM0IlNUNuJTVDbmNvbnNvbGUubG9nKG5ldyUyMEFsZXJ0KCklMkMlMjBuZXclMjBPdGhlckFsZXJ0KCkpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBBbGVydCUyMCU3QiU1Q24lNUN0Y29uc3RydWN0b3IoKSUyMCU3QiU1Q24lNUN0JTIwJTIwY29uc29sZS5sb2coJ3RoaXMlMjBzaG91bGQlMjBiZSUyMHJlbmFtZWQnKSUzQiU1Q24lNUN0JTdEJTVDbiU3RCUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

Not sure what the best heuristic is here as there are some open questions, e.g. what if the default is imported several times and only renamed in some imports and not in others, and what if different aliases are used? Which should win? What we could and probably should do is see if the deconflicting logic could be reversed so that names "closer" to entry points will win over names used in dependencies.

**Comment by haldunanil** [comment]
Hi Lukas, thanks for the reply. I was able to figure it out by integrating it into a single step via the `rollup-plugin-typescript`. I think the issue was happening because I was transpiling TS into JS first and then using rollup on the transpiled output. Adding the plugin resolved the issue.
