### ISSUE TITLE
sourceMap option in plugins

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#257]
Seems like rollup-plugin-npm doesn't support sourcemaps. Is there a plan to fix this?
```
Error: Cannot generate a sourcemap if non-sourcemap-generating transformers are used
```
```js
rollup.rollup({
	entry: 'src/script/main.js',
	plugins: [
		npm({ main: true }),
		commonjs()
	]
}).then(function (bundle) {
	return bundle.write({
		format: 'iife',
		useStrict: true,
		dest: 'assets/js/main.js',
		sourceMap: true
	});
});
```

**Comment by Rich-Harris** [comment]
What other plugins are you using? rollup-plugin-npm doesn't transform anything, so it doesn't *need* to generate a sourcemap – but if you're using e.g. rollup-plugin-commonjs, you'll need to specify that sourcemaps should be generated:

```js
rollup({
  entry: 'main.js',
  plugins: [
    npm({ jsnext: true, main: true }),

    commonjs({
      include: 'node_modules/**',
      sourceMap: true
    })
  ]
}).then(...)
```

I've just realised that it doesn't say that in the README – adding it now.

**Comment by TrySound** [comment]
@Rich-Harris Yeah `sourceMap: true` option works fine. But in this case API doesn't seem pretty. However I can't imagine another way now.

**Comment by TrySound** [comment]
@Rich-Harris DId you see [postcss](https://github.com/postcss/postcss) ast? Every node contains own source code and then chunks compiles in sourcemap. Plugins control only chunks but not compile sourcemaps. Is it possible to make something like that?

**Comment by Rich-Harris** [comment]
@TrySound not sure I fully understand the question. Are you suggesting transformers that manipulate an AST instead of transforming source code (and generating a map for that transformation)? If so... I've wondered about it, since parsing is the most expensive step and it's a nuisance to repeat it, but it makes life rather more complicated (e.g. we'd need to add a codegen step)

**Comment by TrySound** [comment]
@Rich-Harris I thought rollup already manipulate ast.

**Comment by TrySound** [comment]
@Rich-Harris If so why not just contain both chunks and optionally compile whole sourcemap in the end?

**Comment by Rich-Harris** [comment]
@TrySound I still don't understand what you're proposing – Rollup *does* compile a sourcemap at the end of the process that combines all the intermediate sourcemaps.

> I thought rollup already manipulate ast.

The way it works is a little different to e.g. Babel. Because the transformations it needs to make are very slight (removing a chunk of code here, adding `exports.` there, renaming the occasional identifier), it can get away with simply replacing bits of the source code – no need to move whole nodes around etc. It does that in a sourcemap-aware way via [magic-string](https://github.com/Rich-Harris/magic-string). The advantages of this over AST manipulation and codegen are twofold: you keep all the original formatting (including comments etc), and it's very fast (though admittedly the performance benefits are reduced when you have multiple transformation steps, assuming those steps could be replaced by a series of AST manipulations, which actually isn't that realistic)

**Comment by TrySound** [comment]
@Rich-Harris I propose to drop out sourceMap options in plugins. It's not obvious and comfortable to add a few options to get only one functionality.

**Comment by Rich-Harris** [comment]
Do you mean that plugins should automatically generate sourcemaps regardless of the option? I've wondered about that – I'm sympathetic to the idea. The counterargument is that the build takes longer as a result, even for people not using sourcemaps (which I suspect is a lot of people).

**Comment by TrySound** [comment]
@Rich-Harris Yeah, I know. In this case need to think how to do less in plugins and more in rollup optionally.

**Comment by TrySound** [comment]
@Rich-Harris Maybe just need to pass MagicString instance and call generateMap in the end?

**Comment by TrySound** [comment]
@Rich-Harris Good usecase:

I want to have two npm scripts to build js with sourcemap and without. Simpler I can have only one config and just put `--sourceMap` flag. But I can't caz this flag won't be passed to plugins.

**Comment by TrySound** [comment]
@Rich-Harris The simplest, but not elegant solution is just pass sourceMap option to constructor instead of generator and then share this option with plugins. Another way is passing something like wrapper around sourcemap generator function (magicString, maybe babel has the same?).

**Comment by Rich-Harris** [comment]
> Another way is passing something like wrapper around sourcemap generator

I wondered about that but I don't think Babel has something equivalent. Am leaning towards

* plugins should generate a sourcemap by default, regardless of whether it's going to be used
* if a plugin doesn't generate a sourcemap, Rollup should warn and not throw (and treat the last non-sourcemap-accompanied transformation as the original source)

I just want to do a bit of testing around how much overhead automatic sourcemap generation is likely to entail before committing

**Comment by Rich-Harris** [comment]
Have updated all existing transformer plugins (that I know of) to automatically generate sourcemaps, and updated the wiki to encourage other plugin authors to also generate sourcemaps by default. So I'll close this

**Comment by TrySound** [comment]
Nice, thanks!

**Comment by AuthorProxy** [comment]
Same error with config from this issue: #697
