### ISSUE TITLE
import() inside rollup.config.js replaces 'this' in object literal

### ISSUE THREAD

**Issue by mad-hero** [rollup/rollup#2588]
- Rollup Version: 0.67.4
- Operating System (or Browser): Windows 10 10.0.17134.407
- Node Version: 10.14.1

### How Do We Reproduce?

```
// rollup.config.js

const configPromise = new Promise((resolve) => {
    import('./src/metadata.js').then((e) => {
        const config = {
            input: 'src/entry.js',
            output: {
                file: 'dist/bundle.js',
                format: 'iife',
                banner: e.default.getMetadataBlock()
            }
        };
        resolve(config);
    });
});

export default configPromise;
```

```
// src/metadata.js

export default {
    someString: 'asd',
    getMetadataBlock: () => {
        return this.someString;
    }
}
```

### Expected Behavior
Rollup import() not rewriting 'this' to 'undefined' in object literals.

### Actual Behavior

```
> rollup -c

loaded rollup.config.js with warnings
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en#error-this-is-undefined
src\metadata.js
2:     someString: 'asd',
3:     getMetadataBlock: () => {
4:         return this.someString;
                  ^
5:     }
6: }
(node:6076) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'someString' of undefined
...
```

**Comment by lukastaegert** [comment]
I am afraid I believe rollup is entirely correct in rewriting this to `undefined` in this situation. The problem is that you are using an arrow function instead of a traditional function which is not capable of inferring a `this` value from e.g. the way it is called but will always use the outside `this` value which is `undefined` im an ES module.

If you paste the following in your browser console, you will see that it in fact does not log your object but the global object (i.e. `window`). In a script tag with `type="module"` it would be `undefined`.

```js
var x = {
    someString: 'asd',
    getMetadataBlock: () => {
        console.log(this);
    }
}
x.getMetadataBlock();
```

There are at least two solutions here:
Use a traditional function, e.g.
```js
export default {
    someString: 'asd',
    getMetadataBlock() {
        return this.someString;
    }
}
```

or give the object a name and use that instead of `this`:
```js
const x = {
    someString: 'asd',
    getMetadataBlock: () => {
        return x.someString;
    }
}
export default x;
```

**Comment by mad-hero** [comment]
You are right. I wrongly assumed that in this case 'this' should be still be defined, but testing it in the browser shows it does not. Thanks!
