### ISSUE TITLE
Here is a bug when using `export { xxx as default }`

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#2608]
- Rollup Version: 0.66.6
- Operating System (or Browser): No relationship, just in bundling.
- Node Version: 10.9.0

### How Do We Reproduce?

input.js:
```js
exports = null;
var name = 1;
export { name as default };
++name;
```

build.js:
```js
! async function () {

	const { rollup } = require('rollup');

	const bundle = await rollup({ input: __dirname+'/input.js' });

	const { code } = await bundle.generate({ format: 'cjs' });

	require('fs').writeFileSync(__dirname+'/output.js', code);

}().catch(console.error);
```

### Expected Behavior

output.js:
```js
'use strict';

exports = null;
var name = 1;
++name;

module.exports = name;

```

### Actual Behavior

output.js:
```js
'use strict';

exports = null;
exports.default = 1;
++exports.default;

module.exports = exports.default;

```

**Comment by lukastaegert** [comment]
Just out of curiosity, why would you reassign the CJS global variable `exports`?  Rollup has to be able to make some assumptions about the environment to do its work like the script not manually mutating the CJS globals.

Except for not detecting that `exports` is modified, for which it would probably be nice if rollup displayed at least a warning, the rolled up code looks ok to me. Note that rollup needs to be able to update the live-binding of the variable. E.g. in this situation

```js
// lib.js
var name = 1;
export { name as default };
setTimeout(() => ++name);

// main.js
import value from './lib.js';

console.log(value); // 1
setTimeout(() => console.log(value)); // 2
```

we need to ensure that the exported value is updated correctly. Detecting these kinds of situations can be very hard which is why rollup produces the code it does.

**Comment by LongTengDao** [comment]
@lukastaegert I see, there can't be no assumptions. Now I think a warning is good, if the code did something out of rollup's assumptions.
