### ISSUE TITLE
On the website, the back button doesn’t work properly when jumping between sections

### ISSUE THREAD

**Issue by chris-morgan** [rollup/rollup#2629]
When you click on a link on the website that takes you to a different part of the document (setting the hash), you get taken to the right place.

But when you press the back button, nothing happens, or it shifts by a pixel or two. It should take you back to where you were. I think it’s trying to handle it itself with some hashchange thing or similar that’s not quite working properly? I haven’t investigated.

**Comment by GrosSacASac** [comment]
Looking at rollup website I see that there is JavaScript running, it probably interfering with the normal behavior. Search for `scrollTop =` and `event.preventDefault()`

[On this website](https://dom99.now.sh/documentation) I use similar navigation with #hash but there is no problem since there is no JavaScript interfering

**Comment by lukastaegert** [comment]
This should be working now with the latest update. Please reopen if you still have issues.
