### ISSUE TITLE
Module not exported (aws-sdk)

### ISSUE THREAD

**Issue by Meemaw** [rollup/rollup#2655]
Hello there! I am new to Rollup and would appreciate some help at setting up build for my common library written in Typescript. I managed to make build work for sometime but it stopped working at some point. I am getting the following error: 
`[!] Error: 'DynamoDB' is not exported by node_modules/aws-sdk/lib/aws.js`

My package.json looks like this:

```js
{
  "name": "meshwatch-core",
  "version": "1.0.0",
  "main": "dist/meshwatch-core.umd.js",
  "module": "dist/meshwatch-core.es5.js",
  "typings": "dist/types/index.d.ts",
  "files": [
    "dist"
  ],
  "dependencies": {
    "aws-sdk": "^2.387.0",
    "boom": "^7.3.0",
    "joi": "^14.3.1",
    "node-fetch": "^2.3.0"
  },
  "scripts": {
    "test": "jest",
    "build": "tsc --module commonjs -p tsconfig.base.json && rollup -c rollup.config.ts && typedoc --out docs --target es6 --theme minimal --mode file src"
  },
  "devDependencies": {
    "@types/boom": "^7.2.1",
    "@types/jest": "^23.3.12",
    "@types/joi": "^14.0.1",
    "@types/node": "^10.12.18",
    "@types/node-fetch": "^2.1.4",
    "jest": "^23.6.0",
    "lodash.camelcase": "^4.3.0",
    "rollup": "^1.1.0",
    "rollup-plugin-commonjs": "^9.2.0",
    "rollup-plugin-json": "^3.1.0",
    "rollup-plugin-node-builtins": "^2.1.2",
    "rollup-plugin-node-resolve": "^4.0.0",
    "rollup-plugin-size-snapshot": "^0.8.0",
    "rollup-plugin-sourcemaps": "^0.4.2",
    "rollup-plugin-typescript2": "^0.18.1",
    "ts-jest": "^23.10.5",
    "typedoc": "^0.14.0",
    "typescript": "^3.2.2"
  }
```

And my rollup.config.ts like this:
```ts
import camelCase from 'lodash.camelcase';
import commonjs from 'rollup-plugin-commonjs';
import json from 'rollup-plugin-json';
import resolve from 'rollup-plugin-node-resolve';
import { sizeSnapshot } from 'rollup-plugin-size-snapshot';
import sourceMaps from 'rollup-plugin-sourcemaps';
import typescript from 'rollup-plugin-typescript2';

const pkg = require('./package.json');

const input = 'src/index.ts';

const libraryName = 'meshwatch-core';

export default {
  input,
  output: [
    { file: pkg.main, name: camelCase(libraryName), format: 'umd', sourcemap: true },
    { file: pkg.module, format: 'es', sourcemap: true },
  ],
  external: [],
  watch: {
    include: 'src/**',
  },
  plugins: [
    // Allow json resolution
    json(),
    // Compile TypeScript files
    typescript({ useTsconfigDeclarationDir: true }),
    // Allow bundling cjs modules (unlike webpack, rollup doesn't understand cjs)
    commonjs(),
    // Allow node_modules resolution, so you can use 'external' to control
    // which external modules to include in the bundle
    // https://github.com/rollup/rollup-plugin-node-resolve#usage
    resolve({
      preferBuiltins: false,
    }),
    // Get size snapshot of the lib
    sizeSnapshot(),
    // Resolve source maps to the original source
    sourceMaps(),
  ],
};
```

**Comment by TrySound** [comment]
Define named exports of your library in commonjs plugin. `module.exports = require('./bla')` cannot be converted to esm without additional information.

**Comment by Meemaw** [comment]
I have tried the following and it still fails. Am I doing this correctly or is there another problem?

```js
commonjs({
      namedExports: {
        'node_modules/aws-sdk/clients/dynamodb.js': ['DynamoDB'],
      },
    })
```

**Comment by QingLeiLi** [comment]
@TrySound My lib have more than twenty named exports, and it is growing up, It is hard to use `namedExports` option.  
Could rollup auto add name export info in bundle.js？
Maybe add `__rollup_named_export` in module.exports ? Check the attribute when import this pkg in `rollup-plugin-commonjs` plguin.

**Comment by TrySound** [comment]
@QingLeiLi Rollup is esm specific bundle. commonjs plugin is able to process some bundles but you can't deal with tricky commonjs runtime without these options. If you want easier setup then add esm support to the lib or bundle that lib.

**Comment by QingLeiLi** [comment]
I am new to rollup, maybe I am taking a detour.
I use lerna to manage my lib,  lib A and lib B, all write with esm, lib B is depend on lib A.
Now I bundle lib A to umd format, is it still reservation information which is named exported or default exported?
If answer is yes, I do not need to set namedExports option when i bundle lib B, rollup can get that data directly.

**Comment by PepsRyuu** [comment]
I don't feel like Rollup documentation properly explains this, so here's my attempt at it! :) 

As mentioned by others, the problem with CommonJS is that it's not designed to be statically analysable. Imports and exports can only be fully determined at runtime by executing the module. Take the following example:

```
    var load = require;
    var myModule = load('./MyModule');
```

This would work perfectly fine in NodeJS, but would cause a problem for bundlers. Without executing the code, it would be challenging to determine that ```load``` is actually the ```require``` function through static analysis. Same story for exports, although it's even more difficult. Ambiguities related to default exports in particular have to be resolved and there's no correct answer.

```
    // CJS file
    module.exports = { X, Y, Z };

    // Which of the following is the correct translation?

    1. export default { X, Y, Z };
    2. export { X, Y, Z };
```

Here's another problem:

```
    // CJS File
    var MyLib = { X, Y, Z };
    module.exports = MyLib;

    // Only possible translation because it's "unknown" what MyLib is.
    var MyLib = { X, Y, Z };
    export default MyLib;
```

In the latter scenario, while to us the reader it's quite simple to see what's being exported, to a static analyser, it's not so simple. "MyLib" could be anything, not necessarily an object even. ```rollup-plugin-commonjs``` does attempt to determine how to best export the module using known patterns, but there's a limit to how far that can be taken. This is why ```namedExports``` is often needed because there's just so many ways that CJS code can import and export functionality.

You might be thinking, how do other bundlers like Webpack get around this? That's because they decided to go the other way, rather than going from CJS --> ESM, they instead go from ESM --> CJS. CJS cannot be directly translated to ESM, but ESM can be translated to CJS very easily. It's easier to go from a statically analyzable system to a dynamic system, but this has other trade-offs (eg. ```sideEffects``` in package.json to enable tree-shaking, ```__webpack_require__``` overhead). The developer experience with importing CJS modules is easier with Webpack, but you're trading file size for that.

Library authors need to start switching to the ESM standard, but many haven't caught up. There's many other CommonJS features that library authors are depending on that probably are stopping them from migrating. One thing in particular is conditional requires which libraries like React depend on to switch between development and production, and that causes even more problems for bundlers because now bundlers have to start statically detecting ```if``` statements and statically checking if the branch is truthy or falsy. 

Personally though, if it's an option, I would not try to get ```aws-sdk``` bundled in your library. Minified, you're looking at 1872KB. It would be better to use it as an external peer dependency (helps to maximise caching and avoid conflicts), which you can do with ```external``` Rollup configuration option.

**Comment by Meemaw** [comment]
@PepsRyuu Thanks for your very detailed and extensive answer. I agree with external peer dependency. I have added it to the `external` and it builds but I am recieving error at runetime of the project depending on that library:

```js
/Users/msnuderl/Workspace/Personal/meshwatch-final/backend-local/node_modules/meshwatch-core/dist/meshwatch-core.umd.js:5
}(this, function (exports, https, http, Stream, zlib, perf_hooks, crypto, path, awsSdk) { 'use strict';
 ^
TypeError: Cannot read property 'inherits' of undefined
```

I think this is `commonjs` related but have no idea how to fix this.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
