### ISSUE TITLE
Plugin message passing/data-sharing

### ISSUE THREAD

**Issue by tivac** [rollup/rollup#2662]
### Feature Use Case
I'd like to able to generate information about the CSS dependency graph in `@modular-css/rollup` and then have a plugin later in the flow consume that information. Right now I have to write that info out to disk, which is error-prone and slow. We also have several custom one-off rollup plugins that would benefit from a similar sort of system for data-sharing between plugins.

### Feature Proposal
I've written postcss plugins before, and I think the system used there works out ok. Each plugin has access to a [`messages` array](http://api.postcss.org/Result.html#messages) and can either read from the array or push new messages onto it. Each message is an object that has a `type` property describing the type of the message (up to the plugin implementer) and a `plugin` property that should be the name of the plugin adding the message.

Consumers further down the chain can then either `messages.filter()` or `messages.find()` or whatever else they need to do to get access to the results/output from the other plugins. In rollup this could be handled via a new plugin context function, something like `this.addMessage(<type>, <msg>)` and it could be paired with either the raw array (`this.messages`) or an accessor/filter function like `this.getMessages(<type>)`. I'd prefer the array I think, but either would work fine for me.

**Comment by lukastaegert** [comment]
So this is about passing messages between otherwise unrelated plugins? I am asking because recently, I saw a very nice pattern for similar situations where a package exported several plugins that were sharing common state inside the package to solve this communication issue. But I assume something like this would not work for you as the plugins definitely need to be able to reside in separate packages?

I am asking as I think it would be very uncommon for arbitrary plugins to want to talk to each other. If that was the case, we would need to put a lot of thought into how messages are structured, if there are default types of messages etc. In your specific situation, the plugins further down the pipeline need to know about the modular-css plugin. So maybe the modular-css plugin could directly expose a notification handler or even a nested plugin handler?

About the former: As the plugins array is available on the "options" hook, dependent plugins could use this hook to scan for the postcss plugin and register themselves, e.g. via a proprietary prop exposed on the plugin object. Rollup does not care about unknown properties here.

About the latter: I have also been wondering for some time if we couldn't implement a "meta-plugin-format" where plugins do not return a simple object but an array of objects to serve as a kind of plugin-preset. If we implement something like this, the postcss plugin could similarly expose an array containing itself and all its dependent plugins while at the same time know about these plugins to communicate with them.

A message format of course would work as well but then I would like more feedback about possible use cases.

**Comment by tivac** [comment]
The background for all of this is that I'm working on a rollup plugin that can rewrite `import()` statements for chunks that have css (from `@modular-css/rollup`) into `Promise.all([ ... ])` statements that will load both the module **and** all its required CSS at once to avoid FOUC when doing bundle-splitting.

I went with the `postcss`-inspired `messages` approach because it's purposefully very simple and open to interpretation what exactly a message is, beyond the two required fields. It allows for them to be used for whatever plugins may want or need to use them for. They could be for data reporting, lookups, anything really. I'm not super-committed to the idea but figured it was worth bringing up as right now rollup has zero plugin communication facility and that model is one I'm familiar with and like.

A plugin being able to return an array of plugins that can share state via closure vars is probably enough for my needs. I actually just thought of another way of getting what I want here this morning, which is augmenting the `bundle` object passed to both the `generateBundle` and `writeBundle` hooks. It turns out I could have `@modular-css/rollup` attach asset dependencies to each chunk in its `generateBundle` and then my other plugin `@modular-css/rollup-rewriter` could read them in its `writeBundle` hook. It feels a bit... odd, but I confirmed it works so long as the plugins are ordered correctly in the array.

Feel free to close this if you'd prefer, I just think some official way to accomplish this would be useful.

**Comment by ianwalter** [comment]
I have a kind of similar use case, but for me just sharing `this.meta` between plugins or making `meta` available in the output object would get the job done.

**Comment by shellscape** [comment]
Would eventing fit the bill?

**Comment by ianwalter** [comment]
For me it does. It's essentially what I ended up doing.

**Comment by lukastaegert** [comment]
A note from me here:
While I see the value of adding a centrally managed plugin message data system for certain use cases, I shy away from just adding it if there are other options to achieve this.

Main reasons are that of course this would need to be maintained, there might be no filtering of messages between plugins, standards would need to be established etc. (and also I am doing this mostly on my own in my spare time)

As I see, there are several ways of achieving inter-plugin communication that would work today that might help you.

Core points:
* Plugins are basically objects.
* There is no sanitation as to what fields a plugin exposes.
* Plugins can discover each other via the `options` hook.

## Case 1: There is a central plugin that dependent plugins need to send messages to
In this case, the central plugin could expose a callback that dependent plugins can call.

```js
function centralPlugin() {
  return {
    name: 'central',
    receiveMessage(message) {
      console.log('Got message:', message);
    }
  }
}

function dependentPlugin() {
  let sendMessage = () => {};

  return {
    name: 'dependent',
    options(inputOptions) {
      if (Array.isArray(inputOptions.plugins)) {
        sendMessage = inputOptions.plugins
          .find(plugin => plugin.name === 'central')
          .receiveMessage;
      }
    },
    buildStart() {
      sendMessage('Hello from dependent');
    }
  }
}

export default {
  // ... other options
  plugins: [centralPlugin(), dependentPlugin()]
}
```

## Case 2: There is a central plugin that manages bi-directional communication between plugins.
Here we expose a node event emitter to handle the communication.

```js
function centralPlugin() {
  return {
    name: 'central',
    events: new EventEmitter()
  }
}

function dependentPlugin1() {
  let eventBus;

  return {
    name: 'dependent1',
    options(inputOptions) {
      eventBus = getEventBus(inputOptions);
      eventBus.on('message', data => console.log(data))
    },
    buildStart() {
      eventBus.emit('message', 'Hello from plugin 1');
    }
  }
}

function dependentPlugin2() {
  let eventBus;

  return {
    name: 'dependent2',
    options(inputOptions) {
      eventBus = getEventBus(inputOptions);
      eventBus.on('message', data => console.log(data))
    },
    buildStart() {
      eventBus.emit('message', 'Hello from plugin 2');
    }
  }
}

export default {
  // ... other options
  plugins: [centralPlugin(), dependentPlugin1(), dependentPlugin2()]
}
```

You might consider using some more specific names than `receiveMessage` or `events` to avoid the slim chance of conflicts with future Rollup plugin features.

To ease setting this up, the central plugin package could expose a helper function to get access to the event bus from given input options. The reason why I recommend going through the options hook (instead of directly via package imports) is that in that case, we can make sure that only plugins that are part of the current build are taken into account.

**Comment by tivac** [comment]
I've worked around this by decorating the `bundle` keys that need this extra information in the plugin that generates the metadata:

https://github.com/tivac/modular-css/blob/1a84b5d7ee5d0b95160059ebc3c6f604dc2524ec/packages/rollup/rollup.js#L296

And then in the plugin that needs to consume the metadata I read it off the `bundle` key:

https://github.com/tivac/modular-css/blob/1a84b5d7ee5d0b95160059ebc3c6f604dc2524ec/packages/rollup-rewriter/rewriter.js#L92

This works, but feels *very tenuous*, especially since I don't "own" those objects and they could change out from underneath me and introduce collisions. Attaching this metadata to my plugin instance itself via a closure var is safer so I'll move to that long-term.

**Comment by ugin** [comment]
@lukastaegert thanks for helping, found this thread and I'll continue here. I want to instruct the bundler to handle the same type of file in various ways:

`import  css from "./bootstrap.css?raw"` ← import the file content as string
`import style from "./button.css"` ← import CSS Module
`import banner from "./image.jpg?resize=800x600"` ← instruct plugin to resize the image

In `resolveId` hook I tried to attach some info to the object that will later be returned by `this.getModuleInfo()`. But is not working.

By reading the above messages, this is the only way I could make it work:

```js
// plugin-import-query
const queryCache = new Map();

return {
  name: "import-query",
  options(options) {
    options.queryCache = queryCache;
  },
  async resolveId(request, importer) {
    if (!request.includes("?")) return null;

    const [toImport, query] = request.split("?");
    const resolved = await this.resolve(toImport, importer);

    if (!resolved) return null;

    queryCache.set(resolved.id, format(query));

    return resolved;
  },
};
```

```js
// plugin-jpeg-resizer
let queryCache = null;

return {
  name: "jpeg-resizer",
  options(options) {
    queryCache = options.queryCache;
  },
  transform(data, file) {
    if (!file.endsWith(".jpg")) return null;

    if (queryCache.has(file)) {
      //...
    }
  },
};
```

**Comment by lukastaegert** [comment]
Why don't you add a `resolveId` to each plugin separately? The logic would be slightly more complicated but they could reuse a common helper.

1. Check if the path contains a `?`. If not, return `null`.
2. Parse the query. If it contains parameters that trigger this plugin, use `this.resolve` without the query and internally mark this id for this plugin (or whatever you want to do, this is the existing behaviour), otherwise return `null` (this would be different and allow other plugins to inspect the query as well)

That way, each plugin would be independent and you would also not need to force a user to use two plugins to do the job of one.

**Comment by ugin** [comment]
I ended up doing what you suggested. Spent last few days learning Rollup, got stuck on "how to properly do it in rollup". Thank you!
