### ISSUE TITLE
rollup gives error for export *

### ISSUE THREAD

**Issue by taoeffect** [rollup/rollup#2671]
- Rollup Version: 1.1.2
- Operating System (or Browser): macOS
- Node Version: v11.8.0

### How Do We Reproduce?

1. Create a vue.js project and add [vue-circle-slider](https://github.com/devstark-com/vue-circle-slider) as a dependency.
2. In a .vue file, do: `import { CircleSlider } from 'vue-circle-slider'` and try to add it to the component you're creating by adding it to the components property:

    ```js
    export default {
      name: 'MyComponent',
      components: {
        CircleSlider
      },
      // ... stuff ...
    }
    ```

3. Use the `rollup-plugin-node-resolve`, `rollup-plugin-commonjs`, and `rollup-plugin-vue` plugins in your rollup config. You can see an old (but possibly still relevant) version of my rollup config [here](https://github.com/okTurtles/group-income-simple/blob/61da9ac9b355ed45413b3b19b878a9e14a1a1f59/rollup.config.js) (which I'm currently editing and debugging).
4. Run rollup with `rollup -c`
### Expected Behavior

For it to work.

### Actual Behavior

```
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
frontend/simple/views/components/CreateGroupSteps/GroupRules.vue?rollup-plugin-vue=script.js: (130:9)
[!] Error: 'CircleSlider' is not exported by node_modules/vue-circle-slider/index.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
frontend/simple/views/components/CreateGroupSteps/GroupRules.vue?rollup-plugin-vue=script.js (130:9)
128: //
129:
130: import { CircleSlider } from 'vue-circle-slider'
```

### Notes

As far as I can tell, this is due to rollup failing to handle [this file](https://github.com/devstark-com/vue-circle-slider/blob/master/index.js):

```js
import plugin from './dist/vue-circle-slider.common.js'
export default plugin
export * from './dist/vue-circle-slider.common.js'
import './dist/vue-circle-slider.css'
```

Which suggests to me that this was not fully fixed in issue #44 by PR #51, although I could be misdiagnosing the issue.

**EDIT:** I am able to successfully avoid this error by using `require` instead of `import`.

**Comment by PepsRyuu** [comment]
That library doesn't export CircleSlider, it only has a default export. ```export *``` is working correctly here. Inside ```dist/vue-circle-slider.common.js``` is the following:

```
module.exports=function(modules){function __webpack_require__(moduleId
```

In this scenario, it's only possible to determine what the default export is, and that points to a function. With the ```rollup-plugin-commonjs``` plugin, you need to set named exports:

```
commonjs({
    namedExports: {
        'node_modules/vue-circle-slider/dist/vue-circle-slider.common.js': ['CircleSlider']
    }
})
```

I've noticed that you tried to do this, but using ```node_modules/vue-circle-slider/index.js```. This doesn't work because that is an ES module. Named exports only apply to modules that are determined to be CJS modules, which is why you have to directly point to the file the index file is importing. 

Personally, I'd also recommend writing an issue on the library author's repository about exporting a proper ES module. There's no benefit to having that index.js file if it's going to be importing CJS code, and the way the build is structured makes it very difficult to work with bundlers other than Webpack. They should switch from Webpack to Rollup which makes it easy to export ESM files. :)

**Comment by taoeffect** [comment]
Thank you so much for your help, @PepsRyuu!! I'll close this issue since this solved my problem. :)

**Comment by amiroffme** [comment]
> Thank you so much for your help, @PepsRyuu!! I'll close this issue since this solved my problem. :)

can you please demonstrate how did you fix this by using `require` ?

**Comment by PepsRyuu** [comment]
Hi @amiroffme, not quite sure I understand. ```require``` isn't being used to import the ```vue-circle-slider``` library. The solution was fixing the configuration of ```rollup-plugin-commonjs``` and explicitly specifying the named exports.

**Comment by orballo** [comment]
Hi! I'm having this same problem with `@risingstack/react-easy-state`, which makes the build fail with the following line `export * from 'react-dom';`.

The `namedExports` option in the commonjs plugins has been deprecated, so that solution is not available anymore.

Can somebody please point me in the right direction? :)

**Comment by TrySound** [comment]
@orballo You should specify every reexport explicitly like this
```
export { createElement, createPortal } from 'react-dom';
```

**Comment by orballo** [comment]
Thanks. I wasn't clear enough, but that line was part of the `react-easy-state` package. However thanks for pointing this out, so I can suggest to the author to make those changes :)
