### ISSUE TITLE
How to input a directory or including a dynamic required file to bundle?

### ISSUE THREAD

**Issue by TongDaDa** [rollup/rollup#2674]
I have a directory need to build with rollup, I want to build a simple file, but It also uses the require function to target other files,  I do not understand what options can do this, I had tried a lot of format such as `esm`, `cjs` and `life` of options, But I find the file also has the required function. 

What setup can include all code to a simple-file?

Or, I want to set up the `input` option as a directory, that means travels the files of a directory to build it like the input-file, and then it also outputs a directory according to the input directory. for example:

---- app
       -- **.js
       --utls
          -- **.js
          -- **.js
          -- **.js
       --scripts
            -- some file

-- dist

I had attempted to input this path of app around the input field of a rollup config file, but It only builds it from the app -> index.js, I expect rollup to build all directory from app and sub-directory and then output the dist dir according to the struct of the app.

**Comment by TongDaDa** [comment]
This support tag what did it means? 

If you want to support it, I can submit a PR to this repo

**Comment by lukastaegert** [comment]
No, it means that this issue is very vague (i.e. what does "I want to build a directory" even mean) and sounds like it should rather be asked on stackoverflow or a similar forum that can handle support requests.

Also you are not using the issue template. The template exists for a reason because Rollup only has precious few developers working in their spare time. Issues that do not use the template are usually ignored because answering support requests and trying to find out all the missing details will prevent us from doing any work on Rollup at all.

If you rely on "require", which is NOT RECOMMENDED (see here https://rollupjs.org/guide/en/#why-are-es-modules-better-than-commonjs-modules), you probably need https://github.com/rollup/rollup-plugin-commonjs as mentioned here https://rollupjs.org/guide/en/#importing-commonjs and here https://rollupjs.org/guide/en/#how-do-i-use-rollup-in-nodejs-with-commonjs-modules

> I expect rollup to build all directory from app and sub-directory and then output the dist dir according to the struct of the app

Sounds like https://rollupjs.org/guide/en/#preservemodules

**Comment by TongDaDa** [comment]
@lukastaegert Tanks for your answer, I will ask on the StackOverflow next time.
