### ISSUE TITLE
Unknown CLI flag when using custom CLI options

### ISSUE THREAD

**Issue by soanvig** [rollup/rollup#2694]
- Rollup Version: 1.1.2
- Operating System (or Browser): Linux
- Node Version: 11.7.0

### How Do We Reproduce?

1. Create rollup.config.js file with following code:

```js
export default (options) => {
   console.log(options);
   return {}
}
```

2. Launch rollup with any [custom options](https://rollupjs.org/guide/en#configuration-files), e.g.

```
$ ./node_modules/.bin/rollup -c --test
```

### Expected Behavior
Rollup respects given `--test` option, and doesn't scream about `Unknown CLI flags`

### Actual Behavior
Rollup **respects** given `--test` option, but screams about `Unknown CLI flag`

**Comment by tivac** [comment]
I use `--environment` to avoid this, you can set whatever values you want and then grab them off of `process.env`.

**Comment by lukastaegert** [comment]
This is intentional to give the user basic feedback about typos or deprecated options and will therefore not go away. There is however an official way of doing this which is prefexing options with `--config`. I.e. if you write `--configTest`, then rollup will not complain about it. There is even an example detailing this at the very end of this section of the docs: https://rollupjs.org/guide/en#configuration-files

If you are really set on using `--test`, there is another easter egg way of doing it: You can clean up your command line in your config file. This config will allow you to use `--test` without complaints:

```js
export default commandLineArgs => {
  const test = commandLineArgs.test;

  // This is the important part
  delete commandLineArgs.test;

  return {
    // do something interesting with the option
    input: test ? 'test-input.js' : 'input.js' ,
    output: {
    file: 'bundle.js',
      format: 'cjs'
    }
  }
}
```

**Comment by soanvig** [comment]
Well, I find it unituitive, but maybe that's me., that `configTest` is
legal, but `test` not. No CLI tool I know behaves like that.

 Nevertheless I'll use one of the suggested options, and won't propose
Rollup behaviour change.

Issue may be closed then

pt., 15 lut 2019, 06:49: Lukas Taegert-Atkinson <notifications@github.com>
napisał(a):

**Comment by soanvig** [comment]
Thank You for help

pt., 15 lut 2019, 07:35: Mateusz Koteja <soanvig@gmail.com> napisał(a):

**Comment by revelt** [comment]
strangely, this false alarm message started popping up now, it never did before, I had custom flags for many months

**Comment by AlexBrohshtut** [comment]
A little more elegant solution for this using [onwarn](https://rollupjs.org/guide/en/#onwarn):
```typescript
export default commandLineArgs => {
	...
    onwarn(warning, warn) {
      if (warning.code === 'UNKNOWN_OPTION') {
        // This allows using test flag
        if (warning.message.includes('Unknown CLI flags: test')) return;
      }
      warn(warning);
    },
	...
}
```
