### ISSUE TITLE
When using git and watch mode, a file with changes triggers re-build on every file open in some apps

### ISSUE THREAD

**Issue by vladshcherbin** [rollup/rollup#2707]
- Rollup Version: 1.2.1
- Operating System (or Browser): macOS 10.13.4
- Node Version: 11.7.0

### How Do We Reproduce?

Here is a test repo - [rollup-git](https://github.com/vladshcherbin/experiments/tree/master/rollup-git)

It has a basic rollup config and a src file:

```js
function sum(a, b) {
  return a + b
}

console.log(sum(3, 5))
```

Reproduce using Atom:

1) start rollup in build mode
2) change something in src file
3) a new build will be triggered
4) close and reopen file - a new build will be triggered on every file open

Reproduce using another git diff tool (Tower app in my case)

1) start rollup in build mode
2) change something in src file
3) a new build will be triggered
4) view changes in Tower - a new build will be triggered on every file view

**VSCode doesn't trigger rebuilds on file open.**

A video with issue is added below.

### Expected Behavior

No rebuilds are triggered when opening/viewing a file without making changes in watch mode.

### Actual Behavior

Rebuilds are triggered on every file open/view in Atom/Tower without making changes in watch mode. 

**They are not triggered in VSCode though.**

### Video demo

[rollup-git.zip](https://github.com/rollup/rollup/files/2877113/rollup-git.zip)

**Comment by vladshcherbin** [comment]
Doesn't happen when using `chokidar`.

**Comment by shellscape** [comment]
@lukastaegert this seems serious if true. looks like Sapper has moved to `cheap-watch`. Should we consider the same by default?

**Comment by lukastaegert** [comment]
We could definitely move to another solution. I did not find time to look into this specifically, though.

**Comment by shellscape** [comment]
@lukastaegert I've started doing my homework on moving to `cheap-watch`. It won't be trivial and at that point I think having two watching options is added complexity we don't need. chokidar@3.0.0 has changed considerable. See https://paulmillr.com/posts/chokidar-3-save-32tb-of-traffic/. `cheap-watch` adds [38kb](https://packagephobia.now.sh/result?p=cheap-watch) to the package, whereas `chokidar@3` adds [323kb](https://packagephobia.now.sh/result?p=chokidar) but that's down significantly from v2 that weighted in at 2.5mb. It also seems they've gone to great lengths to ensure security of the package. `cheap-watch` has zero additional dependencies, while `chokidar` has 8 (which all originate from the chokidar org). That eliminates the primary reason for sapper moving to `cheap-watch`. `chockidar` is also well-supported.

Given that most of our watching issues come from the native rather than chokidar, I'd like to propose that we adopt chokidar as the default and include it as a hard dependency. Thoughts / Concerns?

**Comment by lukastaegert** [comment]
With your observations, moving to `cheap-watch` as the only solution would save a lot more space. We basically do not use any of chokidars advanced functionalities, maybe this would be an even better solution, also considering the size? Or are there things where chokidar is still ahead that we would benefit from?

**Comment by shellscape** [comment]
Chokidar seems to have come a long way since v2, which is what we currently bundle. The org behind it has taken massive steps to secure the project, and they've cut the package size by 86%. Normally I'd be an advocate for saving the extra 290kbm by using `cheap-watch`, but given how well it's maintained and the quality of the code and testing now my vote would be to keep it and make chokidar the default. When Svelte chose cheap-watch, chokidar@3 hadn't been released yet. I also haven't factored in any tree-shaking that might happen when rollup is bundled, but that might also cut down on how much of chokidar's package ends up in the bundle.

**Comment by shellscape** [comment]
I'm going to close this one in favor of #2988, which I'm going to tackle.

**Comment by vladshcherbin** [comment]
@shellscape sounds great, thank you 👍
