### ISSUE TITLE
Documentation on library bundling best practices

### ISSUE THREAD

**Issue by danimoh** [rollup/rollup#2709]
Documentation Is:

- [X] Missing
- [ ] Needed
- [X] Confusing
- [X] Not Sure?

### Please Explain in Detail...

Hello.
I really like the way rollup bundles projects.
However, there are some questions I'm asking myself every time it comes to bundling a library for publishing, even after reading the documentation and researching the web.

- Does it make a difference for tree shaking in an consuming project whether I bundle my library as an esm bundle or whether I ship the separate es modules?
- Is rollup powerful enough to tree-shake methods that are not explicitly imported but keep the ones that are a dependency to a exported method?
- Are sourcemaps for imported dependencies also automatically imported or only if `rollup-plugin-sourcemaps` is used?

To illustrate this:

#### Source files

`src/a.js`
```js
export default function greetA() {
    console.log('Greetings from A');
}
```
`src/b.js`
```js
function getGreetingB() {
    return 'Greetings from B';
}

export function greetB() {
    console.log(getGreetingB());
}

function getGoodbyeB() {
    return 'Goodbye from B';
}

export function goodbyeB() {
    console.log(getGoodbyeB());
}
```
`src/main.js`
```js
export * from './a.js';
export * from './b.js';
```

#### Case1: building separate files

`rollup.config.js`
```js
export default {
    input: [
        'src/main.js',
        'src/a.js',
        'src/b.js',
    ],
    output: {
        dir: 'dist',
        format: "es",
        sourcemap: true
    }
};
```
In this case rollup essentially just copies the files over to dist but it's just a simplified example anyways.

#### Case 2: Bundling into a single file.

`rollup.config.js`
```js
export default {
    input:'src/main.js',
    output: {
        file: 'dist/main.js',
        format: "es",
        sourcemap: true
    }
};
```
This bundles `a.js` and `b.js` into one file.

#### A consuming project

```js
import { greetB } from 'my-library';

greetB();
```

In this setup, is there any difference regarding tree shaking in whether the library was built as described in case 1 or case 2 when bundling the consuming project?
I.e. `greetB` and `getGreetingB` should get bundled but `greetA`, `goodByeB` and `getGoodByeB` should be left out.
Are sourcemaps for `greetB` and `getGreetingB` automatically imported and mangled with the final sourcemaps of the consuming project?

### Your Proposal for Changes

Provide best practices for library building and some more insights into tree shaking mechanics.
Tree-shaking is one of the main arguments for choosing rollup, however the concepts need to be well understood.

**Comment by lukastaegert** [comment]
There is definitely room for improvement in rollup's documentation. Some pointers that might help and that we could actually link to in our documentation:
* I recently wrote an article highlighting best practices for library bundling (including the use of code-splitting): https://levelup.gitconnected.com/code-splitting-for-libraries-bundling-for-npm-with-rollup-1-0-2522c7437697
* Methods that are not explicitly imported will be tree-shaken if and only if they are not used by some included code. What people often get wrong about tree-shaking (which is because nearly every article about tree-shaking gets this wrong) is that it has nothing specifically to do with ES modules, imports and exports. It is just an algorithm to identify unused code (see https://medium.com/@Rich_Harris/tree-shaking-versus-dead-code-elimination-d3765df85c80). The point where ES modules come into play is that even though tree-shaking works very well in a big file, it only works equally well in many small files if the files have a way to "share their variable bindings"  which is basically what ES modules provide. Last summer I held a talk about this in the context of Rollup that is still valid today: https://events.techcast.com/btd/2018/Garmisch_1130/

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
