### ISSUE TITLE
Allowing plugins to inject dynamic dependencies of a module

### ISSUE THREAD

**Issue by surma** [rollup/rollup#2742]
Roughly, `import(moduleId)` builds `moduleId` as a separate chunk and replaces the module ID with the resulting chunk URL.

However, there are cases besides `import()` that would benefit from this pattern:

* `new Worker(moduleId)`
* `navigator.serviceWorker.register(moduleId)`
* `CSS.paintWorklet.addModule(moduleId)`
* `new AudioContext().audioWorklet.addModule(moduleId)`

etc etc.

It feels like we need something lower level to add `moduleId` as an entry point and provide access to the resulting chunk URL. You could explain `import(moduleId)` on top of this, and developers could use it to create plugins for the various patterns above. This would also future-proof rollup for upcoming APIs with this pattern.

The rest of this post is a proposal, but feel free to ignore it if there's a better way to solve the problem.

---

This solution follows the patterns of assets, but for modules.

**`this.addEntry(moduleId: string) => string`**

Adds an entry point to the graph (as `import(moduleId)` would) and returns its `chunkId`.

**Chunk URLs**

To reference a chunk URL reference from within JS code, use the `import.meta.ROLLUP_CHUNK_URL_[chunkId]` replacement.

```js
load (id) {
  const chunkId = this.addEntry('./foo.js');
  return `export default import.meta.ROLLUP_CHUNK_URL_${chunkId}`;
}
```

[Here's how a plugin developer would use this to handle workers](https://gist.github.com/jakearchibald/2cdead40bf97b9ab2b76d06c4790fc0e).

H/T @jakearchibald for working this out with me

**Comment by surma** [comment]
In the meantime, if people find this thread to try and use workers with rollup: I wrote [rollup-plugin-workz0r](https://github.com/surma/rollup-plugin-workz0r) that abuses dynamic import injection to simulate the behavior described above.

**Comment by lukastaegert** [comment]
Given the context, I see the potential for Rollup here, especially as it allows code reuse between worker and main thread. If we limit the context function to hooks in the build phase, this could actually be possible. Will need to think about this a little more.

**Comment by philipwalton** [comment]
I had a similar issue recently while trying to build a Rollup plugin to support built-in modules.
https://glitch.com/edit/#!/rollup-built-in-modules?path=README.md:1:0

I "solved" it by adding additional entry points in the plugin's `options` hook, but it feels like a more explicit API (as described here) would be a better solution.

**Comment by lukastaegert** [comment]
I am actually actively working on this one. It will contain a bigger refactoring of how modules are loaded. For now I changed the algorithm to allow throwing in new entry points before or while it is running. But figuring out some of the finer details will take some time.

**Comment by jakearchibald** [comment]
@lukastaegert this is great to hear. Really appreciate the effort. For what it's worth, I only just started playing around with Rollup's plugin architecture and I'm impressed with how simple it is compared to other build tools.

**Comment by lukastaegert** [comment]
Just some feedback on the current state of this:
Admittedly I was side-tracked by some bugs I fixed but I am now back working on this. One question that I keep wondering about is this one: If I reference a chunk via `import.meta.ROLLUP_CHUNK_URL_${chunkId}`, what do I expect to get?

If it is just the relative URL, I can safely use this in `import` statements but I cannot safely use it for workers as workers are not necessarily resolved relative to the current JavaScript module.

For example at the moment I can configure my system so that auto-generated chunks are placed in a different folder than my entry points, e.g. in a folder `chunks`. Now if one of my auto-generated chunks would create a worker "worker.js", the relative URL would (correctly) be `../worker.js` but instantiating would fail because the current entry point was actually in the same folder as `worker.js`, so the relative URL would need to be './worker.js';

For assets, @guybedford implemented a mechanism that would actually replace `import.meta.ROLLUP_ASSET_URL_${assetId}` with something like `new URL('../assets/assetfile', import.meta.url).href`. On the other hand, this is something that could just as well be added by a plugin if I give them the relative URL; Rollup, however, would be in a position to render different code depending on the output format (this is how this works for assets at the moment).

So this is my current thought: There could be two ways of referencing a new chunk, either via `import.meta.ROLLUP_CHUNK_URL_${chunkId}`, which adds the additional resolution code, or via `import.meta.ROLLUP_RELATIVE_CHUNK_URL_${chunkId}`, which just gives you a path relative to the current chunk.

Any additional input here is welcome. For the moment, I guess I will look into adding browser based tests to Rollup to be able to test all formats in their native environments.

**Comment by jakearchibald** [comment]
Interesting! I hadn't considered this. I'm happy with your conclusion though.

**Comment by surma** [comment]
Eugh, paths and workers. Always a PITA. Your solution seems sensible to me :)

**Comment by guybedford** [comment]
+1 to `import.meta.ROLLUP_CHUNK_URL_${id}` being the portable expression by default.

I'm not sure I understand what the value is in having `import.meta.ROLLUP_RELATIVE_CHUNK_URL${chunkId}` though?

For absolute outputs, there could be a mode where you can provide the `publicUrl` and these expressions all become absolute URL expressions... but please lets stick with portability by default too.

**Comment by lukastaegert** [comment]
My concern is twofold
- the current mechanism we have for assets is very opinionated as to how these URLs are used. This might make sense for assets but in general I would love to give plugin authors more control over how these URLs are usable, but most importantly
- only the relative URL is usable in import statements

**Comment by lukastaegert** [comment]
Also, in a Node context, browser-based logic seems rather wrong to me. Maybe here, paths should be relative to something else?

**Comment by lukastaegert** [comment]
But as you are here, there are quite a few more questions about the current mechanics for assets that I like to understand as refining these things and creating as many functional tests as possible is the most important task currently blocking progress on this issue.

1. In what situation does `process.browser` exist in a CJS context? What environment/build setup are we handling here?
2. Why do we have a Node specific handling in the IIFE case with the `require('ur'+'l')` (but only for asset URLs)? My feeling is that I would actually remove it and align with the handling for `import.meta.url`

**Comment by lukastaegert** [comment]
Ok, I was wrong about the second point, we always have the node specific handling, but I tend to remove it from the IIFE case.
