### ISSUE TITLE
Preserve import.meta.url from before bundling

### ISSUE THREAD

**Issue by LarsDenBakker** [rollup/rollup#2748]
This is a follow up on the discussion here: https://github.com/rollup/rollup/pull/2164

### Feature Use Case
Using `import.meta.url` to dynamically request files relative to original source file location. 

For example where I work we have a convention where each project to includes an `assets` folder, which is copied over as is when deploying to production. Web components use `import.meta.url` to resolve paths to images placed in the `assets` folder. In order for this to work with bundling, `import.meta.url` should point to the file location before bundling.

### Feature Proposal
Preserve `import.meta.url` file location from before bundling. Or make it configurable, so that the behavior can be chosen. I think preserving the original source file location should be the default however, as your code should work the same with or without bundling.

**Comment by coreyfarrell** [comment]
For reference my current solution to this is [babel-plugin-bundled-import-meta](https://github.com/cfware/babel-plugin-bundled-import-meta#readme) run by rollup-plugin-babel.  For my build process this is acceptable as I already use babel, though it causes the bundle to contain duplicated code when using `import.meta.url` from multiple modules, especially with some of the non-ESM importStyles.  It would be great if a built-in rollup process created a single function to combine the unbundled relative URL with the bundled `import.meta.url` value.  For example:
```js
function prerollup_meta(unbundledURL) {
  return {
    url: new URL(unbundledURL, import.meta.url).href
  };
}
```

Then use that function to construct replacement `import.meta` objects instead of copying the code for each module.  Not the biggest issue when maintaining `import.meta.url` but some of the other importStyle's generate more code.

**Comment by lukastaegert** [comment]
PR at #2785, please have a look if this would work for you.

**Comment by elado** [comment]
Whoever comes here from Google: this plugin helped me include `new URL(.., import.meta.url)` assets in the bundle:
https://www.npmjs.com/package/@web/rollup-plugin-import-meta-assets
