### ISSUE TITLE
Cann't custom context when `format: 'iife'`

### ISSUE THREAD

**Issue by finscn** [rollup/rollup#2794]
- Rollup Version:  v1.9.0
- Operating System (or Browser): all systems & browsers
- Node Version:  10

### How Do We Reproduce?

use options 
```
{
    input,
    output: {
        banner,
        file: path.join(basePath, pkg.bundle),
        format: 'iife',
        freeze,
        name: 'PIXI.particles',
        sourcemap,
        extend: true,
        globals: {
            'pixi.js': 'PIXI'
        },
    },
    context: "window",
    treeshake: false,
    external: ['pixi.js'],
    plugins: [jscc({values:{_IIFE:true}})].concat(plugins),
}
```
to build js file.

I found this issue when I use :  https://github.com/pixijs/pixi-particles 
I've talk it with the author at https://github.com/pixijs/pixi-particles/issues/100
And I found the options.context can't help me to solve that problem.

### Expected Behavior
the global context should be name `window.PIXI`

### Actual Behavior
always  `this.PIXI` 

I found in 
https://github.com/rollup/rollup/blob/e53c73421b12ab663a62560a0d3d8203fc2535e7/src/finalisers/iife.ts#L78

https://github.com/rollup/rollup/blob/fadf7bcc088dfe80fa655db0a513a1d6303bb91b/src/finalisers/iife.ts#L13

there is always `'this'` , so , whatever the options.context is , the result is always `this.XXXXXX`.

**Comment by finscn** [comment]
I've created a PR , but I know you won't merge it. (no test-case , and maybe make some new bugs)

But I hope my PR could help you to find a better way to fix this issue.

**Comment by lukastaegert** [comment]
Thanks for the issue. Unfortunately, `context` is not the right way to fix this as `context` describes the value of `this` *inside* the bundle and not *outside the bundle wrapper*. Which is why `context` is an input option while for configuring the wrapper, it could be an output option.

`context` as it works today is exactly what you need when you need to bundle files that contain global `this` values. Nevertheless looking at your original issue, I think the issue is something else.

IIFE bundles are meant to be consumed via script tags, i.e. `<script src="path/to/bundle.js"></script>`. Here, you do not have `strict mode` and everything works as expected.

The recommended way for bundling several scripts into one is to use ES modules if available (which seems to be the case for pixi-particles https://github.com/pixijs/pixi-particles/issues/100#issuecomment-480636317), imports and possibly a bundler like Rollup or Webpack. Here you will not have issues with IIFE wrappers because there are no wrappers.

If for some weird reason you want to pack several IIFE wrappers into a single file, you should NOT use `strict mode` on the top level but instead inside each wrapper (and put your own code into such a wrapper as well):

```js
this.PIXI = this.PIXI || {};
(function (exports, pixi) {
  'use strict';
  // ...
}(this.PIXI.particles = this.PIXI.particles || {}, PIXI));

(function () {
  // this will only have an effect inside the IIFE wrapper
  'use strict';
  // your own code goes here
} ());
```

However this is a very complicated way of working with JavaScript and I would really recommend switching to ES modules in your setup.

**Comment by lukastaegert** [comment]
Also if the library you consume uses an UMD wrapper instead of an IIFE wrapper, missing `this` will not be an issue as this wrapper has a fallback to use `self`, which should work in strict mode as well.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
