### ISSUE TITLE
Bundle typescript without transpiling

### ISSUE THREAD

**Issue by jeremy-coleman** [rollup/rollup#2824]
### Expected Behavior / Situation
It would be extremely useful to be able to rollup typescript files/directories without transpiling to javascript , and likely beneficial to the ecosystem as a whole, to be able to just concat and resolve ts files. There are several reasons to do this with es modules, but typescript tools and use in conjunction with babel causes a lot of issues that simply concatting files fixes. Also, some people think of single files or importing singlefiles is best, but thats really not the case becaus it only leads to multiple import specifiers of the same bundle.

### Actual Behavior / Situation
no available options thay i know of

### Modification Proposal
Add a skipTranspile: boolean option to output config.

The difference in this from something like gulp concat being that paths are resolved, and modules are converted to esm also

**Comment by LongTengDao** [comment]
I can't understand. Why not use `TypeScript.transpileModule` in `rollup` `plugins` option?

**Comment by jeremy-coleman** [comment]
Sorry, i was unclear in my intent. The use case is to not transpile to javascript, rather to maintain the source files as typescript, while still tree shaking, converting modules, concatting , and resolving. Similar to a codemod but for ‘bundle syntax’ rather than es syntax

**Comment by LongTengDao** [comment]
You mean bundle many `.ts` files to one `.ts` file? Then why not use `require('typescript')` simply?

**Comment by jeremy-coleman** [comment]
does the typescript compiler provide an api for merging files? that would be so great for me if so,  but as for my suggestion here, most front-end projects that use other file types besides js and ts. This request isn't limited to typescript also, imagine a js project using jsx and class properties that wants to maintain the source code , but wants to convert to es modules and merge/treeshake internal project deps.

**Comment by Swatinem** [comment]
You might want to try https://github.com/Swatinem/rollup-plugin-dts to at least generate rollup-ed `.d.ts` files. That way you have a `.js` file with the code and a `.d.ts` file with the corresponding declarations.

**Comment by shellscape** [comment]
closing citing solution mentioned by @Swatinem

**Comment by jsejcksn** [comment]
@shellscape The plugin mentioned by @Swatinem does not address the requirements of the original post: it still transpiles. The original post was asking about concatenating TypeScript source files rather than splitting the types into a separate declaration file.

This is something I'm also interested in for potentially publishing Deno modules in the future.

**Comment by simonespa** [comment]
I'm interested in this feature too.

My use case is broken down in 3 repositories written in Typescript
* Main repository that contains the SPA web app
* UI repository that provides dummy React presentational components
* Utility repository that provides helpers and util function

Usually, you would put everything in one monorepo, and then transpile everything down to ES5. I'd like to import the external library as they were within the repo itself (hence untouched TS/TSX files) so I can then use them as they were part of the repo and leave to the main repo transpiler (webpack, rollup, etc) to do its job on the whole code (regardless if part of it comes from external repos).

By doing so, the transpilation/treeshaking process is run on the final product rather than having to deal with transpiled ES5 code too coming from external dependencies.

**Comment by sstur** [comment]
Has anyone figured out a solution to bundling TS files _without_ transpiling the code? I'd be interested in this, either with or without Rollup. Is there any bundler that's able to do this?

**Comment by sstur** [comment]
Update: I hacked together something that works, by patching in the [typescript-estree](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/typescript-estree) parser which produces a _mostly_ rollup-compliant AST (I had to add start/end properties to nodes), and now I have a bundler that consumes and emits TS with no transpilation.

If anyone's interested I can post a gist or a codesandbox or something.

I'm using this for quite a [weird use-case](https://typescripttolua.github.io/), but I suppose this might help people using Deno or whatever.

**Comment by jsejcksn** [comment]
@sstur I'm interested to see how you managed reconciling unique tokens during concatenation.

**Comment by sstur** [comment]
OK, I've added a CodeSandbox demo to my comment above.

> how you managed reconciling unique tokens during concatenation

The short answer is that I didn't. I let Rollup handle concatenation and symbol renaming.

Which begs the question, how can Rollup process the AST of TypeScript, a language that it does not natively understand. I'll try to elaborate on that.

My initial assumption was that a TypeScript AST was just a JavaScript AST with some extra meta info on certain nodes to include type annotations (turns out this is a slight over-simplification; more on that below). I figured I would have to replace the parser to allow Rollup to ingest TS _and also_ replace the serializer to produce TS output again.

So in my mind, Rollup's process was like this:

1. Read the source code
2. Parse to an AST
3. Walk imports and read more source code/AST
4. Combine
5. Rename identifiers if necessary
6. Remove dead code
4. Serialize the AST back to Source Code

Turns out, after implementing the parser, it worked without me messing with the serializer, and yet the output contained all the type annotations. This was surprising. I thought "How can Rollup turn an AST that includes type annotations into flawless TypeScript code?"

After pondering on this (and console.log'ing a bunch of stuff) I revised my mental model of how Rollup works and came up with the following.

1. Read the source code
2. Parse to an AST
3. Walk imports and read more source code/AST
4. Decide which identifiers need to be renamed to make a conflict-free combined output
6. Iterate the ones that need to be renamed and based on their start/end position in the source code, modify the _original string_ at those indices, performing the rename
7. Similarly walk the AST to find nodes that can be removed and based on those start/end positions, cut those out of the string
4. Throw away the AST and return the modified string

Note: The above is based on my hypothesis, and I have not deeply read the Rollup code, nor am I an expert on this stuff.

This would explain why all the type annotations from my code still remain in the output, without me needing to modify the serializer. I think there isn't a serializer; it's just string manipulation.

OK, so there's a drawback, which I didn't realize till just now. Since Rollup's algorithm to rename identifiers doesn't know anything about standalone TS-only entities, e.g. `type`, `interface`, or `enum`, they won't get renamed.

This means if one file has a `type Foo = ...;` and another file also has a `type Foo`, when combining files, those will collide.

I suppose it wouldn't be a huge amount of effort to modify Rollup to handle these kinds of nodes, but I don't know for sure until I poke around in the internals of Rollup's identifier reconciliation algorithm.

**Comment by Swatinem** [comment]
@sstur you might want to take a look at my plugin https://github.com/Swatinem/rollup-plugin-dts which basically creates an AST that looks nothing like the underlying type declarations, but which rollup uses to stitch strings together and rewrite identifiers. Its a giant hack, but it works. I haven’t really bothered making it compatible with bundling full typescript files.

**Comment by sstur** [comment]
Wow, that's fascinating (and complex). I'm looking at the relevant bits [here](https://github.com/Swatinem/rollup-plugin-dts/blob/master/src/transform/Transformer.ts#L76) and [here](https://github.com/Swatinem/rollup-plugin-dts/blob/master/src/transform/DeclarationScope.ts#L222).

It appears to be converting each type node into some other AST representation so that Rollup can process them. I could probably re-use a ton of that if I were to continue down this path to making a super robust solution (not sure how much farther I'll go since this non-exhaustive solution seems to work for my basic needs for now).

**Comment by aminnairi** [comment]
Another use-case would have been to bundle many TypeScript files into a single one that can then be pushed to the NPM registry and be used, not only on the Node platform (for the transpiled ECMAScript Modules, CommonJS and UMD build) but also on the Deno platform (with the wanted bundled TypeScript file). For now, we have to rely on the GitHub raw content domain to import things and the URL gets pretty wide.

```typescript
import {validate, string} from "https://raw.githubusercontent.com/aminnairi/javascript-jsonvalidator/latest/sources/index.ts";
```

But with the help of Rollup, we could achieve something similar by not having to package all of the source folder (which can be pretty large for some projects) and only bundle the necessary files. For instance, using Unpkg.

```typescript
import {validate, string} from "https://unpkg.com/@aminnairi/jsonvalidator/index.ts";
```

This would help decrease the bundle size of the bundled TypeScript file by not having multiple (and potentially unecessary) files in the final package and still applying tree-shaking for things that are not used and also for convient use. This would also be useful to use a dedicated CDN platform like Unpkg that cache requests and has better response time than the GitHub raw user content CDN.

Deno is a wonderful platform and Rollup could be the defacto bundler for all things TypeScript. By having both Deno & Node users in mind.

**Comment by JoshMcCullough** [comment]
If your goal is to skip the transpilation and publish straight TS sources, then you don't need rollup at all. You can just set your `package.json` to include your TS sources directly, e.g.:

```json
  // rest of package.json
  
  "main": "src/index.ts",
  "files": [
    "src"
  ],
  
  // rest of package.json
```

Obviously there are other reasons to use rollup even if you are publishing TS directly -- e.g. to copy some artifacts into the bundle. 

I commend you for wanting to publish TS sources directly!

**Comment by HoldYourWaffle** [comment]
I have another fairly obscure usecase for this: introducing modularity to [Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/overview/excel).

@sstur Did you ever explore a more robust solution?
I'm not super worried about collisions either, but I might want to take a shot at it anyway out of curiosity.

**Comment by aminnairi** [comment]
> If your goal is to skip the transpilation and publish straight TS sources, then you don't need rollup at all. You can just set your `package.json` to include your TS sources directly, e.g.:
> 
> ```json
>   "main": "src/index.ts",
>   "files": [
>     "src"
>   ],
> ```
> 
> Obviously there are other reasons to use rollup even if you are publishing TS directly -- e.g. to copy some artifacts into the bundle.
> 
> I commend you for wanting to publish TS sources directly!

Thank you, I didn't even know TypeScript was able to resolve TypeScript files directly from Node modules, I combine this with using GitHub directly to bypass having to publish packages to NPM now and it works great!
