### ISSUE TITLE
Is there a "watch" option in the pipeline?

### ISSUE THREAD

**Issue by vdclouis** [rollup/rollup#284]
This would be an awesome adition when debugging/developing for the browser.

**Comment by Rich-Harris** [comment]
Agree. We intend to add some functionality around incremental builds (#191), and this would go hand-in-hand with that. The goal would be for the incremental build stuff to be flexible enough to integrate with existing build systems, but I think it'd make sense for the CLI to support it out of the box:

```bash
rollup -c --watch
```

**Comment by TrySound** [comment]
@Rich-Harris And CLI should be a separate package in this case.

**Comment by CrowdHailer** [comment]
I looked at the issue on creating incremental builds. I write a lot of client JS but not much node so don't know how possible this is. 
Would it be possible to introduce a watch option without incremental builds. I understand it would be slower by rebuilding everything. but at the moment I am proving my workflow with rollup and so working on quite small projects. I could make more of a case for using it with a watch option and then as projects grew hope for a more efficient version.

Is this something that makes sense? or is the watch bit enough work that it makes sense to go hand in hand with partial builds.

**Comment by Swatinem** [comment]
You can always use it with a build system that does watching and can also handle css. There are plenty of options there. [gobble](https://github.com/gobblejs/gobble) is one done by @Rich-Harris that I use.

**Comment by mstade** [comment]
The nuclear option, for those unable to wait till a smarter solution exists:

```sh
nodemon -x "rollup in.js | babel --presets es2015 > out.js"
```
 
The pattern being `nodemon -x "whatever-your-build-command-is"`.

**Comment by egoist** [comment]
@mstade you're right, better adding `--watch src` or the nodemon will keep restarting.

**Comment by sunjay** [comment]
Another temporary solution, though not the best.

    npm install -g watch
    watch "<your build command>" <directories you want to watch>

For example, I use `npm run build` for my build command and keep my source files in `src/`, so my command would be:

    watch "npm run build" src/

You can conveniently put this under `scripts` in your `package.json` file like so:

    "scripts": {
        "watch": "./node_modules/.bin/watch \"npm run build\" src/",
    }

Just make sure you install `watch` locally using `npm install watch --save-dev`

**Comment by mandx** [comment]
Another temporary solution, for those using Linux, is to use `inotifywatch` utility in a simple shell script:
```sh
#!/bin/sh

while true; do
    inotifywait -r -e close_write,moved_to,create .
    rollup -c rollup.config.js
done
```
The `inotifywatch` utility is available on Debian/Ubuntu in the `inotify-tools` package.

**Comment by englercj** [comment]
The benefit of watch isn't that it automatically recompiles, but that it recompiles *incrementally*. Full recompile on change is trivial, its the incremental part that is necessary for this to be useful.

**Comment by rusco** [comment]
Yet another trivial solution for watching and building in one-shot:

```javascript
"use strict";
const fs = require('fs');
const rollup = require('rollup');

let onceCount = 0; //window$ workaround

fs.watch('src', { persistent: true, interval: 20000 }, (event, filename) => {
	
	if (filename && event == 'change' && onceCount % 2 == 0) {
		console.log(new Date().toISOString() + ": file " , filename, "changed.");
		rollup.rollup({entry: 'src/main.js'}).then( function (bundle) {
			bundle.write({	format: 'iife',	dest: './app.js'});
		});
	}
	onceCount++;
});

```

maybe useful for someone

**Comment by bfred-it** [comment]
Another option until this get implemented: https://github.com/Qard/onchange

```sh
onchange 'index.js' -- rollup -o dist/index.js
```

**Comment by timwis** [comment]
I'd just like to express my support for this feature and provide some context as to why: I've used browserify and webpack quite a lot over the last 2 years. One of the reasons I recommend webpack to those new to javascript modules is because it ships with a `--watch` feature, because for those new to js modules, "having to build after every change" sounds daunting. I write in ES6 now and frankly webpack seems like overkill. I'd love to give rollup a try after hearing @Rich-Harris and @Victorystick talk about it on [javascript jabber](https://devchat.tv/js-jabber/195-jsj-rollup-js-with-rich-harris-and-oskar-segersv-rd), but I can't fathom having to manually rebuild every time I make a change, and the solutions above sound like they'd take longer to build since they're not incremental.

Is this on the near-term roadmap? Are there any blockers in its way or is it something that someone new could pick up and work on?

**Comment by bfred-it** [comment]
I might be able to embed `onchange` under a `-w`/`--watch` flag and re-run it when the input file changes. It wouldn't be incremental but it's _something_ while we wait for https://github.com/rollup/rollup/issues/191

**Comment by bcherny** [comment]
@Rich-Harris please prioritize this - rollup is unusable as a standalone in a real world project without watch + incremental builds.

**Comment by bfred-it** [comment]
He's been busy on Bublé probably: http://buble.surge.sh/

**Comment by AlexGalays** [comment]
This is mandatory if we want to use rollup for medium/big projects for sure.

**Comment by TrySound** [comment]
@AlexGalays It was introduced since last night. You can pass previous `bundle` to `cache` option or use `--watch`, `-w` flag with installed `rollup-watch` module,

**Comment by timwis** [comment]
Nice!! Have you had a chance to add it to the docs anywhere yet?

**Comment by Rich-Harris** [comment]
I've just released Rollup 0.29.0, which includes support for `rollup --watch`. The first time you run it, it will tell you that you need to install `rollup-watch`, ideally globally. (This is because we may end up having to use a package like chokidar or pathwatcher, which can be frustrating and time-consuming to install – it's better if you don't have to do it for every project, particular where CI is involved.)

@timwis yep, have added it to the CLI page on the wiki. It's just a matter of adding `-w` (e.g. `rollup -c -w`).

I've started adding a watch task to my package.json's `scripts` section – `"watch": "rollup -c -w"` – which allows me to do `npm run watch` with the locally installed copy of Rollup.

**This is all still experimental** – YMMV! Feedback welcome. Thanks to @TrySound for getting us to a place where we could do this.

**Comment by egoist** [comment]
@Rich-Harris Will `watch` option be available in rollup's js api?

**Comment by TrySound** [comment]
@egoist Nope. It's only cli stuff. You can use any watchers by your choice. It's because for example I need to run live reload when the build is end. If api will create watcher inside we should introduce more and more API stuff for that. It's bad practice.

**Comment by Rich-Harris** [comment]
Just to follow up what @TrySound said, you could use `rollup-watch` itself if you needed to use it from within JavaScript:

```js
import { rollup } from 'rollup';
import watch from 'rollup-watch';
import config from './rollup.config.js';

const watcher = watch( rollup, config );
watcher.on( 'event', event => ... );
```

**Comment by mahmoudHosny** [comment]
Hi
I Installed rollup-watch globally but when I'm trying to use -w it asked me to install it even when I restarted the session

**Comment by yonester** [comment]
@mahmoudHosny See [here](https://github.com/rollup/rollup-watch/issues/10) for solution.

**Comment by Shyam-Chen** [comment]
https://github.com/Permutatrix/rollup-stream#usage-with-caching

**Comment by anteriovieira** [comment]
`rollup --watch` depends on the [rollup-watch package](https://github.com/rollup/rollup-watch), install it with `npm install -D rollup-watch` .
