### ISSUE TITLE
Ship modern JS (es2017) in rollup's package

### ISSUE THREAD

**Issue by manucorporat** [rollup/rollup#2848]
### Feature Use Case
All modern browsers (edge, firefox, chrome and Safari) supports es2017 already, that means native async/await, native classes, native const/let, arrow functions.

In addition, the last two node LTS releases 8 and 10, also supports it. Still, rollup only ships transpiled es5 code (https://unpkg.com/rollup@1.11.3/dist/) in NPM.

At Stencil we have seen massive performance improvements in some internal benchmarks because of the faster async/await in Node 12, since rollup is a core part of our architecture, we would like to have the option to bundle stencil with the es2017 source code of rollup.

### Feature Proposal

Modify the rollup's package.json adding new entry-points for modern JS:

```diff
{
  "name": "rollup",
  "version": "1.11.3",
  "description": "Next-generation ES module bundler",
  "main": "dist/rollup.js",
  "module": "dist/rollup.es.js",
- "jsnext:main": "dist/rollup.es.js",
+ "jsnext:main": "dist/rollup.es2017.es.js",
+ "es2017": "dist/rollup.es2017.es.js",
  "typings": "dist/rollup.d.ts",
```

and emit this addition file in the `dist` folder by transpiling from TS using a different `tsconfig.es2017.json`

**Comment by TrySound** [comment]
jsnext:main should be removed in the next major release. It's the same as `module` field.

**Comment by manucorporat** [comment]
@TrySound we still need "module:next" or something we can agree on, angular uses "es2015", "es2017" and so on for example.

I have always avocated that transpiling should happen in the client side, never in the library author side:
```
1. Bundling modern
2. Transpiling chunks to X
``` 

Instead, library authors (i include myself, are forced to ship es5-esm in "module", because webpack).
Today, the node-resolve plugin allows to customize the resolve field:
```
      mainFields: ['module', 'main'], // Default: ['module', 'main']
```

We would like add add "module:next" or **something** that rollup uses, that points to modern JS, that's all.

**Comment by lukastaegert** [comment]
Some points from me
1. Technically, Rollup only claims to support Node 6+ anyway so switching the output target to ES2015 would be a non-breaking change. I have been meaning to postpone this for the next major release in fear of backlash from people who run it on Node 4 with a ton of polyfills (maybe this is still possible?), but maybe we just go through with it in the next minor.
2. Providing a second build should be possible, not sure if we should put an entry into the package.json file, though (for instance to avoid the discussions above). A direct import should always be possible. Note though that at the moment, Rollup is mostly ES2015 code with no ES2017 features that I am aware of, so there will probably not be much advantage to going for ES2017 yet. Once we switched to native ES2015 output I would consider switching to async-await as the generator-based transpilation option that this enables looks quite nice to me.

Just out of curiosity, how are you using Rollup. Considering that you seem to be interested in an ES modules build, are you actually rebundling it or have it as an external dependency?

Going back to the original question, how about we switch the output target to ES2015 and see if there is backlash, otherwise we keep it.

**Comment by manucorporat** [comment]
>Technically, Rollup only claims to support Node 6+ anyway so switching the output target to ES2015 would be a non-breaking change. I have been meaning to postpone this for the next major release in fear of backlash from people who run it on Node 4 with a ton of polyfills (maybe this is still possible?), but maybe we just go through with it in the next minor.

Something we have done in the past it emitting big warnings before we plan to drop some node version, so people can upgrade before it becomes an error, right now we keep all our users in 8.9 and now we want to push them to at least Node 10 (current LTS).

>A direct import should always be possible. Note though that at the moment

true, but you lose type information when you do the import, fixable for sure. let's keep the conversation pragmatic, don't need to come up with a new field name for package.json today :) (however I think the whole ecosystem would benefit from it.

>Just out of curiosity, how are you using Rollup. Considering that you seem to be interested in an ES modules build, are you actually rebundling it or have it as an external dependency?

We try to reduc the number of "depencencies", so we bundle "rollup" inside stencil's compiler, it's something that is working really well for us. So we have "rollup" as devDependency.

>Going back to the original question, how about we switch the output target to ES2015 and see if there is backlash, otherwise we keep it.

I think that could work!
