### ISSUE TITLE
Syntax Error when rolling up nested ternary

### ISSUE THREAD

**Issue by BryanCrotaz** [rollup/rollup#2850]
- Rollup Version: 1.11.3
- Operating System (or Browser): MacOS
- Node Version: 8 LTS

### How Do We Reproduce?

Rollup a file that contains a nested ternary. Syntax error (unexpected token) at the beginning of the line with the ternary.

e.g. lodash, lodash-es, bluebird etc

Seems to happen with both ES and commonjs.

### Expected Behavior

Succeeds in rolling up with no error

### Actual Behavior

Fails with error.

**Comment by lukastaegert** [comment]
Thanks for the issue, could you add a specific code example how the nested ternary is written that is causing issues (ideally before and after rolling up)?

**Comment by BryanCrotaz** [comment]
From `npm:bluebird/src/debuggability.js`

**Fails**
```
Promise.onPossiblyUnhandledRejection = function (fn) {
    var domain = getDomain();
    possiblyUnhandledRejection =
        typeof fn === "function" ? (domain === null ?
                                            fn : util.domainBind(domain, fn))
                                 : undefined;
};
```
**Succeeds**
```
Promise.onPossiblyUnhandledRejection = function (fn) {
    var domain = getDomain();
    if (typeof fn === "function") {
      possiblyUnhandledRejection = domain === null
                                   ? fn 
                                   : util.domainBind(domain, fn);
    } else {
      possiblyUnhandledRejection = undefined;
    }
};
```

**Comment by BryanCrotaz** [comment]
Seems that all nested ternarys fail. I've got problems with lots of my npm dependencies, including popular libraries lodash and bluebird.

**Comment by lukastaegert** [comment]
I do not see any issues here, as a matter of fact none of the ternaries are transformed in any way: https://rollupjs.org/repl?version=1.11.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMlByb21pc2Uub25Qb3NzaWJseVVuaGFuZGxlZFJlamVjdGlvbiUyMCUzRCUyMGZ1bmN0aW9uJTIwKGZuKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjB2YXIlMjBkb21haW4lMjAlM0QlMjBnZXREb21haW4oKSUzQiU1Q24lMjAlMjAlMjAlMjBwb3NzaWJseVVuaGFuZGxlZFJlamVjdGlvbiUyMCUzRCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0eXBlb2YlMjBmbiUyMCUzRCUzRCUzRCUyMCU1QyUyMmZ1bmN0aW9uJTVDJTIyJTIwJTNGJTIwKGRvbWFpbiUyMCUzRCUzRCUzRCUyMG51bGwlMjAlM0YlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwZm4lMjAlM0ElMjB1dGlsLmRvbWFpbkJpbmQoZG9tYWluJTJDJTIwZm4pKSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0ElMjB1bmRlZmluZWQlM0IlNUNuJTdEJTNCJTVDbiU1Q25Qcm9taXNlLm9uUG9zc2libHlVbmhhbmRsZWRSZWplY3Rpb24lMjAlM0QlMjBmdW5jdGlvbiUyMChmbiklMjAlN0IlNUNuJTIwJTIwJTIwJTIwdmFyJTIwZG9tYWluJTIwJTNEJTIwZ2V0RG9tYWluKCklM0IlNUNuJTIwJTIwJTIwJTIwaWYlMjAodHlwZW9mJTIwZm4lMjAlM0QlM0QlM0QlMjAlNUMlMjJmdW5jdGlvbiU1QyUyMiklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwcG9zc2libHlVbmhhbmRsZWRSZWplY3Rpb24lMjAlM0QlMjBkb21haW4lMjAlM0QlM0QlM0QlMjBudWxsJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzRiUyMGZuJTIwJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQSUyMHV0aWwuZG9tYWluQmluZChkb21haW4lMkMlMjBmbiklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTIwZWxzZSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBwb3NzaWJseVVuaGFuZGxlZFJlamVjdGlvbiUyMCUzRCUyMHVuZGVmaW5lZCUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTdEJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

Do you by chance use any plugin that might interfere here such as rollup-plugin-replace? Or otherwise are you able to produce invalid code in the REPL?

**Comment by lukastaegert** [comment]
Also, does `getDomain` have a fixed return value so that the ternaries might be resolved in some way?

**Comment by lukastaegert** [comment]
Considering that you say that rollup up fails, I would very much expect a plugin to be the culprit. An "unexpected token" is not produced by Rollup itself but by our parser acorn, which means that when we reached the parsing stage, the code was already invalid. Rollup itself does not do any transformations before the parsing so this means that either the code was invalid to begin with (unlikely) or that a plugin transformed the code in an illegal way.

**Comment by BryanCrotaz** [comment]
If the parser you've chosen to use fails then some guidance in the resulting fail from rollup would be useful. I lost a month trying to work out whether it was me at fault, a library (seems unlikely that bluebird would be supported - everyone uses that), rollup (seems unlikely, everyone uses that), or something I've done wrong (copied the example config on the rollup documentation).

If there is a one to one mapping from an error to a necessary plugin, software authors would very much appreciate rollup suggesting "install this plugin to fix that", or just installing it with `rollup --fixit`

**Comment by BryanCrotaz** [comment]
My fix was to give up on rollup and use webpack. Worked first time, from the config suggested in the docs.

**Comment by lukastaegert** [comment]
Then that is your solution, I am sorry we could not help you.

>  I lost a month trying to work out whether it was me at fault, a library

If you had used this month to give us a repository that fails or at least your Rollup config, we might have had a little more to work on. As it stands, just stating that something does not work that seems to work for everyone else and hoping that we figure out what is different is rather optimistic.

So what I see is a missed chance to learn something, even if it is just where to improve documentation. Feel free to reopen if you think you do have something like a repo available.
