### ISSUE TITLE
Strategy when authoring libs for maximum rollup-ability

### ISSUE THREAD

**Issue by robwormald** [rollup/rollup#286]
Not an issue, as such, but you folks seem to be on the ball here.

Consider a library like the new [RxJS](https://github.com/reactivex/rxjs): authored in TS (and thus can be xpiled to ES6)

It's basically a core type (Observable) and 50+ operators that get attached onto the prototype of the Observable prototype.

Currently, we do something like this:
```js
import {map} from './map';
import {filter} from './filter';

class Observable {
  constructor(subscriberFn){ //etc }
}

//extend the prototype
Observable.prototype.map = map;
Observable.prototype.filter = filter;

```
This works fine (and performantly) but doesn't appear to lend itself to rollup-style treeshaking.

So I tried a little experiment, based on the README in this repo:
```js
//map.js
export function map(){
  //do some stuff;
}
```

```js
//filter.js
export function filter(){
  //do some stuff;
}
```

```js
//myLib.js
import {map} from './map';
import {filter} from './filter';

export class MyLib {
  constructor(){}

  map(){
    return map();
  }
  filter(){
    return filter();
  }
}
```

and then used said lib in an "app" module:

```js

import {MyLib} from './mylib';

let lib = new MyLib();

lib.map();
```

I was hoping this would lead to the `filter` module getting ignored, but that doesn't appear to be the case. This is a trivial 5 minute example, so perhaps I'm missing something? 

Is there a best-practice/strategy for accomplishing this sort of thing? RxJS's huge number of operators is a perfect use case for Rollup, as most consumers would likely only ever use, say, 5. 

Thoughts?

**Comment by robwormald** [comment]
cc @blesh @jeffbcross

**Comment by Rich-Harris** [comment]
Unfortunately this is one of those places where static analysis falls down in a language like JavaScript – it's just not possible to track `lib` all the way through your app without actually running it:

```js
doSomethingWith(lib);

const doSomethingWith = Math.random() > 0.5 ?
  lib => lib.map() :
  lib => lib.filter();
```

That's before we even get into things like monkey patching!

Rather than try to handle all the ways in which the methods of `lib` could get called, Rollup relies on some relatively simple rules: `lib` 'depends' on `MyLib` (because of `lib = new MyLib()`, and `MyLib` 'depends' on `map` and `filter` (because they're contained within the `MyLib` class definition).

It *could* be done though:

```js
import { Observable, map, filter };

// this...
const mapped = map( filter( new Observable(...), ... ), ... );

// ...instead of this:
const mapped = new Observable(...).filter(...).map(...);
```

At first glance it's not quite as elegant, but it's arguably a more functional (and therefore composable etc) approach. I've no idea how practical a shift like that would be, though!

**Comment by robwormald** [comment]
That's... not gonna happen :D 

Cheers, figured i'd ask. I'll close this.

**Comment by blesh** [comment]
>That's... not gonna happen :D

Haha. Confirmed.

Honestly though, in ES7 we can use the function bind operator and solve this problem cleanly.

```
import { map } from 'rx/map';

myObservable::map(x => x + 1)
```
