### ISSUE TITLE
Underscore-separated, not camel-cased, global names?

### ISSUE THREAD

**Issue by mbostock** [rollup/rollup#293]
When using the UMD finalizer, dependencies on external modules in globals are referenced using `module.name` which is generated using [`makeLegalIdentifier`](https://github.com/rollup/rollup/blob/master/src/utils/makeLegalIdentifier.js). This replaces letters preceded by a hyphen with capitalized letters, such replacing “d3-arrays” with “d3Arrays”.

This is personal preference, but it’d be nice to substitute different logic for generating the global names, such as “d3_arrays”. I can do that using Rollup’s `-g` argument, but it’s a pain since I have to rename each external module. For example, in [d3-request](https://github.com/d3/d3-request):

```
rollup \
    -f umd \
    -g d3-arrays:d3_arrays,d3-dispatch:d3_dispatch,d3-dsv:d3_dsv \
    -u d3-request \
    -n d3_request \
    -o build/d3-request.js \
    -- build/bundle.js
```

It doesn’t look too hard to add an option that the UMD finalizer can use to substitute a different strategy for makeLegalIdentifier, but perhaps you have an opinion on whether this is the right approach?

**Comment by Rich-Harris** [comment]
In the context of a command line option I think it's probably a bit tricky, because everyone who doesn't want the default behaviour is likely to have slightly different needs. Two options spring to mind, but both rely on either using the Node API or a config file:

* Throw an error if `globals` isn't supplied (since if you're relying on the default makeLegalIdentifiers behaviour and it works, it's basically blind luck...)
* Allow a function to be specified instead of a map

In the meantime, you could do it with a config file like so:

```bash
rollup -c
```

```js
// rollup.config.js
var pkg = require( './package.json' );

function snakeCase ( id ) {
  return id.replace( /-/g, '_' );
}

export default {
  entry: 'src/index.js',
  dest: 'build/' + pkg.name + '.js',
  format: 'umd',
  moduleId: pkg.name,
  moduleName: snakeCase( pkg.name ),
  globals: Object.keys( pkg.dependencies ).reduce( function ( obj, id ) {
    return obj[ id ] = snakeCase( id ), obj;
  }, {})
};
```

That way it could be shared between different modules with relative ease.

**Comment by Victorystick** [comment]
I say enable both options.

* I don't think we should make Rollup's users rely on "blind luck" because of how `makeLegalIdentifier` works. We should make the globals option required and throw if we can't determine the name of a required global.
* We can keep the option for `globals` to be a map and wrap it in a lookup function internally. We'd throw if a global name can't be looked up in the map. Since we'll default to an empty map if the user doesn't supply one, we'd get the behaviour we want.

Something like:
```js
const globals = options.globals || {};

function mapGetter ( map ) {
  return id => {
    const name = map[ id ];

    if ( name ) return name;

    throw new Error( `Cannot determine global name of "${ id }".
See https://github.com/rollup/rollup/wiki/Troubleshooting#globals for more details` );
  };
}

// Always a function to get the identifier of a global module.
const globalName = typeof globals === 'function' ? globals : mapGetter( globals );
```

Then it could be as simple as this, without breaking the API.
```js
// rollup.config.js
var pkg = require( './package.json' );

function snakeCase ( id ) {
  return id.replace( /-/g, '_' );
}

export default {
  entry: 'src/index.js',
  dest: 'build/' + pkg.name + '.js',
  format: 'umd',
  moduleId: pkg.name,
  moduleName: snakeCase( pkg.name ),
  globals: snakeCase
};
```

**Comment by Rich-Harris** [comment]
Closing – `options.globals` can be a function as of 0.23.2
