### ISSUE TITLE
Starter Plugin

### ISSUE THREAD

**Issue by Crisfole** [rollup/rollup#2931]
### Feature Use Case

Creating a rollup plugin from scratch.

### Feature Proposal

 It'd be nice if I could just `degit git@github.com:rollup/rollup-starter-plugin.git my-plugin`  and rock and roll. I'd like all the options there, but commented out, makes for better discoverability. Probably easiest if it's written in Typescript so the expected types are easily visible.

**Comment by lukastaegert** [comment]
Sounds like a great idea! If someone from the community were to set something up, I would be glad to review and move it to the Rollup organization.

**Comment by kenjiO** [comment]
I would like to take a shot at this.  Could I do it in js instead of ts?  I looked at the repos for several plugins and most are in js.  Since this will have all the options commented out, I could still put the types in. Then the authors can remove them when they un-comment what they need to use.

**Comment by lukastaegert** [comment]
Of course you can create it in JS.

Rollup is TS and there is a lot of demand from the community for proper TS typings (which is easiest when it is written in TS to start with). So the way forward for us will be to gradually start moving plugins to TS.

On the other hand, TS adds additional tooling complexity, so I guess in the end there would be demand for both. If we have a JS version, surely someone could create a nice rollup-starter-plugin-ts version.

**Comment by shellscape** [comment]
> surely someone could create a nice rollup-starter-plugin-ts version

Absolutely. I think there's actually value in a standard JS solution as a baseline.

**Comment by kenjiO** [comment]
Awesome, I will start working on a JS starter plugin project then

**Comment by kenjiO** [comment]
@lukastaegert 
I created a plugin starter at [https://github.com/kenjiO/rollup-starter-plugin](https://github.com/kenjiO/rollup-starter-plugin)
Can you let me know what you think?

**Comment by lukastaegert** [comment]
Thanks, looks really good!
Only three comments that came to my mind:
- I think instead of instructing to clone the repo, it would be better to instruct them to use e.g. `degit` to get their copy, i.e.
  
  ```
  mkdir rollup-starter-plugin
  cd rollup-starter-plugin
  npx degit https://github.com/kenjiO/rollup-starter-plugin
  npm install
  ```
  
  The reason is that `degit` will not create a git repo that is "polluted" with your commits but just give them a fresh folder to start from, ideal for starter projects.

- Even though alphabetical ordering is nice, I think it would be more helpful to order the hooks roughly in the order they are called and group them by phase. This could be
  **build phase**
  - options
  - buildStart
  - resolveId
  - resolveDynamicImport
  - load
  - transform
  - buildEnd
  - watchChange
  **generate phase**
  - outputOptions
  - renderStart
  - resolveImportMeta
  - resolveFileUrl
  - renderChunk
  - generateBundle
  - writeBundle
  - renderError
  - banner/intro/outro/footer is probably good at the end, but it might be grouped banner/footer and intro/outro

- I know anchor links on the website currently do not work very well. Nevertheless in the markdown you linked, none of the relative links will work as they assume the file is part of the website. I hope to fix the anchor links soon, eventually the link should be https://rollupjs.org/guide/en/#plugins

**Comment by lukastaegert** [comment]
I invited you as collaborator to the Rollup organization. If you want the starter to become part of the official Rollup, you should be able to transfer the repo to Rollup in Github. I will then make sure you regain full admin control over the repo if there is a problem. We should also not forget to adjust the instructions to use the changed repo link as well as adjust the links in package.json.

**Comment by lukastaegert** [comment]
Ok, first added you to the Rollup main repo by accident. You should have received an invite for the organization, that is the good one.

**Comment by kenjiO** [comment]
I made the changes you suggetsted and squashed everything to the "initial commit" to keep it cleaner.  Can you look over it again to make sure everything looks good?

I only saw one invitation and when I accepted it, it was for access to the rollup/rollup repository.  In my github settings I left that repository but you can double-check to make sure I am not on it anymore.  Can you try to send me the rollup organization invitate again?

**Comment by lukastaegert** [comment]
Looks great 👍
I tried to send you another invite, at the moment you are listed as "pending". You should be able to accept it by going to https://github.com/rollup

I work on fixing the website links, unfortunately it will take a few more days as it involves upgrading from Svelte 2 to Svelte 3 which is definitely non-trivial.

**Comment by kenjiO** [comment]
The invite worked and I was able to move the repo into the rollup organization.

If you have any ideas about improvements or features to add to it let me know I will be glad to try to implement them.

**Comment by lukastaegert** [comment]
Awesome. I created the https://github.com/orgs/rollup/teams/rollup-starter-plugin team and made you maintainer. Everyone in this team has full admin access for the rollup-starter-plugin repo.

**Comment by lukastaegert** [comment]
I believe this closes the original issue. If there is demand for a TypeScript version, I would suggest to create a new issue referencing the existing JS starter repo and this issue.
