### ISSUE TITLE
Build multiple UMD files from multiple entries

### ISSUE THREAD

**Issue by moog16** [rollup/rollup#2935]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
I have a library of components. Let's say I have 
- packageA
  - index.js
- packageB
  - index.js

I'd like this to be on configuration:

```
export default [
	{
		input: ['packages/A/index.js', 'packages/B/index.js'],
		output: {
			name: '[name]Bundle',
			file: '[name].umd.js',
			format: 'umd'
		}
	},
];
```

I expect this to output an A/index.umd.js and a B/index.umd.js file, but I get `[!] Error: UMD and IIFE output formats are not supported for code-splitting builds.`. If I change `format` --> `esm`, `cjs`, etc. it works as expected. I couldn't find any documentation to achieve this with iife/UMD. 

I also went on gitter, but didn't hear from anyone. 

### Your Proposal for Changes

Some documentation to how to build multiple umd files from multiple entry files.

**Comment by lukastaegert** [comment]
It is not documented because it is not supported. Main reasons:
- There is not way to specify imports for UMD or IIFE builds. Thus, the user would need to take care themselves to load the correct files in the correct order; this order would also need to be communicated to the user
- All code-splitting would need to happen via global variables. Not impossible but potentially error-prone
- There is no native way to do dynamic imports for IIFE or UMD builds

All in all, a lot of effort on Rollup side with only limited utility considering ESM, AMD and SystemJS are working alternatives that do not share these issues.

If your issue is just to build independent stand-alone files, then you can just run Rollup several times or use the array form of Rollup options supported by the CLI.

**Comment by lukastaegert** [comment]
> If your issue is just to build independent stand-alone files, then you can just run Rollup several times or use the array form of Rollup options supported by the CLI

In your case

```js
export default [
	{
		input: 'packages/A/index.js',
		output: {
			name: '[name]Bundle',
			file: '[name].umd.js',
			format: 'umd'
		}
	},
	{
		input: 'packages/B/index.js',
		output: {
			name: '[name]Bundle',
			file: '[name].umd.js',
			format: 'umd'
		}
	}
];
```

**Comment by moog16** [comment]
@lukastaegert thanks for the swift response! I've gone the route of multiple configs in an array. Although its not as fast, its still pretty quick.
