### ISSUE TITLE
Incorrect typing for resolveId hook

### ISSUE THREAD

**Issue by slavafomin** [rollup/rollup#2939]
Hello!

Thank you for this great tool!

However, right now, typing for the `resolveId` hook contradicts [the documentation](https://rollupjs.org/guide/en/#resolveid).

According to the docs:

> Returning `null` defers to other resolveId functions and eventually the default resolution behavior...

However, in `rollup.d.ts` there is the following type:
`export type ResolveIdResult = string | false | void | PartialResolvedId;`

There is no `null` return value. This happend after I've updated the Rollup dependency to the latest version. Previously my code was working fine with returning `null`.

What exactly has changed? Should we update the documentation (and the behavior of all plugins) or the typing is just incorrect?

Thanks!

**Comment by slavafomin** [comment]
According to my tests, it looks like the the typings are actually incorrect.

**Comment by lukastaegert** [comment]
I must admit that I was under the impression that `void` is the same as `null | undefined` but this is not (no longer?) the case. Fix at #2941.

**Comment by slavafomin** [comment]
In my opinion, the `null` value should be avoided at all if possible. It's somewhat strange falsy value, which type is `object`.

I would suggest to use the `undefined` instead. This is the default value for non-initialized variables and it's easy to define in TypeScript using question mark syntax.

The `void` type means a lack of value (this should be used only for functions which doesn't return value at all). In practice it's very similar to `undefined` though.

**Comment by lukastaegert** [comment]
This is a religious debate. Others could argue that `undefined` is a variable that can even be redefined if you do it right which is why you should use `null` for explicitly declaring the absence of a value and explicit `undefined` comparisons should be avoided if possible. In any case, you always could use both interchangeably in the hooks and now the types reflect this. You are free to structure your code as you see fit.
