### ISSUE TITLE
__dirname and import.meta in plugins

### ISSUE THREAD

**Issue by jakearchibald** [rollup/rollup#2953]
- Rollup Version: 1.15.6
- Operating System (or Browser): OSX
- Node Version: v12.4.0

### How Do We Reproduce?

In `/whatever/rollup.config.js`:

```js
import plugin from './lib/plugin.js';
```

In `/whatever/lib/plugin.js`:

```js
console.log(__dirname);
console.log(import.meta.url);
```

### Expected Behavior

Logs:

* `/whatever/lib`
* `file:///whatever/lib/plugin.js`

### Actual Behavior

Logs:

* `/whatever`
* `file:///whatever/rollup.config.js`

**Comment by lukastaegert** [comment]
The reason is that Rollup bundles its configuration file including all relative imports. If you import the plugin via an absolute path it should work correctly, but then it should be available as CommonJS. Not sure what the best solution would be here but I assume Rollup should try to polyfill __dirname and __filename per module and adjust the rendering of `import.meta.url`.

**Comment by lukastaegert** [comment]
Note that #4005 will also fix `import.meta.url` for transpiled config files.
