### ISSUE TITLE
Modifying the bundle object in generateBundle

### ISSUE THREAD

**Issue by jakearchibald** [rollup/rollup#2973]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...

https://rollupjs.org/guide/en#generatebundle

I've been modifying the bundle object in the `generateBundle` hook, but there's nothing in the docs that say I can do this, or how I should do it.

Use-cases:

**Adding files**. Something like:

```js
async generateBundle(options, bundle) {
  bundle["index.html"] = {
    fileName: "index.html",
    isAsset: true,
    source
  };
}
```

**Renaming files**. I tend to hash all entry points, however, service worker scripts shouldn't be hashes, so I dig into the bundle and remove the hash from the object key & `fileName`.

**Removing files**. As part of generating `index.html`, I might inline some assets that are no longer needed, so I can `delete bundle[fileName]`.

Is doing this ok? If so, it'd be great if the docs could say so, and what the constraints are. I'm happy to create a PR for this.

The object key and the value's `fileName` property seem to be the same thing. Does either have priority?

**Comment by tivac** [comment]
I've been told that doing that is ok for now, but not guaranteed to continue working. `@modular-css/rollup` directly adds a `.css.map` file to the bundle to avoid the hashing algorithm because it breaks the implicit loading of the source map.

**Comment by lukastaegert** [comment]
The inofficial-official stance (i.e. mine) is, that
- deleting keys from the bundle object or assigning null will probably become the official way of removing stuff from the bundle and should therefore remain safe
- as soon as the new unified file emission API is ready, emitting files with fixed names should be done via this API. I do not think we will protect the bundle from having new keys added but I think it is possible that in the future, other things need to be triggered when files are added.

The new API is top of my list (now that the website is kinda fixed), but development has slowed a little on my end due to family stuff. Hope to get on it the next days.

**Comment by jakearchibald** [comment]
> development has slowed a little on my end due to family stuff

No rush at all. I'm just really happy with where Rollup is heading, & want to capture any rough edges I find.

**Comment by lukastaegert** [comment]
I believe this has been addressed with the new file emission API. There is also a note in the docs that explicitly permits deleting from the bundle in generateBundle.
