### ISSUE TITLE
How to get the current sourcemap in the transform hook ?

### ISSUE THREAD

**Issue by billowz** [rollup/rollup#2983]
I implemented an `istanbul` plugin using `istanbul-lib-instrument`， But the `istanbul-lib-instrument` require the `inputSourceMap` to maps the not instrumented code back to it's original form

How can i get the current sourcemap in the transform hook ?

- istanbul.js

  ```js
  import { createFilter } from 'rollup-pluginutils';
  import istanbul from 'istanbul-lib-instrument';

  export default function (options = {}) {
    return {
      name: 'istanbul',
      transform (code, id) {

        const instrumenter = new istanbul.createInstrumenter({
          produceSourceMap: sourceMap,
          esModules: true,
          codeGenerationOptions: {
            { sourceMap: id, sourceMapWithCode: true }
          }
        });
        
        // TODO require the inputSourceMap that generated by the previous plugins
        code = instrumenter.instrumentSync(code, id, ??? );

        return { code, map: instrumenter.lastSourceMap() };
      }
    };
  }
  ```

- rollup config
  - the `rollup-plugin-jscc` well 

  ```js
  const nodeResolve = require('rollup-plugin-node-resolve'),
     commonjs = require('rollup-plugin-commonjs'),
    jscc = require('rollup-plugin-jscc'),
    typescript = require('rollup-plugin-typescript'),
    istanbul = require('./istanbul')

  module.exports = {
    input: 'src/index.ts',
    output: {
       name: 'test',
       format: 'umd',
       file: 'bundle.js',
       sourcemap: true,
       amd: {id: 'test'}
    },
    plugins: [
      nodeResolve({ jsnext: true, extensions: ['.ts'] }),
      commonjs(),
      jscc({ values: { _DEBUG: true } }),
      typescript({ module: 'ESNext', target }),
      istanbul()
    ]
  }
  ```

**Comment by lukastaegert** [comment]
So what you need is the combined source maps of all previous plugins. Unfortunately at the moment, this is not available. The reason is that there was no use yet, and it would be costly to calculate it by default. This is how sourcemaps work in Rollup:
- The loader and each transformer create source-maps that just describe their own transformations
- These are stored untransformed in an array, the "sourcemap-chain"
- If an output with sourcemaps is created, this chain is merged ("collapsed") with all transformations done by Rollup itself into a final map. This process is costly so we do not do it unless requested.

That being said, I think having a good way to run coverage in Rollup would be really nice, I would be very interested in having a good coverage solution for Rollups sources as well. So maybe we could find a way to request a pre-collapsed source-map from a transform hook?

For instance we could try to add a `this.getCombinedSourceMap()` just to the transform hook, would this solve your issue?

**Comment by billowz** [comment]
@lukastaegert Thank you, it's going to solve my issue.

**Comment by lukastaegert** [comment]
Don't thank me yet, it still needs to be implemented...
