### ISSUE TITLE
Custom naming systems

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#30]
Really loving this project! The APIs are great to work with.

Just been playing around with hooking it in to SystemJS builder and I'm even defining a custom loader to manage everything in-memory which is great.

It would be nice to be able to use the same naming system as SystemJS without having to translate into file paths, so I'm trying to set both resolvePath and resolveExternal, but it seems the entry point still gets resolved to a path.

Would it be possible to have the above resolution run through the same hooks as above?

The ES specification defines module loading through two hooks:

* HostNormalizeModuleName(ID, parentID)
* HostGetSource(normalizedID)

It would be nice to maintain some consistency with this by allowing any naming system.

I know it's very much my use case, but let me know if it's a possibility.

**Comment by Rich-Harris** [comment]
Great! This seems like it might be relevant to #25 (getting Rollup to work in a browser environment). If I understand you correctly, the goal is to replace [this line](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L18) with something that loosely equates to HostNormalizeModuleName (i.e. `resolvePath`, but where [`importer`](https://github.com/rollup/rollup/blob/master/src/utils/resolvePath.js#L6) is `undefined`), so that a subsequent HostGetSource (a.k.a. `load`) operation can load the entry module in the absence of a filesystem. Is that right?

If so, that seems both doable and desirable.

**Comment by guybedford** [comment]
Yes, exactly!

**Comment by Rich-Harris** [comment]
Have to run now, but I've made a start on this in #31 - will pick it up soon, but in the meantime checking out that branch and `npm link`ing it will allow you to try it out if needs be.

**Comment by Rich-Harris** [comment]
Fixed as of 0.9.0. #31 for details. @guybedford let me know if this behaves as you expect!
