### ISSUE TITLE
[Feature Request] Configure tree-shaking of top-level input files

### ISSUE THREAD

**Issue by FredKSchott** [rollup/rollup#3047]
### Background

I maintain @pika/web, an application-bundler alternative that lets you install npm packages that run (and can be ESM imported) directly in the browser. It's powered internally by Rollup. More info here: https://github.com/pikapkg/web

@pika/web works by running Rollup on your node_modules folder with each web dependency as a `inputOptions.input` value. The result is a single JS file per dependency (+ any shared chunks/assets) that can then be imported in the browser. 

```js
// Example of how @pika/web uses rollup
export default {
  input: ['node_modules/lodash-es/index.js', 'node_modules/date-fns/index.js'],
  // ...
}
```

### Expected Behavior / Situation

Rollup has been perfect for what we've needed up to this point, but we've had several users request a new feature: **tree-shaking of the top-level dependencies (`input` files)**. 

As a rollup user, I want to configure Rollup to create bundles containing only certain exports of each input. Example: If you only use `add` from lodash, @pika/web should be able to bundle the lodash package into a single file with all other exports removed.

This would dramatically improve performance of large dependencies in production.

### Actual Behavior / Situation

There doesn't seem to be any way to configure which specific exports to include in any `input` bundle entrypoint, so Rollup includes them all.

### Modification Proposal

**The ability to configure specific exports for an `input` bundle entrypoint.** I'm happy to help bikeshed on what this could look like, as well as make a PR if it's a reasonable amount of work, but I wanted to check first that there was interest as a concept.

If this can't be added, our workaround would have to be to create virtual files that whitelist the exports that we care about, and then bundle those files as the bundle `input` files instead. Example: Bundle `export {foo, bar} from 'lodash-es'` instead of lodash-es directly. 

I'm not opposed to the workaround, but first wanted to check if there was interest in adding this support more generally via Rollup config.

**Comment by lukastaegert** [comment]
Your workaround actually sounds quite sensible to me and like something that could easily be rolled into a plugin (if it does not exist yet, I assume you checked?). This should not have any adverse effects on bundle size. With this in mind, I would prefer to avoid making this a core feature unless many people chime in, to avoid the additional maintenance overhead. If you need help turning it into a plugin I would be happy to give pointers.

**Comment by FredKSchott** [comment]
That's fine by me, and yes I'd love some help getting started. I'm familiar enough with how Rollup plugins work but would love any advice / help getting point in the right direction. 

Only specific question that I can think of: Would you recommend any "virtual" module plugin, like https://github.com/rollup/rollup-plugin-virtual or https://github.com/TrySound/rollup-plugin-memory ? I'm assuming that plugins are still run for all input entrypoints, which would allow use to skip writing/deleting/managing those virtual files on disk.

**Comment by lukastaegert** [comment]
Personally I would roll your own plugin as it is not very difficult and gives you full control over everything. The basics of writing a virtual module are actually the introductory example to the plugin API: https://rollupjs.org/guide/en/#a-simple-example

For your specific use-case, you also want to replace the input with your virtual module so what you want to do is
1. Invent a virtual module name. Let's call it `virtual-entry` for now.
2. Add an options hook https://rollupjs.org/guide/en/#options to your plugin that modifies the input options so that `virtual-entry` is your entry point.
3. Add a `resolveId` hook https://rollupjs.org/guide/en/#resolveid so that Rollup does not ask other plugins or its default mechanism what `virtual-entry` is and what file it points to. This hook should return `virtual-entry` for the virtual entry point and `null` for all other modules.
4. Add a `load` hook https://rollupjs.org/guide/en/#load that tells Rollup how to load `virtual-entry` (and return `null` for all other modules). This is the important part where you write your module with the re-exports. I guess this will be like
   ```js
   load(id) {
     if (id === 'virtual-entry`) {
       return `export {foo, bar} from 'lodash-es'`;
     }
     return null;
   }
   ```

And that's it!

**Comment by FredKSchott** [comment]
For an interface I could see:


      plugin({
        “INPUT_1”: [“export1”, “export2”, ... ],
        “INPUT_2”: “*”,
         ...
      }

**Comment by FredKSchott** [comment]
This is perfect, thanks for the advice! Closing this issue but will update with a plugin once we get it up and running.

**Comment by FredKSchott** [comment]
@lukastaegert just wanted to follow up and say that we finally got this implemented! @pika/web now supports tree-shaking! Thanks for your guidance to help make this possible

**Comment by FredKSchott** [comment]
@lukastaegert just wanted to follow up and say that we finally got this implemented! @pika/web now supports tree-shaking! Thanks for your guidance to help make this possible

PR: https://github.com/pikapkg/web/pull/112
