### ISSUE TITLE
Tree shaking removing variables on compilation

### ISSUE THREAD

**Issue by modermo** [rollup/rollup#3086]
- Rollup Version: rollup v1.20.3
- Operating System (or Browser): OSX 10.14.4
- Node Version: 12.7.0

### How Do We Reproduce?

My `main.js` is: 
 
```
export const hello = (pageTitle) => {
  return attachListenersToPhoneMapEmailTriggers(pageTitle);
}

const attachListenersToPhoneMapEmailTriggers = (pageTitle) => {
  return document
    .querySelectorAll('[data-ga-event-listener]')
    .forEach(clickElement => {
      return clickElement.addEventListener('click', (event, pageTitle) => 
        sendPhoneMapEmailClicksToGA(event, pageTitle))
    })
}
```

and my `config` is
```
export default {
  input: 'main.js',
  output: {
    file: 'bundle.js',
    format: 'iife',
    name: 'yesRick'
  }
};
```

I then run `rollup -c`

### Expected Behavior

IIFE should retain parameters after compilation, like so:
```
var yesRick = (function (exports) {
  'use strict';

  const hello = (pageTitle) => {
    return attachListenersToPhoneMapEmailTriggers(pageTitle); //pageTitle should be here
  };

  const attachListenersToPhoneMapEmailTriggers = (pageTitle) => {
    return document
      .querySelectorAll('[data-ga-event-listener]')
      .forEach(clickElement => {
        return clickElement.addEventListener('click', (event, pageTitle) => 
          sendPhoneMapEmailClicksToGA(event, pageTitle))
      })
  };

  exports.hello = hello;

  return exports;

}({}));
```

### Actual Behavior

```
var yesRick = (function (exports) {
  'use strict';

  const hello = (pageTitle) => {
    return attachListenersToPhoneMapEmailTriggers(); // pageTitle disappears
  };

  const attachListenersToPhoneMapEmailTriggers = (pageTitle) => {
    return document
      .querySelectorAll('[data-ga-event-listener]')
      .forEach(clickElement => {
        return clickElement.addEventListener('click', (event, pageTitle) => sendPhoneMapEmailClicksToGA(event, pageTitle))
      })
  };

  exports.hello = hello;

  return exports;

}({}));
```

**Comment by lukastaegert** [comment]
The reason is that you are not using the parameter in your code. Instead, you are shadowing the paramter with a local variable of the same name. If you remove the variable, the parameter will be retained: https://rollupjs.org/repl/?version=1.20.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwaGVsbG8lMjAlM0QlMjAocGFnZVRpdGxlKSUyMCUzRCUzRSUyMCU3QiU1Q24lNUN0JTJGJTJGJTIwTm93JTIwdGhlJTIwYXJndW1lbnQlMjBpcyUyMGFjdHVhbGx5JTIwdXNlZCU1Q24lMjAlMjByZXR1cm4lMjBhdHRhY2hMaXN0ZW5lcnNUb1Bob25lTWFwRW1haWxUcmlnZ2VycyhwYWdlVGl0bGUpJTNCJTVDbiU3RCU1Q24lNUNuY29uc3QlMjBhdHRhY2hMaXN0ZW5lcnNUb1Bob25lTWFwRW1haWxUcmlnZ2VycyUyMCUzRCUyMChwYWdlVGl0bGUpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMGRvY3VtZW50JTVDbiUyMCUyMCUyMCUyMC5xdWVyeVNlbGVjdG9yQWxsKCclNUJkYXRhLWdhLWV2ZW50LWxpc3RlbmVyJTVEJyklNUNuJTIwJTIwJTIwJTIwLmZvckVhY2goY2xpY2tFbGVtZW50JTIwJTNEJTNFJTIwJTdCJTVDbiU1Q3QlNUN0JTIwJTIwJTJGJTJGJTIwaWYlMjB5b3UlMjBjaGFuZ2UlMjBpdCUyMGJhY2slMjB0byUyMHBhY2dlVGl0bGUlMkMlMjB0aGUlMjBwYXJhbWV0ZXIlMjBpcyUyMHNoYWRvd2VkJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMGNsaWNrRWxlbWVudC5hZGRFdmVudExpc3RlbmVyKCdjbGljayclMkMlMjAoZXZlbnQlMkMlMjBwYWdlVGl0bGVSRU5BTUVEKSUyMCUzRCUzRSUyMCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBzZW5kUGhvbmVNYXBFbWFpbENsaWNrc1RvR0EoZXZlbnQlMkMlMjBwYWdlVGl0bGUpKSU1Q24lMjAlMjAlMjAlMjAlN0QpJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by modermo** [comment]
Totally get it. My bad, and thank you.
