### ISSUE TITLE
Microsoft Edge execution bug and workaround

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#3087]
We just discovered today that in Microsoft Edge, the following code:

```js
import 'a';
import 'b';
```

will not reliably execute `a` and then `b`, and in fact in most cases it will actually execute `b` first!

ChakraCore bug here - https://github.com/microsoft/ChakraCore/issues/6261.

This means that the Rollup output cannot provide a reliable execution order in Edge.

It turns out there is a way to fix this though too, by **inlining the execution chain**.

What that means is in the above, we inline into `b` an `import 'a'`, so that `b` cannot execute before `a`.

The algorithm for this is as simple as (psuedocode):

```js
const execOrder = determineExecOrder(graph);
let lastModule = undefined;
for (const module of execOrder) {
  if (lastModule)
    module.source += `import '${lastModule.url};`;
  lastModule = module;
}
```

It could be worth doing this by default in RollupJS module output so that Edge can be properly supported.

**Comment by kzc** [comment]
The proposed workaround wouldn't work in cases where Rollup doesn't have access to all import files and as result would not be able to modify them. Rollup emits such imports as is. 

Did you try something like converting `import "./m"` to `import * as unused$1 from "./m"`? The presence of the unused symbol may be enough to serialize the imports in Edge. Who knows - just a guess.

It'd be unfortunate to impose an overhead in Rollup "es" output in the general case due to an apparently fundamental bug in a particular browser. I'd suggest either a custom plugin or perhaps creating a new output type "edge" if this must be in rollup core.

**Comment by lukastaegert** [comment]
I definitely agree with @kzc here. Also note that even with that bug, it is still guaranteed that in absence of circular dependencies, dependencies of modules are executed before the modules that depend on them. And when code-splitting, this is the only guarantee that Rollup gives anyway. Rollup does not produce exact executation order when there is more than one chunk or an external dependency and never has, and we got 0 issues because of that, otherwise I would have put some energy into an "exact execution order"  mode that produces more chunks to achieve that.

The core problem is this:
* let A import first B, then C
* let C import D

Then the correct execution order is
B-D-C-A

Now make C an entry point. Now we have these files:
* X contains B-A and imports Y
* Y contains D-C

Now the execution order is
D-C-B-A

In order to be able to produce correct execution order here, Rollup would need to further split chunks so that chunks only contain modules that are in a direct sequence in the execution order. In this case, X would need to be split into two chunks containing only A and B.

Until now, nobody had a requirement for this as code where two modules depend on each other logically that do not have a direct dependency is apparently rather uncommon in the wild.

For that reason, I would especially not invest any energy in core to address something that violates the spec anyway.

**Comment by guybedford** [comment]
@lukastaegert great point, and I agree there is nothing to be done here after more thoroughly looking at the use cases since the ordering guarantees between chunks are exactly the ones that are allowed to be indeterminate. That is, Rollup inlining is effectively the safe ordering inlining.

It is worth noting that the ordering guarantee provided by Rollup code splitting is stronger than you're making it sound like. The order guarantee is the following:

> Given a list of entry points, the Rollup graph will always execute in specification order those dependencies of any subgraph (ie chunk) that would execute in the same order under every ordering of execution of the graph created for every possible initial entry point ordering.

And that quite strongly resembles user intent too which is a nice property. So I wouldn't dismiss the strength of the ordering invariants we have so easily.

Thanks for talking it through here, will close this then.
