### ISSUE TITLE
how to set filename with double output?

### ISSUE THREAD

**Issue by 5shell** [rollup/rollup#3103]
v: 1.21.0

last week, i am using 1.20.3,
i can set output: [{
file: 'index.js'
},{
file: 'index.es.js'
}]

now  how can i set filename in v1.21.0

**Comment by lukastaegert** [comment]
Please use the issue template, we have it for a reason. As you provided no information in what way bundling fails and more importantly, what plugins you are using, this ticket is not very helpful in fixing whatever issue you have. I am sure you ARE using plugins because we ARE testing our code and we also try to avoid intentional breaking changes in minor releases; the `file` property is still supported and tested.

I will close this now as I assume it was the same issue as #3104 and is fixed in 1.21.1.
