### ISSUE TITLE
do nothing format

### ISSUE THREAD

**Issue by pjebs** [rollup/rollup#3106]
It would be good if we could have a format called `null` so that I can use rollup only for minimizing the file and perhaps bundling dependencies (but not packaging as a module for importing)

**Comment by TrySound** [comment]
So you don't want to run the code in any environment, only bundle it, right?

**Comment by pjebs** [comment]
Yes

**Comment by TrySound** [comment]
What is the use case?

**Comment by pjebs** [comment]
I have a normal javascript file (not intended to be used as a module) that I want to inject (down the pipeline) in between a html file's `<script>` tags. But before I inject it in, I want to process it by minimising it and bundling the dependencies.

**Comment by TrySound** [comment]
There are a bunch of non-module formats like iife and umd which fits into your use case. There is not way to make format null. It should be something specific, not just abstract value.
https://rollupjs.org/guide/en/#outputformat

**Comment by lukastaegert** [comment]
The question is, what should happen with your external imports and exports? If there are some, then you need a wrapper of some kind to specify what should happen to them. If you want them to stay imports and exports, just use "esm" as format. If there are none and you do not want wrapper code, again just use "esm" as the format, it has no overhead in that case.

**Comment by leandro-manifesto** [comment]
I would like to suggest reconsidering this.

Right now I'm using Rollup to bundle code for the [Cloudflare Workers environment](https://developers.cloudflare.com/workers/reference/apis) where there is no possibility of importing anything.

Sure I can use the "es" format and carefully control my dependencies so that the generated bundle doesn't contain any import statements, but having a "none" format that could throw an error or something when imports would be generated would be awesome.

**Comment by TrySound** [comment]
@leandro-manifesto Add this and rollup will throw an error if some import is not resolved.
Rollup bundle everything by default. And you need to specify explicitly which modules are external. This gives you the feature for free.
```
export default {
  ...
  onwarn(warning) {
    throw Error(warning.toString())
  }
  ...
}
```

**Comment by FelixZY** [comment]
@TrySound I have a relevant use case:

I'm using [clasp](https://github.com/google/clasp) to develop google apps scripts locally. My script is pretty complex and benefits from being split into multiple files. Google apps scripts does not support imports however, so I'm using rollup to bundle everything before pushing my code.

Since I cannot use imports or e.g. requirejs in google apps scripts, the best I can do is use the `iife` format for my bundle. However, Google apps scripts work by calling named methods in your script and the `iife` output effectively hides these methods.

My current workaround is manually removing the `(function() {` and `})()` parts before pushing but it would be nice to have this out-of-the box. I seem to recall [critic](https://github.com/jensl/critic)'s plugin system doing something similar so the "general" use case might be plugin development.

**Comment by ankeetmaini** [comment]
> @TrySound I have a relevant use case:
> 
> I'm using [clasp](https://github.com/google/clasp) to develop google apps scripts locally. My script is pretty complex and benefits from being split into multiple files. Google apps scripts does not support imports however, so I'm using rollup to bundle everything before pushing my code.
> 
> Since I cannot use imports or e.g. requirejs in google apps scripts, the best I can do is use the `iife` format for my bundle. However, Google apps scripts work by calling named methods in your script and the `iife` output effectively hides these methods.
> 
> My current workaround is manually removing the `(function() {` and `})()` parts before pushing but it would be nice to have this out-of-the box. I seem to recall [critic](https://github.com/jensl/critic)'s plugin system doing something similar so the "general" use case might be plugin development.

Can do something like this to expose your dependencies outside of iife.


```js
// dep1.js
export default '1';
```

```js
// dep2.js
export default '2';
```

```js
// input.js
import one from './dep1';
import two from './dep2';

export default { one, two }
```

```js
// rollup.config.js

module.exports = {
  input: 'input.js',
  output: {
    format: 'iife',
    name: 'AwesomeModule',
    dir: 'output',
  },
  plugins: []
};
```

The output comes as 

```js
var AwesomeModule = (function () {
  'use strict';

  var one = '1';

  var two = '2';

  var input = {
    one, two
  };

  return input;

})();
```

You can now do `AwesomeModule.one` or `AwesomeModule.two`. Replit repl here https://replit.com/@AnkeetMaini/rollup-expose-iife#output/input.js

**Comment by FelixZY** [comment]
@ankeetmaini This does not work as Google Apps Script is unable to find any function declarations in the code.

![Screenshot from 2021-11-18 10-14-08](https://user-images.githubusercontent.com/2656517/142386145-c9e86c41-3eba-4359-ad79-0f79c3a993f5.png)

Note the greyed out "Run" and "Debug" buttons as well as the greyed out "No functions" dropdown menu.

**Comment by TrySound** [comment]
You can remove explicit exports, use commonjs output and disable treeshaking so these methods wouldn't be removed.

**Comment by FelixZY** [comment]
Sorry, that's my bad. Please see this example instead. GAS is able to recognize the `main` method as it is defined at the top level, but not `AwesomeModule.abc()` since `abc()` is no

![Screenshot from 2021-11-18 12-49-24](https://user-images.githubusercontent.com/2656517/142410344-2b61b156-47f3-45c4-8a57-43d267a87c34.png)
t.

**Comment by lukastaegert** [comment]
So does your last example work or does it not? Because that looks like you could do this by simply concatenating the last three lines. Otherwise, tree-shaking is indeed a problem: How would your "none" format know what to keep and what to remove if your top-level functions indeed are equivalent to exports.
If you disable tree-shaking, you could also use ESM as your format.

**Comment by FelixZY** [comment]
Actually, yes, my last example does work. Concatenating the last the lines as @lukastaegert suggests does solve the problem (and a bit more elegantly imo). Could generation of such a `main` method be standardized as an output option perhaps? Something like

```js
output {
  format: 'iife',
  entrypoint: 'abc',
}
```

or

```js
output {
  format: 'iife',
  entrypoints: {
    main: 'abc',
    test: 'runTests'
  },
}
```
