### ISSUE TITLE
Allow plugin transforms to only return AST

### ISSUE THREAD

**Issue by FND** [rollup/rollup#3146]
### Expected Behavior / Situation

Transform hooks accept an AST without an accompanying code string:

```javascript
transform(code, id) {
    let ast = this.parse(code);
    ast = rewrite(ast);
    return ast;
}
```

### Actual Behavior / Situation

As I understand it, Rollup primarily expects a code string, accepting an additional AST only as an optimization to avoid redundant parsing in subsequent plugins.

```javascript
transform(code, id) {
    let ast = this.parse(code);
    ast = rewrite(ast);
    return {
        code: escodegen.generate(ast),
        ast
    };
}
```

From a plugin author's perspective, having to serialize the AST seems oddly redundant - assuming Rollup itself also performs AST modifications, generating code at the end.

(It's not actually clear to me whether Rollup expects the original or the modified AST here.)

### Modification Proposal

Extend plugin transforms' API to optionally return an AST instead of code, as described above.

**Comment by lukastaegert** [comment]
I agree that there are some optimizations possible in this area, to me however it is unclear how your suggestion could work out. Rollup heavily relies on the AST being accompanied by a matching code string because it is that string that Rollup will be doing transformations on to generate the output, not the AST. The AST is just giving markers as to where nodes start and end. There is no logic within Rollup to regenerate the source from an AST, which would probably mean pulling in a huge library to do just that, which at least I would not be happy about. Also if a plugin is not the last plugin to implement `transform`, subsequent plugins will also need the source to work with.

**Comment by FND** [comment]
> There is no logic within Rollup to regenerate the source from an AST

In that case, my assumption above was simply wrong: I hadn't expected all of Rollup's own transformations to be possible with just [magic-string](https://github.com/Rich-Harris/magic-string). Of course I agree Rollup shouldn't take on an additional dependency if it's not actually being used internally, so the assumed redundancy does not in fact exist.

Thus I'd consider this issue resolved. Thanks for the explanation.

**Comment by lukastaegert** [comment]
Sure, no problem, I love spreading knowledge here. Note that these kinds of issues are very welcome as they often help add some new perspective to how we do things.
