### ISSUE TITLE
Treeshaking can produce invalid syntax

### ISSUE THREAD

**Issue by TehShrike** [rollup/rollup#3158]
- Rollup Version: 1.23.1
- Operating System (or Browser): macOS
- Node Version: 12.8.1

### How Do We Reproduce?

[REPL reproduction](https://rollupjs.org/repl/?version=1.23.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZvcihjb25zdCUyMHdhdCUyMGluITAlMkNmYWxzZSljb25zb2xlLmxvZygnd2F0JyklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

[Github repo with reproduction](https://github.com/TehShrike/rollup-treeshaking-issue-repro)

### Expected Behavior

The output should be valid parseable JS.

### Actual Behavior

The lack of a space between the `in` and the next line causes Rollup to output invalid syntax when the `!0,` is removed.

### Other notes

Setting `treeshake: false` in the Rollup config and running the build will produce valid syntax.

I ran into this issue in the wild when importing `@auth0/auth0-spa-js`, which contains this kind of code (search <https://unpkg.com/@auth0/auth0-spa-js@1.3.0/dist/auth0-spa-js.production.js> for "`for(Be in!0`").

**Comment by lukastaegert** [comment]
Thanks for finding this. This lead me to look for similar cases and I compiled this list:
https://rollupjs.org/repl/?version=1.23.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMCUyMyUyMGRpZmZlcmVudCUyMHNpbXBsaWZpZWQlMjBleHByZXNzaW9ucyU1Q24lNUNuJTJGJTJGJTIwc2VxdWVuY2UlNUNuZm9yKGNvbnN0JTIwd2F0JTIwaW4hMCUyQ2ZhbHNlKWNvbnNvbGUubG9nKCd3YXQnKSU1Q24lMkYlMkYlMjBjb25kaXRpb25hbCU1Q25mb3IoY29uc3QlMjB3YXQlMjBpbiEwJTNGZmFsc2UlM0FmYWxzZSljb25zb2xlLmxvZygnd2F0JyklNUNuJTJGJTJGJTIwbG9naWNhbCU1Q25mb3IoY29uc3QlMjB3YXQlMjBpbiEwJTI2JTI2ZmFsc2UpY29uc29sZS5sb2coJ3dhdCcpJTVDbiU1Q24lMkYlMkYlMjAlMjMlMjBkaWZmZXJlbnQlMjBzdXJyb3VuZGluZyUyMGV4cHJlc3Npb25zJTVDbiU1Q24lMkYlMkYlMjBmb3IlMjBvZiUyMGV4cHJlc3Npb24lNUNuZm9yKGNvbnN0JTIwd2F0JTIwb2YhMCUyNiUyNmZhbHNlKWNvbnNvbGUubG9nKCd3YXQnKSU1Q24lNUNuJTJGJTJGJTIwcmV0dXJuJTIwZXhwcmVzc2lvbiUyQyUyMGFscmVhZHklMjB3b3JraW5nJTVDbmZ1bmN0aW9uJTIwdGVzdCgpJTdCJTVDbiUyMCUyMHJldHVybiEwJTNGZmFsc2UlM0FmYWxzZSUzQiU1Q24lN0QlNUNuY29uc29sZS5sb2codGVzdCgpKSU1Q24lNUNuJTJGJTJGJTIweWllbGQlMjBzdGF0ZW1lbnQlMkMlMjBhbHJlYWR5JTIwd29ya2luZyU1Q25mdW5jdGlvbiUyMCp0ZXN0MigpJTdCJTVDbiU1Q3R5aWVsZCEwJTNGZmFsc2UlM0FmYWxzZSU1Q24lN0QlNUNuY29uc29sZS5sb2codGVzdDIoKSklNUNuJTVDbiUyRiUyRiUyMHRocm93JTIwc3RhdGVtZW50JTVDbmZ1bmN0aW9uJTIwdGVzdDMoKSU3QiU1Q24lMjAlMjB0aHJvdyEwJTNGZmFsc2UlM0FmYWxzZSUzQiU1Q24lN0QlNUNuY29uc29sZS5sb2codGVzdDMoKSklNUNuJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

As it turns out, a similar issue has already been identified and fixed for return and yield expressions which I will extend to the other ones. Apparently, await binds so strongly to its argument that there is nothing to be fixed at the moment.

**Comment by TehShrike** [comment]
Radical 💯
