### ISSUE TITLE
Code coverage in rollup based project.

### ISSUE THREAD

**Issue by ayushmad** [rollup/rollup#319]
Hi,
Thanks a lot for the effort. The project is really amazing.
I had a question about possible support for a code coverage.
I am writing a small library using rollup. For unit testing I used something like d3 test infrastructure and created a loader which uses rollup, which imports a specific test file(after being rolled up) and the test cases run on that.
Now I was proceeding to add code coverage to my test setup. I was planning to use a istanbul and programmatically instrument the rolled up code before injecting into the test cases. 
However this gives skewed code coverage results.
Consider this example:

``` javascript
// fileA.js
export function Hello() { console.log("Hello" };


// fileB.js [File under test]
import { Hello } from './fileA.js'

if (true) { 
   Hello();
}
else { 
   console.log('Hi');
}
```

My loader code looks like.

``` javascript
rollup.rollup({entry: 'fileB.js' }).then(function(bundle) {
       code = bundle.generate({format: 'cjs' }); // Generate the code
       // Instrumentation code
       code = new istanbul.Instrumenter({}).instrumentSync(code.code, 'fileB.js'); 
      // However this end ups instrumenting both fileA and file B. Even though we are just testing fileB
})
```

Since rollup bundles both the files together instrumentation gets added to both the file and skews the result.
I wanted to check if there is a correct way to do it.
So to solve this I had two questions.
a) Can the rollup javascript API can take a string instead of a entry file (then I can instrument it and pass it) ?  
b) Otherwise I could try to come up with a rollup plugin for instrumenting the modules. I wanted to check if this would be a good idea. If so I can start working on it.   

Thanks for all the help.

**Comment by Rich-Harris** [comment]
> a) Can the rollup javascript API can take a string instead of a entry file (then I can instrument it and pass it) 

It can, but the way that you'd do it is with a transform plugin, so...

> b) Otherwise I could try to come up with a rollup plugin for instrumenting the modules. I wanted to check if this would be a good idea

...this sounds like a fantastic idea! I *think* it would just be a case of doing something like this:

```js
import { createFilter } from 'rollup-pluginutils';
import istanbul from 'istanbul';

export default function ( options = {} ) {
  const filter = createFilter( options.include, options.exclude );

  return {
    transform ( code, id ) {
      if ( !filter( id ) ) return;

      new istanbul.Instrumenter({}).instrumentSync(code, id);
    }
  };
}
```

There may turn out to be a bit more to it than that but I reckon that's the general gist. Thanks for the great idea. If you end up creating it let us know so we can add it to the [wiki](https://github.com/rollup/rollup/wiki/Plugins#list-of-plugins) :grinning:

**Comment by klaascuvelier** [comment]
@ayushmad do you have any update on this? Did you create/finish something?

**Comment by lukeapage** [comment]
You can also use something like remap-istanbul to not only sourcemap your code coverage to the original files,  but it can take multiple coverage results and merge them,  meaning your results wouldn't be skewed (unless you want to disable coverage on something inadvertently being tested?)

**Comment by artberri** [comment]
Hi, I'm trying to implement this but I'm having a problem. 

After trying the @Rich-Harris proposed solution, to create a transform plugin to instrument the code, I can not make it work because the code that arrives to the instrumenter still has the import/export statements (rollup has not replaced them yet) and istanbul/isparta can not instrument the code that arrives. It throws `Unexpected token` when it sees a line with `export` or `import` statement.

In the @ayushmad question's code he's trying to instrument the code after generating the bundle, but doing this it will also instrument the test file code which is not the behavior I want.

While istanbul is not able to instrument ES2015 module syntax I'm not sure if I'm going to be able to isntrument the code properly.

I'm misunderstanding something maybe? Any help on this?

**Comment by artberri** [comment]
Ok, I've solved it just some minutes after asking. Adding `esModules: true` option to the istanbul instrumenter solves the problem because this will add 'sourceType: 'module' option to `esprima`:
https://github.com/gotwarlost/istanbul/blob/master/lib/instrumenter.js#L456

Seems that is working fine now. I'll came back with the whole solution.

**Comment by eventualbuddha** [comment]
@artberri Once you have a working plugin it'd be great to add it to the [Plugins wii page](https://github.com/rollup/rollup/wiki/Plugins). Just post here with a link to the project and we'll take a look.

**Comment by artberri** [comment]
Hi @eventualbuddha you can see the plugin ready here:
https://github.com/artberri/rollup-plugin-istanbul

I have not published it yet to npm because I want to test it a bit more before publishing. But I will be glad if you can take a look at it first to find any possible issue.

**Comment by artberri** [comment]
@eventualbuddha the plugin is ready: https://github.com/artberri/rollup-plugin-istanbul

On `npm`: https://www.npmjs.com/package/rollup-plugin-istanbul

The Wiki is editable so I've just add the plugin also to the wiki page: https://github.com/rollup/rollup/wiki/Plugins

I've already used it (the istanbul plugin) in my most popular project Sidr:
https://github.com/artberri/sidr/tree/rollup

I will merge it to the Sidr master branch soon and I'll create a new release because Rollup.js is really nice, it has removed a lot of rubbish that browserify was adding to it:
https://github.com/artberri/sidr/compare/rollup?expand=1#diff-2214410579b5db97b31968d165413a19

You guys did a really good job with rollup.js, thank you.

**Comment by Rich-Harris** [comment]
Doing some tidying up, looks like we can close this now that rollup-plugin-istanbul exists. Thanks @artberri!
