### ISSUE TITLE
esm definition split across multiple packages

### ISSUE THREAD

**Issue by dlants** [rollup/rollup#3206]
Documentation Is:

- [X] Missing
- [X] Needed
- [ ] Confusing
- [X] Not Sure?

### Please Explain in Detail...
I'm trying to bundle firebase into my app. Recently, firebase started including `.esm.js` files, so it seems that rollup should be able to use those files directly. However, in order to optimize bundle size, firebase splits its functionality into several packages. There's a core `firebase/app` and peripheral packages like `firebase/firestore`, `firebase/auth`, `firebase/storage`, etc... with the idea being that you only include the extensions you intend to use in your application.

When I try to bundle it with rollup, it complains with errors like:
```
storage is not exported by node_modules/firebase/app/dist/index.esm.js
```
I think this is because the `firebase` object is defined in that file, and does not include the `firebase/storage` "extensions" which are specified in `node_modules/firebase/storage/dist/index.esm.js`. How do I get rollup to understand that the esm module definition is augmented in this way?

### Your Proposal for Changes
I'm not sure if this is possible, or if this is a new feature request. However, it seems that since a mainstream project is set up this way, it's probably a use case worth walking users through.

**Comment by lukastaegert** [comment]
This is just not possible. What you are asking is that a module gets additional exports somehow "injected" by another module, and this is simply forbidden by the ES module specification. I would recommend contacting firebase to find out how you are intended to use the extensions. I would assume, that they just expect you to import them separately where you use them.

Alternatively, you could create a simple reexport file and import firebase from there instead of the usual location:

```js
// firebase-combined.js
export * from 'firebase/app/dist.index.esm.js';
export * from 'firebase/storage/dist.index.esm.js';
```

Then it should become a "drop-in" replacement. At the moment, I do not see anything we could do on Rollup side.
