### ISSUE TITLE
What about constantizing strings in final bundle?

### ISSUE THREAD

**Issue by frederikhors** [rollup/rollup#3227]
### Feature Use Case

Many times I have a final bundle with many times the same strings in it.

### Feature Proposal

Is there a way (a plugin maybe, but I can't find one) to make those string a const?

Example:

- my final bundle BEFORE:

```js
console.log("helloImTheString"),console.log("helloImTheString"),console.log("helloImADifferentString");
```

- my final bundle AFTER:

```js
const theFamousString='helloImTheString';console.log(theFamousString),console.log(theFamousString),console.log("helloImADifferentString");
```

Am I brutally wrong?

**Comment by kzc** [comment]
Without compression AFTER would be smaller with a shorter variable name and using `var` instead of `const`. 

With gzip compression BEFORE would be smaller in most cases (dependent on the distance between the string literal occurrences and the dictionary window) so it's not really worth it.  

Probably out of scope for a bundler. A minifier would be better suited for this sort of thing.

**Comment by shellscape** [comment]
You'll find a feature like that in some of the compilers for JS like terser, babel, uglify, etc. That's not going to be something that rollup should really be in charge of. You _could_ create a plugin which goes through the AST looking for similar strings and pulls them out into a const, but that's typically a feature of a minifier or compiler.
