### ISSUE TITLE
Missing "use strict"

### ISSUE THREAD

**Issue by icambron** [rollup/rollup#327]
This could totally be some misunderstanding on my part, but I'd have expected that if I put "use strict" in the input, that it would show up in the output. Simplified example:

```
-> more test.js
"use strict";
class Hello { }
export default Hello

-> rollup test.js
class Hello { }
```

I noticed that some of the other output formatters do stick in there, just not the es6 one. What am I missing?

**Comment by TrySound** [comment]
@icambron I think new standard has strict mode by default.

**Comment by TrySound** [comment]
And es2015 modules is new standard

**Comment by Victorystick** [comment]
It's exactly as TrySound says. Strict Mode is implicit for ES6 modules, but explicitly required for the others.

Since Rollup expects to receive (implicitly strict) ES6 modules as input, it must add the `"use strict"` directive when outputting any non-ES6 format.

So with Rollup, you don't need to write `"use strict"`; your code will always be strict.

**Comment by icambron** [comment]
OK, thanks.
