### ISSUE TITLE
support for TC39 Stage 3 (class fields ...)

### ISSUE THREAD

**Issue by arlac77** [rollup/rollup#3274]
### Feature Use Case
bundle js source containing stage 3 code without transpilation

### Feature Proposal

enable [acorn-stage3](https://github.com/acornjs/acorn-stage3) plugin while reading js source

**Comment by GrosSacASac** [comment]
Does this solve your use case ?

- acorn
- acornInjectPlugins

https://rollupjs.org/guide/en/#danger-zone

**Comment by lukastaegert** [comment]
This would also be my recommendation. We try to be up to date with everything stage-4 and also sometimes add a stage-3 feature, but I am wary of adding ALL stage-3 features by default. The reason is that sometimes, a feature needs more than just adjusting the acorn plugins, so new features should be reviewed in detail, AST types should be adjusted etc. By default, Rollup *should* handle most features out-of-the-box by deoptimizing unknown nodes as much as possible, but there is no guarantee. Also, even stage-3 features can sometimes change.

**Comment by arlac77** [comment]
**acornInjectPlugins** works for me.
Thank You.

```js
import acornClassFields from "acorn-class-fields";

return {
...
acornInjectPlugins: [acornClassFields]
};

```
