### ISSUE TITLE
SyntaxError: Unexpected token default

### ISSUE THREAD

**Issue by mbostock** [rollup/rollup#33]
This may or may not be related to #32. Here’s the test case:

https://gist.github.com/mbostock/d7717d61446600938e47

The problem is:

```
var default = Baz(baz);
    ^^^^^^^
SyntaxError: Unexpected token default
```

**Comment by caridy** [comment]
right, `default`` is a reserved keyword, my recommendation is to use a custom generated token when creating a local binding for the default export https://gist.github.com/mbostock/d7717d61446600938e47#file-build-js-L7

**Comment by mbostock** [comment]
Yes, Rollup should not be generating a `var default`.

**Comment by Rich-Harris** [comment]
Ordinarily default exports are given a 'suggested' name by the first encountered module that imports them (i.e. `import foo from './foo'` causes the default export from foo.js to be named `foo`). In this case the `Baz` function is included (because functions are deemed capable of mutating their arguments - eventually need to get a bit more sophisticated about this) but because the default export isn't used, there's no suggested name. Rollup accounts for this scenario in 0.8.3.
