### ISSUE TITLE
Update minimum required Node version to Node 10

### ISSUE THREAD

**Issue by shellscape** [rollup/rollup#3320]
### Expected Behavior / Situation

_Not applicable_

### Actual Behavior / Situation

Node 8 has exited LTS and is now end-of-life. https://nodejs.org/en/about/releases/

### Modification Proposal

I propose that Rollup remove official support for Node 8. This would involve:

- An announcement
- Updating documentation
- Updating plugins (and their documentation)
- Updating `engines` in package.json
- Updating CI configurations
- Bumping a major version

Please share thoughts and reactions. Please use the 👍  reaction button (top right of this post) to show support for this. Please comment and/or use other reactions to show support _against_ this proposal.

**Comment by lukastaegert** [comment]
We definitely want this. However I think it would be waste of a major version to do this separate from the other pending breaking changes so I updated the Rollup 2.0.0 project and added it: https://github.com/rollup/rollup/projects/2

I also adjusted the title so that it looks better in the Project view.

I think once the current batch of PRs is reviewed and hopefully released, I would be free to tackle some of the 2.0.0 projects. My suggestion would be to create PRs for the 2.0.0 release against a separate 2.0.0 branch that we merge to master once all breaking changes have been collected. We could also do preview releases (i.e. 2.0.0-0, 2.0.0-1) for each PR merged to the 2.0.0 branch as long as we do not move the "latest" tag.

**Comment by shellscape** [comment]
The nice thing about major versions is that there are a lot of numbers 😄  I tend to lean more towards keeping everything current than relying on scheduling or task lists when it comes to Node versions - especially so when end of life is reached on a version. Life comes at us fast, and there's no telling how long it'll take to get through that batch.

Waiting to update will also hold up the plugins repo and the 22 core plugins.

**Comment by lukastaegert** [comment]
Every major version causes unnecessary friction for users, but that’s just my opinion. It is not that updating minimum requirements will enable us to do anything fantastic that could not wait for a few weeks. The code is already using async await. I wonder why this is blocking the plugins, though. There is no reason to have a hard dependency here.

**Comment by shellscape** [comment]
I would agree that it does cause friction for some users. That can be mitigated by good communication, which I think we definitely have.

We adopted a policy for the plugins that we follow rollup core as the source of truth for `engines`. It makes sense - if rollup core supported Node 8 but a plugin didn't, that'd be kind of silly. Wouldn't want to hamstring users of Node 8 while core still supported it.

I'd also agree that a few weeks is no big deal.

**Comment by lukastaegert** [comment]
I'll see it gets high priority now.

**Comment by lukastaegert** [comment]
Solved in rollup@2.0.0
