### ISSUE TITLE
Options hook doesn't have access to warn and error

### ISSUE THREAD

**Issue by shellscape** [rollup/rollup#3330]
### Feature Use Case

Consider this snippet from `@rollup/plugin-node-resolve`:

```js
export default function nodeResolve(opts = {}) {
  const options = Object.assign({}, defaults, opts);
  const warnings = [];

  if (options.only) {
    warnings.push('node-resolve: The `only` options is deprecated, please use `resolveOnly`');
  }

  return {
    options() {
      for (const warning of warnings) {
        this.warn(warning);
      }
    }
  }
```

During plugin setup/init we're checking for a set of valid plugin-specific options. Should we find one that's not quite right, we want to warn or error as soon as possible in the build process, using Rollup's mechanisms so that output is uniform.

### Feature Proposal

Provide a minimal context to plugin hooks for access to `this.warn` and `this.error`.

I understand that `buildStart` has access to both functions, but it doesn't appear as if that's the first step in the lifecycle. We're going for minimal delay.

**Comment by lukastaegert** [comment]
It would be a bit of work to set this up and there is really nothing expensive happening between option and buildStart except that the options are parsed. The big issue here is that the options also include `onwarn`. We do not known before this hook is complete if there is a custom warning handler present and what it does. If a plugin wants to hook into warnings e.g. to display them in a special way, it would miss all warnings from the options hook. I would rather have people use buildStart because that is the first time everything is known.

**Comment by lukastaegert** [comment]
We could provide this.error of course

**Comment by shellscape** [comment]
I think we mark `buildStart` as the right place for this type of thing. It makes sense given the `onwarn` handler, and I hadn't considered that would make for one hell of a whacky paradox.
