### ISSUE TITLE
Use only as bundler (if not already possible) + load to global namespace

### ISSUE THREAD

**Issue by pjebs** [rollup/rollup#3339]
### Feature Use Case

I have a non-standard use case where I need rollup to **only bundle** some npm packages.

1. All I want to do is bundle the npm packages and load it to the **global namespace**, which an independent javascript file will assume it exists.
2. Presumably tree shaking will have to be disabled because rollup will assume that nothing is actually being used in the packages.
3. **`require('electron')`** and **`require('os')`** has to be left alone.
4. It is for a **node.js** application but `cjs format` doesn't work.

```javascript
// File: imports.js

global.XMLHttpRequest = require('xhr2');

global.main = {
    ipcMain: require('electron').ipcMain,
    uuidv4: require('uuid/v4'),
    os: require('os'),
}
```

**I can't find an example that shows that it can be done.**

```javascript
import builtins from "builtin-modules";
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import { terser } from "rollup-plugin-terser";

...
	{
		input: "imports.js",
		treeshake: false,  // Presumably required
		output: {
			file: "imports.out.js",
			format: ?, // what format should it be for just loading to global namespace
			sourcemap: false
		},
		external: ["electron", ...builtins], // require('electron') should be left alone
		plugins: [
			resolve(),
			json(),
			commonjs(),
			terser({ecma: 6})
		]
	},
```

### Feature Proposal

1) Ability to do plain bundling and leave some `require()` statements in place. 
2) Load to global namespace

**Comment by lukastaegert** [comment]
If your files explicitly create global variables by assigning them to `global`, then this is a side-effect that Rollup will recognize so you can and probably should keep treeshaking enabled.

You did not specify, though, in how far `cjs` output does not work. Without detailed information here, there is nothing really we can do. My best guess is that since your code is apparently written as CommonJS, you should play with the options of rollup-plugin-commonjs: https://github.com/rollup/rollup-plugin-commonjs

Not that it is NOT recommended to write your sources as CommonJS if you can avoid it! Rollup will produce suboptimal results if the sources are CommonJS as rollup-plugin-commonjs will need to translate everything to ES modules first, which is an imprecise science with some overhead and does not work for every scenario, e.g. conditional require statements and circular dependencies.

Also I would try without `terser` first just to be sure nothing is messed up there.
