### ISSUE TITLE
@rollup/plugin-typescript ignored imports in output

### ISSUE THREAD

**Issue by vdegenne** [rollup/rollup#3341]
- Rollup Version: 1.29.0
- Operating System (or Browser): Fedora 31/Chrome (last)
- Node Version: 13.6.0

### How Do We Reproduce?
- install `koa-bodyparser`, `@types/koa-bodyparser`, `rollup` and typescript plugins
- then create the files
*input.ts*
```typescript
import bodyParser = require('koa-bodyparser');
```
*rollup.config.js*
```javascript
import typescript from '@rollup/plugin-typescript';

export default {
  input: 'input.ts',
  output: { file: 'output.js', format: 'cjs' },
  plugins: [typescript()]
}
```

### Expected Behavior
*output.js*
```javascript
'use strict';
const bodyParser = require('koa-bodyparser');
```
output of vanilla typescript.

### Actual Behavior
```javascript
'use strict';
```
generates an empty file.

**Comment by lukastaegert** [comment]
This is quite likely an issue for rollup-plugin-typescript so please in the future open plugin issues in the appropriate repository: https://github.com/rollup/plugins

Still some points to consider:
- TypeScript does not actually appear to emit anything for an `import = require` if you do not use it: https://www.typescriptlang.org/play/index.html?module=1#code/JYWwDg9gTgLgBDApgZ3gXjlRBHArsLACgHIlViBKAbgCgaB6euXAOwGMIQREX4YI4AQzYxcggDbiAnnGDtxuACaIEACxWhIsBkw4tkEcYgB04iAHNCZGBSA
- TypeScript does also not emit anything when targeting ES modules: https://www.typescriptlang.org/play/index.html?module=5#code/JYWwDg9gTgLgBDApgZ3gXjlRBHArsLACgHIlViBKAbgCgaB6euXAOwGMIQREX4YI4AQzYxcggDbiAnnGDtxuACaIEACxWhIsGhxbII4xADpxEAOaEyMCkA
  This is a problem because Rollup without any other plugins only understands ES modules. Luckily, TypeScript lists some alternatives. As a rule of thumb, use ES module imports and not this weird TypeScriptism when using Rollup. Alternatively, you can target CommonJS modules with TypeScript and use rollup-plugin-commonjs, but this will produce suboptimal results.
- Even if the import was emitted by TypeScript, Rollup would render it a an empty import because you do not use `bodyParser`

**Comment by vdegenne** [comment]
Thanks for your feedback and sorry for missing the right section.
Also my code fulfills all the points you mentioned above. My code makes use of `bodyParser`, it targets `cjs` and even if I use ES module syntax for the import the problem persists. So I'll open the issue in the right place as it appears to be a bug and yesterday I spent so much time trying to make it works. According to `@types/koa-bodyparser` `import ... =` is the version to use.
