### ISSUE TITLE
typescript: export type MyType "is not exported by a module".

### ISSUE THREAD

**Issue by houd1ni** [rollup/rollup#3351]
Reexporting typescript causes error that not cached by typescript and vscode.
Tried to repl it, but repl doesn't support typescript.

![image](https://user-images.githubusercontent.com/7501201/72786494-c6d97380-3c3e-11ea-998a-238ddb994c0b.png)

causes (log is a bit simplified to only src folder and depA and depB from real files):

```
[!] Error: 'Num' is not exported by src\depB.ts
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src\depA.ts (1:9)
1: export { Num } from './depB'
            ^
Error: 'Status' is not exported by src\depB.ts
    at error (C:\Users\pinke\Music\agg\node_modules\rollup\dist\rollup.js:5330:30)
```

If the error isn't easily reproducible, I'll make an isolated repo.

- Rollup Version: 1.29.1
- Operating System (or Browser): win10 latest
- Node Version: 13.2.0

### Expected Behavior
rollup sees the exported type.

### Actual Behavior
it does not.

**Comment by lukastaegert** [comment]
Rollup does not support TypeScript, so you should file the issue in https://github.com/rollup/plugins/tree/master/packages/typescript rather than Rollup core.

Moreover, the error mentions a file `./depB` and a variable `Status`, none of which are part of the files you listed. Thus your information is incomplete or at least inconsistent, which you should probably fix before re-filing the issue.

**Comment by houd1ni** [comment]
@lukastaegert Status was the original type's name. I've fixed the name here.

**Comment by houd1ni** [comment]
@lukastaegert  Just found it there https://github.com/rollup/plugins/issues/71
Thanks!
