### ISSUE TITLE
Redundant files with only import statements are produced in 1.30.1

### ISSUE THREAD

**Issue by philipwalton** [rollup/rollup#3358]
- Rollup Version: 1.30.1
- Operating System (or Browser): N/A
- Node Version: 10.17.0

### How Do We Reproduce?

[REPL Link](https://rollupjs.org/repl/?version=1.30.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmZvbyU3RCUyMGZyb20lMjAnLiUyRmxpYi5qcyclM0IlNUNuJTVDbmFzeW5jJTIwZnVuY3Rpb24lMjBtYWluKCklMjAlN0IlNUNuJTIwJTIwZm9vKCklM0IlNUNuJTVDdGF3YWl0JTIwaW1wb3J0KCcuJTJGZHluYW1pYy5qcycpJTNCJTVDbiU3RCU1Q24lNUNubWFpbigpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybGliLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwZm9vKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCdmb28oKScpJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBiYXIoKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5sb2coJ2JhcigpJyklM0IlNUNuJTdEJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmR5bmFtaWMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwbGliJTIwZnJvbSUyMCcuJTJGbGliLmpzJyUzQiU1Q24lNUNubGliLmJhcigpJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

### Expected Behavior

In the above build, I'd only expect two files to be produced:

1. main.js
2. dynamic-XXXX.js

### Actual Behavior

Three files are produced:

1. main.js
2. main-XXXX.js
3. dynamic-XXXX.js

And `main.js` has no code in it except for code that imports `main-XXXX.js`, making having both files redundant.

In addition, since I configure my Rollup build to _not_ include hashes in the entry or chunk filenames, this is problematic for me because I get duplicate files (technically, Rollup names it `main2.js`, but that's not what I want either).

Ideally, Rollup could detect that all the contents of `main-XXXX.js` could be dropped into `main.js` so I'd just have two output files with predictable names.

**Comment by lukastaegert** [comment]
The reason is that Rollup needs to add additional exports to your file, tainting its export signature, so Rollup is creating a facade entry to fix that. There is no logic yet to handle the case when there are no exports differently, and I am not sure this is how I want to play it. The situation is that you do not care about exports of an entry point when you want to place it in a script tag, so maybe we will add a way to specify we do not care about the exports of an entry point. For developing libraries, maintaining proper export signature is usually important though, you do not want to leak private stuff.

**Comment by philipwalton** [comment]
I see, and I agree that makes sense in the case of a library. In my case it'd be great to have an option to not preserve entry point export signatures.

Another related issue that I'd be curious to get your take on: I noticed the above because I have a custom plugin that fails the build if it detects any duplicate chunk names—since I don't use chunk hashes, I don't want any duplicate names. Of course, when this facade entry is added (with the same name), I can't currently distinguish that from the case where I accidentally name two dynamic entry points with the same filename (perhaps in different folders or different npm modules).

Any thoughts on how to distinguish the above two cases (one where I'd still want to fail the build, and one where I'd be OK with the autogenerated `main2` filename)?

**Comment by lukastaegert** [comment]
> Another related issue that I'd be curious to get your take on

We are really getting side-tracked here, but I would look at the `name` property of chunks in the bundle object of the `generateBundle` hook. Even though the file names are deduplicated, `name` is not, so you could use it to detect conflicts.

**Comment by lukastaegert** [comment]
Back to the original issue, as I agree this should be improved but I would very much like some feedback. First there are two ways of doing it:
1. Allow the user to specify entry-by-entry if we are interested in a correct export signature
2. Add a single option to switch it for all entries

I am leaning very much to 2. as this would usually be the difference between building a library and bundling for the web. Should there ever be demand for 1., we could make the option e.g. accept an array of chunk names instead of a boolean.

Next, what should the option be called and what should its precise effects be?
From an implementation perspective, the most difficult version would be one where the user could have exports in the file with names that need to be preserved, mixed with additional exports they do not care about.

However when bundling for the web, as I see it I am never interested in having exports of my entries preserved. But it might be possible the entries have exports because a dependent module wants to import something from an entry (even though this would mean a circular import).

So what I would like to implement is an option that
1. Does not include exports of entry points by default unless they are used internally
2. Does not create facades for entry points if new exports are added
3. Will minify any exports of entry points

The option itself should be a boolean but of course by default, facades should be created. To make it discoverable for users, I would add a warning to the case where Rollup would create a facade for an entry without exports stating that "this is likely not what they want and they should specify a value for that option", including a web link. If the option is set to either `true` or `false`, the warning is skipped (important in case they DO want a facade for a chunk without exports).

So what should it be called, and should it be a positive or negative option? Suggestions welcome! But of course any other feedback welcome as well.

**Comment by lukastaegert** [comment]
Names that come to my mind:
- `preventEntryFacades` (this would not explain that exports are not preserved, though)
- `ignoreEntryExports` (slightly better I guess)
- `preserveEntryExports` (the inverse, does not feel too bad to me)
- `preserveEntrySignature` (might be too technical)
- …

**Comment by LarsDenBakker** [comment]
I think in some cases people want to be able to make a choice between performance/ease of use and purity. Adding some minified and/or random exports to an entrypoint might not be a realistic issue for some people, even for library authors. I have a use case myself where I'm bundling a large ecosystem with a lot of entrypoints, which ends up creating quite a lot of chunks.

For shipping things in the browser it's an easier choice, although I do hope some day we are able to access the module object from a script tag. 

If possible, I'd have two optionts. One for configuring whether to add exports to the entrypoint(s) or create separate chunks, and one for configuring whether to remove the exports from the entrypoints and saving some bytes.

**Comment by lukastaegert** [comment]
I see. Do you think it is necessary to make this configurable on individual entry level or would it be enough to have an option that configures all entry points the same? With your input, I am thinking about a three-state flag (e.g. false, true, or a specific string for the third state, similar to the `moduleSideEffects` option)
1. Do not include exports and we do not care about explicit signatures (the web bundling mode)
2. Include exports and keep their names, but do not care about tainting signatures (the case you outline. There may still be facades created e.g. when everything ends up in the same chunk for some reason but you have more than one entry)
3. The current behaviour

The reason why I would want to mix the two is because they are not completely separate: It does not make sense to maintain a facade if you do not include all exports. It is more like different levels of compliance to me. Also this would be additional friction to web bundling as you would always need to set two options.

Again, name suggestions welcome.

**Comment by LarsDenBakker** [comment]
A three state flag seems like a good option. 

For the use cases I can think of, a project wide configuration is enough. It would be nice if we dont close the door on adding it later though, maybe through plugins. 

`preserveEntryExports` seems like a good name to me

**Comment by lukeed** [comment]
I think it'd be safe to apply a bundle-wide configuration only, at least to start. I think it makes most sense to place it as an `output.exports` key that accepts an enum of string options  _or_ as an `output.facade: boolean` key. I'm leaning towards `output.facade`

```js
output: {
  format: 'esm',
  dir: 'build/esm',
  facade: false
}
```

This would also make it possible to apply a different `output.facade` values when outputting multiple formats:

```js
output: [{
  format: 'esm',
  dir: 'build/esm',
  facade: true
}, {
  format: 'cjs',
  dir: 'build/cjs',
  facade: false
}]
```

**Comment by philipwalton** [comment]
Sorry @lukastaegert, somehow I've been missing update notifications for this issue!

I think my preference is slightly toward `preserveEntrySignature`, and here's why. If I'm understanding the issue correctly, under normal usage (for both apps and libraries) the issue is not that exports are removed, it's that additional exports are collapsed into a single module. To me, `preserveEntryExports` means: _don't modify my existing exports in any way_, but it doesn't necessarily mean: _don't add new exports to this module_. Whereas `preserveEntrySignature` means: _don't add, remove, or modify any exports_.

That being said, I think with proper docs, either `preserveEntrySignature` or `preserveEntryExports` would be fine.

> I am leaning very much to 2. as this would usually be the difference between building a library and bundling for the web. Should there ever be demand for 1., we could make the option e.g. accept an array of chunk names instead of a boolean.

Yes, I agree. I don't see a strong use case for customizing this option per-entry.

**Comment by LarsDenBakker** [comment]
@lukastaegert I wonder if this behavior could be implemented easily in a plugin, at least until it's implemented in rollup itself?

**Comment by lukastaegert** [comment]
I do not see how, unfortunately. I hope I can fix this soon.

**Comment by lukastaegert** [comment]
So, unless something pressing comes in, I decided this is finally next on my list.

**Comment by lukastaegert** [comment]
Here is a working draft PR to play around with: #3498

**Comment by lukastaegert** [comment]
Per-output configuration will not be possible yet as this would require a major refactoring in Rollup's architecture, namely to move the chunking from the build to the output generation phase. This will come at some point, though.

**Comment by LarsDenBakker** [comment]
Is there a way to install PR to test out in a project?

**Comment by lukastaegert** [comment]
It appears the comment from Rollup-Bot is easily overlooked? 😉
https://github.com/rollup/rollup/pull/3498#issuecomment-614248113
