### ISSUE TITLE
Rollup and NodeJS: Error: 'existsSync' is not exported by node_modules/rollup-plugin-node-builtins/src/es6/empty.js

### ISSUE THREAD

**Issue by kopax** [rollup/rollup#3364]
I am trying to build my rollup node script:

    Error: 'existsSync' is not exported by node_modules/rollup-plugin-node-builtins/src/es6/empty.js

I have created a package to store my global rollup configuration: https://github.com/rollup-umd/rollup/blob/master/src/index.js#L65

I want it to support WEB, Node and Web+Node using a simple configuration switch (yeah rollup should not change so much)

I have tried to passe the following node resolve options to `createConfig`, but I still have this error: 

```js
{
  nodeResolveOptions: {
    browser: false,
    preferBuiltins: true,
  },
}
```

How can I change my `createConfig` in order to support WEB/Node and Web+Node. ?

**Comment by shellscape** [comment]
_If you are sure this is a bug, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by JJ** [comment]
I know this is closed, but I still would like to know the answer, if you found it.
