### ISSUE TITLE
Isn’t jsnext:main too broad?

### ISSUE THREAD

**Issue by rauschma** [rollup/rollup#337]
Wondering: it seems like locking down what features are allowed for code pointed to by `jsnext:main` would be useful. Wouldn’t (e.g.) `es2015:main` be a better name? Otherwise, there is little that tools can rely on.

**Comment by eventualbuddha** [comment]
I've been thinking about this too lately. The first thing that came to mind that might be sane is that all other ECMAScript features used (e.g. classes, template strings, etc) should run natively in whatever engines match the [`engines` field](https://docs.npmjs.com/files/package.json#engines) in package.json. Thoughts?

**Comment by rauschma** [comment]
That property does indeed seem relevant. There needs to be a way to provide several versions of the same library: one for ES6, one for Node.js < v4, etc. I don’t think `engines` can do that. But it’d be nice if it could.

**Comment by rauschma** [comment]
Additional thought: whatever mechanism is used to provide multiple versions of `main`, it should work for `bin`, too.

**Comment by rauschma** [comment]
[npm ecosystems](http://blog.npmjs.org/post/94662089625/the-future-of-the-npm-website-lets-map-this#ecosystems) are another option worth looking at. But, AFAICT, they don’t allow you to use the same package name for different ecosystems.

**Comment by Rich-Harris** [comment]
Some more discussion of this issue [here](https://github.com/jsforum/jsforum/issues/5). My personal answer is that `jsnext:main` should only refer to `import` and `export`, because otherwise packages end up having to transpile the source code of their dependencies, which results in chaos. But there's no answer that doesn't involve compromise somewhere.

**Comment by callumlocke** [comment]
Is it too late to change the name to something more precise like `main:esmodule`? I think the name `jsnext` makes it sound more complex/threatening than it is!

Also, how about having a separate Github repo for documenting and discussing it as a proposed package.json extension?

**Comment by mstade** [comment]
I think `jsnext:main` is a bad idea, and instead I propose you recommend people to use version identifiers instead.

ES2015 is ratified, it's **done**. Everyone *should* publish ES2015 modules because anything else is legacy. However, legacy unfortunately rules the world until engines catch up. If you don't publish legacy output *alongside* your new and shiny output, may people will probably just ignore your work. Thus, let's take it as self-evident that for some unknown (but hopefully short) time it's a necessity to publish both ES5 and ES2015 modules.

The proposed field `jsnext:main` is too broad. One day, what we call `jsnext` now will be `jslegacy`, and so introducing that field is really just introducing a maintenance problem, because `main` isn't going away and unless *everyone* gets on board with using new fields whenever new tech comes along it's just never going to work.

Instead of inventing a new field in package.json, we should use `version`. It is designed to demarcate different versions of packages anyway, so why not introduce some additional data to show which version should be used in which context? [Semver] allows for prerelease identifiers, and metadata, so one of those could be used. Metadata should not be used for determining version precedence however, so that will pose a problem in trying to publish the same version just with different metadata. Prerelease identifiers have a *lower* precedence than versions without the identifier, so that matters too.

[semver]: http://semver.org

Given that, what might it look like? Well, if one considers ES2015 to be the wave of the future, and ES5 to be legacy and soon to go away, then I'd say using a prerelease identifier to note the *legacy* version would make sense, something like `1.0.0-es5`. That way, whenever someone does `npm install your-module` they'd get the modern ES2015 version. It may not be what they want, but it's the future man! To alleviate this (hopefully very) temporary problem, library authors should take care to put something like this in their READMEs:

> # Installation instructions
> ## ES2015
> To install the ES2015 version of this module, just use npm as you would install any other package:
> ```sh
> npm install this-package
> ```
> ## ES5 version
> To install the ES5 version of this module, please append the `-es5` identifier to the version
> ```sh
> npm install this-package@$(npm view this-package version)-es5
> ```

Yeah, it's not gonna win any beauty pageants, but temporary problems don't need pretty solutions. (I'd have hoped there was a semver range you could use, like `*-es5` or something, but apparently [that's not quite cool](https://github.com/npm/node-semver#prerelease-tags).) N.B.: the above assumes that the author always includes an `-es5` version whenever a new version is published. If they don't, they'd have to pin the version in their docs.

(Ab)using pre-release identifiers like this would also mean *actual* prerelease identifiers would have to be handled. I.e. something like `1.0.0-beta.0` would have to become `1.0.0-beta-es5.0` or something to that effect. It doesn't really matter what the convention is, so long as it's easy to follow, non-ambiguous, and well documented.

---

The flip side of this discussion is: how does rollup know whether a package is in fact ES2015 or not? It can't just trust that a missing `-es5` identifier means the package is ES2015 – after all most packages out there *don't* opt in to this version abuse I'm suggesting. How about using heuristics though?

If rollup is explicit about treating versions with an `-es5` (verbatim) identifier as ES5 packages, then that's an early exit for rollup – it can just assume that package should be left out of the bundle, and let the runtime figure it out, or whatever rollup decides to do.

For anything else, something like this might work:

1. Are there `export` statements?
  - yes: es6 module – **rollup**
2. Are there references to global `module.exports` or `exports`?
  - yes: commonjs module – **ignore**
3. Is the module being imported for side effects? I.e. `import "some-module"`?
  - yes: **rollup**
4. None of the above?
  - yes: **ignore**

By **ignore** I mean do whatever early exit means, as mentioned earlier. There are probably more cases, but I'm sure it wouldn't be rocket surgery to try and figure them out.

In any event, I think inventing new package.json fields is probably the wrong way to go, for what is really a version demarcation issue.

Just some thoughts.

**Comment by eventualbuddha** [comment]
One issue with publishing a package with `main` pointing to a file using ES2015 is that recent node versions support many features, like classes and template strings, but not `import` and `export` statements. I think that's likely to remain the case for some time, but I admit to not being up to date on any recent (~6mo) developments in that regard.

**Comment by mstade** [comment]
@eventualbuddha the tl;dr of that is that until V8 supports ES2015 modules, node will continue to only support commonjs. The crap side of that is that V8 probably won't see ES2015 module support until the [Loader spec][1] is relatively stable – this will take some time. It's still a temporary problem; not as in it'll be fixed within the next couple of weeks, but it might within the next year.

[1]: http://whatwg.github.io/loader/

Even if node supports *some* ES2015 features, it still doesn't take away from the idea that you can publish multiple versions that target different language specs, because node (and most any other engine) supports *all* of ES5. My reasoning isn't so much about whether anything can actually run the ES2015 version *right now*, but rather it's about making the assumption that sooner or later, most engines *will*, and getting into the habit of producing ES2015 versions as a default.

Of course, it can be argued that the inverse would make more sense – provide ES2015 versions under a `-es2015` identifier or something similar – but the only thing you'd do then is introduce a problem down the line when you will have to decide what your threshold for making the switch is. It's not by any means an insurmountable issue, and could probably be hand-waved away by simply incrementing the major version, but it's a bit odd none-the-less I think.

**Comment by rauschma** [comment]
@mstade Completely agree with your assessment of the problem. W.r.t. the solution, `engines` feels like a really good choice: If you currently deploy code with ES6 features that only Node.js v5 supports, you could, in theory, also transpile it so that it runs on older engines. The only obstacle is that, AFAICT, you can’t publish the same package (or rather, the same version of a package) multiple times for different engines. Either that should be enabled, or we could go with a “fat binary” approach for uploading (for downloading, the unnecessary bits could be removed if one specifies a directory per engine). Then `package.json` would look as follows:

```
...
"engines": [
    {
        "node": ">=0.10.3 <0.12",
        "main": "./es5/index.js",
        "bin": { "foo": "./es5/bin/foo.js" }
    },
    {
        "ecmascript": "2015",
        "main": "./es2015/index.js",
        "bin": { "foo": "./es2015/bin/foo.js" }
    }
],
...
```

**Comment by mstade** [comment]
@rauschma you can't publish the same version multiple times, no, but you can publish the same version number with different identifiers however – hence the `-es5` suggestion. The fat binary suggestion I'd say is the best possible way to resolve this, but isn't `engines` one of those not-really-quite-a-standard field where different package.json consumers handle it differently? I don't think node really cares, npm does care, but only as an advisory (unless `engineStrict` is also used,) and things like heroku use it to figure out which node version to deploy and would get utterly confused by seeing an array I'm sure.

But your idea of fat binaries is solid, and I'm thinking that there's a way to resolve it by developing a compatibility module which acts as an entry point and selects the right *true* entry point depending on runtime environment. For now, I think that would mean an IIFE that does kind of the inverse of UMD, looking for loaders instead of definitions. Something like this:

```javascript
;(function (global) {
  var document = global.document
    , require  = global.require
    , define   = global.define
    , Loader   = global.Loader

  if (Loader && typeof Loader.import === 'function') {
    Loader.import('main-es2015.js')
  } else if (typeof define === "function" && define.amd) {
    require(['main-amd.js'], function() {})
  } else if (typeof exports !== "undefined") {
    require('main-common.js')
  } else if (document && typeof document.createElement === 'function') {
    var entry = document.createElement('script')
    entry.setAttribute('src', 'main-global.js')
    document.head.appendChild(entry)
  } else {
    // What is this I don't even
    throw new Error('(╯°□°)╯︵ ┻━┻')
  }
})(this)
```

(I don't even know if there's any environment in which that table flipping case would occur...)

I have no idea if that thing would even run, but I hope it gets the general idea across. I.e. look around for various different mechanisms to load the entry point, and then go. In the example, these entry points are all named after their respective formats, but really it could be just two files: `main-es2015.js` for the ES2015 syntax and `main-umd.js` for everything else.

Now, this still would only help with *runtime* environments; rollup would have to get smart in analyzing this kind of file if it is to figure out the ES2015 statically, unless it's denoted some other way. It wouldn't be too difficult to see the pattern and basically look for global `Loader.import` statements and use that as a heuristic, but I'm sure it'd be fraught with pathological cases. We could use `engines`, but given it's this kind of half-orphan field that isn't really that well defined it might be dangerous; at least to redefine it from an object to an array. Something like this could work though:

```json
{
  "engines": {
    "rollup": {
      "main": "main-es2015.js",
      "bin": "bin-es2015.js"
    }
  }
}
```

(Exhange `rollup` for `ecmascript` if you so choose, but potato/tomato I'd say.)

Maybe that's helpful to rollup to find the main entry point (what is it supposed to do with `bin`?) but anyone else will probably ignore it, so the `bin` and `main` of the root object would still have to point to files with the loader boilerplate above. (Easily generated though.) It's effectively the same as `jsnext:main` I suppose, but narrower.

It may just be that `jsnext:main` should really be `main:es2015`. It may seem broad, but it really is much narrower than the ambiguous `jsnext` – the module syntax is unlikely to change again anytime soon, and if it does it will be incremental sugar more than anything. I'd very much doubt we'll see ES2018 come out with a radically new module syntax, given the pain the world's been through with module formats so far and how much thought has actually gone into designing the ES2015 module syntax in the first place. (It really is quite well designed.) This enables people to provide fat packages with both ES5 and ES2015 distributables, and they can choose whether `main` points to the former or the latter. Combined with a loader like the one above then `main:es2015` would pretty much just be advisory to tools like rollup, that can then bypass the runtime loader altogether and head straight for the bacon.

The `engine` field could then be (ab)used by packages that really do care to be strict about what engines they support, in case they don't want to support things (well, let's be honest: node) that don't have ES2015 module support. It wouldn't matter at all for the wild west nature of browser environments, but that's going to be a case of diminishing returns for when ES2015 module syntax adoption hits some breakpoint – i.e. providing universal scripts will be meaningless in a world where there's only five people on an island somewhere that's running legacy engines like they just don't care, piña coladas in hand and all.

Please excuse the rambling and wall of text – this was all basically just a stream of consciousness thing. I hope it helps.

**Comment by eventualbuddha** [comment]
I agree that `jsnext:main` is too broad. Pinning a specific version is probably the right way to go, and `main:es2015` seems as good a name as anything. @Rich_Harris, what do you think?

**Comment by mstade** [comment]
I might be able to find some time in the next few days to do a PR to support `main:es2015`, and build a sample "fat" project which has a universal entry point as `main` which loads the correct file based on runtime environment. It'd be nice to see this end-to-end, and not just for node but for browsers too.

**Comment by Rich-Harris** [comment]
> Instead of inventing a new field in package.json, we should use `version`. It is designed to demarcate different versions of packages anyway, so why not introduce some additional data to show which version should be used in which context?

I'm not sure I agree with this statement – we're not talking about things with different features or bug fixes, we're talking about different manifestations of *the exact same* library. 'Target' would be a better word than 'version', in my view. 

> How about using heuristics though?

Nope nope nope :grinning: That way madness lies. It has to be explicit and unambiguous, or you're going to end up in a sticky situation.

> For now, I think that would mean an IIFE that does kind of the inverse of UMD, looking for loaders instead of definitions

That wouldn't work in a `<script>` soup environment unfortunately, because the library needs to load synchronously.

My feeling is this: if the goal is to encourage library authors to distribute ES6 modules, then pragmatic considerations trump ideological ones:

* creating multiple versions for environments with different feature sets is a wonderful idea, but adds a huge amount of complexity for package authors – the kind of complexity that the sorts of people engaging in conversations like these are liable to underestimate!
* `jsnext:main` is not a great name for what it's being used for, and `main:es2015` probably *is* better, but at this point there's a switching cost involved. If we want to bring people along with us then unilaterally creating a new pseudo-standard without widespread support is guaranteed to add confusion.

Therefore I think we should stay the course with `jsnext:main`, despite its warts.

**Comment by rauschma** [comment]
@Rich-Harris I mostly agree. However, a generic mechanism that can also support ECMAScript versions beyond ES6, later on, would be nice. Furthermore, I frequently write shell scripts in ES6 for Node.js. Having support for ES6 executables, eventually, would be great.

How about this?

```js
"targets": {
  "es2015": {
    main: ...,
    bin: ...
  }
}
```

I’m not sure that would be much more work for package authors that are already using ES6 – they’d simply include both `src` and `build` directories. However, managing packages properly if any package can contain multiple targets will get more difficult.

**Comment by rauschma** [comment]
Related: jspm uses a `package.json` property called `format` which can have the values: `es6`, `amd`, `cjs`, `global`

Source: https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm

**Comment by bfred-it** [comment]
Why is `jsnext:main` there and what is rollup? What problem are the two things trying to resolve?

My understanding is that that field is only temporarily there to allow `rollup` to make use of ESM(odules) before they are natively implemented in node.

Once that happens ([v8 issue](https://bugs.chromium.org/p/v8/issues/detail?id=1569#c29)), rollup's interest in the property should drop in my opinion. To my understanding, the target of the output is not relevant to rollup.

I think `jsnext:main` should stay as it is to avoid further fragmentation and dilution of maintainers' efforts.

**Comment by balupton** [comment]
Thought I'd chime in as it's an area I've been working with a for a while.

I'm surprised it is called `jsnext:main` when https://github.com/rollup/rollup/wiki/jsnext:main says:

> jsnext:main will point to a module that has ES2015 module syntax but otherwise only syntax features that node supports.

Which is not JSNext, or ESNext or whatever at all, it's just ES Modules... which is not what anyone associates to JSNext/ESNext...

https://github.com/nodejs/node/wiki/ES6-Modules-in-Node has some options that are being discussed within the node core for supports ES Modules, of which a `module` property that works just the same as the current `jsnext:main` property seems the best fit, as that is actually what `jsnext:main` currently means according to that wiki explanation of it.

Regarding which to load, we've been using the notion of a esnextguardian for over a year now (originally as a script inside each package, and now as its own package) - https://github.com/bevry/esnextguardian and it has worked quite well

However, it doesn't solve identifying which editions exist within the package and goes for that, so then I created https://github.com/bevry/base/issues/21 and currently https://github.com/bevry/editions to work around that. I find this notion of editions very nice, as it works at runtime like esnextguardian to pick the correct edition, but unlike esnextguardian can also blacklist syntax combinations that failed to load speeding up the process, and because of the editions listing inside `package.json` can be incorporated with tooling like https://github.com/bevry/projectz for the README usage details, as well as hopefully things like loaders which know specifically which syntaxes they support.

It's early days for editions however I'm ready to start pushing it up over the week, however esnextguardian has been used successfully for a year now.

**Comment by balupton** [comment]
https://github.com/bevry/editions is now released, and includes README rendering with https://github.com/bevry/projectz — keen to get everyone's feedback — can probably have projectz render a note about rollup and `jsnext:main` if that property exists in the package

**Comment by TrySound** [comment]
Close it since `module` field is introduced in rollup-plugin-node-resolve2.

**Comment by bfred-it** [comment]
So as defined by the [ES6 Module Interoperability document](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#51-determining-if-source-is-an-es-module) you can specify:

```json
{
  "main": "cjs-exports.js",
  "module": "es-exports.js",
  "es:next": "es-exports.js" // backwards compat
}
```

Correct?

**Comment by TrySound** [comment]
@bfred-it Yep. And module is enabled by default. So configuration is decreased a bit.

**Comment by balupton** [comment]
As `module` apparently is the way to go, from the above comments, shouldn't https://github.com/rollup/rollup/wiki/jsnext:main be updated, and the README section that references it:

```
Can I distribute my package as an ES6 module?

If your package.json has a jsnext:main field, ES6-aware tools like Rollup can import the ES6 version of the package instead of the legacy CommonJS or UMD version. You'll be writing your code in a more future-proof way, and helping to bring an end to the dark days of JavaScript package management. Learn more here.
```
