### ISSUE TITLE
Create a diagram showing hook lifecycle

### ISSUE THREAD

**Issue by jakearchibald** [rollup/rollup#3410]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Once the order of hooks is documented (https://github.com/rollup/rollup/issues/3409), create a diagram that provides an overview of the lifecycle.

### Your Proposal for Changes

It isn't clear what type of diagram would be best, but hopefully that will be clearer once https://github.com/rollup/rollup/issues/3409 is resolved.

## Update

by @lukastaegert:

Previous and next steps in the hooks are now documented on the website. @jakearchibald  created a nice writeup which could be used to build a diagram upon here: https://github.com/rollup/rollup/pull/3418#issuecomment-594523196

**Comment by shellscape** [comment]
@lukastaegert if you can put together a simple ascii diagram, I can translate that into something interactive and open a PR

**Comment by jakearchibald** [comment]
I have a vague worry that trying to create this diagram-first might encourage the wrong kind of diagram.

Instead, #3409 (which is useful on its own) will provide the data need to plan the diagram.

**Comment by lukastaegert** [comment]
I actually started on #3409, hope I can finish it soon (need to squeeze it in between other work at the moment)

**Comment by jakearchibald** [comment]
I listed the steps in order in https://github.com/rollup/rollup/pull/3418#issuecomment-594523196. It feels like it could be used to build a flow chart or something similar.

**Comment by yfwz100** [comment]
Can we add such a diagram to the documentation?

![image](https://user-images.githubusercontent.com/983211/128985616-373c9f51-d40a-4f6d-9902-4f0f1bd729e5.png)

The notation [S] means sequential, [F] means first and [P] means parallel.
Which is generated from mermaid:

```mermaid
flowchart TB
    buildStart["[P] buildStart"]
	buildEnd["[P] buildEnd"]
	load["[F] load"]
	moduleParsed["[P] moduleParsed"]
	options["[S] options"]
	resolveDynamicImport["[F] resolveDynamicImport"]
	resolveId["[F] resolveId"]
	transform["[S] transform"]
    options-->buildStart-->|entry|resolveId-->|external|buildEnd
    resolveId-->load-->transform-->moduleParsed-->buildEnd
    moduleParsed-->resolveDynamicImport-->load
    moduleParsed-->resolveId
    resolveDynamicImport-->|external|buildEnd
```

**Comment by lukastaegert** [comment]
That looks really nice! Do you think there is a way to make the hooks clickable and link them to the documentation via mermaid?

**Comment by lukastaegert** [comment]
Ah, seems you can add some click handlers: https://mermaid-js.github.io/mermaid/#/flowchart?id=interaction
I think that is fabulous, we just need to integrate it with the build pipeline.

**Comment by yfwz100** [comment]
I've added link below but I'm new to rollup and need some time or someone to integrate it into the build pipeline. The diagram is drawn to learn the process of rollup. Having a diagram is helpful to understand how plugin works. :-)

Build hooks

```mermaid
flowchart TB
    buildStart["[P] buildStart"]
	buildEnd["[P] buildEnd"]
	load["[F] load"]
	moduleParsed["[P] moduleParsed"]
	options["[S] options"]
	resolveDynamicImport["[F] resolveDynamicImport"]
	resolveId["[F] resolveId"]
	transform["[S] transform"]
	click buildStart "https://rollupjs.org/guide/en/#buildstart"
	click buildEnd "https://rollupjs.org/guide/en/#buildend"
	click load "https://rollupjs.org/guide/en/#load"
	click moduleParsed "https://rollupjs.org/guide/en/#moduleparsed"
	click options "https://rollupjs.org/guide/en/#options"
	click resolveDynamicImport "https://rollupjs.org/guide/en/#resolvedynamicimport"
	click resolveId "https://rollupjs.org/guide/en/#resolveid"
	click transform "https://rollupjs.org/guide/en/#transform"
    options-->buildStart
    buildStart-->|entry|resolveId
    resolveId-->|external|buildEnd
    resolveId-->load
    load-->transform
    transform-->moduleParsed
    moduleParsed-->buildEnd
    moduleParsed-->resolveDynamicImport
    resolveDynamicImport-->load
    moduleParsed-->resolveId
    resolveDynamicImport-->|external|buildEnd
```

Output Generation Hooks

```mermaid
flowchart TB
	augmentChunkHash["[S] augmentChunkHash"]
	banner["[P] banner"]
	closeBundle["[P] closeBundle"]
	footer["[P] footer"]
	generateBundle["[S] generateBundle"]
	intro["[P] intro"]
	outputOptions["[S] outputOptions"]
	outro["[P] outro"]
	buildEnd-->|error|closeBundle
	buildEnd-->outputOptions
	renderChunk["[S] renderChunk"]
	renderDynamicImport["[F] renderDynamicImport"]
	renderStart["[P] renderStart"]
	resolveFileUrl["[F] resolveFileUrl"]
	resolveImportMeta["[F] resolveImportMeta"]
	writeBundle["[P] writeBundle"]
	click buildEnd "https://rollupjs.org/guide/en/#buildend"
	click augmentChunkHash "https://rollupjs.org/guide/en/#augmentchunkhash"
	click banner "https://rollupjs.org/guide/en/#banner"
	click footer "https://rollupjs.org/guide/en/#footer"
	click generateBundle "https://rollupjs.org/guide/en/#generatebundle"
	click intro "https://rollupjs.org/guide/en/#intro"
	click outputOptions "https://rollupjs.org/guide/en/#outputoptions"
	click outro "https://rollupjs.org/guide/en/#outro"
	click renderChunk "https://rollupjs.org/guide/en/#renderchunk"
	click renderDynamicImport "https://rollupjs.org/guide/en/#renderdynamicimport"
	click renderStart "https://rollupjs.org/guide/en/#renderstart"
	click resolveFileUrl "https://rollupjs.org/guide/en/#resolvefileurl"
	click resolveImportMeta "https://rollupjs.org/guide/en/#resolveimportmeta"
	click closeBundle "https://rollupjs.org/guide/en/#closebundle"
	click writeBundle "https://rollupjs.org/guide/en/#writebundle"
	augmentChunkHash-->resolveFileUrl
	augmentChunkHash-->resolveImportMeta
	banner-->renderDynamicImport
	footer-->renderDynamicImport
	generateBundle-->writeBundle
	intro-->renderDynamicImport
	outputOptions-->renderStart
	outro-->renderDynamicImport
	renderChunk-->generateBundle
	renderDynamicImport-->augmentChunkHash
	renderStart-->banner
	renderStart-->footer
	renderStart-->intro
	renderStart-->outro
	resolveFileUrl-->renderChunk
	resolveImportMeta-->renderChunk
```

**Comment by yfwz100** [comment]
I couldn't find the build scripts for docs. Are there anything I can start working with?

**Comment by lukastaegert** [comment]
It is slightly complicated. I actually started setting something up but will until tomorrow to be able to push it so that we can have a look. Most stuff is happening in the rollup/rollupjs.org repo while we also need to link the diagrams from the docs in the main repo.

**Comment by yfwz100** [comment]
Ok, if there're something I can help. I'm glad to do it. Hope to see the diagrams in the offical docs. :-)

**Comment by lukastaegert** [comment]
So it turned out this was much more involved than anticipated but here we go now: https://deploy-preview-230--rollup.netlify.app/guide/en/#build-hooks

It is now based on a comment syntax and placing files in the docs folder, see #4206 and rollup/rollupjs.org#230

**Comment by yfwz100** [comment]
Nice! It's more clear now.

**Comment by jakearchibald** [comment]
This is great! Couple of notes:

- It isn't clear what the difference is between lines and dotted lines
- It isn't clear where "each entry" ends. Currently it looks like `buildEnd` could happen per entry.
- `moduleParsed` has an 'each import' branch, should this be 'each unresolved import'?

**Comment by lukastaegert** [comment]
> moduleParsed has an 'each import' branch, should this be 'each unresolved import'?

No, resolveId happens for all of them. Technically what does not happen necessarily is the load-transform steps if we already have this module. We could mention this as well.

> It isn't clear where "each entry" ends. Currently it looks like buildEnd could happen per entry.

I was not sure how to write it without severely increasing complexity, but suggestions welcome. At the moment, an "each" usually ends at a dotted line.

> It isn't clear what the difference is between lines and dotted lines

Roughly "if nothing else needs to be done here, we can eventually end up here". With that logic, I guess we need even more dotted lines in the output graph, i.e. for `renderDynamicImport`.

I am really open for suggestions. Luckily, Mermaid has a nice [live editor](https://mermaid-js.github.io/mermaid-live-editor/edit#eyJjb2RlIjoiZmxvd2NoYXJ0IFRCXG4gICAgY2xhc3NEZWYgaG9vay1wYXJhbGxlbCBmaWxsOiNmZmIzYjMsc3Ryb2tlOiMwMDA7XG4gICAgY2xhc3NEZWYgaG9vay1zZXF1ZW50aWFsIGZpbGw6I2ZmZDJiMyxzdHJva2U6IzAwMDtcbiAgICBjbGFzc0RlZiBob29rLWZpcnN0IGZpbGw6I2ZmZjJiMyxzdHJva2U6IzAwMDtcbiAgICBjbGFzc0RlZiBob29rLXNlcXVlbnRpYWwtc3luYyBmaWxsOiNmZmQyYjMsc3Ryb2tlOiNmMDA7XG5cblx0YnVpbGRlbmQoXCJidWlsZEVuZFwiKTo6Omhvb2stcGFyYWxsZWxcblx0Y2xpY2sgYnVpbGRlbmQgXCIvZ3VpZGUvZW4vI2J1aWxkZW5kXCIgX3BhcmVudFxuXG4gICAgYnVpbGRzdGFydChcImJ1aWxkU3RhcnRcIik6Ojpob29rLXBhcmFsbGVsXG5cdGNsaWNrIGJ1aWxkc3RhcnQgXCIvZ3VpZGUvZW4vI2J1aWxkc3RhcnRcIiBfcGFyZW50XG5cblx0bG9hZChcImxvYWRcIik6Ojpob29rLWZpcnN0XG5cdGNsaWNrIGxvYWQgXCIvZ3VpZGUvZW4vI2xvYWRcIiBfcGFyZW50XG5cblx0bW9kdWxlcGFyc2VkKFwibW9kdWxlUGFyc2VkXCIpOjo6aG9vay1wYXJhbGxlbFxuXHRjbGljayBtb2R1bGVwYXJzZWQgXCIvZ3VpZGUvZW4vI21vZHVsZXBhcnNlZFwiIF9wYXJlbnRcblxuXHRvcHRpb25zKFwib3B0aW9uc1wiKTo6Omhvb2stc2VxdWVudGlhbFxuXHRjbGljayBvcHRpb25zIFwiL2d1aWRlL2VuLyNvcHRpb25zXCIgX3BhcmVudFxuXG5cdHJlc29sdmVkeW5hbWljaW1wb3J0KFwicmVzb2x2ZUR5bmFtaWNJbXBvcnRcIik6Ojpob29rLWZpcnN0XG5cdGNsaWNrIHJlc29sdmVkeW5hbWljaW1wb3J0IFwiL2d1aWRlL2VuLyNyZXNvbHZlZHluYW1pY2ltcG9ydFwiIF9wYXJlbnRcblxuXHRyZXNvbHZlaWQoXCJyZXNvbHZlSWRcIik6Ojpob29rLWZpcnN0XG5cdGNsaWNrIHJlc29sdmVpZCBcIi9ndWlkZS9lbi8jcmVzb2x2ZWlkXCIgX3BhcmVudFxuXG5cdHRyYW5zZm9ybShcInRyYW5zZm9ybVwiKTo6Omhvb2stc2VxdWVudGlhbFxuXHRjbGljayB0cmFuc2Zvcm0gXCIvZ3VpZGUvZW4vI3RyYW5zZm9ybVwiIF9wYXJlbnRcblxuXHR3YXRjaGNoYW5nZShcIndhdGNoQ2hhbmdlXCIpOjo6aG9vay1zZXF1ZW50aWFsLXN5bmNcblx0Y2xpY2sgd2F0Y2hjaGFuZ2UgXCIvZ3VpZGUvZW4vI3dhdGNoY2hhbmdlXCIgX3BhcmVudFxuXG4gICAgY2xvc2V3YXRjaGVyKFwiY2xvc2VXYXRjaGVyXCIpOjo6aG9vay1zZXF1ZW50aWFsLXN5bmNcblx0Y2xpY2sgY2xvc2V3YXRjaGVyIFwiL2d1aWRlL2VuLyNjbG9zZXdhdGNoZXJcIiBfcGFyZW50XG5cbiAgICBvcHRpb25zXG4gICAgLS0-IGJ1aWxkc3RhcnRcbiAgICAtLT4gfGVhY2ggZW50cnl8cmVzb2x2ZWlkXG4gICAgLi0-IHxleHRlcm5hbHxidWlsZGVuZFxuXG4gICAgcmVzb2x2ZWlkXG4gICAgLS0-IHxub24tZXh0ZXJuYWx8bG9hZFxuICAgIC0tPiB0cmFuc2Zvcm1cbiAgICAtLT4gbW9kdWxlcGFyc2VkXG4gICAgLi0-IHxubyBpbXBvcnRzfGJ1aWxkZW5kXG5cbiAgICBtb2R1bGVwYXJzZWRcbiAgICAtLT4gfFwiZWFjaCBpbXBvcnQoKVwifHJlc29sdmVkeW5hbWljaW1wb3J0XG4gICAgLS0-IHxub24tZXh0ZXJuYWx8bG9hZFxuXG4gICAgbW9kdWxlcGFyc2VkXG4gICAgLS0-IHxlYWNoIGltcG9ydHxyZXNvbHZlaWRcblxuICAgIHJlc29sdmVkeW5hbWljaW1wb3J0XG4gICAgLi0-IHxleHRlcm5hbHxidWlsZGVuZFxuXG4gICAgcmVzb2x2ZWR5bmFtaWNpbXBvcnRcbiAgICAtLT4gfHVucmVzb2x2ZWR8cmVzb2x2ZWlkIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0) where you can just copy and paste the code from here https://github.com/rollup/rollup/blob/master/docs/build-hooks.mmd to try out different things so that we can talk about it.
