### ISSUE TITLE
CLI equivalent of sourceMapFile?

### ISSUE THREAD

**Issue by developit** [rollup/rollup#344]
Hi @Rich-Harris & co:

I can't seem to find a way to specify `sourceMapFile` from the rollup CLI.  This would be useful as it triggers relative paths in the generated external sourcemap, which are better handled by uglify-js.

Am I just missing something, or is this a mapping that could be added?

**Comment by Victorystick** [comment]
Rollup's `-m` flag is overloaded. `-m inline` results in an inline source map. Any other name creates a new file with that name. Try `rollup entry.js -d out.js -m another-name.js.map`.

**Comment by Rich-Harris** [comment]
Actually it doesn't look like there's a way to specify a different sourcemap file name – in the example above the `another-name.js.map` part gets discarded.

Done some digging and it turns out that the `dest` option is being passed from the CLI to Rollup, but it's relative to `process.cwd()` (i.e. `-o out.js` is passed straight through). Because of that, the sources are absolute (because magic-string, which is actually generating the sourcemaps, can't know that `/path/to/my-project/src/foo.js` is in fact a short hop away from `/path/to/my-project/dist/bundle.js` when all it sees is `bundle.js`.

I think what we need to do is ensure that the `dest` or `sourceMapFile` option is always resolved. PR inbound

**Comment by Rich-Harris** [comment]
Closing, as fixed in latest releases
