### ISSUE TITLE
Missing functions after rollup

### ISSUE THREAD

**Issue by xbqian** [rollup/rollup#3448]
- Rollup Version: 1.24.0-latest
- Operating System (or Browser): windows
- Node Version (if applicable): 12.16.0
- Link to reproduction (IMPORTANT, read below): https://github.com/PeculiarVentures/PKI.js/issues/264

### Expected Behavior
All functions works fine in bundle.js after rollup.

### Actual Behavior
These functions are all missing after rollup(version >= 1.24.0). But it works well with rollup version <=1.23.1.
The project link is https://github.com/PeculiarVentures/PKI.js . The issue detail is described in url above.
Thanks for your attention.

**Comment by lukastaegert** [comment]
This is not a bug in Rollup. The problem is exactly this here:
https://github.com/PeculiarVentures/PKI.js/blob/master/examples/CertificateComplexExample/es6.js#L822-L839

Note the nice title "Hack for Rollup.js" 😜

The version in question introduced support for tree-shaking statements after return expressions as they are essentially dead code.

I have no idea why your setup is as it is, but if your goal is to put those functions on the global object, I very much recommend against creating "dead code usages" of those functions to keep them in the bundle and then attach them to the global object using an outro. Apart from the issue at hand, this will also break if variables are renamed. Things you could do:
- Attach them to the global object inside your code (but apparently you do not want this for ESM output. Then again, what is the worth of an ESM build if you do not export anything?)
- Export them (this would create a global namespace containing the exports that you could then attach safely to the global object, maybe not in an outro but in a `footer`)

**Comment by lukastaegert** [comment]
Also might be a bad sign if you have to turn off inspections to be able to write your code...
