### ISSUE TITLE
No longer possible to get all modules used for chunk

### ISSUE THREAD

**Issue by PepsRyuu** [rollup/rollup#3487]
### Expected Behavior / Situation
In ```renderChunk```, it should be possible to know what modules were read in order to generate the chunk. This used to be possible with ```chunkInfo.modules```, as it included all modules, including ones that were tree-shaken completely. This is logged as a breaking change in Rollup 2 for ```generateBundle```.

![image](https://user-images.githubusercontent.com/6637882/78697138-41d63000-78f8-11ea-8a0d-0fab732c7fcb.png)

This feature was incredibly useful for plugins like CSS, where I can see which chunks imported what CSS files, and very useful for HMR where I can easily tell what CSS files have been removed from the dependency tree. The reason these don't appear anymore, is because for CSS files, the transform function returns an empty string (as it should because there's no JS code to emit).

Example:

```
transform (code, id) {
    // check if css, parse css
    files[id] = code;
    return '';
}

renderChunk (code, chunkInfo) {
    let output = '';

     Object.keys(chunkInfo.modules).forEach(filename => {
         if (files[filename]) {
             output += files[filename] + '\n';
         }
      });

      this.emitFile({
          type: 'asset',
          source: output,
          name: 'styles.css'
      });
}
```
**Rollup 1:**

![image](https://user-images.githubusercontent.com/6637882/78696895-f6238680-78f7-11ea-994b-ba15623f7da4.png)

**Rollup 2:**

![image](https://user-images.githubusercontent.com/6637882/78696854-e73cd400-78f7-11ea-928a-9cfa5f52826c.png)

### Actual Behavior / Situation
As far as I can tell, it's no longer possible to determine inside the ```renderChunk``` hook (or any other involving code generation for that matter), what files were included as part of the chunk, as they're all omitted because they've been tree-shaken. Therefore it breaks these types of plugins that transform code to nothing but require to know that they're included in the chunk. At the moment, I have to roll-back to Rollup 1, because I can't see how it's possible looking through the documentation.

### Modification Proposal
In order to not introduce a breaking change so soon, it may be preferable to introduce a new array into ```chunkInfo``` that contains a list of all of the modules that are part of the dependency tree for this chunk.

**Comment by lukastaegert** [comment]
I see your point but the problem is: With the new chunking algorithm, those modules are not part of ANY chunk, so we cannot just re-add this information. Chunk association is based on either the module having a side-effect or someone using an export of the module. As empty modules have neither, they are never added to a chunk, hence the breaking change.

I guess your approach will need to be changed. Ideas could be:
- introduce a side-effect into those modules that you can easily find again via e.g. a RegExp and remove it in renderChunk (you will need to make sure you specifically set `moduleSideEffects: true` for those modules to override if a user sets them to `false`). A simple side-effect could be a call to an imaginary global function.
- use `this.getModuleInfo()` on the modules that are in the chunk to determine which of those modules imported one of the CSS stub modules. `getModuleInfo` contains the complete graph information. I guess this approach is preferable as it avoids the potentially expensive chunk editing in `renderChunk`

**Comment by PepsRyuu** [comment]
Thanks for the quick response and the suggestions! :)

I'll give those workarounds a go and see if they can still implement the use case. They do sound somewhat hacky though. In regards to the second approach with ```getModuleInfo``` which seems more preferable, is it reliable that it will contain the complete dependency graph in future versions of Rollup?

Just want to make sure this isn't an unintended feature for empty modules to be included in some metadata, but not included in others.

**Comment by lukastaegert** [comment]
> is it reliable that it will contain the complete dependency graph in future versions of Rollup?

Definitely, and that is intentional. This function can be called as soon as a module has been parsed and is meant as a tool for plugin authors to be able to explore the initial module graph and gather some basic information, cf. https://rollupjs.org/guide/en/#thisgetmoduleinfomoduleid-string--moduleinfo . It is conceivable that in the future, it will also contain tree-shaking information once available, but the ability to traverse the entire graph will definitely remain.

> They do sound somewhat hacky though

I do not see how creating an empty module as a placeholder for a CSS file and searching for it in the output and removing it if the content of the importing file was removed is less hacky, though 😜. This would be easily broken if the user left a log statement in the file or just some code that cannot be removed such as a constant that is exported and used elsewhere.

If the CSS imports would actually import something that would be used in the code such as a classname, that would give you reliable and proper tree-shaking on top. But I guess it depends on how you expect people to use your framework.

**Comment by PepsRyuu** [comment]
Thanks for providing the reassurance! I've investigated the ```getModuleInfo``` solution and it works to some degree (passes the initial test cases I've defined, needs further testing), but it is fairly expensive to use and involves the plugin author doing some obscure checks. The additional complexity (and performance hit for the circular check) feels like a huge regression compared to the Rollup v1 implementation as posted previously.

```javascript
// Find the entry file, because reading all
// modules here will involve multiple traversals down the same tree.
// Only the entry module can be relied on, because if you import a JS file
// and that only imports CSS files, that JS file will not be included in chunkInfo.
let entry = Object.keys(chunkInfo.modules).filter(filename => {
    return this.getModuleInfo(filename).isEntry;
})[0];

// Traverse the dependency tree and search for CSS modules
let modulesChecked = {};
let findCSS = (id) => {
    // Circular Dependency check
    if (modulesChecked[id]) {
        return;
    }

    modulesChecked[id] = true;
    this.getModuleInfo(id).importedIds.forEach(id => {
        if (files[id]) {
            output += files[id] + '\n';
        } else {
            findCSS(id);
        }
     });
};

findCSS(entry);
```

Ignoring the CSS use case, I can imagine this being an issue for plugin authors looking to implement a similar use case of exporting imported modules to a separate file, and remembering to check for all of these things. Would be interested in hearing your thoughts on if this is the intended usage of the API as original envisioned, and whether or not the complexities would be a concern from Rollup's perspective?

**Comment by lukastaegert** [comment]
I am not sure this is what you want. For starters, `importedIds` will also contain modules from other chunks and I was under the impression that you were interested in chunking? Or do you really just want to include all CSS imports that can be reachable from an entry chunk? If that is the case, your approach looks valid.

Otherwise you could instead look at the modules actually included in each chunk (not only the entry chunks) and just check the imported ids for each of those if they import a CSS file. This would give you all files that are imported by a module that is not completely tree-shaken (if that is what you rather want).

Not sure I can say this is how it was "envisioned", at least your use case was not explicitly considered when it was created, but yes, this is how you could go about it.

In any case, I would not be worried about performance, this should be fast compared to the actual Rollup run.

**Comment by PepsRyuu** [comment]
The problem with ```chunkInfo.modules``` is the following:

**main.js**
```
import './other';

// do something
```

**other.js**
```
import './style.css';
import './anotherstyle.css';
import './morestyles.css';
```

In this scenario, ```other.js``` is tree-shaken because all it does is import files, so it doesn't appear in ```chunkInfo.modules```. As a result it makes ```chunkInfo.modules``` in Rollup 2 highly unreliable and untrustworthy.

**Comment by chmelevskij** [comment]
> The problem with `chunkInfo.modules` is the following:
> 
> **main.js**
> 
> ```
> import './other';
> 
> // do something
> ```
> 
> **other.js**
> 
> ```
> import './style.css';
> import './anotherstyle.css';
> import './morestyles.css';
> ```
> 
> In this scenario, `other.js` is tree-shaken because all it does is import files, so it doesn't appear in `chunkInfo.modules`. As a result it makes `chunkInfo.modules` in Rollup 2 highly unreliable and untrustworthy in this context.
> 
> I'll have to experiment further and see what I can come up with. I'll leave it up to yourself to decide whether or not this is something to be further reconsidered or closed. :)

Facing exactly this issue now here https://github.com/egoist/rollup-plugin-postcss/pull/276

**Comment by lukastaegert** [comment]
I am feeling with you, but see that in the future the situation may become even more difficult as there are ideas that might eventually lead to modules being split up over several chunks (e.g. a helper library file `util.js` has two exports `foo` and `bar`; at some point it could be that `foo` is in another chunk as `bar`).

In this scenario, the only viable way I see is to find a way to handle certain modules differently. The easiest way would be to give those modules a side-effect, but then this side-effect would need to be removed in post-processing, which is slow.

How about we extend the `load` hook with a flag to turn off tree-shaking for specific modules? The effect should be that of course all statements of this module are included, but also that this module is considered as having side-effects even if it is empty. Then it would re-appear in the output, and even in the future this module would never be "split" between chunks. Or any other ideas?

Of course attaching this to tree-shaking would not be strictly necessary, but for me it makes the most sense and can give some added utility to this feature.

**Comment by isidrok** [comment]
I actually worked around this returning a dummy module in the transform hook:
```js
function dummyModuleResult() {
    return {
      code: `export default undefined`,
      moduleSideEffects: 'no-treeshake',
      map: {mappings: ''},
    };
  }
```
Which ends up being
```js
var undefined$1 = undefined;
```
in the final bundle.

**Comment by IanVS** [comment]
>How about we extend the load hook with a flag to turn off tree-shaking for specific modules?

Was this ever implemented?  I'm also trying to build a dependency graph which traces css files back up to the entrypoint, and was surprised to find that the chain was broken for a few of my files which are javascript modules that only import css files.  I'm working on a method that uses `getModuleInfo()`, but if another paved path has been found / made, I'd love to hear about it.

**Comment by lukastaegert** [comment]
> Was this ever implemented?

Exactly, return `moduleSideEffects: 'no-treeshake'` as shown here https://github.com/rollup/rollup/issues/3487#issuecomment-700259850

**Comment by IanVS** [comment]
Thanks, should this issue be closed now?

**Comment by lukastaegert** [comment]
Feel free to reopen if there is still need for discussion
