### ISSUE TITLE
"generateBundle" hook deprecation notice is ambiguous

### ISSUE THREAD

**Issue by slavafomin** [rollup/rollup#3489]
Hello!

Thank you for this great tool!

However, the "generateBundle" hook deprecation notice:

`A plugin is directly adding properties to the bundle object in the "generateBundle" hook. This is deprecated and will be removed in a future Rollup version, please use "this.emitFile" instead.`

doesn't contain any information about the actual plugin that has the issue.

I've tried enabling logging/debugging mode using `DEBUG=*`. Also Rollup's documentation doesn't reference any options to enable verbose output.

How does the user should know what plugin is a culprit in such case?

Thanks!

**Comment by shellscape** [comment]
_If you are sure this is a bug, please take the time to refile this issue **using the issue template** and we'll reopen it._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by slavafomin** [comment]
@lukastaegert could you still look into this, please?

**Comment by lukastaegert** [comment]
> I've tried enabling logging/debugging mode using DEBUG=*. Also Rollup's documentation doesn't reference any options to enable verbose output.

Unfortunately there is neither a verbose mode nor a debug mode.

> How does the user should know what plugin is a culprit in such case?

Rollup does not know it either. This message is like a post-mortem where the bundle object is searched for "broken" files that were added incorrectly. At the moment, Rollup repairs those files and issues the message. I vaguely remember we added this behaviour to work around issues in rollup-plugin-postcss. At the moment, this is apparently still broken, if this is your problem, this is an issue you could watch: egoist/rollup-plugin-postcss#258

**Comment by shellscape** [comment]
> Rollup does not know it either. 

Could we remedy that by adding a property onto hook functions within a plugin to reflect the plugin name?

**Comment by lukastaegert** [comment]
Not sure I fully understand what you mean. So here the issue is that the check in general is performed only after all plugins have run. We could try to run the check after each hook separately, but that would be some effort, scanning all bundle entries again and again. And if it is really rollup-plugin-postcss again, I would not want to go that far. I do not expect new plugins to do that now that the file emission APIs are well established.
