### ISSUE TITLE
Tree shaking class methods

### ISSUE THREAD

**Issue by rapodaca** [rollup/rollup#349]
Using the interactive page, I created this example:

_main.js_

```
import { Foo } from './foo.js';

var foo = new Foo();
console.log(foo.bar());
```

_foo.js_

```
export class Foo {
  constructor(x) {
    this.value = x;
  }

  bar() {
    return 'bar';
  }

  baz() {
    return 'baz';
  }
}
```

This was the output in ES2015 mode:

```
class Foo {
  constructor(x) {
    this.value = x;
  }

  bar() {
    return 'bar';
  }

  baz() {
    return 'baz';
  }
}

var foo = new Foo();
console.log(foo.bar());
```

I was expecting the ES2015 output to only contain the function bar because it's the only one called. Instead, function baz was also included.

Is this expected behavior?

**Comment by Victorystick** [comment]
@rapodaca Yes. Rollup's tree shaking is limited to imports/exports and top level variables, since they're much easier to statically analyse. JavaScript's dynamic nature make it very difficult to determine if a method is used or not.

**Comment by Rich-Harris** [comment]
Added the `enhancement` label. Would be great to have this feature, but we'd need to be much smarter about keeping track of values (and accepting that it's often not possible statically as @Victorystick says)

**Comment by krzksz** [comment]
Ok, so if I understand everything correctly we can make following assumptions to simplify dynamism of the code:
- disable class tree shaking for entire bundle when: 
    - any form of `eval` is used anywhere inside a bundle,
- disable class tree shaking for a specific module when:
    - imported class is used on the right hand side of any assignment,
    - imported class is accessed using array notation `[]`

Is there anything I forgot about?

**Comment by backspaces** [comment]
Just FYI: #645 above discusses the "object container" module style, where an object containing functions is also treated monolithically. I don't use classes, preferring prototypal inheritance, Self style. But I still have the problem discussed here.

Now this is completely understandable, es6 modules are *soooo* new. No blame, no shame.

BUT: I'd love to see see a best practices approach that is as easy as classes/object containers but is tree shakable. I think it goes past simply exporting each function individually, but also includes how to import a subset easily. My bet is there's some magic here that I've missed.

**Comment by thelgevold** [comment]
This would be a really cool enhancement of Rollup.
Any updates on the feasibility of this?

**Comment by Attrash-Islam** [comment]
Comment I wrote on closed issue regards the class method removal behaviour:

I'd not recommend that behaviour of removing unused method of a class! In a real-world example at work we're working with old AngularJS 1.x code and new fresh Reactjs code (Some kind of migeration).

For AngularJS controller I'm creating a class which contains method that the most of them is linked in the html template via ng- attributes, which means that they have "0 references" in the js files because we inject the whole class to the AngularJS eco-system.

This kind of method shaking will shake my whole app 😂

**Comment by lukastaegert** [comment]
Fear not, if this is EVER implemented it will be implemented in a way such that the algorithm will always include all methods/all object keys if the object is passed to an unknown function or a function that will have a different effect if some keys are omitted.

In your example there ARE functions in angular that parse all available keys or at least depend on all keys being present so this would not be an issue. However I do not expect such a feature to arrive any time soon anyway as it is REALLY difficult to get right and would need to opt out of this behaviour quite easily anyway.

**Comment by wmhilton** [comment]
As a library author, is there a way I could somehow *opt in* to method shaking? I've got this monster of a class in [isomorphic-git](https://github.com/wmhilton/isomorphic-git) (961 kB fully bundled & minified) but 300kb of that is the openpgp crypto library and is only called in one or two methods to sign/verify PGP-signed commits, which is a feature many users might never use. I don't want to make users "opt in" - I'd much rather provide a "batteries included" default export - but if users never use those methods, I hate for them to be dragging around 300kB of cruft.

One possibility is to provide a "batteries included" export, and tell users if they want smaller bundles to switch to a second API where you only import the functions you need and mix them into a tiny base class. But I hate to place that kind of burden on users.

I was reading about the [`@__PURE__`](https://github.com/mishoo/UglifyJS2/pull/1448) hint to mark functions as having no side effects, and was wondering if something similar could work on class methods?

**Comment by lukastaegert** [comment]
Hi @wmhilton, even though I do not know about each available tree-shaking tool I find it very unlikely that any of them will remove class methods. The reason is that it is VERY difficult to do this in a way that does not break anything:
* You have to identify calls to instance methods. Instances are basically objects which can be modified just as any object.
* You can call methods via computed property keys, e.g. you can instance['my' + 'Method']() or even instance[getMethodKey()](). Even the best algorithms will not be able to find every invocation here. Therefore, the algorithm will need to include the key if something like this is detected
* Omitting class methods can also potentially break many other things that do not call methods but just rely on the presence of keys. This includes copying methods to other variables. Again, an algorithm will need to opt out once this is detected.

None of these problems is unsolvable but each one is no triviality. IMO not attaching things to a class is the way to go. If you want for your users to be able to access your functions via a common namespace, providing named exports and advising them to `import * as someNameSpace from "..."` is one way to go. If they use a tool like rollup, the calls to `someNameSpace.method()` will then be treated and tree-shaken like direct calls to the original methods.

**Comment by Pauan** [comment]
@wmhilton Currently, the only JavaScript optimizer (that I am aware of) that can do dead code elimination on class methods is the [Google Closure Compiler](https://github.com/google/closure-compiler). It does a lot of awesome optimizations that other tools (e.g. Webpack, Uglify, Rollup) do not do.

However, in order to achieve those optimizations, it requires you to [follow various restrictions](https://developers.google.com/closure/compiler/docs/limitations). Those restrictions means that most JavaScript libraries won't work. Generally, only code which has been specifically written for Google Closure Compiler will work.

If you are using a library which was not designed for Google Closure Compiler, you can sometimes get it to work by [writing an extern file](https://developers.google.com/closure/compiler/docs/api-tutorial3#externs).

**Comment by wmhilton** [comment]
Thanks for the feedback and advice. @lukastaegert you make some very good points... if I ever design a programming language I'll have to carefully design the reflection capabilities to prevent such antipatterns as `instance[getMethodKey()]()`. If JS had more formal methods for reflection or a type system that preserved such meta information about property keys, even if the optimizer had removed the methods, maybe there would be a simpler path to do this kind of bundle size reduction.

Thanks @Pauan. I'll see if I can make my library Google Closure Compiler compliant (although I don't know how many people actually use Closure Compiler). It would be nice if they were able to benefit from class method pruning.

But it sounds like for now the answer is to export each method separately. I think this is doable for my project, as there isn't much state being stored in the instance objects as they are. I'm tempted to do a "mixin" approach, but I think that ~~would complicate or make flow/typescript definitions impossible.~~ I just googled "TypeScript mixin" and it looks like it *can* statically infer the methods on a mixin class... how interesting. (I don't use TypeScript myself, but I want to support that VS Code auto-completion experience. ;) )

**Comment by Soul-Master** [comment]
I think it should be much better to has some option to enable this feature via configuration or class metadata. All methods/properties of these specified classes must be statically reference. I think this way should simplify this feature.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by aleclarson** [comment]
Perhaps a good compromise would be to have a compiler hint (similar to `#__PURE__`) that tells Rollup to not worry about dynamic access and trust that it's safe to treeshake the method/property if not statically accessed.

wdyt @lukastaegert?

**Comment by lukastaegert** [comment]
How much do you trust your users to only access the method in a statically analysable? If we do this, I would prefer to do it without extra annotations because they just create unrealistic expectations. We are actually quite close to tree-shaking object properties. I would go for that first as a testing ground before moving on the the more complex classes.

**Comment by thelgevold** [comment]
While you wait for support in Rollup, I would recommend checking out Google's closure compiler as it already supports these complex cases. It will also give you an indication of some of the challenges related to using aggressive optimizers :-)

**Comment by slavafomin** [comment]
Hello! Is this issue closed as "won't fix" or was it closed accidentally? Can we expect this feature to be implemented in the future?

**Comment by lukastaegert** [comment]
Maybe farer future. This would be rather complex to get right, object expression tree-shaking should probably come first, and that one is currently far down the pipeline

**Comment by lukastaegert** [comment]
We are currently working on tree-shaking for object literals, which is even more basic but still very hard. However, there has been great progress recently, see #5420, which I am currently actively finalizing. Once this is released and has good performance and few enough bugs, we could extend the logic to static methods, and possibly instance methods eventually.
I really would love to have that, but let me assure you, it is a lot of work to get right.

**Comment by jimtendo** [comment]
> We are currently working on tree-shaking for object literals, which is even more basic but still very hard. However, there has been great progress recently, see #5420, which I am currently actively finalizing. Once this is released and has good performance and few enough bugs, we could extend the logic to static methods, and possibly instance methods eventually. I really would love to have that, but let me assure you, it is a lot of work to get right.

Would love to see this for static methods (and, if possible, instance methods). Any idea whether this still looks like it will be possible? I'm currently architecturing a number of Primitive classes for a project and am being pretty cautious about what I include in each primitive (we have some BIG WebASM programs), but would be able to make these a lot more convenient if unused static and instance methods could be shaken.

**Comment by lukastaegert** [comment]
This is definitely possible, but I can give you no timeline. At the moment, we are still redesigning the basic algorithm to improve performance bottlenecks.
