### ISSUE TITLE
support node --disable-proto

### ISSUE THREAD

**Issue by nitsky** [rollup/rollup#3500]
Hi, in rollup 2.4.0 acorn-private-class-elements was added as a transitive dependency: https://github.com/rollup/rollup/compare/v2.3.5...v2.4.0. That package uses the `__proto__` property, but node recently added a `--disable-proto` option to disable its use due to security issues: nodejs/node#32279. Similarly, deno also recently removed support for `__proto__`: denoland/deno#4341.

I opened an issue with acorn-private-class-elements: https://github.com/acornjs/acorn-private-class-elements/issues/13. I am opening an issue here as well because I saw that rollup is currently using forks of a couple acorn packages from @guybedford. Do you suggest waiting for the change to be made in acorn-private-class-elements or adding another fork?

**Comment by shellscape** [comment]
_If you are sure this is a bug, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
