### ISSUE TITLE
Allow emitFile with relative paths

### ISSUE THREAD

**Issue by SASUKE40** [rollup/rollup#3507]
### Feature Use Case
It is banned from emitFile with relative paths in rollup v2.
https://github.com/egoist/rollup-plugin-postcss/issues/250#issuecomment-616409318

### Feature Proposal
Allow plugin to emitFile with relative paths.

**Comment by lukastaegert** [comment]
I think there is a clear misunderstanding what this is about. A relative path is a path starting with `./` or `../`. We do not allow those because we do not know what it should be relative to. This does not mean we do not allow paths, though.

A legal path starts with neither `./ `, `../ ` nor `/` and will be considered a path relative to the bundle root. E.g.

```js
this.emitFile({fileName: 'dir/subdir/file.txt', ...})
```

will be written to `<bundleRoot>/dir/subdir/file.txt` and be stored in the bundle as `dir/subdir/file.txt`.

So if you have your relative paths for whatever reason what you need to do is figure out where in the bundle the emitted file should end up and emit the file with the corresponding `fileName` or `name`.

Any other paths were NEVER officially supported, it was more luck and coincidence if anything else ever worked, and there is no plan to support anything else in the future as e.g. paths leaving the bundle root would violate the assumption that Rollup will only ever modify the target directory.

Incidentally it is trivial to construct such a path from a relative path because unless you are leaving the bundle root, Node's `path.relative` will give you exactly such a path.

e.g.

```
const bundleRoot = ...
const relativePath = ...
const relativePathBase = ... // whatever the relative path is relative to

const path = require('path');
const fileName = path.relative(bundleRoot, path.resolve(relativePathBase, relativePath));
```

**Comment by SASUKE40** [comment]
I know what you mean, but in that case the plugin doesn't support `fileName` like `extract: '../bundle.css'`.

**Comment by lukastaegert** [comment]
But what is it relative to? And how would this translate to a location in the bundle?

**Comment by SASUKE40** [comment]
Someone want to exract css files outside the bundle.js, and it has left the bundle root.

**Comment by tu4mo** [comment]
I have multiple output's, `dist/esm` and `dist/cjs`. I'm not bundling, I'm using `preserveModules`. I wanted to extract css file in `dist`, now it gets created in the `output.dir`s. But if that's not happening, I'll just create a script to move the file after rollup.

**Comment by lukastaegert** [comment]
The canonical approach here would be to move `output.dir` one level higher and then change `entryFileNames` and `chunkFileNames` accordingly to be one level lower.

**Comment by vladshcherbin** [comment]
> The canonical approach here would be to move `output.dir` one level higher and then change `entryFileNames` and `chunkFileNames` accordingly to be one level lower.

This trick doesn't work when using `output.file` 🤔

**Comment by NikosEfthias** [comment]
I cant understand why this is still an issue parcel fixed this sort of problems like a billion years ago is it this difficult to just follow paths during build. Because of this bug i will try to use webpack because simply i cant import an npm package that uses relative paths

**Comment by shellscape** [comment]
Please make sure that replies to issues in the repository are courteous,. constructive, and respectful.

**Comment by thousandsofraccoons** [comment]
> But what is it relative to? And how would this translate to a location in the bundle?

@lukastaegert  without relative paths it's quite complicated to use TailwindCSS which is normally served from `/static` or `/public` folders outside of target path.
