### ISSUE TITLE
"@rollup/plugin-node-resolve": "^7.1.3", 

### ISSUE THREAD

**Issue by ssanbeg** [rollup/rollup#3512]
Using with Svelte and Sapper. Issue 'npm run dev' and this errors:
(node:22730) UnhandledPromiseRejectionWarning: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './plugin-node-resolve' is not defined by "exports" in path_to_file/node_modules/rollup/package.json

**Comment by lukastaegert** [comment]
Next time, please use the issue template and add a reproduction, there is no support team here that is paid to look at this. Otherwise even though you gave me nearly nothing, it looks that you likely imported from `rollup/plugin-node-resolve` while you should have written `@rollup/plugin-node-resolve`.
