### ISSUE TITLE
Rollup will report an error when packaging lodash

### ISSUE THREAD

**Issue by suanmei** [rollup/rollup#3515]
rollup's current main is lodash.js ,when packaging lodash, report the error
`[!] Error: 'isArrayLike' is not exported by node_modules/lodash/lodash.js`

Do you have any advice?

**Comment by shellscape** [comment]
_If you are sure this is a bug, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by TrySound** [comment]
@suanmei Use `lodash-es` or add `@rollup/plugin-commonjs`
