### ISSUE TITLE
Dead code in bundle

### ISSUE THREAD

**Issue by binjospookie** [rollup/rollup#3528]
Hi! 

Rollup, Lerna and Typescript are used in my project. I have 2 packages (A, B). Package B export 3 functions(foo, bar, baz), and A package import foo function from B. After build A package bundle includes all 3 functions from B (not only foo).

What should I do to solve this problem?

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
