### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by binjospookie** [rollup/rollup#3532]
- Rollup Version: 2.7.6
- Operating System (or Browser): macOS Catalina
- Node Version (if applicable): v12.16.1
- Link to reproduction (IMPORTANT, read below): https://github.com/binjospookie/rollup

Hi! I have a project with Rollup, Lerna and TypeScript.
Package A export function from package B and export smth like `!fnFromB()`.
Package B have a dependency (ramda for example). It export 2 functions. One of them just return true (package A import this function). Another function return `pick(['1'])` (pick imports from ramda).

### Expected Behavior
`A` package have only one function from `B`

### Actual Behavior
`A` package have 2 functions and ramda's part

**Comment by lukastaegert** [comment]
The problem is that Rollup does not know that the call to `pick` does not have side-effects, and it is quite hard to figure this out through all of Ramda's currying helpers. You can fix this by adding an annotation to the toussaint package that instructs Rollup that the `pick` call does not have side-effects:

```js
export const a = () => true;
// @ts-ignore
import { pick } from 'ramda';

export const b = /*#__PURE__*/pick(['1']);
```

**Comment by binjospookie** [comment]
Thank you for the answer!
Is it possible to mark whole toussaint package as a pure? I have a lot functions like `makeSmth = compose(cFn,bFn,aFn)` in my real project.

**Comment by lukastaegert** [comment]
Not in the way you want. You can use the `moduleSideEffects` option to mark a module as "having no side-effects if nothing is imported", but as soon as something is imported, all potential side-effects will be included as well.
You can avoid this limitation if you define all exports in separate modules i.e. create many small files instead of a big one and mark all of them as side-effect-free.

**Comment by binjospookie** [comment]
Thank you so much!
