### ISSUE TITLE
Use 'import rollup from "rollup";' in the examples

### ISSUE THREAD

**Issue by dilyanpalauzov** [rollup/rollup#3537]
Consider that everybody understands and uses ES6 modules and rewrite the examples at http://rollupjs.org/guide/en/ to be in ES6 syntax.  In particular replace "const rollup = require('rollup');" with "import rollup from 'rollup' ".

Otherwise people will not start new projects with ES modules.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
