### ISSUE TITLE
Entry file import library from child file

### ISSUE THREAD

**Issue by conioX** [rollup/rollup#3538]
hi,  I try to create library using rollup, material-ui and some dependency.

rollup.config.js

```
module.exports = config => {
    config.input = {
        index: './src/index.js',
        wrapper: './src/lib/wrapper/index.js',
        Button: './src/lib/Button/index.js'
    };
    config.output = [
        {
            globals: {},
            format: 'esm',
            dir: './dist',
            name: 'Test'
        }
    ];

    return config;
};
```

index.js before build with rollup : 

```
export { default as Button } from './lib/Button';
export { default as Wrapper } from './lib/wrapper';

```

index.js after build with rollup :
```
import 'react';
import '@material-ui/core/Button';
export { default as Button } from './Button.js';
export { default as Wrapper } from './wrapper.js';

```

Button after build with rollup :

```
import React from 'react';
import { Button } from '@material-ui/core';

var Button = function Button() {
  return /*#__PURE__*/React.createElement(Button, {
    variant: "contained"
  }, "Default");
};

export default Button;
```

as you can see my index.js after build with rollup include code `import '@material-ui/core/Button';` from child component (Button) how to remove that? because when we only using wrapper not button our app bundle all dependency from `material-ui`.
any suggestions?

> Note : include material-ui in peerDependencies and external or global didn't work result all same entry file still import library from child file

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
