### ISSUE TITLE
Spread attributes not supported?

### ISSUE THREAD

**Issue by Kflash** [rollup/rollup#354]
Hi

I'm running into problems with rollup. I'm using spread attributes in my code, and rollup throws error on that.

I tried everything so far. Babel 5, babel 6 and all rollup plugins. Same thing.

Last error message I got was a long line with regex. 

How to solve this? Spread attributes are part of the es2015 specs and es2016 will support spread objects as well. 

I was reading somewhere only stage 2 supported?  Maybe that's an another issue coz I need to run stage-0.

I like the way rollup bundle things without the bloat that's included with browserify and webpack. So I hope there is a solution. ..

**Comment by eventualbuddha** [comment]
Can you provide a link to your project, or a sample project that illustrates the issue? It would help to see how you tried to configure it using `rollup-plugin-babel` and the `.babelrc`.

**Comment by Kflash** [comment]
I tried many different solutions, but this code from the build file I use. And this is ES2015, so I'm using a preset. Not a plugin.

```
var babel = require('rollup-plugin-babel')
var replace = require('rollup-plugin-replace')

rollup.rollup({
  entry: 'src/index.js',
  plugins: [
    babel({
      presets: ['es2015-rollup']
    })
  ]
})
// Standalone Dev Build
.then(function () {
  return rollup.rollup({
    entry: 'src/index.js',
    plugins: [
      replace({
        'process.env.NODE_ENV': "'development'"
      }),
      babel({
        presets: ['es2015-rollup']
      })
    ]
  })
  .then(function (bundle) {
    return write('dist/' + pack.name + '.js', bundle.generate({
      format: 'umd',
      banner: banner,
      moduleName: 'xxx'
    }).code)
  })
})

function write (dest, code) {
  return new Promise(function (resolve, reject) {
    fs.writeFile(dest, code, function (err) {
      if (err) return reject(err)
      resolve()
    })
  })
}
```

**Comment by Kflash** [comment]
Here is one out of many error messages I get:

```
{ [SyntaxError: xxx.js: Unexpected token (33:30)]
  pos: 1489,
  loc: Position { line: 33, column: 30 },
  _babel: true,
  codeFrame: '\u001b[0m  31 |     \u001b[36mif\u001b[39m \u001b[94m\u001b[1m(\u001b[22m\u001b[39mattrs \u001b[1m!=\u001b[22m \u001b[36mnull\u001b[39m\u001b[94m\u001b[1m)\u001b[22m\u001b[39m \u001b[32m{\u001b[39m\n  32 |         \u001b[36mif\u001b[39m \u001b[94m\u001b[1m(\u001b[22m\u001b[39mexcludeAttrs\u001b[94m\u001b[1m)\u001b[22m\u001b[39m \u001b[32m{\u001b[39m\n> 33 |             \u001b[36mconst\u001b[39m newAttrs \u001b[1m=\u001b[22m \u001b[32m{\u001b[39m\u001b[1m...\u001b[22mattrs\u001b[32m}\u001b[39m\u001b[1m;\u001b[22m\n     |                               ^\n  34 | \n  35 |             \u001b[36mfor\u001b[39m \u001b[94m\u001b[1m(\u001b[22m\u001b[39mlet attr \u001b[36min\u001b[39m excludeAttrs\u001b[94m\u001b[1m)\u001b[22m\u001b[39m \u001b[32m{\u001b[39m\n  36 |                 \u001b[36mif\u001b[39m \u001b[94m\u001b[1m(\u001b[22m\u001b[39mnewAttrs\u001b[33m[\u001b[39mattr\u001b[33m]\u001b[39m\u001b[94m\u001b[1m)\u001b[22m\u001b[39m \u001b[32m{\u001b[39m\u001b[0m' }
```

**Comment by Kflash** [comment]
The code rollup doesn't like, looks like this:

```
const newWorld = {...world };
```

**Comment by eventualbuddha** [comment]
@Kflash I believe you want something like the solution discussed in https://github.com/rollup/rollup/issues/347 to get the syntax to work properly. That should be better enabled by rollup in the future, somehow.

The issue with `./` not resolving but `./index` resolving is due to that behavior being part of `npm`, so you want to use `rollup-plugin-npm` to get that behavior.

**Comment by Victorystick** [comment]
@Kflash The spread operator for arrays, iterators and function calls are all part of ES2015. However, _object rest spread_ is part of an ES2016 proposal. Rollup currently doesn't support anything beyond ES2015 natively. You must enable the appropriate Babel transforms for it; `babel-syntax-object-rest-spread` and `babel-transform-object-rest-spread` I believe.

**Comment by eventualbuddha** [comment]
@Victorystick @Kflash Adding both `babel-plugin-transform-object-rest-spread` and `babel-plugin-syntax-object-rest-spread` seems to make it work for me, fyi.

**Comment by Victorystick** [comment]
Aah. Forgot `plugin-`...

**Comment by Kflash** [comment]
@Victorystick @eventualbuddha With Babel 6.x and preset 2015, things like the spread attribute works right out of the box when I use them with Browserify and Webpack. So all plugins included there.

However. As I stated all the time, this is not supported by Rollup. At least tons of issues to solve to get it working, and I still haven't got it working.

I gave up rollup, and went with a webpack solution. It took me 2 minutes to set up, and spread attribute works. So this is a non-issue for me now.

**Comment by Kflash** [comment]
Just to make things clear. Another example on spread attributes not working. And this has nothing to do with plugins or a whole bunch of other things.

However. Not a big deal for me. I left rollup and will never return.

```
SyntaxError: xxx.js: Unexpected token (62:36)
> 62 |                     const attempt = { ...lastAttempt };
     |                                     ^
```

**Comment by eventualbuddha** [comment]
@Kflash I'm sorry to hear you've found rollup to be so bad as to never consider it again in the future! That is quite drastic, but if you've found a setup that works for you I'm glad to hear it. I wish you luck with browserify and webpack!

For anyone else coming to this thread later, I'd like to clear a few things up:

### `babel-preset-es2015` does not include object spread

Without even considering rollup yet, creating [a project with a `.babelrc` file only including the `es2015` preset](https://gist.github.com/eventualbuddha/4d2c1591e495106e3149) means babel will not work with object spreads:

```
$ ./node_modules/.bin/babel index.js
SyntaxError: index.js: Unexpected token (2:13)
  1 | const obj = {a: 1};
> 2 | console.log({...obj});
    |              ^
  3 |
```

If you install the `babel-plugin-syntax-object-rest-spread` package and add it to `.babelrc`, the above command runs without error:

```
$ ./node_modules/.bin/babel index.js
"use strict";

var obj = { a: 1 };
console.log({ ...obj });
```

Finally, installing the `babel-plugin-transform-object-rest-spread` package and adding that to `.babelrc` will then actually transform the object spread:

```
$ ./node_modules/.bin/babel index.js
"use strict";

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

var obj = { a: 1 };
console.log(_extends({}, obj));
```

This is the final `.babelrc` for that setup:

```js
{
  "presets": ["es2015"],
  "plugins": ["syntax-object-rest-spread", "transform-object-rest-spread"]
}
```

### rollup can work with object spreads

To use rollup with the setup from above, we install `rollup` and `rollup-plugin-babel` plugins:

```
$ npm i -D rollup rollup-plugin-babel
```

And configure rollup with a `rollup.config.js` file:

```js
import babel from 'rollup-plugin-babel';

export default {
  entry: 'index.js',
  plugins: [babel()]
};
```

And configure babel to use the rollup preset:

```js
{
  "presets": ["es2015-rollup"],
  "plugins": ["syntax-object-rest-spread", "transform-object-rest-spread"]
}
```

Now, we can use rollup to build JS that uses object spreads:

```
$ ./node_modules/.bin/rollup -c
reating 'rollup-plugin-babel' as external dependency
var babelHelpers = {};

babelHelpers.extends = Object.assign || function (target) {
  for (var i = 1; i < arguments.length; i++) {
    var source = arguments[i];

    for (var key in source) {
      if (Object.prototype.hasOwnProperty.call(source, key)) {
        target[key] = source[key];
      }
    }
  }

  return target;
};

babelHelpers;
var obj = { a: 1 };
console.log(babelHelpers.extends({}, obj));
```

### rollup can import `index.js` files implicitly

If we add a `utils` directory with an `index.js` file inside it and we try to import it with `import './utils';`, by default rollup will not be able to find the file because the convention of using `index.js` when importing a directory is an `npm` convention that doesn't exist in all environments. This is easy to fix by using the `rollup-plugin-npm` package:

```
$ npm i -D rollup-plugin-npm
```

And editing `rollup.config.js`:

```js
import babel from 'rollup-plugin-babel';
import npm from 'rollup-plugin-npm';

export default {
  entry: 'index.js',
  plugins: [babel(), npm()]
};
```

This also means that any packages in npm will be resolved. This may not be the desired behavior. If the only feature you want is the `index.js`-finding, you can call the plugin as `npm({ main: false })` instead.

See [rollup-354](https://github.com/eventualbuddha/rollup-354) for a complete project with this setup and commits showing the steps.

---

**For rollup maintainers:** What can we do in the future to make this less likely to happen? One thing I can think of is improving [rollup-starter-project](https://github.com/eventualbuddha/rollup-starter-project) to give instructions on using babel features outside the `es2015` preset. Perhaps the wiki documentation could be improved?

@Kflash, if you feel up to it, having an "exit survey" from you with a quick note about what you found so frustrating would be beneficial. Feel free to email me@brian-donovan.com.

**Comment by Kflash** [comment]
@eventualbuddha I dropped you an email to avoid making this thread any longer.

**Comment by Kflash** [comment]
@eventualbuddha I sent you an email.

**Comment by Kflash** [comment]
@eventualbuddha One last thing regarding this issue. I used a few minutes to put together a boilerplate based on Rollup. And still this things are not working. However. I couldn't get the npm plugin working either.

The repo is here: https://github.com/Kflash/boily

If you run sample code with spread on this rollup boilerplate, it fails. If you try with my other boilerplates, it works.

But I saw your example repo, and what you did. So I will try that later on.

**Comment by stryju** [comment]
minimal version to support object spread:
```json
{
  "plugins": [
    "transform-es2015-parameters",
    "transform-es2015-destructuring",
    "transform-es2015-spread",
    "transform-object-rest-spread"
  ]
}
```

**Comment by snuggs** [comment]
@eventualbuddha have been working on a tool past couple weeks that should solve startup problems in the future. `buble-tape` #WIP.  I knew this was going to happen as same situation happened in the ruby community. just need a thin wrapper of conventions.

Best part is it's not a toy project. It was driven from the same concerns @ghost is having. Other will have it.

Your thoughts...

https://github.com/snuggs/buble-tape

**Comment by braco** [comment]
Is this because of acorn? If so,

https://github.com/UXtemple/acorn-object-spread

Is there a way to pass acorn plugins from rollup config?

**Comment by jharris4** [comment]
I ran into an issue getting the object spread operator to work, which seems to depend on the order of the plugins in my rollup.config.js. Described in the issue comment here: https://github.com/rollup/rollup/issues/1148#issuecomment-275922534
