### ISSUE TITLE
Documentation for `output.paths` is ambiguous

### ISSUE THREAD

**Issue by jacksteamdev** [rollup/rollup#3571]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The documentation for `output.paths` is ambiguous regarding when is it applied. 

- What happens to a module id not listed in `external`?
- Between what plugin hooks does it run? 
- Does it run before or after the plugin `node-resolve`?

### Your Proposal for Changes

We should document this more clearly. If someone wants to clarify in a comment here, I'll be glad to put together a PR! 🙂

**Comment by lukastaegert** [comment]
> What happens to a module id not listed in external

That depends. If it is not listed in external but cannot be found, it becomes external automatically and a warning is displayed. This case will be handled exactly the same as if it was listed as external explicitly.

Otherwise, `output.paths` is not applied, this option is strictly for external dependencies. At the moment, there is no elegant way to rewrite imports of internal dependencies, i.e. other chunks, elegantly. The only way is to manually adjust them in the `renderChunk` hook.

This would be definitely a separate issue to discuss but I would be interested to hear about scenarios where internal chunk imports should be rewritten. Some knowledge about interesting scenarios here would help us spec out a good api for this in the future.

> Between what plugin hooks does it run

At the moment, it is run after `renderDynamicImport` and just before `augmentChunkHash` would run.

> Does it run before or after the plugin node-resolve

`node-resolve`, or any other module resolution, is run much earlier during the build phase, which is shared for all outputs. `output.paths` is run during the output generation phase and allows to rewrite external dependencies just for a single output. The scenario here is e.g. to have one output where a dependency is loaded from a CDN instead of node_modules.

> If someone wants to clarify in a comment here, I'll be glad to put together a PR

I hope this helped, documentation PRs are ALWAYS very welcome!

**Comment by lukastaegert** [comment]
> This would be definitely a separate issue to discuss but I would be interested to hear about scenarios where internal chunk imports should be rewritten. Some knowledge about interesting scenarios here would help us spec out a good api for this in the future.

Maybe #3570 could be a good place to collect ideas here.

**Comment by jacksteamdev** [comment]
@lukastaegert Thanks for the friendly and well put answer! I've submitted a PR that hopefully distills this down to a few lines for the docs.
