### ISSUE TITLE
Allow specifying implicit dependencies when emitting chunks for better chunking

### ISSUE THREAD

**Issue by LarsDenBakker** [rollup/rollup#3574]
- Rollup Version: 2.10.5
- Operating System (or Browser): Chrome (the REPL runs in the browser?)
- Node Version (if applicable): NA
- Link to reproduction (IMPORTANT, read below): https://repl.it/repls/SpeedyEasyCoordinates

**Update**: As the discussion drifted towards a new feature, this text is no longer applicable, see the comments below.

### Expected Behavior
When manually emitting a chunk using `emitFile`, I would expect the emitted chunk to respect the `preserveEntrySignatures` option and reuse exports from the main entrypoint when they are available. 

### Actual Behavior
A new chunk is created and shared between the main entrypoint and the emitted chunk. 

When I trigger a chunk creation through a dynamic import, it does work correctly.

**Comment by lukastaegert** [comment]
Did you try the `preserveSignature` flag? https://rollupjs.org/guide/en/#thisemitfileemittedfile-emittedchunk--emittedasset--string

It is decoupled from main options as chunks are emitted by plugins and there may or may not be reasons to preserve their signature that are only known to the plugin.

**Comment by LarsDenBakker** [comment]
Yep, this is the config (see the REPL to see it in action)

```js
import path from 'path';

export default {
  input: 'src/main',
  preserveEntrySignatures: 'allow-extension',
  output: { format: 'esm' },
  plugins: [
    {
      buildStart() {
        this.emitFile({
          type: 'chunk',
          id: 'shared-chunk',
          preserveSignature: 'allow-extension',
          name: 'shared-chunk',
        });
      },

      resolveId(id) {
        if (id === 'shared-chunk') {
          return id;
        }
      },

      load(id) {
        if (id === 'shared-chunk') {
          return `export * from '${path.resolve('src/my-lib.js')}';`;
        }
      },
    }
  ]
};
```

**Comment by lukastaegert** [comment]
In your example, everything is working correctly. As "my-lib" is actually shared between the chunks, it needs to go into a separate chunk. The reason is that Rollup does not know that both "main" and "shared-chunk" contain nothing but reexports. Thus it assumes they also contain some custom code that should not be executed when only the other chunk is loaded and cannot merge "my-lib" into one of the chunks. Admittedly, this could be improved.

> It is decoupled from main options

Actually this is not true. Instead, it uses the value defined by the user unless overridden by the emitting plugin.

**Comment by lukastaegert** [comment]
See also #3541

**Comment by LarsDenBakker** [comment]
I understand this would be the case in #3545 because the other chunk is an entrypoints. 

But when I emit a chunk manually it's not an entrypoint. And since there is only a single entrypoint it is always loaded before anything else. When I use a dynamic import to load this other chunk, it does happen the way I expected. I guess that's because then rollup knows who is the actual initiator of the dynamic import?

**Comment by lukastaegert** [comment]
emitted files are treated just like regular entry points. Rollup makes no assumption in which order they are loaded. Consider a worker: In a worker thread, no code is loaded before the worker entry point. We could however add an option to say: Assume that this entry is only loaded after those entries are loaded, i.e. treat it like a dynamic import for chunking purposes. Sounds like that is actually what you are after?

**Comment by LarsDenBakker** [comment]
Ah I see, yeah that makes sense. I think an option like that would be useful.

**Comment by lukastaegert** [comment]
Maybe we could allow to add an array of module ids when emitting files to say that "do the chunking as if those modules dynamically import this entry"

**Comment by LarsDenBakker** [comment]
Sounds good, that would be make it work for non-entrypoint modules too.

**Comment by LarsDenBakker** [comment]
@lukastaegert Do you think this will be complex to implement? Maybe with some pointers I could try to make  PR for this.

**Comment by lukastaegert** [comment]
If we go with the suggestion to make it work like dynamic imports, it should not be too difficult algorithmically. There are however several questions that need to be answered first, which makes this slightly non-trivial:

- what should the additional emit option be called like?
- should it really be an array? This might be counter-intuitive to some people as chunking will get WORSE the more entries the array has. I.e. if there is a single entry, it will assume that all static dependencies of this module are loaded. If there are two, only the intersection of dependencies can be assumed to be loaded. At the very least, the docs need to explain this carefully
- should it be represented in the return of `this.getModuleInfo`? If so, in what way? Should there also be a representation in the return value of `bundle.generate`? Tools might use this information to automatically load dependent chunks in the correct order.
- how should we handle if one of the provided ids does not exist or is external. Ignore, warn or error? And if we error, at what point? If we do it while emitting, the graph may be incomplete. If we do it after the graph is complete, we may lose the information which plugin emitted the file and the error/warn might not be as helpful.

If we have good answers for these questions, implementation should be rather smooth.

**Comment by LarsDenBakker** [comment]
Is it possible to hook it up to the regular dependency graph logic? So you emit the file and from there on it is treated as if it is imported by the specified module(s). This would solve a some of the questions and reuse a lot of existing logic. 

- what should the additional emit option be called like?
If we can reuse existing dependency graphing logic, it could be something like `importers` or `dependants`. Otherwise something like ` virtualImporters`, `manualImporter`, `virtualDependants`, `manualDependants`.

- should it really be an array? 
I think it should be. It's a power user feature, you need to know what you're doing. But it should be documented properly of course.

- should it be represented in the return of `this.getModuleInfo` and `bundle.generate`
If we can reuse existing logic, it could be available under the existing properties. Otherwise it could be exposed under the name we pick in the emit option.

- how should we handle if one of the provided ids does not exist or is external.
I think doing it after the graph is complete is the only option. Showing the chunk name should help pointing out which one it is.

**Comment by lukastaegert** [comment]
> Is it possible to hook it up to the regular dependency graph logic? So you emit the file and from there on it is treated as if it is imported by the specified module(s). This would solve a some of the questions and reuse a lot of existing logic

Yes, that would be the plan. But some modification would still be needed. For the chunking to pick this up, the new dependencies need to be processed the same way as dynamic imports here https://github.com/rollup/rollup/blob/462bff7b1a0c384ecc3e278b1ea877e637c70f41/src/utils/chunkAssignment.ts#L119-L120 and here https://github.com/rollup/rollup/blob/462bff7b1a0c384ecc3e278b1ea877e637c70f41/src/utils/chunkAssignment.ts#L144-L148 and in theory that should do the trick.

Also, such emitted files can no longer be regular entry points. So when such a file is emitted here https://github.com/rollup/rollup/blob/462bff7b1a0c384ecc3e278b1ea877e637c70f41/src/utils/FileEmitter.ts#L280 we need to signify that this is not really an entry but something that depends on other stuff when calling `ModuleLoader.addEntryModules` (most of the logic here would still apply, though, so maybe an additional property on `UnresolvedModule`?). For easy graph lookup, the `ModuleLoader` should add corresponding properties to both the new files and the files that depend on the new file.

> If we can reuse existing dependency graphing logic, it could be something like importers or dependants

I'm starting to like to call such dependencies "implicit dependencies" as they are not reflected explicitly in the code, what do you think? And maybe `importer` is not really correct here due to the implicit nature. Then modules could receive `implicitDependencies` and `implicitDependants`, similar to `imports` and `importers`.

> it could be available under the existing properties

I'm hesitant to reuse the existing properties because they imply a relationship that does not exist. My thinking is that if there is an actual dynamic import, I do not have to take care that the other chunk is loaded but if there is an implicit dependency, action needs to be taken by the user to ensure load order. Tooling might read this information to do that.

So with the suggestion above, `this.getModuleInfo` could return

```ts
interface ModuleInfo {
	dynamicallyImportedIds: string[];
	dynamicImporters: string[];
	hasModuleSideEffects: boolean;
	id: string;
	implicitDependants: string[];
	implicitDependencies: string[];
	importedIds: string[];
	importers: string[];
	isEntry: boolean;
	isExternal: boolean;
}
```

while for symmetry, we extend the output of generate to

```ts
interface PreRenderedChunk {
	dynamicImports: string[];
	exports: string[];
	facadeModuleId: string | null;
	implicitDependencies: string[];
	imports: string[];
	isDynamicEntry: boolean;
	isEntry: boolean;
	modules: {
		[id: string]: RenderedModule;
	};
	name: string;
}
```

> I think doing it after the graph is complete is the only option. Showing the chunk name should help pointing out which one it is.

👍

Then I think we are all set. If you want to give it a shot, please let me know, if you open a PR we can also collaborate on this one if you do not prevent maintainer commits. Otherwise, I can look into this once I am through with the current open PRs.

**Comment by lukastaegert** [comment]
I have started working on this but it will take at least another day until I will have something to play around with

**Comment by lukastaegert** [comment]
First draft PR here: #3606
