### ISSUE TITLE
Cannot read property 'bind' of undefined, but only when compiling/bundling via script

### ISSUE THREAD

**Issue by darrickyee** [rollup/rollup#3578]
- Rollup Version: 2.9.0+
- Operating System (or Browser): Windows 10
- Node Version (if applicable): 12.16.3 (latest LTS)
- Link to reproduction (IMPORTANT, read below): https://github.com/darrickyee/rollup-test

To reproduce, download the linked repository, install dependencies, and run the "build" script (`npm run-script build`).

The overall goal is to compile the Typescript files with typings, then use rollup to bundle the resulting JS files, and `dts()` to bundle the typing files.

main.ts has a single line `export * from './elem/myelem';`.  The project also has a script called "build" that executes `tsc && rollup -c`.

If I execute the script, I get the error.  However, the error does NOT occur if I do ANY of the following:

1. Change main.ts to `export { templ } from './elem/myelem';` instead of `export * from './elem/myelem';`. 

2. Execute `tsc && rollup -c` from the command prompt instead of running the npm script (on Windows).

3. Revert Rollup to version 2.8.2 or earlier.

I think I am not expert enough in NPM to be able to figure out why this is happening, or why it's happening with the latest Rollups but not earlier versions.  Any idea on what's going on?

### Expected Behavior

`build` script executes without errors.

### Actual Behavior

Error: `Cannot read property 'bind' of undefined`

**Comment by lukastaegert** [comment]
> Execute tsc && rollup -c from the command prompt

The reason this behaves differently is that this will use the versions of tsc and rollup installed in your global node_modules instead of your local ones. If you do `npx tsc && npx rollup -c`, you will see the issue again.

I had a look but it keeps coming back to the fact that rollup-plugin-dts is creating a non-standard AST. Namely, the AST node for ExportAllDeclaration does not have an `exported` property while it should have `exported: null`. This is not really the plugin's fault; the `exported` property was added only very recently in ES2020. Still, the plugin would benefit from adding it.

**Comment by lukastaegert** [comment]
I think we might be able to work around this, though.

**Comment by lukastaegert** [comment]
Actually it would cause further bugs down the line if we work around this. The problem is that if the first AST that Rollup parses comes from rollup-plugin-dts, further ASTs that use the `exported` property that are parsed later may be broken because the property is missing.

**Comment by lukastaegert** [comment]
Would you create an issue for that plugin?

**Comment by darrickyee** [comment]
Thank you!  I've gone ahead and created an issue in the rollup-plugin-dts repo.

**Comment by darrickyee** [comment]
Just tested with rollup-plugin-dts 1.4.7 and rollup 2.10.7, and it works.  Thanks!!
