### ISSUE TITLE
Rollup doesn't transpile to ES5?

### ISSUE THREAD

**Issue by Kflash** [rollup/rollup#359]
Hi. I just discovered that Rollup doesn't transpile to ES5 from ES2015. How to activate this? 

I got uglify issues and can't make a minified code now because of this it seems.

**Comment by Kflash** [comment]
Finally. I got it to transpile, and ran into a new issue now. module.exports not found in browser environment.
Ok. I'm going to TRY to solve this issue as well, but after that if I ran into more, I push the delete button and publish a 12 page info about my horrible experience with Rollup. Got enough now.

**Comment by eventualbuddha** [comment]
@Kflash There's very little we can do to help without specifics. The [`rollup-starter-project`](https://github.com/rollup/rollup-starter-project) already demonstrates how to transpile from ES2015 to ES5. If there's something that could be done to make it more clear we'd be happy to adjust as needed.

From what I can tell, it sounds like you're trying to compile to CommonJS output instead of e.g. globals. If you do not provide a CommonJS shim in your browser then that explains why `module.exports` is undefined. I believe the documentation covers this, but again, if there's some way we can improve it we'd like to hear it.

I'm going to close this, but I'll reopen if you provide more details (i.e. code, configuration) about what you're trying to do and what isn't behaving as you expect.

**Comment by Kflash** [comment]
I figured it out and got it working.
However. I guess this is all a hacky solution:

https://github.com/Kflash/boily/blob/master/config/rollup.config.js
