### ISSUE TITLE
import { default as unit } from './js/unit.js';

### ISSUE THREAD

**Issue by x8core** [rollup/rollup#3622]
Yo!

Why rollup not support import like this?

```
import { default as unit } from './js/unit.js';
```
and in unit.js i have

```
export default async(msg) => {
    console.log('super-fun');
}
```

After run rollup -c rollup.config.js

i got this.

(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
path (imported by ../anyx/src/index.js)
util (imported by ../anyx/src/index.js)
http (imported by ../anyx/src/index.js)

But after use module resolve i got another issue.
```
[!] Error: 'default' is not exported by ../anyx/node_modules/express/index.js, imported by ../anyx/src/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
../anyx/src/index.js (9:9)
 7: import * as cookie from 'cookie';
 8: import * as fsExtra from 'fs-extra';
 9: import { default as express } from 'express';
             ^

```

In webpack everything working ok.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
