### ISSUE TITLE
Does not export makeDOMDriver error. Is it a bug or incorrect setup?

### ISSUE THREAD

**Issue by arlair** [rollup/rollup#366]
Hi, I decided to try rollup on one of the Cycle.js examples by replacing browserify. It needs to create a standalone bundle.

I get the following error:

    Module /Users/arlair/n/cycle-rollup-example/node_modules/@cycle/dom/lib/cycle-dom.js does not export makeDOMDriver (imported by /Users/arlair/n/cycle-rollup-example/src/main.js)

Cycle.js does use ES6 code, but I think because there is no js next it is using the ES5 code so I was using the npm and commonjs plugins and included both typescript and babel plugins.

relevant parts of cycle-dom.js

    var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

    ...
    
    var _require = require("./render-dom");

    var makeDOMDriver = _require.makeDOMDriver;

    ...

    var CycleDOM = _extends({
      makeDOMDriver: makeDOMDriver,
    ...
    });

    module.exports = CycleDOM;    

I created a repo [here](https://github.com/arlair/cycle-rollup-example) if it is any help to see what I have setup. I'm not sure if I have configured something incorrectly or if it is a bug in Rollup.

**Comment by eventualbuddha** [comment]
Thanks for the thorough description and example repository! That makes figuring out what is going on much easier. The `rollup-plugin-commonjs` package can only [detect named exports written in a fairly specific way](https://github.com/rollup/rollup-plugin-commonjs/blob/a05e05921b24abc72f6a9212790b8bf2f902b218/src/index.js#L82-L102), namely `exports.foo = bar;` or `module.exports = { some: object };`. Because `cycle` uses `module.exports = CycleDOM;` there's no good way to determine what the named exports would be without running the code, so it falls back to simply treating it as a single default export. Therefore you need to use it like so:

```js
import DOM from '@cycle/dom';
const {makeDOMDriver} = DOM;
```

It's not ideal, but it's probably the best we can do for now. One way to improve it would be to get the `cycle` package to use ES6 modules in their ES6 version and include a build that leaves them in place (along with `jsnext:main` for bonus ease-of-use!).
