### ISSUE TITLE
Browser API Incremental builds

### ISSUE THREAD

**Issue by baryla** [rollup/rollup#3665]
I've noticed that rollup's `watcher` isn't exported in the browser API which means that it's pretty much impossible to do incremental builds without any complex plugin (maybe even that wouldn't help). Are there any plans for something that would help with that? If not, do you have any pointers how something like this could be tackled? I have some ideas but nothing concrete yet.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
