### ISSUE TITLE
How to get rid of forced stupid code in compiled source?

### ISSUE THREAD

**Issue by himalayafan** [rollup/rollup#367]
Hey. Great work! However. I like my code clean and nice looking. Like a one single file.
I see that after I bundled it get poisoned with babelhelpers on top of the file.
Some extra bytes to my code I never added, and don't want there.

How to get rid of it ????????

And I get loads of errors if I try to use babel 2015 preset. What's wrong with rollup?

**Comment by eventualbuddha** [comment]
@himalayafan Could you provide more details about the project you're using rollup with? What is the code you're trying to use rollup with? What is your rollup configuration? What is the output you're getting versus what you expect? The addition of babel helpers is expected if you're using the `rollup-plugin-babel` package and using ES2015 constructs that require them.

**Comment by Kflash** [comment]
@eventualbuddha  I have same issues as @himalayafan and tried to refactor my rollup config to solve. Is there any workaround for this?

My rollup config: https://github.com/trueadm/inferno/blob/dev/config/rollup.config.js

**Comment by himalayafan** [comment]
I skipped Rollup and ended up using Browserify. So this is not an issue for me anymore.

**Comment by eventualbuddha** [comment]
@himalayafan Okay, no problem. Would you mind helping to make rollup better for others by explaining a bit more what you meant originally?

@kflash I'll took a look at your config, but without knowing what part of the output you're talking about I don't know how to help.

**Comment by Kflash** [comment]
@eventualbuddha in my case if I bundle this code. Babel helpers are injected in top of the page. 
I tried to find a workaround so this not happen.

Normal babel 2015 won't work.  So I tried with all plugins minus cjs plugin. It start screaming for helpers.

I also noticed on rollup babel page that I need to include the helpers...

No way around? 56 lines of nasty looking code I never need.

Btw. And off topic. Environment variables. How to get them to work aka react solution for dev mode.
The replace plugin didn't help me here. It only replace text it seems.

**Comment by Rich-Harris** [comment]
@Kflash The [instructions](https://github.com/rollup/rollup-plugin-babel#babel-6) are perfectly clear – if you're using Babel 6, use the [babel-preset-es2015-rollup](https://github.com/rollup/babel-preset-es2015-rollup) preset, which excludes modules and includes helpers.

> I bundled a lot of es2015 and this is the first time I need helpers.

You know why? Because unless you instruct it not to, Babel will insert the helpers at the top of *every individual file* that needs them. rollup-plugin-babel makes your bundle smaller by only including them once in the entire bundle. Otherwise that '56 lines of nasty looking code I never need' would be a lot more.

> Btw. And off topic. Environment variables. How to get them to work aka react solution for dev mode.
> The replace plugin didn't help me here. It only replace text it seems.

Yes, it replaces text like `'process.env.NODE_ENV'` with `'development'` or `'production'`. Very simple really. But you're right, it's off topic – if you're having problems, open an issue on that repo.
