### ISSUE TITLE
Rolling up chokidar with plugin-commonjs breaks due to fsevents dependency (non-Darwin platforms)

### ISSUE THREAD

**Issue by christiantjl** [rollup/rollup#3681]
- Rollup Version: 2.21.0
- Operating System (or Browser): Ubuntu 20.04
- Node Version (if applicable): 14.5
- Link to reproduction (IMPORTANT, read below): https://repl.it/@christiantjl/rollup-repro#rollup.config.js

### Expected Behavior
`rollup --config` should execute without errors and write output to a file, and `node output.js` should execute without errors.

### Actual Behavior
In my live environment, I can roll the script up, but executing the output with `node output.js` will throw `Error: Cannot find module 'fsevents'`. On repl.it, the rollup process initially succeeded, but now fails at the package installation stage, i.e.:

```none
Repl.it: Updating package configuration

--> npm install fsevents
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-07-18T20_37_47_805Z-debug.log
exit status 1
```

Please close if this belongs in the plugins repo, I just assumed the rollup tool itself might want to handle platform-specific dependencies.

**Comment by lukastaegert** [comment]
You will not be able to bundle fsevents. Rollup itself is bundling chokidar, and we had to jump through quite a few hoops to make it work, namely to patch the chokidar code in a plugin hook. The problem is
1. fsevents is an optional dependency that is only installed on MacOS. Making it external does not really work because the CommonJS pattern of requiring a dependency in a try-catch and then not using it when it throws can not easily be translated to ESM. The CommonJS plugin will just make it a static dependency of your bundle that will make it throw if it is not installed.
2. You cannot bundle on MacOS either because fsevents contains binary code that cannot be handled by Rollup.

In Rollup, we ended up creating a stateful wrapper module https://github.com/rollup/rollup/blob/master/src/watch/fsevents-importer.ts that is imported first before we dynamically import a patched version of chokidar that then references the wrapper module https://github.com/rollup/rollup/blob/master/build-plugins/conditional-fsevents-import.js. It relies on code-splitting, I do not think if you can make it work easily in a single bundle.

**Comment by lukastaegert** [comment]
Otherwise if you expect any improvements on Rollup side, they would need to happen in the CommonJS plugin and therefore that repo. But I do not want to keep your hopes up.

**Comment by christiantjl** [comment]
Okay, thank you very much for your explanation @lukastaegert.
