### ISSUE TITLE
`this` has been rewritten to `undefined` when importing moment.js

### ISSUE THREAD

**Issue by orobert91** [rollup/rollup#3685]
When using latest moment version and compiling with Rollup:

```
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules\moment\moment.js
 9:     typeof define === 'function' && define.amd ? define(factory) :
10:     global.moment = factory()
11: }(this, (function () { 'use strict';
      ^
12:
13:     var hookCallback;
```

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by aminya** [comment]
@orobert91 This also happens in the coffee-script plugin. The reason is that Rollup replaces any `this` that is not inside a function or class with `undefined`.

Does your code stop working or it does not affect the bundle?
https://github.com/lautis/rollup-plugin-coffee-script/issues/7

**Comment by orobert91** [comment]
Yes it still seem to work for what I use of the library, but still I don't like to have warnings that I don't know how to fix and was wondering if it's caused by a bug in roll-up or a problem in moment.

**Comment by aminya** [comment]
Maybe we can improve the warning and give more useful information in the text. That sounds like a PR!

**Comment by LarsDenBakker** [comment]
It feels like this warning comes from an era before es modules were commonplace, and there was a need to educate developers. With native es module development workflows becoming more commonplace, if someone uses a global `this` it's most like deliberate as some form of feature detection. I wonder if it makes sense to keep warning about this.

**Comment by aminya** [comment]
CoffeeScript 2 still generates these in ES6. Check my issue here: https://github.com/lautis/rollup-plugin-coffee-script/issues/7#issue-655567805

However, I am not sure in which case this is important.
