### ISSUE TITLE
when i pack up CMD module, I get a problem

### ISSUE THREAD

**Issue by PGambler** [rollup/rollup#3699]
my module like :

	// a.js
	
	global.a = 1;
	
	global.b = require('./b')
	
	console.log(global.a)

other one:

	// b.js
	
	global.a = 2
	
	module.exports = 3
the config:

    // rollup.config.js
    
    import resolve from 'rollup-plugin-node-resolve';
    import commonjs from 'rollup-plugin-commonjs';
    
    export default {
      input: './a.js',
      output: [
    	{ file: 'bundler.a.js', format: 'cjs' }
      ],
      plugins: [
        resolve({
          extensions: ['.js', '.coffee'],
          customResolveOptions: {
            moduleDirectory: 'node_modules'
          }
        }),
        commonjs({
          extensions: ['.js', '.coffee']
        })
      ]
    }
the pack up result:

    'use strict';
    
    var commonjsGlobal = typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};
    
    commonjsGlobal.a = 2;
    
    var b = 3;
    
    commonjsGlobal.a = 1;
    
    commonjsGlobal.b = b;
    
    console.log(commonjsGlobal.a);
    
    var a = {
    
    };
    
    module.exports = a;

this bundle will print 1, but It was supposed to be 2.

i find all the variable in main program is defined in bundle end.

when i want the global variable in main program define in bundle head, what should i do?

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by aminya** [comment]
@PGambler This seems like a tricky situation. Rollup does not handle the order that global variables are called. Could you define `a` in the second file as an exported variable and then import it in the second file?

**Comment by PGambler** [comment]
@shellscape Thank you for your reply, I am not good at make a issue, I will refer to other people's issue to re-propose

**Comment by PGambler** [comment]
@aminya Thank you for your reply, I think exported variable could‘t solve my problem. I hope I can get a global variable at dependent modules, But it is always is undefined ...

**Comment by lukastaegert** [comment]
The problem is that at this point, `@rollup/plugin-commonjs` does not preserve exact execution order. Top-level require statements are hoisted you the beginning, messing it up for you. There is unfortunately no good solution to this. If you need to write CommonJS, try to move all your require statements to the top to not trip up here.
