### ISSUE TITLE
Circular dependency bundling error

### ISSUE THREAD

**Issue by ile** [rollup/rollup#3713]
- Rollup Version: 2.23.1
- Link to reproduction (IMPORTANT, read below):https://github.com/ile/quill-delta-test

### Expected Behavior, Actual Behavior

I'm bundling the package https://github.com/quilljs/delta/. With that I'm creating a delta of the html code (html included in the repository). Then the html code is modified and a new delta and a diff is created. Webpack can do this but the one bundled with rollup fails.

There is a circular dependency in `quill-delta` and it seems that the rollup version fails because of that. If you inspect the bundled code, there is a class initialization before the bundling takes place in rollup's created code. This all works with webpack though.

Thank you.

**Comment by shellscape** [comment]
Closing this for a couple reasons:

- Missing sections of the issue template
- There are a multitude of other issues addressing circular dependencies, what it means in Rollup, how to address, and if nothing can be done. Please search the issues before opening a new one: https://github.com/rollup/rollup/issues?q=circular

**Comment by ile** [comment]
I'll use webpack and regret the wasted time for creating this issue.

**Comment by shellscape** [comment]
It always strikes me as odd that folks will respond in that way.

First and foremost, it's really not our fault that instructions weren't followed. It's a huge bummer that any amount of time is wasted, and we feel that because our time is certainly as valuable. But that time was wasted due to a failure to follow instructions; instructions that exist to save everyone's time and effort.

The notion that using another open source tool to perform a job is somehow a bad thing is always curious. Rollup isn't in competition with Webpack, and when someone chooses Webpack over Rollup, we cheer. We cheer because a rising tide lifts all ships, and it's great to have alternatives in software just like it's great to have alternative routes on the road.

We're here to work on something we love and provide help where we can. Unless a project has a large amount of funding, an open source project is maintained freely with donated time from the folks who care. Here, respect is mutual, and we ask users to respect the time and effort given freely to the world by the maintainers by following some super simple instructions when seeking help.

I'd highly recommend reading The Libera Manifesto, as it might give some valuable perspective to a user new to Github and new to the world of open source https://liberamanifesto.com/
