### ISSUE TITLE
Write CSS outside the JS destination folder

### ISSUE THREAD

**Issue by 8483** [rollup/rollup#3776]
Why is the path relative to the `bundle.js` destination?  

I need to save the CSS in a separate location, **outside** the destination, and it doesn't allow it, gives this error.

```
Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute 
nor relative paths and do not contain invalid characters, received "/bundle-svelte-activities.css".
```

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
