### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined

### ISSUE THREAD

**Issue by kri7217** [rollup/rollup#3804]
function PrivateKey(opts) {
	assert_1.object(opts, 'options');
	key$1.call(this, opts);

	this._pubCache = undefined;
}
util__default['default'].inherits(PrivateKey, key$1);  //Here key$1 is undefined and leads to this error

var key$1 = function(){}
..........................................................................................................................................

Key$1 coming as undefined.
Above apart of the code is generated by rollup.

Error:
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined
at Proxy.inherits (util.js:280:11)

- Rollup Version: 2.0.0
- Operating System (or Browser): Ubuntu 18.04
- Node Version (if applicable): 10.16

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
