### ISSUE TITLE
The command line did not exit after execution

### ISSUE THREAD

**Issue by chnliquan** [rollup/rollup#3827]
- Rollup Version: 2.3.4
- Operating System (or Browser): macos 10.15.7 
- Node Version (if applicable): v12.18.3
- Link to reproduction (IMPORTANT, read below): https://github.com/chnliquan/svelte-login-component

### Expected Behavior
the command line will exit after execution npm run build:rollup

### Actual Behavior
the command line did not exit after execution

**Comment by lukastaegert** [comment]
This is not Rollup's fault. Both your `serve` plugin and the live-reload plugin are spawning child processes/running tasks that prevent Rollup from exiting. Remove those plugins and everything is fine.

**Comment by chnliquan** [comment]
@lukastaegert `sever` and `live-reload` plugin just used in development mode, in production mode they not enable, but still not exit after execution

**Comment by lukastaegert** [comment]
If I run `npm run build:rollup` then everything exits nicely for me.

**Comment by lukastaegert** [comment]
Ah, actually it does not. It seems that just instantiating the `livereload` plugin creates a sub-process that prevents everything from exiting. This is definitely not an issue with Rollup but with the livereload plugin. My recommendation would be to only instantiate the plugin, i.e. call the function, if you are actually using it. Otherwise, please open an issue with that plugin.
