### ISSUE TITLE
Unexpected token (Note that you need plugins to import files that are not JavaScript `<!-- This file is generated by Sapper — do not edit it! -->`

### ISSUE THREAD

**Issue by thousandsofraccoons** [rollup/rollup#3833]
Hello, please help

```bash
Unexpected token (Note that you need plugins to import files that are not JavaScript 
<!-- This file is generated by Sapper — do not edit it! -->
```

How do I get rid of this error?

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
