### ISSUE TITLE
import('./index.css') is missing after packing

### ISSUE THREAD

**Issue by Yukyi** [rollup/rollup#3836]
Rollup Version: from 2.30.0

I want to introduce a CSS dynamically, import('./index.css')

I set  inlineDynamicImports: true . 

It's missing after packing

how can i introduce a CSS dynamically?

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
