### ISSUE TITLE
Why do output plugins run before input plugins?

### ISSUE THREAD

**Issue by aleclarson** [rollup/rollup#3844]
If both an input plugin and output plugin have a `generateBundle` hook, the output plugin's hook runs first. Is there a reason for this?

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by aleclarson** [comment]
@lukastaegert Ping. This is a question, not a support request.

**Comment by shellscape** [comment]
Looks like a documentation to me. Please use the issue templates. We ask this of everyone, maintainers included (even Lukas and myself), and we don't except anyone from this request, which is spelled out quite plainly in every issue template. We're all equal here.
