### ISSUE TITLE
Error: Could not load fs/promises

### ISSUE THREAD

**Issue by dman777** [rollup/rollup#3854]
using node v 15.0.1 and rollup v2.33.1

my file:

```
import fs from 'fs/promises';
```

error when building:

```
[!] Error: Could not load fs/promises (imported by src/exec-audit.js): ENOENT: no such file or directory, open 'fs/promises'
Error: Could not load fs/promises (imported by src/exec-audit.js): ENOENT: no such file or directory, open 'fs/promises'
```

rollup config:

```
import { nodeResolve } from '@rollup/plugin-node-resolve';
import multi from '@rollup/plugin-multi-entry';

export default {
  input: ['./src/exec-audit.js'],

  output: {
    file: './bin/exec-audit.js',
    format: 'cjs',
    banner: '#!/usr/bin/env node',
  },

  plugins: [
    multi(),
    nodeResolve(),
  ]
};
```

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
