### ISSUE TITLE
[!] Error: Could not resolve './components/picker-view' from src/index.js

### ISSUE THREAD

**Issue by youngjuning** [rollup/rollup#3855]
I want compile 

```
export { default as DatePicker } from './components/picker-view/
```

to

```
export { default as DatePicker } from './components/picker-view/
```

not

```js
export { default as DatePicker } from './components/picker-view/index.js
```

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/97988524-137dec00-1e18-11eb-8fbf-ff89b1ce4ae9.png)

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
