### ISSUE TITLE
Multiple conflicting contents for sourcemap with VUE

### ISSUE THREAD

**Issue by theajack** [rollup/rollup#3885]
I use rollup-plugin-vue to handle .vue file
In watch and sourcemap mode, if I change the vue file, the error Multiple conflicting contents for sourcemap source G:\code_src\github_projects\x-state\src\dev\main.vue happened.
But it works with js file

"rollup": "^2.33.3",
"vue": "^2.6.10",
"rollup-plugin-vue": "^5.0.1",

![image](https://user-images.githubusercontent.com/23377279/100497592-5f158280-3197-11eb-9562-7e0c948ed2cb.png)

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
