### ISSUE TITLE
how to upgrade to v7 and rollup.config.js

### ISSUE THREAD

**Issue by chovy** [rollup/rollup#3901]
I was using a year old version of svelte/sapper and I recently upgraded all the packages, but not the rollup.config.js is outdated I think.

I get this error in the UI:

App.render is not a function

Here is my rollup.config.js:

http://sprunge.us/aj5fs6

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
