### ISSUE TITLE
@babel/plugin-transform-runtime  :  Error: Could not load \node_modules\@babel\runtime\helpers\esm\extends

### ISSUE THREAD

**Issue by hkaikai** [rollup/rollup#3902]
**rollup.config.js**
```
...
babel({
    babelHelpers: 'runtime',
    presets: [
      [
        '@vue/babel-preset-app',
        {
          modules: false, // 禁用 Babel 的模块转换，而让打包工具来处理
          useBuiltIns: false, // 应用程序的用户来负责polyfill
          loose: true, // 看得懂的代码
        },
      ],
    ],
    // @babel/runtime-corejs3 新语法、全局变量、方法
    plugins: [['@babel/plugin-transform-runtime', { useESModules: true /**, corejs: 3  */}]],
  }),
...
```
**package.json**
```
"dependencies": {
    "@babel/runtime": "^7.12.5",
    "core-js": "^3.8.1",
  },
```
**error**
_[!] Error: Could not load \node_modules\@babel\runtime\helpers\esm\extends_

**错误出处**
**\node_modules\rollup\dist\shared\rollup.js**
[
![企业微信截图_16076041429784](https://user-images.githubusercontent.com/19343340/101773891-5b371800-3b28-11eb-84b0-8dbdb2aaadc1.png)
](url)

file missing _.js_

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
