### ISSUE TITLE
rollup striping away exports from the original input files?

### ISSUE THREAD

**Issue by hrstoyanov** [rollup/rollup#3912]
The issue is described at length [here](https://github.com/SAP/ui5-webcomponents/discussions/2618).

P.S: Also, please stop requiring people to create accounts and use discord just to chat... Github rolled out [Github Discussions](https://docs.github.com/pt/free-pro-team@latest/discussions) which is a much better and well integrated tool for discussion around Hithub projects

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
