### ISSUE TITLE
warning rollup > fsevents@2.1.3: "Please update to latest v2.3 or v2.2"

### ISSUE THREAD

**Issue by Valexr** [rollup/rollup#3925]
warning rollup > fsevents@2.1.3: "Please update to latest v2.3 or v2.2"

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
