### ISSUE TITLE
iife: return object with multiple named exports

### ISSUE THREAD

**Issue by mnater** [rollup/rollup#399]
Currently, when I _rollup_ this (format iife):

````javascript
export function bar (n) {
    return n;
}

export function baz () {
    return 42;
}
````

it results in this:
````javascript
(function (exports) { 'use strict';
    function bar(n) {
        return n;
    }

    function baz() {
        return 42;
    }

    exports.bar = bar;
    exports.baz = baz;

})((this.foo = {}));
````
but I'd prefer this:
````javascript
var foo = (function () {
    'use strict';
    function bar(n) {
        return n;
    }

    function baz() {
        return 42;
    }

    return {
        bar: bar,
        baz: baz
    };
    /* or if we don't want inherit from Object, something like:
    return Object.create(null, {
        bar: {value: bar},
        baz: {value: baz}
    });
    */
}());
````
because this looks much more like the iife we get on _default_ exportMode and it's -- imho -- easier to read.

What is the reason behind the current behaviour?

**Comment by Rich-Harris** [comment]
There are a couple of reasons it's done this way. The first is that it means we can reuse the same pattern with AMD and CommonJS, where the only way to support cyclical dependencies between your bundle and other modules – something that's really finicky to do manually – is to assign properties to an existing object rather than creating a new one.

The second reason is that [sometimes we need to modify the exports object](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22iife%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20var%20counter%20%3D%200%3B%5Cnexport%20function%20incr%20()%20%7B%5Cn%20%20counter%20%2B%3D%201%3B%5Cn%7D%22%7D%5D%7D) after the module's initial evaluation:

```js
export var counter = 0;
export function incr () {
  counter += 1;
}
```

If this used a return value instead, either we'd break the module semantics...

```js
(function () { 'use strict';

  var counter = 0;
  function incr () {
    counter += 1;
  }

  return {
    incr: incr,
    counter: counter // would never change!
  };

})((this.myBundle = {}));
```

...or we'd have to reintroduce the exports object anyway:

```js
(function () { 'use strict';

  var exports = {};

  exports.counter = 0;
  function incr () {
    exports.counter += 1;
  }

  exports.incr = incr;
  return exports;

})((this.myBundle = {}));
```

Because of all these tricky edge cases, it's easier to just do things in a consistent way, even if the end result is slightly counter-intuitive at first.

**Comment by Victorystick** [comment]
We could return the [_namespace objects_](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22iife%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22%2F%2F%20compare%20with%20%60export%20*%20from%20'.%2Fmod'%3B%60%5Cnimport%20*%20as%20ns%20from%20'.%2Fmod'%3B%5Cnexport%20default%20ns%3B%22%7D%2C%7B%22name%22%3A%22mod.js%22%2C%22code%22%3A%22export%20let%20count%20%3D%200%3B%5Cn%5Cnexport%20function%20inc()%20%7B%5Cn%20%20return%20count%2B%2B%3B%5Cn%7D%22%7D%5D%7D) that we use internally. It requires that we use ES5 getters, but since we already do it might be better.

With `exports`
```js
(function (exports) { 'use strict';

  exports.count = 0;

  function inc() {
    return exports.count++;
  }

  exports.inc = inc;

})((this.bundle = {}));
```

With `namespace objects`
```js
var bundle = (function () { 'use strict';

  let count = 0;

  function inc() {
    return count++;
  }

  return Object.freeze({
    get count () { return count; },
    inc: inc
  });

})();
```

**Comment by mnater** [comment]
Thanks for your explanations.

**Comment by Rich-Harris** [comment]
> Perhaps we should always use such objects and getters? That way we could get rid of `exports` altogether.

It would solve the bindings issue, but not the cyclical dependencies issue (because the `exports` object would get blown away). Also, it would fail in IE8 – not a huge deal, but still a reason not to do it that way. Will close this issue

**Comment by Victorystick** [comment]
I guess there's no point to `defineProperties` on `exports` instead? Sure, that would reintroduce the `exports` object, but eliminate the need to assign to any of its properties. Not a big enough gain I suppose.

Either way, some bundles produced by Rollup will fail in IE8 anyway because of the `internal namespaces` we create to preserve the binding semantics.
