### ISSUE TITLE
Allow relative requires to be treated as externals

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#410]
If I have:

```javascript
import 'dep.js';
```

I can return `false` in `resolveId` to have dep excluded from the rollup optimization.

But if instead I have:

```javascript
import './dep.js';
```

Then returning `false` in `resolveId` will give the error _Could not resolve ./dep.js from test.js`_.

Because we need externals to occur across module format boundaries in SystemJS, and a relative module can be say CommonJS, this case breaks down here.

**Comment by Victorystick** [comment]
This may be useful, but it could cause conflicts since `./dep.js` could point out any number of modules.

```
/project
  /src
    file.js
    dep.js
  index.js
  dep.js
```

Which `./dep.js` should be excluded? Any external modules must be an absolute path or an external name to avoid this ambiguity.

**Comment by guybedford** [comment]
This is a great point, and I think this could be considered a conflict due to a conflation of unresolved and resolved namespaces.

This can be avoided by letting the `externals` excludes act against the **resolved** module list. That is still run the `resolveId` function for possible externals, then check exclusions within the resolved namespace.

This way, we always know exactly what we are excluding as it happens in a concrete resolved namespace which is known to be unique.

**Comment by Rich-Harris** [comment]
Ha, we just passed each other @guybedford! Turns out great minds think alike – @Victorystick implemented it exactly as you suggest.

**Comment by guybedford** [comment]
Awesome! Thanks for your great work here :)

**Comment by joeldenning** [comment]
I've just been poring through the code and I'm not sure if I am missing something or if even after @Victorystick's pull request, rollup errors out because it's trying to resolve a relative import that I have specifically declared to be external. Below is a self contained example (I'm running rollup 0.25.4):

```
// rollup.config.js
export default {
    entry: 'src.js',
    dest: 'bundle.js',
    external: ['./dep.js'],
}
```

```
// src.js
import dep from './dep.js';

console.log(dep)
```

```
// dep.js
export default 1;
```

My expected result is that bundle.js would have an `import` statement for `./dep.js` still. But my actual result is the following error:
```
Error: Could not resolve ./dep.js from /Users/joel/playground/test/src.js
    at /Users/joel/playground/test/node_modules/rollup/www/ROLLUP/rollup/src/Bundle.js:186:42
    at tryCatch (/Users/joel/playground/test/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:185:12)
    at invokeCallback (/Users/joel/playground/test/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:197:13)
    at publish (/Users/joel/playground/test/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:168:7)
    at flush (/Users/joel/playground/test/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/asap.js:87:5)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3
```

I am certain that all of my file paths are correct because if I comment out the `externals` property, the bundle succeeds in putting `dep.js` into the bundle. I think that it has something to do with the [resolveId](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L33-L37) function because it [resolves `false`](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L34) when `./dep.js` is in the `this.externals` array, which then [fails the check](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L182) to determine if the module should be forced to be external.

Am I misunderstanding what @guybedford was going for with this issue or what @Victorystick was trying to do with the pull request? If so, would be happy to know why, and if not I'm happy to submit a pull request to fix it.

**Comment by joeldenning** [comment]
Ping.

If you'd prefer, I can create a new issue

**Comment by Victorystick** [comment]
@joeldenning Sorry for not getting back to you earlier. The `external` array is designed to contain the _resolved_ ids to be excluded (or the name of an external dependency); like

```js
external: [
  'library-foo',
  path.resolve( './dep.js' )
]
```

I suppose Rollup _could_ do the `path.resolve` invocations for you, but that feature has not yet been requested nor discussed.

**Comment by joeldenning** [comment]
Ah thanks. Is there anywhere in the guide, wiki, or Readme that explains this? If not I'd be happy to add to the docs.

**Comment by Victorystick** [comment]
@joeldenning Just updated [the wiki](https://github.com/rollup/rollup/wiki/JavaScript-API#external).

**Comment by TrySound** [comment]
@Victorystick Are you sure `import * as path from 'path'`? `import path from 'path'` works for me too.

**Comment by Victorystick** [comment]
@TrySound We are importing the entire "path" _namespace_, not the _default_ export, so I think it's more correct as it is.
