### ISSUE TITLE
SyntaxError: Unexpected token ')' in sequence elements with function

### ISSUE THREAD

**Issue by bahkostya** [rollup/rollup#4109]
- Rollup Version: 2.49.0 and higher
- Operating System (or Browser): MacOS BigSur 11.4 / Windows 10
- Node Version (if applicable): 14.16.1
- Link to reproduction (IMPORTANT, read below): https://replit.com/join/nwqpewuw-bahkostya

### Expected Behavior
```
npx rollup --version & npx rollup -c | node

src/main → stdout...
created stdout in 78ms
PASS
```

### Actual Behavior
```
npx rollup --version & npx rollup -c | node
rollup v1.31.0

src/main → stdout...
created stdout in 72ms
[stdin]:1
function test(){ console.log("PASS"); }(), 3;
                                        ^

SyntaxError: Unexpected token ')'
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at Object.runInThisContext (vm.js:309:10)
    at Object.<anonymous> ([stdin]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_stdin.js:29:5
    at Socket.<anonymous> (internal/process/execution.js:207:5)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
```

Related to https://github.com/rollup/rollup/issues/4105

**Comment by lukastaegert** [comment]
Could catch! Incidentally, I was just working on a PR for an issue with the same root cause but a different error message. As it turns out, #4110  will also fix this issue: https://rollupjs.org/repl/?pr=4110&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMjElMkMlMjBmdW5jdGlvbiUyMHRlc3QoKSU3QiUyMGNvbnNvbGUubG9nKCU1QyUyMlBBU1MlNUMlMjIpJTNCJTIwJTdEKCklMkMlMjAzJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

I will release it later today.
