### ISSUE TITLE
Lodash: Cannot read property 'exports' of undefined

### ISSUE THREAD

**Issue by tsminh** [rollup/rollup#4192]
Hello, I tried to make a simple module which wraps lodash (4.0.0), and seems like I can't used it in other react app.

The error is: Uncaught TypeError: Cannot read property 'exports' of undefined

My module structure:
```
src
 - index.ts
```

index.ts
```js
import { chunk } from 'lodash';

export default function test() {
  return chunk([1, 2, 2, 3, 4, 2, 3, 4, 5], 2);
}
```  

rollup.config.js
```js
import peerDepsExternal from 'rollup-plugin-peer-deps-external';
import cleaner from 'rollup-plugin-cleaner';
import babel from '@rollup/plugin-babel';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import ttypescript from 'ttypescript';
import typescript from 'rollup-plugin-typescript2';


export default {
  input: components,
  output: [
    {
      dir: 'lib',
      format: 'cjs',
      preserveModules: true,
      preserveModulesRoot: 'src',
      exports: 'auto',
    },
  ],
  plugins: [
    cleaner({ targets: ['lib'] }),
    babel({ babelHelpers: 'bundled' }),
    peerDepsExternal(),
    resolve(),
    commonjs(),
    typescript({
      typescript: ttypescript,
      tsconfig: 'tsconfig.build.json',
    }),
  ],
};
```

I noticed that if I turn off `preserveModules`, then I can use it properly.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
