### ISSUE TITLE
Can rollup 2.x plugins be declared in pure esm form?

### ISSUE THREAD

**Issue by mreinstein** [rollup/rollup#4203]
Every single rollup plugin I've looked at is authored with a build step that generates a commonjs output file.  I'm wondering if  there is anything in rollup that prevents one from implementing a pure esm module instead?

For example, this tiny plugin https://github.com/mreinstein/rollup-plugin-substrate

I haven't seen any mention in the the plugin authoring docs about what is expected/required here.

**Comment by lukastaegert** [comment]
When opening issues, please use the issue template instead of deleting it!
There is no issue with distributing plugins as ESM except that users need to be able to load them from config files. This only works if the config file itself is
1. ESM and
2. not transpiled (which currently means it uses the .mjs extension)
See here for further information: https://rollupjs.org/guide/en/#using-untranspiled-config-files

**Comment by mreinstein** [comment]
It sounds like the major limitation is that if someone is using `rollup.config.js` in their project, an esm only plugin won't work, is that right?

is https://github.com/rollup/rollup/pull/4123 the fix for (2) ?

**Comment by lukastaegert** [comment]
In a way yes, though if someone is using TypeScript, they would still transpile their config file to CommonJS, so having a CommonJS version never hurts.
