### ISSUE TITLE
Provide an way to modify Emited chunk in generateBundle | writeBundle hooks

### ISSUE THREAD

**Issue by hardfist** [rollup/rollup#4210]
### Feature Use Case

Given that rollup's bundle speedy is not fast, I want to leave third party module bundle to esbuild(and rollup bundle user code), considering supports code splitting, I need to modify the emited chunk in generateBundle hooks, which seem not supported yet
```ts
    async generateBundle(options, chunkMap) {
      const entryPoints = {};
      for (const [file, chunk] of Object.entries(chunkMap)) {
        if (file.endsWith('.js')) {
          entryPoints[path.resolve(config.root, file)] = chunk;
        }
      }
      const context = this;
      const result = await build({
        entryPoints: Object.keys(entryPoints),
        write: false,
        absWorkingDir: __dirname,
        bundle: true,
        outdir: '/assets',
        format: 'esm',
        allowOverwrite:true,
        splitting:true,
        plugins: [
          {
            name: 'memfs',
            setup(build) {
              build.onResolve({ filter: /.*/ },async (args) => {
                const realPath = path.resolve(args.resolveDir, args.path);
                if (entryPoints[realPath]) {
                  return {
                    path: realPath
                  };
                }else {
                  const result = await context.resolve(args.path, args.importer, {
                    skipSelf:true
                  })
                  return {
                    path: result.id
                  }
                }
              });
              build.onLoad({ filter: /.*/ }, (args) => {
                const res = entryPoints[args.path];
                if (res) {
                  return {
                    contents: entryPoints[args.path].code,
                    resolveDir: path.dirname(args.path)
                  };
                }
              });
            }
          }
        ]
      });
      for(const output of result.outputFiles){
        const fileName= path.relative('/', output.path);
        console.log('fileName:', fileName);
        // rollup not support emitChunk in generate bundle,which is hard to deal with
        this.emitFile({
          type: 'chunk', // support modify 'asset' but not support modify 'chunk'
          fileName: fileName,
          source: output.text
        })
      }
    }
```

### Feature Proposal

provide an hook likes `updateFile` to modify emited chunk & asset

**Comment by lukastaegert** [comment]
Emit them as "asset". "chunk" has a lot of implications (like Rollup actually processing it after emitting and generating a chunk from it) that do not work with what you are doing.

**Comment by hardfist** [comment]
> Emit them as "asset". "chunk" has a lot of implications (like Rollup actually processing it after emitting and generating a chunk from it) that do not work with what you are doing.

I actually use this plugin in vite, and vite internal plugin heavily depends on chunk(and asset doesn't have information like `facadeModuleId`and `isEntry`), so change `chunk` to  `asset` not play nicely with vite internal logic

**Comment by lukastaegert** [comment]
I also do not understand what this would accomplish: generateBundle is one of the last hooks, at this points "everything" happened. Why would you run esbuild *after* that? This will only make stuff even slower.
If you want to make things fast, I would expect you to run esbuild on some part of the input, i.e. at some point in the build phase.

**Comment by hardfist** [comment]
> I also do not understand what this would accomplish: generateBundle is one of the last hooks, at this points "everything" happened. Why would you run esbuild _after_ that? This will only make stuff even slower.
> If you want to make things fast, I would expect you to run esbuild on some part of the input, i.e. at some point in the build phase.

```
//index.ts
import * as lodash from 'lodash';
import {add}  from './add';
export function main(){
   lodash.map([1,2,3],x => add(x,1))
}
```

```
//add.ts
export const add = (a,b) => a+b;
```

in the generateBundle hooks, I will get chunk code as following
```
import * as lodash from 'lodash';
const add = (a,b) => a+b;
export function main(){
   lodash.map([1,2,3],x => add(x,1))
}
```
then I use esbuild to bundle lodash to the final chunk
```
xxxx lodash code
const add = (a,b) => a+b;
export function main(){
   lodash.map([1,2,3],x => add(x,1))
}
```

![image](https://user-images.githubusercontent.com/8898718/130313334-2845952c-e2b9-4b6b-8784-1f24e4bfd0ed.png)

It really reduce the build time after I use this plugin

**Comment by lukastaegert** [comment]
I see. So what you want is to emit an asset but add the same meta information as if it was a chunk. That should not be too difficult to add as a feature and might actually be useful for other things as well.

**Comment by hardfist** [comment]
> I see. So what you want is to emit an asset but add the same meta information as if it was a chunk. That should not be too difficult to add as a feature and might actually be useful for other things as well.

yes

**Comment by lukastaegert** [comment]
If someone wants to pick this up: One idea could be to add a third type of emitted file, let’s call it `prebuilt-chunk`.
In its simplest form, it would accept the same parameters as `chunk` but instead of an `id` it would receive a `code` and optionally `map`. It could also receive all meta-data that a chunk can have and fill in reasonable defaults if it is missing.
In the bundle, it would turn up as a regular `chunk`.
As a potential feature to build on this, we could allow to fill the chunk `code` and other details in a deferred way, similar to how `setSource` works for assets at the moment. That way, prebuilt chunks can be referenced from regular entries. But this can remain separate from an initial implementation.

**Comment by TrickyPi** [comment]
I would try to do it.

**Comment by TrickyPi** [comment]
I'm implementing the `prebuilt-chunk` api, and I have a problem that we should create an entry module for the prebuilt-chunk and load its deps? But the `prebuilt-chunk` doesn't accept the id needed to create the module.

**Comment by lukastaegert** [comment]
> we should create an entry module for the prebuilt-chunk and load its deps?

Not sure I understand you here. The "chunk" itself would not have an entry module as the chunk is just an "asset" of data that happens to have some chunk attributes. We might load its dependencies (that we could get from the information passed when the chunk is created), but for the initial implementation we could also just forbid that a prebuilt-chunk has dependencies.
But of course yes, the chunk needs an `id` or a `fileName`, otherwise other modules cannot reference it. For the first version, we might limit it to `fileName` because otherwise, the name can contain a hash, which will make it harder to reference.

This is what emitting a `prebuilt-chunk` could look like:

```js
this.emitFile({
  type: 'prebuilt-chunk',
  fileName: 'my-chunk.js',
  code: 'export const foo = "bar";',
  map: null // or a proper SourceMap,
  exports: ['foo']
});
```

All other properties of `OutputChunk` might be initialized with defaults, i.e. it will become

```
{
  // properties we set
  code: 'export const foo = "bar";',
  map: null,
  fileName: 'my-chunk.js',
  exports: string[],

  // properties with default values
  facadeModuleId: null,
  isDynamicEntry: false,
  isEntry: false,
  isImplicitEntry: false,
  moduleIds: [],
  name: 'my-chunk.js',
  type: 'chunk',
  dynamicImports: [],
  implicitlyLoadedBefore: [],
  importedBindings: {},
  imports: [],
  modules: {},
  referencedFiles: []
}
```

To use the chunk in code, a plugin will need to declare it as "external" in a `resolveId` hook, i.e.

```js
const plugin = {
  resolveId(id) {
    if (id === 'my-chunk.js') {
      return {
        id: 'my-chunk.js',
        external: true
      }
    }
  }
}
```

Then any code can just `import {foo} from 'my-chunk.js'`. This would be really very basic but already useful. We can then implement additional features based on user requests.
