### ISSUE TITLE
rollup does not build on Windows virtual drives

### ISSUE THREAD

**Issue by egonelbre** [rollup/rollup#4260]
With Windows virtual drives the `npm ci` does not work for the given project.

To reproduce the issue run the following commands:
```
mkdir vdrive
subst X: vdrive
X:
git clone https://github.com/rollup/rollup.git
cd rollup
npm ci
```

This fails with:
```
> rollup@2.58.3 build
> shx rm -rf dist && git rev-parse HEAD > .commithash && rollup --config rollup.config.ts --configPlugin typescript && shx cp src/rollup/types.d.ts dist/rollup.d.ts && shx chmod a+x dist/bin/rollup


cli/run/loadConfigFile.ts, src/node-entry.ts → dist...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
F:\vdrive\rollup\cli\run\loadConfigFile.ts (16:46)
14:
15: function supportsNativeESM() {
16:   return Number(/^v(\d+)/.exec(process.version)![1]) >= 13;
                                                   ^
17: }
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (X:\rollup\node_modules\rollup\dist\shared\rollup.js:158:30)
    at Module.error (X:\rollup\node_modules\rollup\dist\shared\rollup.js:12339:16)
    at Module.tryParse (X:\rollup\node_modules\rollup\dist\shared\rollup.js:12742:25)
    at Module.setSource (X:\rollup\node_modules\rollup\dist\shared\rollup.js:12645:24)
    at ModuleLoader.addModuleSource (X:\rollup\node_modules\rollup\dist\shared\rollup.js:22105:20)
    at ModuleLoader.fetchModule (X:\rollup\node_modules\rollup\dist\shared\rollup.js:22158:9)
    at async Promise.all (index 0)
```

For context, I've been trying to pin down an issue with virtual drives in Vite (https://github.com/vitejs/vite/issues/4635). I'm not sure whether rollup is the underlying cause, but it does seem to have a similar problem. It could be some common dependency between them.

The same underlying issue with invalid path handling could be related to:
* https://github.com/rollup/rollup/issues/4118
* https://github.com/rollup/rollup/issues/4248
* https://github.com/rollup/plugins/issues/689

**Comment by egonelbre** [comment]
`NODE_PRESERVE_SYMLINKS` is not a fix, it's a workaround for incorrect handling.

Note there is also https://github.com/rollup/plugins/blob/master/packages/node-resolve/src/fs.js#L20 that would need an additional link.

**Comment by lukastaegert** [comment]
Can you check if this issue still persists in rollup@2.74.0?

**Comment by egonelbre** [comment]
I did a quick test, but it doesn't look like the failure is relate:

```
s:\temp\rollup\rollup>node --version
v16.14.2
s:\temp\rollup\rollup>npm --version
8.9.0

npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> rollup@2.74.0 prepare
> husky install && npm run build

husky - Git hooks installed

> rollup@2.74.0 build
> shx rm -rf dist && node scripts/update-git-commit.js && rollup --config rollup.config.ts --configPlugin typescript && shx cp src/rollup/types.d.ts dist/rollup.d.ts && shx chmod a+x dist/bin/rollup

[!] TypeError: defaultLoader is not a function
TypeError: defaultLoader is not a function
    at Object.require.extensions.<computed> [as .ts] (s:\temp\rollup\rollup\node_modules\rollup\dist\shared\loadConfigFile.js:617:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (s:\temp\rollup\rollup\node_modules\rollup\dist\shared\loadConfigFile.js:622:42)
    at loadConfigFile (s:\temp\rollup\rollup\node_modules\rollup\dist\shared\loadConfigFile.js:565:11)
    at Object.loadAndParseConfigFile (s:\temp\rollup\rollup\node_modules\rollup\dist\shared\loadConfigFile.js:545:21)
    at getConfigs (s:\temp\rollup\rollup\node_modules\rollup\dist\bin\rollup:1691:39)
    at runRollup (s:\temp\rollup\rollup\node_modules\rollup\dist\bin\rollup:1665:43)
```

**Comment by egonelbre** [comment]
It looks like it's still not calculating the path correctly somewhere:
```
cli/run/loadConfigFile.ts, src/node-entry.ts → dist...
[!] (plugin commonjs--resolver) Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
../../../../F:/vdrive/temp/rollup/rollup/cli/run/loadConfigFile.ts (5:12)
3: import { pathToFileURL } from 'url';
4: import * as rollup from '../../src/node-entry';
5: import type { MergedRollupOptions } from '../../src/rollup/types';
               ^
6: import { bold } from '../../src/utils/colors';
7: import { error } from '../../src/utils/error';
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (s:\temp\rollup\rollup\node_modules\rollup\dist\shared\rollup.js:198:30)
    at Module.error (s:\temp\rollup\rollup\node_modules\rollup\dist\shared\rollup.js:12719:16)
    at Module.tryParse (s:\temp\rollup\rollup\node_modules\rollup\dist\shared\rollup.js:13096:25)
    at Module.setSource (s:\temp\rollup\rollup\node_modules\rollup\dist\shared\rollup.js:13001:24)
    at ModuleLoader.addModuleSource (s:\temp\rollup\rollup\node_modules\rollup\dist\shared\rollup.js:22475:20)
```

Notice the `../../../../F:/vdrive` part.

**Comment by pos777** [comment]
The issue is still here in rollup@2.74.0.

I am stuck on the following for now:

- The rollup repository is placed at `C:\repos\rollup`;
- There are X: alias for it (C:\repos);
- Execute `npm run build` from `X:\rollup`.

The issue occurs when the `cli/run/loadConfigFile.ts` file is processed:
- The commonjs plugin's [resolveId](https://github.com/rollup/plugins/blob/36de7cc9c3915667bc0dd203ee7b139da8858959/packages/commonjs/src/resolve-id.js#L61) function calls the [resolve](https://github.com/rollup/plugins/blob/36de7cc9c3915667bc0dd203ee7b139da8858959/packages/commonjs/src/resolve-id.js#L134) and the [load](https://github.com/rollup/plugins/blob/36de7cc9c3915667bc0dd203ee7b139da8858959/packages/commonjs/src/resolve-id.js#L148) functions.
- The `resolve` function calls the node-resolve plugin's [doResolveId](https://github.com/rollup/plugins/blob/a7b56eb5c8182fad3ddabe8176c72e03b96059e6/packages/node-resolve/src/index.js#L85) function. It resolves the `cli/run/loadConfigFile.ts` id to `C:\repos\rollup\cli\run\loadConfigFile.ts`.
- The `load` function calls the typescript plugin's [load](https://github.com/rollup/plugins/blob/8ff10f64e0fa60cdd7a7a14207ef8e22a440ec48/packages/typescript/src/index.ts#L119) function. The `C:\repos\rollup\cli\run\loadConfigFile.ts` does not meet [filter](https://github.com/rollup/plugins/blob/8ff10f64e0fa60cdd7a7a14207ef8e22a440ec48/packages/typescript/src/index.ts#L120) because the filter expects `X:\rollup\cli\run\loadConfigFile.ts`.
- As result the `loadConfigFile.ts` file is not processed - error occurs.

commonjs, node-resolve, typescript plugins are involved here so it is complicated a little. I think, that the node-resolve plugin ([doResolveId](https://github.com/rollup/plugins/blob/a7b56eb5c8182fad3ddabe8176c72e03b96059e6/packages/node-resolve/src/index.js#L85)) should be researched at first.

**Comment by pos777** [comment]
The https://github.com/pos777/rollup_plugins_build_issue simple sample demonstrates the issue.
Run the [test.cmd](https://github.com/pos777/rollup_plugins_build_issue/blob/main/test.cmd) to reproduce:
```
> test@1.0.0 build
> rollup --config rollup.config.ts --configPlugin @rollup/plugin-typescript

src/index.ts → dist...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
../C:/Users/pos777/source/repos/rollup_plugins_build_issue/src/index.ts (1:12)
1: import type { RollupOptions } from 'rollup';
               ^
2:
3: const test: RollupOptions = { };
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (X:\node_modules\rollup\dist\shared\rollup.js:198:30)
    at Module.error (X:\node_modules\rollup\dist\shared\rollup.js:12555:16)
    at Module.tryParse (X:\node_modules\rollup\dist\shared\rollup.js:12932:25)
    at Module.setSource (X:\node_modules\rollup\dist\shared\rollup.js:12837:24)
    at ModuleLoader.addModuleSource (X:\node_modules\rollup\dist\shared\rollup.js:22311:20)
```
Note: there is no issue if remove the `@rollup/plugin-node-resolve` from the [rollup.config.ts](https://github.com/pos777/rollup_plugins_build_issue/blob/main/rollup.config.ts).

**Comment by pos777** [comment]
The resolve v1.22.1 package contains the fix. @lukastaegert, should I update the [package-lock.json](https://github.com/rollup/rollup/blob/1792cdf7d75308573c38b904bafb02f1612dcb3b/package-lock.json#L4148-L4158) with the new version?

**Comment by lukastaegert** [comment]
Much appreciated
