### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by goga-m** [rollup/rollup#4289]
Hey there,

Trying to inject `Buffer` as a global variable for third-party packages that are trying to access it globally like `bstring` but it fails to add the required buffer import in the module. Using `@rollup/plugin-inject` for the injection.

It builds with no errors but when I open the bundle in the browser I get the  `Browser is not defined` error from `bstring`.

`package.json` already contains buffer package from https://www.npmjs.com/package/buffer

Do you see anything wrong with the configuration below or any direction where the problem could be?

Thanks in advance.

Here's the config:

```js

import commonjs from "@rollup/plugin-commonjs";
import inject from "@rollup/plugin-inject";
import json from "@rollup/plugin-json";
import resolve from "@rollup/plugin-node-resolve";
import ts from "rollup-plugin-ts";
import builtinModules from "builtin-modules";
import nodePolyfills from "rollup-plugin-polyfill-node";
import { terser } from "rollup-plugin-terser";

const pkg = require(`${process.cwd()}/package.json`);


const browserConfig = {
	input: "source/index.ts",
	output: [
		{
			file: pkg.unpkg,
			format: "esm",
			plugins: [terser()],
		},
		{
			file: pkg.browser,
			format: "esm",
		},
	],
	external: [...Object.keys(pkg.dependencies || {})],
	plugins: [
		json(),
		resolve({ preferBuiltins: false, browser: true }),
		commonjs({ include: /node_modules/ }),
		ts({
			transpiler: "babel",
			transpileOnly: true,
			tsconfig: {
				declaration: false,
			},
			babelConfig: {
				presets: [["@babel/preset-env", { loose: false, modules: false, targets: { esmodules: true } }]],
			},
		}),
		inject({
			modules: {
				BigInt: require.resolve("big-integer"),
				process: "process-es6",
				Buffer: ['buffer', 'Buffer']
			},
		}),
		nodePolyfills(),
	],
};

```

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by shellscape** [comment]
You might want to open a bug report here: https://github.com/withastro/rollup-plugin-polyfill-node instead.
