### ISSUE TITLE
Unused dep gets bundled in final output

### ISSUE THREAD

**Issue by Septh** [rollup/rollup#4367]
### Rollup Version

v2.66.0

### Operating System (or Browser)

N/A

### Node Version (if applicable)

N/A

### Link To Reproduction

https://replit.com/@Septh/rollup-pluginutils-repro

### Expected Behaviour

I'm really not sure whether this is a Rollup issue, a pluginutils issue or something else (maybe plugin-commonjs ?) so please forgive me if this does not land at the right place.

I wanted to use `makeLegalIdentifier` from `@rollup/pluginutils` in my project and realized Rollup injected the full `picomatch` lib in my bundle although I'm not using it at all (not using `createFilter`, only `makeLegalIdentifier`).

The REPL shows that with a minimal repro (see `input.js` and `output.js`)

I would expect only `makeLegalIdentifier` to be bundled in.

### Actual Behaviour

`picomatch` gets bundled along with `makeLegalIdentifier`.

**Comment by lukastaegert** [comment]
Unfortunately, Rollup is not able to detect reliably if picomatch has any side-effects when imported, which is why it is included. I would recommend trying to set the `treeshake: {moduleSideEffects: false}` option, or if that causes problems, setting the option to a function (which will receive module ids) and setting it to false just for the pico match files.

**Comment by dnalborczyk** [comment]
or better yet: you could create a PR for `picomatch` to declare the module as having no side effects with `sideEffects: false` in `package.json`. that would benefit everyone, assuming `picomatch` has no side effecs.
