### ISSUE TITLE
Error if the empty bundle is generated

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup#444]
After seing Rollups current results of bundling the examples in #440, I think Rollup should reject if it generates an empty bundle. The user doesn't expect to get  nothing when telling Rollup to bundle their code.

**Comment by thepian** [comment]
Is this also the behavior when there is an error in the parsing or resolution of rollup. I'm trying to make sense of how to use Rollup in build.

**Comment by Victorystick** [comment]
@thepian No. If there is a parse or module resolution error, Rollup will be sure to complain. :wink:

**Comment by callumlocke** [comment]
I'm not sure if this is a good idea.

> The user doesn't expect to get nothing when telling Rollup to bundle their code.

I do expect exactly that if my source code is an empty string.

Why would I want to bundle an empty string: sometimes files are just temporarily empty during development. And if I'm using rollup in an automated way (e.g. re-bundling any entries in a given source directory whenever they change), I don't want it second-guessing me and erroring out just because I temporarily had an empty JS file in there.

**Comment by Pauan** [comment]
Perhaps a warning would be better than an error?
