### ISSUE TITLE
Is there any way to get like `import Something from 'mylib/something'`

### ISSUE THREAD

**Issue by Batman4234** [rollup/rollup#4447]
can i get something like `import Something from 'mylib-something'`, instead of `import { Something } from 'mylib/something'`

**Comment by Waqqars987** [comment]
I am also looking for the same, if you find something please reply.

**Comment by wladi0097** [comment]
This is basic module handling of js and not an issue with rollup. 

import statements like `import Something from 'mylib-something'` rely on the `default export` of the module. -> `export default mylib`
import statements like `import { Something } from 'mylib/something'` rely on `named exports` from the module. -> `export {mylib}`

if you control `mylib` you can export with the `default` keyword and then it will be possible to access it like described. eg:

```
// mylib.js
export default class mylib {...}

// index.js
import mylib from 'mylib'
```

otherwise you have to use the named imports which the library provides. 
MDN has a very good explanation on how exporting and importing modules works: https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#syntax
