### ISSUE TITLE
Add file formats to plugin options.

### ISSUE THREAD

**Issue by LabEG** [rollup/rollup#448]
Rollup now supporting only file formats hard coded in rollup code:
```
function addJsExtensionIfNecessary(file) {
	if (isFile(file)) return file;

	file += '.js';
	if (isFile(file)) return file;

	return null;
}
```
This is not a best solution, because plugin developer need modify source code for rollup processing. This problem exists for all transpillers, current and done in the future..

I suggest add `options.fileFormats=['.ts', 'tsx']` this property to plugins options. And use him in `addJsExtensionIfNecessary` function. This will greatly simplify the development of plug-ins and add them to stability.

**Comment by TrySound** [comment]
@LabEG I think for this case you should specify extension.
As you can see https://github.com/rollup/rollup/blob/master/src/Bundle.js#L1-L18 we are recommend to add even `.js` extension,

**Comment by LabEG** [comment]
Add '.js' to each path this is not best way. Because i must parse all file for find him, trying each on exist, after all this need make replace string.

This to hard and heavy operation about just search by array. Rollup will be work slower. 

Example. i have file with resolution .xxx. And i need make only one ease operation, example extract fragment of code from line 0 to line 10. And for this easy operation i must parse all file with custom syntax?

**Comment by TrySound** [comment]
@LabEG Mm.. nope. You will parse only one file. First operations is resolve, the second - load then transform. resolve returns only one path.

**Comment by Rich-Harris** [comment]
I'm with @TrySound – I can't understand how this would result in fewer filesystem queries, and I don't understand what source code manipulation is currently necessary that wouldn't be with this option. What is the difference? If you explain more clearly what you're trying to do we can help you figure out the optimal way to do it.

As an aside, @TrySound is right that explicitly adding file extensions is recommended. Dropping extensions from `require` has got to be one of the worst design mistakes in Node.js, and I expect that when browsers start implementing module loaders they will require file extensions (because browsers don't have the luxury of trying out a whole bunch of different extensions until they make a network request that doesn't 404).

**Comment by TrySound** [comment]
Looks like resolved. :)
