### ISSUE TITLE
Expose internal libs, modules and plugins of core

### ISSUE THREAD

**Issue by scriptjs** [rollup/rollup#449]
I believe both webpack and rollup suffer from some of the same issues in that their cores are monolithic and expose a surface area too small for developer access. While there are plugins, the internal code and APIs that drive transformation are not fully exposed properly for programmatic use. This limits their value.

On the current track, I am not certain that webpack nor rollup are the answer to module bundling. Their configuration and relationships to babel remain quite incoherent. Babel plugins also attempt to address some of the same issues. While it is possible to develop with this, that or some combination; bundling and build tooling is all growing in a way that is rather undesirable for use to say the least. Rollup also seems to be emulating much of webpack's config that has already been determined to be a significant sore point with developers.

The ask here is to consider exposing the internal libs in a way similar to lodash (that would not involve bringing the whole of the project to get access to these libs, modules or plugins within the core).

There is very good work being done by both projects and I applaud this. That said, the future of bundling may be neither webpack nor rollup specifically but projects that make use of libs that were thoughtfully crafted and exposed by these projects.

https://github.com/webpack/webpack/issues/1893

**Comment by eventualbuddha** [comment]
While in theory I agree with you, there are good reasons to keep code "locked up" inside one repo for a while. Usually it takes a while to figure out whether the way you've structured it makes sense, and having the freedom to change the internals without introducing huge amounts of breaking changes to the surrounding ecosystem is a good thing. But it is a balance, and once the structure bakes and is well understood, splitting out functionality makes a lot of sense.

Are there specific things that rollup has you think ought to be separated? What, exactly, about the webpack config is a sore point and in what way is rollup emulating it (I literally have never configured webpack, though others here probably have)?

**Comment by Rich-Harris** [comment]
Thanks for the thoughtful feedback – I certainly understand where you're coming from.

Aggressive modularisation is certainly one approach to building a tool like Rollup, which is composed of a variety of discrete steps (e.g. in our case resolving, loading, transforming, analysing, bundling, tree-shaking, rendering and so on). Each of those steps could have its own package, and its own API. This, loosely, is the Browserify approach, and it *has* worked for them (for example [browser-pack](https://www.npmjs.com/package/browser-pack), a component of Browserify, has many dependants that aren't Browserify).

But I think it has some under-appreciated downsides. The first, as @eventualbuddha says, is that it's harder to develop – far from abstracting separate concerns into their own self-contained worlds, in my experience you end up with the same level of mutual dependency but without any of the flexibility that comes from a single package, forcing you to jump through all sorts of crazy hoops to synchronise releases and so on. It's also much, much harder to optimise the process. For example, Rollup conducts an analysis of the code when it's first loaded that's used by subsequent steps – if it was composed of discrete packages, we'd either have to re-run parts of that analysis or expose internal classes in a way that's less than ideal. And anyone that wants to use those individual packages has to figure out how to glue them all together in a way that's useful, probably in the face of poor documentation (because documenting package `foo` that only really exists to work alongside `bar` and `baz` generally isn't a high priority).

The opposite approach is a monolith, and I agree that monoliths are generally bad.

The third way, which we're currently striving for, is to have as small a core as is practical without sacrificing performance and developer convenience. (A lot of the recent conversation around JavaScript tool fatigue has focused on the problem of having to co-ordinate so many different elements of a project – in my view, a 'batteries included' tool that contains most or all of its essential functionality internally is a lot more convenient than one you have to jury rig.) Clearly defined plugin hooks get you the rest of the way (and if they don't, we can add more) in a form that is easy to reuse between otherwise very different project setups.

To me, starting with a useful, semi-opinionated tool that allows you to modify behaviour at key moments via options and plugins beats a tool that you essentially have to rebuild from scratch if you want to swap something out. 

> Their configuration and relationships to babel remain quite incoherent. Babel plugins also attempt to address some of the same issues

I'd be interested to understand specifically what you mean by this. 

> Rollup also seems to be emulating much of webpack's config that has already been determined to be a significant sore point with developers.

The configuration has to live *somewhere* – either it can live in a standardised config file (if you need config, that is – you can be productive with the basic CLI), or it can live in an ad hoc form with a completely custom build script that glues together the various different packages you're envisaging.

None of this is dogma: it's just the results of my experience, which no doubt differs from yours. Am certainly open to suggestions and persuasion, if you have concrete ideas about what functionality deserves to live in its own place, and how that could be achieved without the sacrifices I've talked about.
