### ISSUE TITLE
Rollup doesn't respect the order of import statement in multiple entries

### ISSUE THREAD

**Issue by iheyunfei** [rollup/rollup#4539]
### Rollup Version

2.75.7

### Operating System (or Browser)

Edge

### Link To Reproduction

https://rollupjs.org/repl/?version=2.75.7&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGYS5qcyclNUNuaW1wb3J0JTIwJy4lMkZiLmpzJyUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm90aGVyRW50cnkuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJy4lMkZiLmpzJyU1Q25pbXBvcnQlMjAnLiUyRmEuanMnJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY29uc29sZS5sb2coJ2EnKSUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnNvbGUubG9nKCdiJyklMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### Expected Behaviour

If I run `otherEntry.js`, I expect the output of the console would be 
```
b
a
```

### Actual Behaviour

the output of the console is

```
a
b
```

**Comment by lukastaegert** [comment]
This is a known limitation of the current algorithm that takes the first entry as the basis for determining execution order. While this issue can be fixed with some effort by creating more chunks, there was not too much real world demand for improving this so I worked on other things. The problem is that "fixing" this will likely create more chunks for nearly everyone while solving only things I assume are edge case situations. The problem with the additional chunks can also be mitigated to some extent by taking side-effect information into account (precise execution order does not matter for modules that do not have side effects as long as declarations are executed first), but this makes this a larger issue to fix.

Nevertheless, this is a legitimate bug that I hope we will fix eventually.

**Comment by iheyunfei** [comment]
I guess this issue is duplicate due to https://github.com/rollup/rollup/issues/3888. Just close this one.
