### ISSUE TITLE
rollup build with react components, with multi inputs and multi outputs. how to set all outputs into one object name

### ISSUE THREAD

**Issue by jinphic** [rollup/rollup#4544]
this is my rollup config.
```js
export default (filename, targetName, ...plugins) => [
  {
    input: `src/components/A/index.tsx`,
    output: {
      format: 'umd',
      file: `dist/A.umd.development.js`,
      name: 'Market.Common'
    },
  },
  {
    input: `src/components/B/index.tsx`,
    output: {
      format: 'umd',
      file: `dist/B.umd.development.js`,
      name: 'Market.Common'
    },
  }
]
```

what I expect is:
```bash
window
    Market
        Common
            A
            B
```

what I have got is:
```bash
window
    Market
        Common
            B
```

I guess， the second entry `input: src/components/B/index.tsx` rewrite the object `window.Market.Common` to `window.Market.Common = Module B`, so the Module A was drop。

how can I get my expect output

**Comment by lukastaegert** [comment]
Please
a) Do not delete the issue template
b) Provide an actual reproduction. The issue template will tell you how to do that.

With the information you provided, I have hardly an idea what your actual problem is and would need to spend considerable effort on my side to look into it, which I will not do as that will harm the entire Rollup project as I cannot spend the time developing actual features.
