### ISSUE TITLE
Simple reproductible issue with treeshaking

### ISSUE THREAD

**Issue by CGNonofr** [rollup/rollup#4582]
### Rollup Version

2.77.0

### Operating System (or Browser)

Google Chrome 103.0.5060.134

### Link To Reproduction

https://rollupjs.org/repl/?version=2.77.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwVG90byUyMCU3QiU3RCU1Q25Ub3RvLkZJRUxEJTIwJTNEJTIwJ3RhdGEnJTVDbiU1Q25mdW5jdGlvbiUyMHB1cmVGdW5jdGlvbiUyMCgpJTdCJTdEJTVDbnB1cmVGdW5jdGlvbihUb3RvKSU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behaviour

The code should be empty

### Actual Behaviour

The class remains

Not that either [removing the field assignement ](https://rollupjs.org/repl/?version=2.77.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwVG90byUyMCU3QiU3RCU1Q24lMkYlMkYlMjBUb3RvLkZJRUxEJTIwJTNEJTIwJ3RhdGEnJTVDbiU1Q25mdW5jdGlvbiUyMHB1cmVGdW5jdGlvbiUyMCgpJTdCJTdEJTVDbnB1cmVGdW5jdGlvbihUb3RvKSU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE) or [removing the call to the function](https://rollupjs.org/repl/?version=2.77.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwVG90byUyMCU3QiU3RCU1Q25Ub3RvLkZJRUxEJTIwJTNEJTIwJ3RhdGEnJTVDbiU1Q25mdW5jdGlvbiUyMHB1cmVGdW5jdGlvbiUyMCgpJTdCJTdEJTVDbiUyRiUyRnB1cmVGdW5jdGlvbihUb3RvKSU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE) make it work

**Comment by TrickyPi** [comment]
@lukastaegert I took a look and found that deoptimizePathing a class argument causes it to lose track.

deoptimizePath here
https://github.com/rollup/rollup/blob/1ab9833b4ca39ad7f5303943a7658b03f93ff109/src/ast/nodes/CallExpression.ts#L128

lost here.
https://github.com/rollup/rollup/blob/1ab9833b4ca39ad7f5303943a7658b03f93ff109/src/ast/nodes/shared/ObjectEntity.ts#L78

Therefore, in the next tree-shaking, Rollup will detect that `Toto.FIELD = 'tata'` has side effects.
https://github.com/rollup/rollup/blob/1ab9833b4ca39ad7f5303943a7658b03f93ff109/src/ast/nodes/shared/ObjectEntity.ts#L296
If only to solve this problem, I think we can avoid using deoptimizePath for unused arguments, e.g.
```js
if (
	!(
		this.callee.variable instanceof LocalVariable &&
		this.callee.variable.init instanceof FunctionBase &&
		this.callee.variable.init.params.length === 0
	)
) {
	for (const argument of this.arguments) {
		// This will make sure all properties of parameters behave as "unknown"
		argument.deoptimizePath(UNKNOWN_PATH);
	}
}
```
But it doesn't cover common usage, e.g. it doesn't work in this case,
https://rollupjs.org/repl/?version=3.17.3&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY2xhc3MlMjBUb3RvJTIwJTdCJTdEJTVDblRvdG8uRklFTEQlMjAlM0QlMjAndGF0YSclNUNuJTVDbmZ1bmN0aW9uJTIwcHVyZUZ1bmN0aW9uJTIwKGZvbyklN0IlNUNuJTIwJTIwY29uc3QlMjBhJTIwJTNEJTIwZm9vJTVDbiUyMCUyMHJldHVybiUyMGEuRklFTEQlNUNuJTdEJTVDbnB1cmVGdW5jdGlvbihUb3RvKSU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlN0QlN0Q=
If you are free, could you give me some advice?

**Comment by lukastaegert** [comment]
This is a very deep issue and there is no easy "good" fix. Actually, I already started working on this last summer but I got distracted by other things.

The problem is of course that a function can do anything with the arguments passed. As it turns out, we could actually *know* what a function does with its arguments by tracking what it does with its ParameterVariables (there is an edge case when a function uses `arguments`, but I guess it would be ok to fully deoptimize in that case).

Now how could we handle this? As it turns out, we already handle a very similar issue with regard to deoptimizing "this". And as "this" is just a hidden additional parameter, it should be possible to extend this logic. See this example: https://rollupjs.org/repl/?version=3.17.3&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwbW9kaWZ5QigpJTIwJTdCJTVDbiUyMCUyMHRoaXMuYiUyMCUzRCUyMHRydWUlM0IlNUNuJTdEJTVDbiU1Q25jb25zdCUyMG9iaiUyMCUzRCUyMCU3QiU1Q24lMjAlMjBhJTNBJTIwZmFsc2UlMkMlNUNuJTIwJTIwYiUzQSUyMGZhbHNlJTJDJTVDbiUyMCUyMG1vZGlmeUIlNUNuJTdEJTNCJTVDbiU1Q25vYmoubW9kaWZ5QigpJTNCJTVDbiU1Q25pZiUyMChvYmouYSklMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2coJ3RyZWVzaGFrZW4nKSU1Q24lN0QlNUNuJTVDbmlmJTIwKG9iai5iKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZygnbXV0YXRpb24lMjB3YXMlMjB0cmFja2VkJyklM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQXRydWUlN0QlN0Q=

So by calling `obj.modifyB();` which modifies `this.b`, `obj.b` is changed. And that is even though it does not know inside `modifyB` that this function is actually injected into `obj`.

Instead, this is achieved by calling `this.callee.deoptimizeThisOnInteractionAtPath` in `CallExpression` right next to where the arguments are deoptimized. This is then picked up by `FunctionNode` to call `this.scope.thisVariable.addEntityToBeDeoptimized(interaction.thisArg)`. Now `ThisVariable` is a powerful beast: It tracks every deoptimization that happens to it. Now when an entity is added via `addEntityToBeDeoptimized`, it will apply all deoptimizations that have happened to `this` until that point in time. But it will also store the variable and if further deoptimizations happen in the future, they will also be applied to that variable.

Now it should be possible to extend this logic to call arguments. And actually I already worked quite a bit on this last summer, but then I got distracted. It is in the `selective-parameter-deoptimization` branch.

I think there were some tricky issues to be resolved, maybe there was also a performance issue. I will try to update the branch so that we can investigate.

**Comment by TrickyPi** [comment]
I pulled the `selective-parameter-deoptimization` branch. There were some TODO lists, Should we do this before merging this branch?

**Comment by lukastaegert** [comment]
Yes, and some may even be wrong. I think I want to have another look myself first, but it will take a few days.

**Comment by TrickyPi** [comment]
Okay, please let me know if there's anything that I can do to help you.
