### ISSUE TITLE
Error `TRANSPILED_ESM_CONFIG` provides insufficient information

### ISSUE THREAD

**Issue by flying-sheep** [rollup/rollup#4616]
### Rollup Version

2.78.1

### Operating System (or Browser)

Linux/Firefox

### Link To Reproduction

https://replit.com/@flying-sheep/rollup-repro-esm-from-ts

### Expected Behaviour

Until fixing the underlying bug #4617, I’d expect the error message to

1. Offer a solution that actually has a chance of working (I can’t rename a typescript file to .cjs or .mjs)
2. The actual problem can only be debugged knowing the content of the discarded original error’s message, which tells me which imported module causes the error.

   ```
   Error: require() of ES Module <projdir>/node_modules/@mdx-js/rollup/index.js from <projdir>/rollup.config.ts not supported.
   Instead change the require of index.js in <projdir>/rollup.config.ts to a dynamic import() which is available in all CommonJS modules.
   ```

### Actual Behaviour

An encountered node error with code `ERR_REQUIRE_ESM` gets converted into a rollup error with code `TRANSPILED_ESM_CONFIG`, in the process discarding vital information to figure out where that happened:

https://github.com/rollup/rollup/blob/bf1ff32b3c963baf1f81f92b1cc089c26e73b29c/cli/run/loadConfigFile.ts#L127-L129

I encountered this utterly unhelpful error,

```
[!] Error: While loading the Rollup configuration from "rollup.config.ts",
Node tried to require an ES module from a CommonJS file, which is not supported.
A common cause is if there is a package.json file with "type": "module" in the same folder.
You can try to fix this by changing the extension of your configuration file to ".cjs" or ".mjs" depending on the content,
which will prevent Rollup from trying to preprocess the file but rather hand it to Node directly.
```

**Comment by lukastaegert** [comment]
It should be possible to add the original error to the other error message. As by my other post, as transpilation to CommonJS is currently mandatory for TypeScript, a more helpful advice would be to place the config in a sub-folder with `type: "commonjs"`. This advice could always be given instead of the original error message when a command plugin is used, as in that case, transpilation is required.

PRs for both improvements are very much welcome.

**Comment by lukastaegert** [comment]
Fix at #4621

**Comment by flying-sheep** [comment]
Very cool! Will 3.0 be released soonish? Otherwise quality of life improvements like this should probably also be back ported to the 2.x branch, no?

**Comment by lukastaegert** [comment]
It will be released in the next two months. And no, we cannot back port because it is a major breaking change.

**Comment by lukastaegert** [comment]
There will probably be another pre-release with the change in the next week.

**Comment by flying-sheep** [comment]
Thanks for the info, i really like a transparent and responsive maintenance style! I didn't know you considered a new error type a breaking change. A backwards compatible way would be to enhance the existing error with full information, but I'm happy with a pre release too!

**Comment by lukastaegert** [comment]
It is not merely a new error type, this completely changes how modules are loaded. Basically for the TypeScript case, we switched CJS output with ESM output (with the ability to switch back to CJS output), but the same error was also fixed for the plain JavaScript case, where the fix is to no longer bundle in any case, which has very deep implications.

**Comment by flying-sheep** [comment]
Ah, i meant to backport only the `\n\nOriginal message` and `stack: originalError.stack` parts, but as said, I'm happy with the prerelease
