### ISSUE TITLE
Plugin code TypeScript build error starting 2.78.0

### ISSUE THREAD

**Issue by jeremymeng** [rollup/rollup#4623]
### Rollup Version

2.78.0

### Operating System (or Browser)

all

### Link To Reproduction

https://github.com/jeremymeng/rollup-repro

### Expected Behaviour

existing code not broken

### Actual Behaviour

```
$ tsc
test.ts:7:10 - error TS2339: Property 'call' does not exist on type 'ObjectHook<(this: PluginContext, id: string) => LoadResult | Promise<LoadResult>, {}>'.
  Property 'call' does not exist on type '{ handler: (this: PluginContext, id: string) => LoadResult | Promise<LoadResult>; order?: "pre" | "post" | null | undefined; }'.

7     load.call(context, id);
           ~~~~


Found 1 error.
```

This seems to be related to PR  #4600.  Before that `load` is of type `any`. Now it's an `ObjectHook<>`

**Comment by lukastaegert** [comment]
This error is correct. Now it is possible that plugin hooks are objects instead of functions and you should use a type guard if you want to directly call a plugin hook.
This change which is breaking for you was unavoidable to introduce the feature. Nevertheless we chose to introduce it in a minor version as it should not affect end users and is only a typing issue.

**Comment by jeremymeng** [comment]
Got it. Thanks for the explanation!
