### ISSUE TITLE
Plugins array is not re-evaluated when config file is edited in watch mode

### ISSUE THREAD

**Issue by Septh** [rollup/rollup#4628]
### Rollup Version

All

### Operating System (or Browser)

N/A

### Node Version (if applicable)

N/A

### Link To Reproduction

Un-needed

### Expected Behaviour

Updates to the `Plugins` array should be reflected in the build. Or, if this is intentional, the actual behavior should be documented.

### Actual Behaviour

While Rollup updates its options when the config file is edited in watch mode, the `Plugins` array remains unaffected, meaning that adding or removing plugins or changing a plugin configuration simply has no effect on the build.

Not a big deal really, that's just limiting the usefulness of watching the config file.

**Comment by lukastaegert** [comment]
> Link To Reproduction
> Un-needed

If you say so, maybe let us be the judge of that. After all as you may not be aware, it works correctly for many setups, so it is likely linked to peculiarities in your setup.

That being said, I have an idea what might be going on. I guess that you have an `.mjs` config file, and we did not implement a cache-busting mechanism for natively loaded modules.

This should be fixed in the upcoming 3.0 release of Rollup, but without a reproduction, you will need to check yourself via `npm install rollup@beta`.

**Comment by Septh** [comment]
You're right, I use an `.mjs` config file. Sorry I didn't realize that might cause the issue.
