### ISSUE TITLE
rollup cannot find index files/ignores them

### ISSUE THREAD

**Issue by mrtnbroder** [rollup/rollup#470]
I use `index.js` files quite a lot in my directories, especially now with es6 modules it makes a lot of things much easier to import/export, e.g. you can simply `export * as foo from './mymodule'` within your `index.js` file and have them imported otherwhere by just referencing the directory.

e.g. in my `rollup.config.js` I want to simply import my entry `index.js` file via:
```
{
  entry: './src'
}
```

I guess this works, but as soon as I start using `import { foo } from '../foo/bar'`, (where an `index.js` file resides), rollup complains:

`Cannot find module`

**Comment by mrtnbroder** [comment]
Sorry, this can be closed, I was actually using `index.jsx` files ;)

**Comment by mrtnbroder** [comment]
Actually, this indeed doesn't work for `.index.js` files.

**Comment by TrySound** [comment]
@mrtnbroder rollup can only add .js extension. You can use rollup-plugin-npm which resolve also local modules like directory with index.js.

**Comment by dariocravero** [comment]
@TrySound could you expand on the solution with `rollup-plugin-npm` for this use case? I understand that the `index.js` convention comes from node but using `rollup-plugin-npm` for code within the same package kind of feels like an overkill to me. Am I missing something? Thanks :)

**Comment by TrySound** [comment]
@dariocravero Nothing overkill. Maybe npm is not very correct name. It's just use node resolver, nothing more. Adding rollup-plugin-commonjs in local modules is overkill.

**Comment by dariocravero** [comment]
@mrtnbroder or anybody else that would like to test it with `rollup-plugin-npm`, here's a `config.js` file you can run with `rollup -c config.js` to test that:

```
import npm from 'rollup-plugin-npm';

export default {
  dest: 'next.js',
  entry: 'index.js',
  format: 'es6',
  moduleName: 'my-package',
  plugins: [
    npm({ jsnext: true, main: true })
  ]
};
```

@TrySound the problem with using `rollup-plugin-npm` is that it will bundle everything from `node_modules` which isn't the objective here. It does recognise and resolve the local `index.js` file but it also bundles more things than what you may want because the idea here is to import from within project, not from a dependency of it.

Perhaps a plugin with [getCandidatesForExtension](https://github.com/rollup/rollup-plugin-commonjs/blob/master/src/index.js#L25-L30) in `rollup-plugin-commonjs` could be extracted to support this use case. @Rich-Harris what are your thoughts on this?

**Comment by eventualbuddha** [comment]
It is pretty easy to use the NPM plug-in for only matching index.js files. Just pass `main: false` and `jsnext: false`.

**Comment by dariocravero** [comment]
I tried that @eventualbuddha but it [fails](https://github.com/rollup/rollup-plugin-npm/blob/master/src/index.js#L48) saying that any of those options have to be true:

```
$ rollup -c .rollup/cjs.js
To import from a package in node_modules (./actions), either options.jsnext or options.main must be true
```

**Comment by TrySound** [comment]
@dariocravero If you will use only './' (local) paths then resolver will look only local modules.

**Comment by TrySound** [comment]
@dariocravero Rollup works in the same way but it doesn't support not local modules at all.
https://github.com/rollup/rollup/blob/master/src/utils/defaults.js#L28

**Comment by Rich-Harris** [comment]
> @Rich-Harris what are your thoughts on this?

Resolving `index.js` files is a (really silly!) [feature of Node](https://nodejs.org/api/modules.html#modules_all_together), rather than a feature of CommonJS, so the logic does belong to rollup-plugin-npm (which [needs to be renamed](https://github.com/rollup/rollup-plugin-npm/issues/20)). (It's *extremely* unlikely that native module loaders will support that method of resolution, since they're designed to work in browsers, which can't afford to make speculative requests and get 404s in response – which is why Rollup itself doesn't and won't support it.)

I'm a little confused about why you're seeing that failure – if you're importing a local module, that shouldn't happen. Can you reproduce it in a gist or small repo that we can look at? Feel free to open a new issue (probably on rollup-plugin-npm) if necessary.

**Comment by mattecapu** [comment]
Is there a way to resolve `.jsx` files too?

**Comment by TrySound** [comment]
@mrtnbroder Is it really hard for you to write extension? Use this resolver
https://github.com/dot-build/rollup-plugin-includepaths

**Comment by mrtnbroder** [comment]
Uhm what? I've solved my issue already, not sure I can follow.

**Comment by adnan1naeem** [comment]
@mrtnbroder  How did you resolved the issue.I am having  same issue

**Comment by matthew-dean** [comment]
Does `@rollup/plugin-node-resolve` actually resolve index files? 🤔  I'm trying to get it to do that now.

**Comment by TrySound** [comment]
Yes it is. Are you trying to resolve index.js specifically?
