### ISSUE TITLE
@rollup/plugin-babel cannot convert Spread API correct when target is 'es5'

### ISSUE THREAD

**Issue by touchpillow** [rollup/rollup#4701]
### Rollup Version
rollup 2.78.0
@rollup/plugin-babel 5.3.1

### Operating System (or Browser)
macOS 11.6.7
browser: chrome 107.0.5304.87 

### Node Version
14.18.0

### rollup config
```javascript
const plugins = [
  nodeResolve({
    preferBuiltins: false,
    modulesOnly: true,
    extensions: ['js', '.ts'],
  }),
  commonjs(),
  // json(),
  // globals(),
  // builtins(),
  typescript({
    target: 'es5',
    declaration: true,
    declarationDir: 'dist',
  }),
  babel({
    exclude: 'node_modules/**',
    babelHelpers: 'runtime', // 开启体积优化
  }),
// others
]
```
### questions
I use `Spread` to convert a `Set` variable to `Array` variable, just like this:
```javascript
const set = new Set();
const getSet = () => {
  return [...set]
}
```
but I found that this function return `[]` all the time, so I check the build files, and found the `Spread` API is converted to `Array.prototype.slice`:
```javascript
function __spreadArray(to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
}
```
However, `Array.prototype.slice` cannot handle the `Set`, or in  other word,  Array.prototype.slice.call(Set) will return `[]` all the time, and it works if I set the target to `es6`.

### expect
So, my questions is , how can it work when target is 'es5'? I think maybe I need add some configs, but I can't find a solution in document or other article

**Comment by lukastaegert** [comment]
Rollup does not convert your spread operator, it must be one of your plugins, either `typescript` or `babel`. I fear this is not an issue that can be solved in the Rollup ecosystem but needs to be solved with either TypeScript or Babel.

**Comment by touchpillow** [comment]
> 

I have used the `rollup/plugin-babel` plugin to convert my code, is my config wrong?

**Comment by touchpillow** [comment]
> Rollup does not convert your spread operator, it must be one of your plugins, either `typescript` or `babel`. I fear this is not an issue that can be solved in the Rollup ecosystem but needs to be solved with either TypeScript or Babel.

I have used the `@rollup/plugin-babel` plugin to convert my code, is my config wrong?

**Comment by touchpillow** [comment]
Sorry, I will put this issue into rollup/plugin

**Comment by lukastaegert** [comment]
No, the plugin won't help you either, they do not maintain Babel. AndI do not think Babel is the problem because their transform looks reasonable: https://bvaughn.github.io/babel-repl/#?babili=false&browsers=&builtIns=false&code_lz=MYewdgzgLgBBCmsC8MzwO4wMqIBQEoBuAKFElgHNEdkYCYkA-GAb2JhgCdEBXTsGAG0AdKIRQAusQC-QA&debug=false&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&showSidebar=true&targets=

I think you need to open an issue for TypeScript itself (not the Rollup the plugin but the language): https://www.typescriptlang.org/play?target=1#code/MYewdgzgLgBBCmsC8MzwO4wMqIBQEoBuAKFElgHNEdkYCYkA+GAb2JhgCdEBXTsGAG0AdKIRQAusQC+QA

It is also the only part in your setup that has this `target` option you keep talking about.
