### ISSUE TITLE
Treeshake doesn't work for class with this reference

### ISSUE THREAD

**Issue by Soul-Master** [rollup/rollup#4764]
### Rollup Version

3.7.5

### Operating System (or Browser)

Browser

### Link To Reproduction

https://rollupjs.org/repl/?version=3.7.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEZvbyUyMCU3RCUyMGZyb20lMjAnLiUyRnV0aWwuanMnJTNCJTVDbmltcG9ydCUyMCU3QiUyMHVzZWRDb25zdCUyQyUyMGJhciUyMCU3RCUyMGZyb20lMjAnLiUyRnNoYXJlZE1vZHVsZS5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKCdmb28nJTJDJTIwdXNlZENvbnN0KSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnV0aWwuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY2xhc3MlMjBGb28lMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3RydWN0b3IoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjB0aGlzLm9wdGlvbjElMjAlM0QlMjAxMjMlM0IlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJzaGFyZWRNb2R1bGUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwRm9vJTIwJTdEJTIwZnJvbSUyMCcuJTJGdXRpbC5qcyclM0IlNUNuJTVDbiUyRiUyRiUyMFRoZSUyMGZvbGxvd2luZyUyMGxpbmUlMjBzaG91bGQlMjBiZSUyMHJlbW92ZWQuJTVDbmNvbnN0JTIwdW51c2VkQ29uc3QlMjAlM0QlMjBuZXclMjBGb28oKSUzQiU1Q24lNUNuJTJGJTJGJTIwVGhlJTIwZm9sbG93aW5nJTIwbGluZSUyMHNob3VsZCUyMGJlJTIwaW5jbHVkZWQuJTVDbmV4cG9ydCUyMGNvbnN0JTIwdXNlZENvbnN0JTIwJTNEJTIwbmV3JTIwRm9vKCklM0IlNUNuZXhwb3J0JTIwY29uc3QlMjBiYXIlMjAlM0QlMjAxMjMlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### Expected Behaviour

Unused variable and its new expression should be removed.

### Actual Behaviour

Rollup still include new expression and drop only unused variable.

**Comment by lukastaegert** [comment]
I think you are hitting a current limitation of the algorithm here:
- We cannot remove `this.option1 = 123;` because it changes something relevant because the class is used, so it is a side effect
- Therefore, creating a new instance of `Foo` is always a side effect

The best approach I can think of to fix this would be a solution similar to how we handle e.g. `break` statements (which are always included but not considered side effects): When checking if the constructor has side effects, we add a tree-shaking context flag to ignore `this` mutations while those mutations are not ignored when actually including the constructor.
