### ISSUE TITLE
"Cannot find module" when a dependency tries to require() a JSON file

### ISSUE THREAD

**Issue by callumlocke** [rollup/rollup#480]
Stack trace (using [longjohn](https://github.com/mattinsler/longjohn) to give a bit more info):

```
Cannot find module './typos' from '/Users/callum/code/testing-rollup/node_modules/normalize-package-data/lib'
Error: Cannot find module './typos' from '/Users/callum/code/testing-rollup/node_modules/normalize-package-data/lib'
    at /Users/callum/code/testing-rollup/node_modules/resolve/lib/async.js:55:21
    at load (/Users/callum/code/testing-rollup/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/callum/code/testing-rollup/node_modules/resolve/lib/async.js:92:31)
    at /Users/callum/code/testing-rollup/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
---------------------------------------------
    at /Users/callum/code/testing-rollup/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/asap.js:45:13
    at asap (/Users/callum/code/testing-rollup/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/asap.js:17:7)
    at reject (/Users/callum/code/testing-rollup/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:134:3)
    at /Users/callum/code/testing-rollup/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:58:7
```

When I look inside `./node_modules/normalize-package-data/lib`, it seems the problem is the file is called `typos.json`.

Here's my `rollup.config.js`:

```js
import 'longjohn';
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import json from 'rollup-plugin-json';
import npm from 'rollup-plugin-npm';

export default {
  entry: 'src/index.js',
  dest: 'dist/index.js',
  plugins: [
    json(),
    babel(),
    npm({
      jsnext: true,
      main: true,
    }),
    commonjs({
      extensions: [ '.js', '.json' ]
    }),
  ],
  format: 'iife',
};
```

I've included `.json` as an extension in the commonjs plugin's options, but that doesn't seem to solve it. As a workaround I've added the `normalize-package-data` to the npm plugin's `skip` option, but I'd prefer to solve this properly.

**Comment by eventualbuddha** [comment]
I think you want to just use the `.json` extension when importing.

**Comment by callumlocke** [comment]
But it's not in my code, it's in a dependency. A package is doing `require('./typos')` to load a file local to that package called `typos.json`.

In Node's `require()` that's OK... And I'm using the npm and commonjs plugins, which are supposed to translate from Node require calls, right?

Isn't this what my config line `extensions: [ '.js', '.json' ]` is supposed to do?

**Comment by Rich-Harris** [comment]
Ack, this is tricky. The way that rollup-plugin-json knows that it needs to wrap a file is because it has the `.json` extension. I can never get over how short-sighted Node's decision to support extensionless `require`s was – it's bad for performance (lots of unnecessary fs calls), bad for readability, and forces any piece of tooling that wants to be compatible with Node to accommodate the same resulting combinatorial explosion of possible resolutions. *Sigh...*

> Isn't this what my config line `extensions: [ '.js', '.json' ]` is supposed to do?

It would allow the commonjs plugin to transform `.json` files, but that's not what we want – we want the json plugin to transform it. I think the solution is probably for rollup-plugin-json to have a `resolveId` function that finds `.json` files given extensionless imports. (The reason the commonjs plugin has this option is so that you can compile a CoffeeScript module to CommonJS, and from there to ES6.)

We've also talked about having a general purpose rollup-plugin-node, which would combine the behaviours of the commonjs, npm and json plugins (plus provide polyfills for Node built-ins like `Buffer`, potentially). That would also solve the issue.

**Comment by Rich-Harris** [comment]
I've just released rollup-plugin-npm version 1.4.0, which supports the `extensions` option. So your config should look like this:

```js
import 'longjohn';
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import json from 'rollup-plugin-json';
import npm from 'rollup-plugin-npm';

export default {
  entry: 'src/index.js',
  dest: 'dist/index.js',
  plugins: [
    json(),
    babel(),
    npm({
      jsnext: true,
      main: true,
      extensions: [ '.js', '.json' ]
    }),
    commonjs(),
  ],
  format: 'iife',
};
```

Related: it's increasingly apparent that the npm plugin is badly named: https://github.com/rollup/rollup-plugin-npm/issues/20

**Comment by Rich-Harris** [comment]
(Side-note: headaches like this are exactly the reason that [libraries should expose a bundled version](http://pouchdb.com/2016/01/13/pouchdb-5.2.0-a-better-build-system-with-rollup.html), rather than expecting their consumers to deal with these quirks.)

**Comment by callumlocke** [comment]
> I've just released rollup-plugin-npm version 1.4.0, which supports the extensions option.

thank you!

> libraries should expose a bundled version

Interesting... I would have thought this could be a bit of a performance problem though? What about when two of my dependencies each depend on something common, like lodash... if they are built according to this advice, they would each expose a bundle that includes lodash buried inside it, so when I bundle up my code it's going to contain two copies of lodash? Or have I misunderstood

**Comment by Rich-Harris** [comment]
> What about when two of my dependencies each depend on something common, like lodash...

External dependencies can stay external – so your `foo` and `bar` dependencies can share a mutual `lodash` dependency. But `foo` and `bar` should bundle their *own* source code. 99% of the problems that arise when creating bundles are due to things like `foo.version = require('../package.json')`, or a dependency using stage 0 ES features that require the consumer to either a) transpile the code or b) happen to be using the same Babel version that `foo` uses.

For a long time this stuff didn't really matter because there was only Browserify (well, and RequireJS...), but now there are more choices. The *only way* to guarantee that people will be able to use your library, without forcing them to adopt the quirks of your build process, is to give them a version that is ready to run in the environments you support.

Bonus: even for packages that only run in Node and not the browser, you end up with a leaner package that's quicker to start up (because you then only need one `require` per package, and [require is dog slow](https://kev.inburke.com/kevin/node-require-is-dog-slow/)).

Rollup actually goes a step further and *does* bundle its own external dependencies (like magic-string, sourcemap-codec, most of acorn). That's because in the situations where you'd be using it duplication isn't a big issue. The result is that installing Rollup takes a fraction of the time it takes to install similar tools, and it takes much less space on disk – personally I think that makes for a much better developer experience.

**Comment by callumlocke** [comment]
OK that makes sense.

I can see the benefit in particular of bundling *everything* (inc. external) into a CLI tool (or anything intended to be run as an app). And with a library it makes more sense to keep external deps out of the library bundle, as the library is intended for use in other apps - and those apps might want to bundle multiple libraries together, so it's better if the libraries can ultimately share their deps in an app bundle. 

I guess that's an argument for publishing separate modules for stuff that is both library and app, like babel-core and babel-cli, so you can get the fast startup/installation benefits for the CLI, but the best eventual bundle-ability for the library... Have you ever considered separating out rollup-cli?

**Comment by Rich-Harris** [comment]
> Have you ever considered separating out rollup-cli?

It's definitely crossed my mind (and other people's). I'm not sure if there's enough of a benefit though – from personal experience (with [Gobble](https://github.com/gobblejs/gobble), a somewhat-neglected general purpose build tool), it does introduce a good bit of complexity – it's easy for mismatched versions to cause bugs, and there's the cognitive overhead of understanding you need both. I think it made more sense back in the day when you would run `grunt` to build everything, and `grunt-cli` (globally installed) was just responsible for finding the local installation of `grunt` and kicking it off. Nowadays the community seems to be moving more towards local-everything (i.e. installing the CLI locally and invoking it via `npm run`), which is what I personally recommend.

As far as bundle-ability goes, my feeling is that the benefits of keeping Rollup's deps external aren't that great, because you're basically only going to run it in a Node environment where if there *is* duplication, it doesn't really matter. (You might be running it in a browser a la http://rollupjs.org, but it's unlikely you'd be using its dependencies separately.) But that equation will vary from one library to another.

**Comment by TrySound** [comment]
Can be closed?

**Comment by Rich-Harris** [comment]
yep

**Comment by aluanhaddad** [comment]
I hit this when when a configuration file, say `.babelrc` that has a special snowflake filename, is loaded via via ESM syntax. A parse error is thrown as the file is parsed as JavaScript. I played around with the extensions property of _rollup-plugin-node-resolve_ but was not able to get this working.

I just want to confirm that this is intentionally unsupported.
