### ISSUE TITLE
Massive amount of semicolons added to the end of sourcemap

### ISSUE THREAD

**Issue by yaycmyk** [rollup/rollup#489]
I'm not entirely sure how to show this bug off without revealing the source of a private project, but this is the tail of source map output from rollup for about 20 modules:

![screen shot 2016-02-01 at 4 51 01 pm](https://cloud.githubusercontent.com/assets/570070/12732539/fed3a9b6-c903-11e5-990b-bad3228abc00.png)

I'm not sure what to make of it...

**Comment by yaycmyk** [comment]
I am using `rollup-plugin-babel`, by the way.

**Comment by msegado** [comment]
I'm seeing what I suspect is a related (or the same) bug... need to file some paperwork before displaying any source for that project, but hopefully the following helps troubleshoot in the meantime:

I'm actually running Rollup and Babel in sequence via Gobble; e.g.,
```js
module.exports = gobble('src')
  .transform('rollup', {
    entry: 'index.js',
    dest: `${pjson.name}.js`,
    sourceMap: true,
  })
  .transform('babel');
```

My output sourcemap looks like this... note all the semicolons plus only two listed sources:
```
{"version":3,"file":"zdom.js","sources":["../src/index.js","../src/utils.js"],
"sourcesContent":[ <snip> ], "names" [],"mappings":
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;QCcgD,
OAAO,yDAAC,KAAK,CAAC,UAAU;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;sCDctC,QAAQ;AAAR,cAAQ;;;;;;;;;;;;;;;;;;;;;"}
```
However, if I *omit* `.transform('babel')`, I get**
```
{"version":3,"file":"zdom.js","sources":["../src/index.js","../src/fragment.js",
"../src/utils.js","../src/element.js","../src/attributes.js","../src/text.js"],
"sourcesContent":[ <snip> ],"names":["resolveNamespace"],"mappings":
"AKEe,MAAM,KAAK,CAAC;EACzB,WAAW,CAAC,IAAI,EAAE,KAAK,EAAE,WAAW,EAAE;IACpC,IAAI,CAAC,
IAAI,GAAG,MAAM,CAAC,IAAI,CAAC,CAAC;IACzB,IAAI,CAAC,WAAW,GAAG,WAAW,CAAC;IAC/B,IAAI
          <many more lines of this>
OAAO,CAAC,IAAI,EAAE,GAAG,EAAE,GAAG,EAAE,KAAK,CAAC,CAAC;CAChC,CAAC;;"}
```

Is it possible that the sourcemap output from Rollup is corrupted in such a way that the Babel transformer cannot read it properly? Or alternatively, that there's problem with the way Babel is reading sourcemaps that affects both `gobble-babel` and `rollup-plugin-babel`?

Another note: if I pass it through `.transform('concat',  {dest: 'bundle.js', files: ['*.js']})` instead of `.transform('babel')`, the sourcemap comes out looking fine.


**I know, I know... it's yet _another_ virtual DOM library =P

**Comment by msegado** [comment]
Aha - @yaycmyk, assuming you're using UMD, AMD, or SystemJS output, it is indeed a Babel issue:

https://phabricator.babeljs.io/T3044
https://phabricator.babeljs.io/T6903
https://phabricator.babeljs.io/T7056
https://phabricator.babeljs.io/T7070

They just found a fix for the SystemJS one, so hopefully UMD/AMD fixes will also follow in time.

**Comment by yaycmyk** [comment]
Yeah I'm using 'umd' output

**Comment by eventualbuddha** [comment]
You should be using rollup-plugin-babel rather than doing that transform as a separate step. Let us know here if that doesn't fix it.

**Comment by msegado** [comment]
@yaycmyk, try removing the `transform-es2015-modules-amd` from your Babel configuration and just using Rollup's `format: 'umd'` option instead.

@eventualbuddha Thanks for the feedback. Yeah, that should fix it in my case... I initially moved away from `rollup-plugin-babel` because I wanted regular inline helpers instead of `external-helpers` (for another hacky post-processing step that I'm doing), but I might go back if the Babel issue isn't resolved soon...

**Comment by msegado** [comment]
(FYI, it looks like https://github.com/babel/babel/pull/3314 will fix this.)

**Comment by mtrias** [comment]
I'm seeing this same issue, but i'm using `iife` output and not using Babel nor any other ES transpiler.

Any ideas what else could cause this?
