### ISSUE TITLE
can't resolve the exports correctlly

### ISSUE THREAD

**Issue by tjx666** [rollup/rollup#4903]
### Rollup Version

3.19.1

### Operating System (or Browser)

MacOS  Ventura 13.0.1 (22A400

### Node Version (if applicable)

v18.14.1

### Link To Reproduction

https://github.com/tjx666/rollup-esm-issue

### Expected Behaviour

can build with no error.

![image](https://user-images.githubusercontent.com/41773861/224692406-94e87cc8-5da8-493b-b45a-ff6ee074b973.png)

But can build by vite:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/224708399-25d9bbc1-5fbd-47f8-8e31-27314d614e8e.png">

### Actual Behaviour

```shell
❯ b

> rollup-esm-issue@1.0.0 build
> rm -rf ./dist && rollup -c


index.js → dist/cjs, dist/es...
[!] Error: Could not load /Users/yutengjing/code/rollup-esm-issue/node_modules/math/dist/es/add (imported by index.js): ENOENT: no such file or directory, open '/Users/yutengjing/code/rollup-esm-issue/node_modules/math/dist/es/add'
Error: Could not load /Users/yutengjing/code/rollup-esm-issue/node_modules/math/dist/es/add (imported by index.js): ENOENT: no such file or directory, open '/Users/yutengjing/code/rollup-esm-issue/node_modules/math/dist/es/add'

```

**Comment by XiSenao** [comment]
This is a path resolution exception. Vite can normally resolve paths because of the ability provided by `vite:resolve` plugin. If you have an understanding of how this plugin works, you will find that in the tryFsResolve method, it will join default extensions to determine the final path. This problem is related to your configuration of exports in math module's package.json. If possible, please also include the suffixes for specific modules.

**Comment by tjx666** [comment]
There are many subdirectory and differen file extension in the package, I can only use this exports to express resolution. So, how to define a correct exports?

**Comment by tjx666** [comment]
close because this issue behavior the same as node, vite support extensions because vite builtin plugin
