### ISSUE TITLE
Conditionals are not Treeshaken for Constants when in a Try Block

### ISSUE THREAD

**Issue by ryansolid** [rollup/rollup#4915]
### Rollup Version

3.11.0

### Operating System (or Browser)

Chrome 111

### Link To Reproduction

https://rollupjs.org/repl/?version=3.11.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwbWFpbkZlYXR1cmUlMkMlMjBzcGVjaWZpY0ZlYXR1cmUlMjAlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmxpYi5qcyU1QyUyMiU1Q24lNUNuJTJGJTJGJTIwdW5jb21tZW50JTIwdG8lMjB1c2UlNUNuJTJGJTJGc3BlY2lmaWNGZWF0dXJlKCklM0IlNUNuJTVDbm1haW5GZWF0dXJlKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmxldCUyMHVzZVNwZWNpZmljRmVhdHVyZSUyMCUzRCUyMGZhbHNlJTNCJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwc3BlY2lmaWNGZWF0dXJlKCklMjAlN0IlNUNuJTIwJTIwdXNlU3BlY2lmaWNGZWF0dXJlJTIwJTNEJTIwdHJ1ZSUzQiU1Q24lMjAlMjBjb25zb2xlLmxvZyglNUMlMjJJbml0JTIwdGhlJTIwZmVhdHVyZSU1QyUyMiklNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMG1haW5GZWF0dXJlKCklMjAlN0IlNUNuJTIwJTIwJTJGJTJGJTIwbGVhdmVzJTIwdGhlJTIwY29uZGl0aW9uYWwlNUNuJTIwJTIwdHJ5JTIwJTdCJTVDbiUyMCUyMCUyMCUyMGlmJTIwKHVzZVNwZWNpZmljRmVhdHVyZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJTVDJTIyRG8lMjBpdCUyMHRoZSUyMHNwZWNpYWwlMjB3YXklNUMlMjIpJTVDbiUyMCUyMCUyMCUyMCU3RCUyMGVsc2UlMjBjb25zb2xlLmxvZyglNUMlMjJEbyUyMGl0JTIwbm9ybWFsJTVDJTIyKSUyMCU1Q24lMjAlMjAlN0QlMjBjYXRjaChlcnIpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKGVyciklNUNuJTIwJTIwJTdEJTVDbiU1Q24lMjAlMjAlMkYlMkYlMjBwcm9wZXJseSUyMEhhbmRsZXMlMjBpdCU1Q24lMjAlMjBpZiUyMCh1c2VTcGVjaWZpY0ZlYXR1cmUpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKCU1QyUyMkRvJTIwaXQlMjB0aGUlMjBzcGVjaWFsJTIwd2F5JTVDJTIyKSU1Q24lMjAlMjAlN0QlMjBlbHNlJTIwY29uc29sZS5sb2coJTVDJTIyRG8lMjBpdCUyMG5vcm1hbCU1QyUyMiklMjAlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMmxpYi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlN0QlN0Q=

### Expected Behaviour

For the conditional on constants that will always be false/null to be dropped even when inside a try block.

### Actual Behaviour

When a condition is put in a try block the code is not eliminated. This persists to any conditionals that would be found in any functions called under the try block as well. So for library code, it adds up.

**Comment by lukastaegert** [comment]
That is by design, there is an option to disable this behavior: https://rollupjs.org/configuration-options/#treeshake-trycatchdeoptimization

https://rollupjs.org/repl/?version=3.11.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwbWFpbkZlYXR1cmUlMkMlMjBzcGVjaWZpY0ZlYXR1cmUlMjAlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmxpYi5qcyU1QyUyMiU1Q24lNUNuJTJGJTJGJTIwdW5jb21tZW50JTIwdG8lMjB1c2UlNUNuJTJGJTJGc3BlY2lmaWNGZWF0dXJlKCklM0IlNUNuJTVDbm1haW5GZWF0dXJlKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmxldCUyMHVzZVNwZWNpZmljRmVhdHVyZSUyMCUzRCUyMGZhbHNlJTNCJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwc3BlY2lmaWNGZWF0dXJlKCklMjAlN0IlNUNuJTIwJTIwdXNlU3BlY2lmaWNGZWF0dXJlJTIwJTNEJTIwdHJ1ZSUzQiU1Q24lMjAlMjBjb25zb2xlLmxvZyglNUMlMjJJbml0JTIwdGhlJTIwZmVhdHVyZSU1QyUyMiklNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMG1haW5GZWF0dXJlKCklMjAlN0IlNUNuJTIwJTIwJTJGJTJGJTIwbGVhdmVzJTIwdGhlJTIwY29uZGl0aW9uYWwlNUNuJTIwJTIwdHJ5JTIwJTdCJTVDbiUyMCUyMCUyMCUyMGlmJTIwKHVzZVNwZWNpZmljRmVhdHVyZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJTVDJTIyRG8lMjBpdCUyMHRoZSUyMHNwZWNpYWwlMjB3YXklNUMlMjIpJTVDbiUyMCUyMCUyMCUyMCU3RCUyMGVsc2UlMjBjb25zb2xlLmxvZyglNUMlMjJEbyUyMGl0JTIwbm9ybWFsJTVDJTIyKSUyMCU1Q24lMjAlMjAlN0QlMjBjYXRjaChlcnIpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKGVyciklNUNuJTIwJTIwJTdEJTVDbiU1Q24lMjAlMjAlMkYlMkYlMjBwcm9wZXJseSUyMEhhbmRsZXMlMjBpdCU1Q24lMjAlMjBpZiUyMCh1c2VTcGVjaWZpY0ZlYXR1cmUpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKCU1QyUyMkRvJTIwaXQlMjB0aGUlMjBzcGVjaWFsJTIwd2F5JTVDJTIyKSU1Q24lMjAlMjAlN0QlMjBlbHNlJTIwY29uc29sZS5sb2coJTVDJTIyRG8lMjBpdCUyMG5vcm1hbCU1QyUyMiklMjAlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMmxpYi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQSU3QiUyMnRyeUNhdGNoRGVvcHRpbWl6YXRpb24lMjIlM0FmYWxzZSU3RCU3RCU3RA==

**Comment by ryansolid** [comment]
I see. And the explanation is good too. Well that's too bad there is no way from a library perspective I could make that decision for users. But I guess it's a cool trick for demos and benchmarks. Thank you.
