### ISSUE TITLE
Filter or exclude modules at rollup time

### ISSUE THREAD

**Issue by rapodaca** [rollup/rollup#497]
I have a composite module that bundles many child modules together. Its central entry point is <code>index.js</code> at a top-level directory.

A few child modules import native Node modules. These run just fine on Node. However, the presence of these modules generates errors when the bundled script is loaded in a browser.

Is there a convenient way to exclude such modules from the compiled bundle, without having to change the structure of the module source files?

To make this more concrete, one of my classes extends the stream.Transform class. I want to exclude this class and others like it from the output rollup. I'm willing to supply a list of child module names to exclude.

**Comment by TrySound** [comment]
You can use `globals` option
https://github.com/rollup/rollup/wiki/JavaScript-API#globals

**Comment by rapodaca** [comment]
It's not clear how <code>globals</code> works.

Let's say I have a module Baz that I import with:

```javascript
import Baz from './foo/bar/baz';
```

What would be the corresponding <code>globals</code> value to eliminate Baz from the rollup?

**Comment by TrySound** [comment]
@rapodaca globals is an object
```
globals: {
  './foo/bar/baz': 'Baz'
}
```

Please read documentation more attentively.

**Comment by rapodaca** [comment]
Thanks, but that didn't work, either.

To be clear, I have a file at <code>./foo/bar/baz.js</code> that exports the default <code>Baz</code>. This file is part of a tree of other modules in the same directory structure (<code>./foo/red</code>, <code>./foo/green</code>, etc). I want to eliminate Baz from my rollup entirely, while retaining every other module.

I tried the suggestion like so:

```javascript
bundle.write({
 format: 'iife',
  dest: 'build/bundle.js',
  moduleName: 'bundle',
  sourceMap: false,
  globals: {
    './foo/bar/baz': 'Baz'
 }
});
```

Yet the rollup still contains <code>Baz</code>. I've seen nothing in the documentation that treats this specific case. Nor does the documentation you linked to say anything about the purpose of <code>globals</code> - in other words, what happens to your rollup if it's used.

Moreover, the <code>globals</code> documentation only gives examples for external third-party modules (underscore and backbone). In my case, I want to strip out a few of my own modules from a hierarchy I created.

Ideas?

**Comment by Rich-Harris** [comment]
It's possible to use the `external` option with absolute paths to keep dependencies external to the bundle, as per [this example](https://gitlab.com/Rich-Harris/rollup-497/blob/master/rollup.config.js). Unfortunately I don't think that's what you want, because the IIFE output then just assumes that the missing modules are on the page, and the [resulting check](https://gitlab.com/Rich-Harris/rollup-497/blob/master/dist/bundle.js#L4) would cause an error (though that's fixable).

I guess what you really want is to be able to replace modules altogether (simply excluding them with `null` or `{}` doesn't quite work, for various reasons). Rollup itself has to do this for its browser build – it has a custom plugin that [replaces specific modules](https://github.com/rollup/rollup/blob/master/rollup.config.browser.js#L4-L9) with [these](https://github.com/rollup/rollup/blob/master/browser/fs.js) [files](https://github.com/rollup/rollup/blob/master/browser/promise.js).

Over on #483 we talked about creating a plugin that would genericise that process – I believe @callumlocke was looking into it.

@TrySound please be more considerate when responding to issues! Comments like [the one above](https://github.com/rollup/rollup/issues/497#issuecomment-180796016) come across as openly hostile in many cultures, even if it's not what you intend.

**Comment by rapodaca** [comment]
Thanks for first two links, but unfortunately both give 404.

#483 does look close to what I'm looking for. In that case, though, it looks like a whitelist. What I'm really after is a blacklist. In other words, a list of file paths within <code>entry</code> that will be be ignored by rollup.

Something like this would be ideal:

```javascript
rollup.rollup({
  entry: 'foo/index.js',
  ignore: [
    'foo/bar/baz.js'
  ]
}).then(function (bundle) {
  bundle.write({
    format: 'iife',
    dest: 'build/bundle.js',
    moduleName: 'bundle'
  });
});
```

If this doesn't yet exists, what are your thoughts on the feasibility of creating a plugin to do it? Do the necessary hooks already exist in Rollup, and if so, could you point me to them?

**Comment by Rich-Harris** [comment]
Oops – was a private project. Now fixed.

The rollup-plugin-source plugin wouldn't be a whitelist, per se – it would just ensure that Rollup got module code from the supplied options *before* looking at the filesystem. So if you had a config file like this...

```js
// rollup.config.js
import source from 'rollup-plugin-source';

export default {
  entry: 'foo/index.js',
  dest: 'build/bundle.js',
  plugins: [
    source({
      'foo/bar/baz.js': 'export default null'
    })
  ],
  format: 'iife',
  moduleName: 'bundle'
}
```

...then Rollup would, on encountering an `import` statement that referenced `foo/bar/baz.js` (wherever it was found), load `export default null`, rather than loading the contents of that file. Everything else would bypass the plugin and load normally. 

> What I'm really after is a blacklist. In other words, a list of file paths within `entry` that will be be ignored by rollup

As things stand, it would be impossible, because Rollup checks that an imported module has the necessary exports. So if you 'ignored' `foo/bar/baz.js` by replacing it with an empty module, Rollup would throw an error along the lines of `Module foo/bar/baz.js does not export default (imported by foo/index.js)`. We could change that behaviour for ignored modules, in theory, but it's a lot more flexible if you can control exactly what goes into the replacement module – e.g. you can provide end users with useful error messages, etc.

**Comment by rapodaca** [comment]
To follow up, here's a solution that worked for me.

Strip out the <code>index.js</code> file. I only needed it for building browser/node bundles anyway.

Create a new directory <code>module</code>. In it place two files, <code>server.js</code>, and <code>client.js</code>. <code>server.js</code> exports all classes, and <code>client.js</code> exports only those classes that can be loaded in a browser.

Depending on the kind of rollup being built, use either js file as the entry point.

**Comment by Alphapage** [comment]
Any news about rollup-plugin-source #483 ?
I can't find a way to create it easily via a plugin: I know where to start from the documentation, but I don't know which object to override.

**Comment by TrySound** [comment]
There is similar plugin here https://github.com/Permutatrix/rollup-plugin-hypothetical

**Comment by tbranyen** [comment]
Just so people get an idea of how to use the aforementioned plugin hypothetical, you need to enable real files, and pass references to your files from your project's root, very cool plugin!

``` js
  hypothetical({
    allowRealFiles: true,
    files: {
      // Remove tagged template helper in runtime.
      './lib/html.js': `
        import createTree from './tree/create';

        export default function html(...args) {
          return createTree(...args);
        }
      `,

      // Remove parser in runtime.
      './lib/util/parser.js': `
        export default () => console.log('Runtime is not built with parsing');
      `
    }
  }),
```

:+1:

**Comment by matthiasg** [comment]
I think the OP is looking for something like `babel-plugin-discard-module-references`  for babel, this can also be used for use cases such as embedding tests next to production code (see https://medium.com/@arnaudrinquin/frictionless-unit-testing-in-javascript-with-browser-tap-6ac2cea89a59) ..

**Comment by GerkinDev** [comment]
Any news on this? I can't find a way to successfully ignore a module. I'm trying to build a module that use `request` & `winston` packages on node but should simply skip them in the browser. Any help appreciated :)

**Comment by steph643** [comment]
Found this thread while looking for how to exclude a file from rollup input. Here is a solution: the `exclude` option of [rollup-plugin-multi-entry](https://github.com/rollup/rollup-plugin-multi-entry).

**Comment by balloob** [comment]
I wandered upon this issue when looking for an ignore plugin and couldn't find one, so I wrote my own (cheers for beautiful Rollup plugin API). Leaving it here so that if people are looking for one, they can copy it: https://github.com/home-assistant/frontend/blob/872e46a076c8d1096f3175dada4910ed6abde0dd/build-scripts/rollup-plugins/ignore-plugin.js

It just replaces files with empty ones, so only useful to filter things imported for their side effects.
