### ISSUE TITLE
How do you debug potential performance issues beyond the documented `--perf` flag?

### ISSUE THREAD

**Issue by NullVoxPopuli** [rollup/rollup#4978]
### Documentation is

- [ ] Missing
- [X] Needed
- [ ] Confusing
- [ ] Not sure?

### Please Explain in Detail...

I have this `--perf` output:

```
❯ pnpm rollup --config --perf

 → dist...
# ...
# BUILD: 30494ms, 306 MB / 384 MB
## initialize: 62ms, -710 kB / 77.8 MB
- plugin 1 (addon-modules) - buildStart: 60ms, -1.54 MB / 76.9 MB
- plugin 5 (node-resolve) - buildStart: 0ms, 2.53 kB / 76.9 MB
- plugin 4 (babel) - resolveId: 538ms, 40.1 MB / 612 MB
- plugin 6 (ember-externals) - resolveId: 622ms, 1.26 MB / 612 MB
## generate module graph: 30321ms, 295 MB / 373 MB
- plugin 7 (preprocess-glimmer-template-tag) - resolveId: 246ms, 79.3 MB / 612 MB
- plugin 8 (rollup-hbs-plugin) - resolveId: 840ms, 406 MB / 612 MB
- plugin 9 (copy-assets) - resolveId: 875ms, 427 MB / 612 MB
- plugin 11 (addon-css-rollup) - resolveId: 444ms, 17.9 MB / 612 MB
- plugin 15 (stdin) - resolveId: 330ms, 15.7 MB / 612 MB
- plugin 5 (node-resolve) - resolveId: 551ms, 283 MB / 612 MB
- plugin 4 (babel) - load: 98ms, 15.4 MB / 505 MB
- plugin 5 (node-resolve) - load: 0ms, 68.2 kB / 505 MB
- plugin 7 (preprocess-glimmer-template-tag) - load: 4ms, 683 kB / 505 MB
- plugin 8 (rollup-hbs-plugin) - load: 11ms, 975 kB / 505 MB
- plugin 11 (addon-css-rollup) - load: 1ms, 242 kB / 505 MB
- plugin 15 (stdin) - load: 0ms, 40.8 kB / 505 MB
- plugin 0 (json) - transform: 1ms, 144 kB / 506 MB
- plugin 4 (babel) - transform: 22ms, 12.1 MB / 506 MB
- plugin 10 (addon-rewritecss-rollup) - transform: 3ms, 823 kB / 509 MB
- plugin 11 (addon-css-rollup) - transform: 2ms, 341 kB / 509 MB
- plugin 12 (addon-js-unplugin) - transform: 2ms, 291 kB / 509 MB
- plugin 13 (addon-hbs-rollup) - transform: 1ms, 352 kB / 509 MB
generate ast: 87ms, -4.97 MB / 509 MB
analyze ast: 96ms, 6.31 MB / 509 MB
## sort and bind modules: 16ms, 7.6 MB / 380 MB
## mark included statements: 94ms, 3.63 MB / 384 MB
treeshaking pass 1: 31ms, 4.67 MB / 385 MB
treeshaking pass 2: 41ms, -1.11 MB / 384 MB
treeshaking pass 3: 7ms, 10.7 MB / 395 MB
treeshaking pass 4: 5ms, -8.49 MB / 386 MB
treeshaking pass 5: 4ms, 6.91 MB / 393 MB
treeshaking pass 6: 4ms, -9.43 MB / 384 MB
# GENERATE: 125ms, 20.4 MB / 405 MB
## initialize render: 0ms, 4.12 kB / 384 MB
## generate chunks: 7ms, 5.94 MB / 390 MB
## render chunks: 35ms, 1.03 MB / 391 MB
## transform chunks: 39ms, 12.7 MB / 404 MB
sourcemaps: 30ms, 3.26 MB / 406 MB
## generate bundle: 43ms, 439 kB / 405 MB
- plugin 2 (public-assets-bundler) - generateBundle: 4ms, 760 kB / 405 MB
- plugin 3 (app-reexports) - generateBundle: 5ms, -4.76 MB / 400 MB
- plugin 5 (node-resolve) - generateBundle: 0ms, 352 B / 400 MB
- plugin 9 (copy-assets) - generateBundle: 5ms, 1.07 MB / 401 MB
- plugin 11 (addon-css-rollup) - generateBundle: 1ms, 191 kB / 402 MB
- plugin 14 (delete) - generateBundle: 0ms, 8.62 kB / 402 MB
# WRITE: 29ms, 2.41 MB / 407 MB
```

most of the time is spent in the generation of the module graph
```
## generate module graph: 30321ms
```
but the output doesn't say what could be responsible for this much time.
Where is all the time going, and how do I find out?

I've done a `--cpu-prof` with node, and it seems most time is spent `resolve`ing -- but I'd like to know from what and why.

### Your Proposal for Changes

Could more instrumentation be added to `--perf`?

**Comment by lukastaegert** [comment]
There is (to my knowledge) only one thing not covered by these timings: Time spent in asynchronous plugin hooks. And I do not know how to improve reporting here, unfortunately.

Let me explain:

Most plugins hooks like `load` or `resolveId` support promises. However, while of course we can measure how much time it takes for a hook to complete, the result is usually completely misleading. The problem is that we are running dozens if not hundreds of these asynchronous hooks in parallel. So while one hook might take long, we have no way to find out if it is because the hook itself was slow or if another slow hook was running at the same time, blocking the event loop.
What we do measure is the synchronous time spent in each hook until it releases control to the event loop for the first time as we can be sure that this time is spent in the hook. These are the numbers you see above.

To know more, I fear using a real profiler is the best thing you can do, and you should look for time spent in plugins.

**Comment by NullVoxPopuli** [comment]
So, here is a goofiness:
 - one plugin, [here](https://github.com/embroider-build/embroider/pull/1413/files#diff-636ddf3a8d0a978099de278db57c1287277575d27820c8d218ec85c77fbe38aeR7), I originally thought the issue was coming from because commenting out the plugin in the rollup.config.mjs resulting in massive performance improvement
 - after diving deeper in to the cause (of a lot of extra resolve calls), I found that another plugin was to blame -- because of [this particular bit of code](https://github.com/NullVoxPopuli/rollup-plugin-glimmer-template-tag/blob/rollup-plugin-glimmer-template-tag%400.4.0/packages/rollup-plugin-glimmer-template-tag/src/rollup-plugin.js#L37-L38).

So, I fixed rollup-plugin-glimmer-template-tag, here, [by **not** defaulting to iterating 3 times over every potential import/source](https://github.com/NullVoxPopuli/rollup-plugin-glimmer-template-tag/blob/rollup-plugin-glimmer-template-tag%400.4.1/packages/rollup-plugin-glimmer-template-tag/src/rollup-plugin.js#L38).

Less is more.

The goofiness tho is that, I never saw plugin names during my profiling. I _did_ see a ton of resolve/async time tho. 
Maybe I profiled wrong, idk.

**Comment by mansona** [comment]
I think this issue should probably be opened again because the title and the difficulty of discovering the loss of time is still there and I think we could help guide users a bit better.

For example @NullVoxPopuli in your perf output you have the following: 

```
## generate module graph: 30321ms, 295 MB / 373 MB
```

but the combined times for all things under that all combine to `3431ms` which is an order of magnitude out 🤔 

@lukastaegert I get your point to say that the actual `ms` measurement will be incorrect for various reasons, but it would still point people in the direction of things that might be causing an issue.

**Comment by mansona** [comment]
Also we have tried out a plugin called `rollup-timer` that gives us some "interesting" data about which plugins are using the time, it has a few issues where it's over-reporting time but maybe we can figure out some middle ground between `rollup-timer` and the `--perf` arg 

Here is an issue that tries to describe the over-reporting that I'm talking about https://github.com/timdp/rollup-timer/issues/31
