### ISSUE TITLE
A way to get finalized file name from non-finalized file name in generateBundle hook

### ISSUE THREAD

**Issue by sapphi-red** [rollup/rollup#5080]
### Feature Use Case

`renderChunk` hook uses non-finalized file names (e.g. `foo-!~{001}~.js`) and `generateBundle` hook uses finalized file names (e.g. `foo-af91836c.js`).
I'm storing some data in a `Map` in `renderChunk` hook and using that data in `generateBundle` hook. I'm currently relying on `chunk.moduleIds` to judge the corresponding chunk.
But if there's a way to get the finalized file names from the non-finalized file names, it would be more reliable and more clear.

Actual usecase: https://github.com/vitejs/vite/blob/dd9d4c13202c6b639d43cad18e43d3b5d1a62fb2/packages/vite/src/node/plugins/css.ts#L734-L751

### Feature Proposal

Either

1. Add `nonFinalizedFileName` property to `ChunkInfo`
    - I noticed that this can be implemented by a plugin ([stackblitz](https://stackblitz.com/edit/rollup-repro-cwg9ey?file=rollup.config.js)). But I think it can be included in rollup.
1. Add `this.getFinalizedFilename(nonFinalizedFilename)` that can be used in `generateBundle` hook

The second one seems to be more flexible than the first one.

**Comment by lukastaegert** [comment]
I think an additional property would be easier to implement, otherwise Rollup needs to maintain some mapping somewhere. The property could just be added here where the final file name is determined: https://github.com/rollup/rollup/blob/3d90b3fc6d481dc7e3fb0bb781dee8c715bc196a/src/Chunk.ts#L328-L353
BTW the internal name would be `preliminaryFileName`. PR welcome.
