### ISSUE TITLE
Export * at bundle boundary

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup#51]
Issue #44 focused on `export * from '...'` within a bundle. This issue presents the problem of exporting all exports of a module through the bundle boundary. This simple example:
```js
// --- main.js
export * from './wat';

export function a() {}

// --- wat.js
export function wat () { return 4711; }
```
results in the following error:
```
Cannot read property 'id' of undefined
TypeError: Cannot read property 'id' of undefined
    at /.../repo/node_modules/rollup/.gobble-build/01-rollup/1/rollup.js:1922:41
    at Array.forEach (native)
    at Bundle.generate (/.../repo/node_modules/rollup/.gobble-build/01-rollup/1/rollup.js:1882:19)
    at Object.generate (/.../repo/node_modules/rollup/.gobble-build/01-rollup/1/rollup.js:2183:32)
    at /.../repo/node_modules/rollup/bin/runRollup.js:56:23
```

I'll take a look at the cause and possible solutions to the issue.

**Comment by Victorystick** [comment]
@Rich-Harris What exactly is the difference between Statement's `dependsOn` and `stronglyDependsOn`?

**Comment by Rich-Harris** [comment]
@Victorystick `dependsOn` just means that the statement references another name, so that it needs to be defined *somewhere* in the bundle - ideally before the statement, but not if that violates any strong dependencies. `stronglyDependsOn` means that the other name must be defined first (though strictly speaking that's not the case if the other name is a function declaration, because hoisting). In other words...

```js
class A {
  b () {
    return new B();
  }
}

class B extends A {
  a () {
    return new A();
  }
}
```

...`A` depends weakly on `B`, but `B` depends strongly on `A` – it can't be defined until `A` has been. A topological sort (which defines the module order) is undefined when you have cyclical dependencies, so differentiating between 'strong' and 'weak' dependencies allows us to ensure that `A` appears before `B`, regardless of which happens to be 'visited' first by the toposort.

In practice, a dependency is weak if the name is referenced inside a function (though an [exception](https://github.com/rollup/rollup/blob/913390201b4586f6b60dea868bbb1c68e8cbb2b3/src/Statement.js#L115-L126) is made for IIFEs, because it was the only way I could get [three-jsnext](https://github.com/rollup/three-jsnext) to work... it has lots of cyclical dependencies!).

**Comment by Victorystick** [comment]
The example I specified above, `export * from './internal'` should probably not be too difficult to get working. But I've been thinking about another case.

Since we cannot statically analyse `export * from 'external'`, I think we should recommend against it when bundling. It probably won't be very common for a bundle to export all from some external source. We could recommend `export * as namespace from 'external'`. Then we can do static analysis up to that point. Otherwise we'd have to do something similar to [what Babel does](https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&code=export%20*%20from%20'external'%3B). It makes the whole thing a lot more dynamic.

What do you think?

**Comment by caridy** [comment]
@Victorystick `export * from 'external'` is a very common case :), while `export * as namespace from 'external'` as a very different purpose, and using it extensibly will have perf implications.

The reason why `export * from "foo"` is very common is because in ES2015 modules you cannot modify/monkeypatch modules from outside, the only when to do so is by creating a proxy module that reexport everything, and patch some pieces of it. That's the case of conditional loader, patching, bucket testing, etc.

**Comment by Victorystick** [comment]
It's a rather peculiar situation I'm thinking of, where the exports of the entire bundle becomes dynamic due to some external module.

```js
// main.js
export * from './internal';

// internal.js
export * from 'exteral';
export var a = 6;
```

Also, do the named exports of a module take precedence over an `export *` re-export or not? We'd have to be able to check dynamically if the external module has defined `a` and then be careful not to overwrite it's binding with our own named export.

**Comment by caridy** [comment]
@Victorystick that's in the spec, local bindings take precedence. 

As for the dynamic check, yes, most errors related to bindings are dynamic errors anyway.

**Comment by Victorystick** [comment]
@caridy Haven't been able to find that part of the spec. But thanks a lot for telling me. It's great that local bindings take precedence.

So it won't be all that hard to solve. Great news.

**Comment by caridy** [comment]
@Victorystick here is the algo that describes the priority:

http://www.ecma-international.org/ecma-262/6.0/index.html#sec-getexportednames

step 7.d is the one that describes the semantics of it, excluding the default export and skipping anything that was exported using other export forms.

**Comment by krisselden** [comment]
As a workaround, I've just been generating my entry file with the re-exports I need, instead of `export * from './constants';`

**Comment by Victorystick** [comment]
I believe `export * from './internal'` from the entry file should be working now. I'll verify before closing this issue.

@caridy I haven't forgotten about `export * from 'external'`. I'll make sure to create a new issue for it.

**Comment by Victorystick** [comment]
Verified to be working.
