### ISSUE TITLE
Importing a module into a module hanging rollup

### ISSUE THREAD

**Issue by petulla** [rollup/rollup#52]
Rich

I must be missing something basic.

I have a module `foo.js`:

 ```
  var isTouch = true;
  function fooTest() {
    return isTouch
   }
   export { fooTest }
 ```

In my `main.js` I import successful :
`import { fooTest } from "foo";`

But if I try to import from within another module, say, `foo2.js`:

`import { fooTest } from "foo";`

This hangs rollup. What is the stupid thing I am doing wrong?? I'm following this [ES6 syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import).

**Comment by petulla** [comment]
Needed to use a relative path (even with the module in the same directory as the other module)

`import { fooTest } from "./foo";`

**Comment by Rich-Harris** [comment]
Hmmm... interesting that the MDN page has module names ending with `.js` - haven't seen that elsewhere. By default, Rollup basically does what node/Browserify does (if it's a relative path, gravy, otherwise use the external module resolution algorithm which defaults to looking for `node_modules/foo` in parent folders).

I discovered the hard way that you can't take shortcuts here - if you use `foo` to mean 'resolve foo against the base path' (where 'base path' is either explicit, or the directory containing the entry module, or the directory of the importing module), you end up in hot water because no-one else can then consume your package (because they can't make any guarantees about the base path). Even though that doesn't always apply (e.g. you're building an app, not a library to be consumed by others), this is one of those cases where failing early prevents some truly bewildering problems further down the line.

You *can* override the resolution logic if necessary:

```js
rollup.rollup({
  resolveId: function ( importee, importer ) {
    // simplified example - assumes no external modules
    if ( importee[0] !== '.' ) {
      return path.resolve( baseDir, importee ) + '.js';
    }
    return path.resolve( path.dirname( importer, importee ) ) + '.js';
  },
  // other options
}).then(...)
```

**Comment by petulla** [comment]
Makes sense. Thanks for articulating the use case logic, Rich.

**Comment by Twipped** [comment]
Leaving this here for anyone else who happens to stumble across this thread while trying to solve the same build hang that I've been chasing.

`node-sass` has an outstanding bug where if the event loop gets halted before it finishes compiling, the thread deadlocks and the process refuses to obey `process.exit()`. So if you're using rollup-plugin-postcss with sass, and the build fails because of a missing module, node-sass prevents rollup from exiting.

https://github.com/sass/node-sass/issues/1048
