### ISSUE TITLE
Rollup 4 with `minify` option

### ISSUE THREAD

**Issue by KingSora** [rollup/rollup#5217]
### Feature Use Case

Since rollup `v4` now uses `swc` for parsing under the hood, it might be beneficial if it also uses its minification capabilities for the output. This would eliminate the need of the [@rollup/plugin-terser](https://www.npmjs.com/package/@rollup/plugin-terser#rollupplugin-terser) and might increase the bundling performance for projects that use minification.

### Feature Proposal

- Add a new option in the `outputOptions` object called `minify` or `minified` which is a `boolean` or an options `object`.
- If a new option is undersired it could also be realised with a dedicated `@rollup/minify` plugin.

**Comment by lukastaegert** [comment]
That would be nice, but unfortunately, that is nothing that will happen within at least the next year. The reason is that we only use SWC for parsing, but not for rendering. Rendering would require huge refactors on our side and it is not clear if this is where Rollup is headed. It is not that I do not see such a feature on the horizon, but probably not anytime soon.
For now, if you want a faster minified, rollup-plugin-esbuild could be a good option.

**Comment by KingSora** [comment]
@lukastaegert thanks for the reply! This was just an idea in case nobody has thought of it.. I know there are several plugins to increase the performance over the `terser` one.

I'll close the issue then

**Comment by lukastaegert** [comment]
Yes, and it is not a bad idea. But I would not put this into core unless I see a way how this could work noticeably better than a separate plug-in but utilizing the data structures we already have. At the moment, we are only using a small sub-set of SWC features compiled directly into Rollup, and as a result, Rollup is also considerably smaller than SWC.
