### ISSUE TITLE
Reduce minimum file name template hash size in light of switch to base64

### ISSUE THREAD

**Issue by isker** [rollup/rollup#5234]
### Expected Behavior / Situation

The enforced minimum `hash` size in rollup `entryFileNames`/`chunkFileNames`/`assetFileNames` is 6.  This value hails from the times of the hash being rendered in hexadecimal (base 16).  Since rollup 4, it is rendered in base64.

The expectation is that this minimum limit would have been reduced when the hash encoding density was increased.

To be sure, this is a nitpick; we're trying to shave some bytes off an application manifest comprising a few thousand assets and feel we could go lower than 6 base64 digits.

### Actual Behavior / Situation

The minimum hash size has not been reduced:

```
RollupError: To generate hashes for this number of chunks (currently 1), you need a minimum hash size of 6, received 5. Check the "output.entryFileNames" option.
```

### Modification Proposal

I propose reducing it to 4. 64^4 === 16^6 === 16777216.

This might be easier said than done, seeing as the current minimum is a consequence of the placeholder implementation (?), rather than something specified arbitrarily:
https://github.com/rollup/rollup/blob/17d33a9bfb094e5e4242da8c84a082264ad299ec/src/utils/hashPlaceholders.ts#L26-L36

**Comment by lukastaegert** [comment]
The number 6 is a technical limitation, not an arbitrary one. This is due to how referenced hashes in the code are replaced by placeholders initially. The placeholders have the format `!~{1}~` where the number in the middle is an internal index of the hash. You see that 6 is the minimum length, supporting 10 hashes. You will also get an error when choosing 6 but generating more than 10 hashes chunks.
The placeholder format was chosen to ensure there is only minimal risk for accidentally having a collision with actual code.
