### ISSUE TITLE
Duplicated modules included in bundle when plugin resolved a relative path for id

### ISSUE THREAD

**Issue by sapphi-red** [rollup/rollup#5250]
### Rollup Version

4.4.1

### Operating System (or Browser)

Stackblitz

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-mparei?file=dist%2Fmain.js

### Expected Behaviour

Any of

1. Invalid id error to be thrown. For example: non-external resolved id should be absolute path.
2. Failed to load error to be thrown. For example: id `src/sub.js` cannot be loaded by the default behavior of rollup as it's not relative path.
3. The module is not duplicated.

### Actual Behaviour

The module `./src/sub.js` is duplicated in the bundle.

**Comment by lukastaegert** [comment]
This is not a bug. An `id` is a unique identifier for a module. Rollup's internal algorithm uses absolute paths to identify modules. If additionally you return a relative path for some other import of the same modules, then you are using two different ids for the same module, which means Rollup treats it as two different modules.
This is a feature as it does indeed allow you to duplicate modules—though you usually also write a `load` hook if you use a custom id that is not the absolute path. That you did not need this here is just because the default `load` algorithm can also load a relative path.

**Comment by sapphi-red** [comment]
To give some context, I found this behavior with this (misconfigured) config using alias plugin.
```js
import { test as test1 } from './sub.js';
import { test as test2 } from '$/sub.js';

console.log(test1);
console.log(test2);
```
```js
// rollup.config.js
alias({ entries: { $: 'src' } }) // should be path.resolve('src')
```
https://stackblitz.com/edit/rollup-repro-s5tmli?file=src%2Fmain.js

I felt the behavior is difficult to understand, because `src/sub.js` doesn't work but `$/sub.js` works.

In this case, would it make sense to add a warning to the alias plugin? I guess no one would use the alias plugin to duplicate the module.

**Comment by lukastaegert** [comment]
I think it would make sense. Of course theoretically, one could use the alias plugin to alias to some virtual modules, but I think if you understand these concepts, you would not use the alias plugin but directly write a resolveId hook. So it is a reasonable assumption that aliases only should be full paths and warn if this is not the case (or alternatively, resolve the path in the alias plugin).
