### ISSUE TITLE
Issue with rollup 4.6.0, building with jspreadsheet

### ISSUE THREAD

**Issue by olivierchatry** [rollup/rollup#5274]
### Rollup Version

4.5.1

### Operating System (or Browser)

Fedora 39

### Node Version (if applicable)

20

### Link To Reproduction

https://stackblitz.com/edit/vitejs-vite-kuhfs9?file=index.html,package.json&terminal=dev

### Expected Behaviour

Software should build. I'm sorry I used a vite repl, but it's the only way I found to show the behavior. I think 4.6.0 does not work as well as when I force the dependency, I get the same results.

### Actual Behaviour

11.19 [commonjs--resolver] Identifier "val" has already been declared
11.19 file: /build/app/node_modules/jspreadsheet-ce/dist/index.js:3499:24
11.19 3497:                     var i = parseInt(time[1]);
11.19 3498:                     obj.date = [y, m, d, h, i, 0];
11.19 3499:                     var val = obj.setLabel(newValue, obj.options);
11.19                               ^
11.19 3500: 
11.19 3501:                     // Current selection day
11.19 error during build:
11.19 RollupError: Identifier "val" has already been declared
11.19     at error (file:///build/app/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
11.19     at Module.error (file:///build/app/node_modules/rollup/dist/es/shared/node-entry.js:12737:16)
11.19     at BlockScope.addDeclaration (file:///build/app/node_modules/rollup/dist/es/shared/node-entry.js:7520:32)
11.19     at TrackingScope.addDeclaration (file:///build/app/node_modules/rollup/dist/es/shared/node-entry.js:7522:50)
11.19     at TrackingScope.addDeclaration (file:///build/app/node_modules/rollup/dist/es/shared/node-entry.js:9767:22)
11.19     at BlockScope.addDeclaration (file:///build/app/node_modules/rollup/dist/es/shared/node-entry.js:7522:50)
11.19     at Identifier.declare (file:///build/app/node_modules/rollup/dist/es/shared/node-entry.js:7188:39)
11.19     at VariableDeclarator.declareDeclarator (file:///build/app/node_modules/rollup/dist/es/shared/node-entry.js:10178:17)
11.19     at VariableDeclaration.initialise (file:///build/app/node_modules/rollup/dist/es/shared/node-entry.js:11843:24)
11.19     at new NodeBase (file:///build/app/node_modules/rollup/dist/es/shared/node-entry.js:4607:14)

**Comment by sapphi-red** [comment]
minimal reproduction: [1](https://rollupjs.org/repl/?version=4.6.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZih2YWwpJTIwJTdCJTVDbiUyMCUyMGlmJTIwKHRydWUpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGlmJTIwKHRydWUpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHZhciUyMHZhbCUyMCUzRCUyMCcnJTVDbiUyMCUyMCUyMCUyMCU3RCUyMGVsc2UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwdmFsJTIwJTNEJTIwJyclNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCU3RCU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTdEJTdE), [2](https://rollupjs.org/repl/?version=4.6.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZih2YWwpJTIwJTdCJTVDbiUyMCUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwdmFyJTIwdmFsJTIwJTNEJTIwJyclNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjB2YWwlMjAlM0QlMjAnJyU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTdEJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlN0QlN0Q=)

Interestingly, if I remove the `val` in `if` or `else` or the parameter, the error disappears.

BTW the parse error itself was happening in `./node_modules/jsuites/dist/jsuites.js` instead of `./node_modules/jspreadsheet-ce/dist/index.js`.

**Comment by lukastaegert** [comment]
Thanks, this was a huge help. Fix at #5276.
