### ISSUE TITLE
In plugins, renaming files as part of transformation

### ISSUE THREAD

**Issue by Conduitry** [rollup/rollup#530]
When writing plugins that transform files between completely different 'formats', it would be helpful to be able to rename the files as the transformation is happening - in particular, being able to change the file extension. This would let later plugins in the chain not worry about weird file extensions that have already been transformed into something they know what to do with.

Is this currently possible?

I don't see anything in the documentation about this. I do, however, see something that looks relevant, in https://github.com/mtojo/rollup-plugin-stylus-css-modules/blob/master/index.js - The object that's returned by the `transform()` function has an `id` property. Is this doing what I'm looking for? When I was trying that sort of thing with test plugins, the later plugins were still getting the original `id` from the filename.

**Comment by Victorystick** [comment]
No, it's not currently possible. But I've thought of the use-case.

**Comment by Conduitry** [comment]
Okay thanks. So that `id` value returned by `transform()` in stylus-css-modules doesn't actually do anything currently?

**Comment by Conduitry** [comment]
From my brief experiments, it looks like this would be as simple as adding something like

    if (result.id) {
      id = result.id;
    }

right around here: https://github.com/rollup/rollup/blob/master/src/utils/transform.js#L32

I haven't looked at rollup's code very much so this could have a lot of bad side effects.

Is this a feature that people want? Does this seem like a sane way to implement it?

**Comment by Conduitry** [comment]
Poke. Is this a feature any maintainers are interested in, and does this seem like a non-awful implementation of it?

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.

**Comment by graup** [comment]
Is there any other way to do this? What's the best way to rename a module after transforming it?

**Comment by graup** [comment]
I need this in a CSS processor for a library to change the output asset names so that downstream processors don't transform them again.

I actually found a solution, we can change module names using `entryFileNames`.

```
entryFileNames({ name }) {
  return `${name.replace('.css', '.css.processed')}.js`;
},
```

**Comment by SystemParadox** [comment]
I am confused as to why this is closed? How are you supposed to write a plugin that does a transform and outputs something to be transformed by the next plugin?

For example, if you have a custom `.foo` format that can be transformed to `.svelte`, how do you get the svelte plugin to recognise it since it's only looking for `.svelte` files?

This is the best I've come up with so far but it feels really convoluted and messy:

- Use `resolveId` to change the filename to `.foo.svelte`
- Add a `load` hook that matches `.foo.svelte` files and reads the original `.foo` file instead of using the default `load` that would now try to read `.foo.svelte`
- The `transform` hook matches against `.foo.svelte` files and returns svelte code

Also in vite-land this messes up `vite:dep-scan` so this is clearly not the right answer.

**Comment by SystemParadox** [comment]
With the svelte plugin at least you can configure the extensions, so if you tell it to also match `.foo` files then you only need `transform`. It seems very odd if this is the "official" way of doing this - the upstream plugin has to support this otherwise you're out of luck.
