### ISSUE TITLE
wasm-node fails on s390x

### ISSUE THREAD

**Issue by pavolloffay** [rollup/rollup#5354]
### Rollup Version

4.9.5

### Operating System (or Browser)

s390x

### Node Version (if applicable)

18

### Link To Reproduction

https://github.com/jaegertracing/jaeger-ui/pull/2119

### Expected Behaviour

Be able to build https://github.com/jaegertracing/jaeger-ui/pull/2119 with `wasm-node`  s390x

e.g. `docker buildx build --progress plain --platform linux/s390x --tag pavolloffay/jaeger-ui:s390x --build-arg=TARGETARCH=s390x -f ./Dockerfile .`

### Actual Behaviour

```
#9 568.4 $ NODE_ENV=production REACT_APP_VSN_STATE=$(../../scripts/get-tracking-version.js) vite build
#9 576.0 vite v5.0.11 building for production...
#9 576.5 ✓ 0 modules transformed.
#9 576.5 [vite:build-html] memory access out of bounds
#9 576.5 file: /workspace/packages/jaeger-ui/index.html
#9 576.5 error during build:
#9 576.5 RuntimeError: memory access out of bounds
#9 576.5     at wasm://wasm/0063bf96:wasm-function[1558]:0x162080
#9 576.5     at wasm://wasm/0063bf96:wasm-function[249]:0x104dc0
#9 576.5     at wasm://wasm/0063bf96:wasm-function[1442]:0x15f2f9
#9 576.5     at module.exports.xxhashBase64Url (/workspace/node_modules/rollup/dist/wasm-node/bindings_wasm.js:159:14)
#9 576.5     at getXxhash (file:///workspace/node_modules/rollup/dist/es/shared/node-entry.js:16781:12)
#9 576.5     at FileEmitter.assignReferenceId (file:///workspace/node_modules/rollup/dist/es/shared/node-entry.js:18266:27)
#9 576.5     at FileEmitter.emitAsset (file:///workspace/node_modules/rollup/dist/es/shared/node-entry.js:18311:34)
#9 576.5     at FileEmitter.emitFile (file:///workspace/node_modules/rollup/dist/es/shared/node-entry.js:18181:25)
#9 576.5     at Object.emitFile (file:///workspace/node_modules/rollup/dist/es/shared/node-entry.js:17585:41)
#9 576.5     at fileToBuiltUrl (file:///workspace/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:16718:43)
#9 576.7 error Command failed with exit code 1.
#9 576.7 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#9 ERROR: process "/bin/sh -c yarn install --frozen-lockfile && cd ./packages/jaeger-ui && yarn build" did not complete successfully: exit code: 1
------
 > [4/4] RUN  yarn install --frozen-lockfile && cd ./packages/jaeger-ui && yarn build:
576.5     at wasm://wasm/0063bf96:wasm-function[1442]:0x15f2f9
576.5     at module.exports.xxhashBase64Url (/workspace/node_modules/rollup/dist/wasm-node/bindings_wasm.js:159:14)
576.5     at getXxhash (file:///workspace/node_modules/rollup/dist/es/shared/node-entry.js:16781:12)
576.5     at FileEmitter.assignReferenceId (file:///workspace/node_modules/rollup/dist/es/shared/node-entry.js:18266:27)
576.5     at FileEmitter.emitAsset (file:///workspace/node_modules/rollup/dist/es/shared/node-entry.js:18311:34)
576.5     at FileEmitter.emitFile (file:///workspace/node_modules/rollup/dist/es/shared/node-entry.js:18181:25)
576.5     at Object.emitFile (file:///workspace/node_modules/rollup/dist/es/shared/node-entry.js:17585:41)
576.5     at fileToBuiltUrl (file:///workspace/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:16718:43)
576.7 error Command failed with exit code 1.
576.7 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
Dockerfile:7
--------------------
   5 |     COPY . .
   6 |     
   7 | >>> RUN  yarn install --frozen-lockfile && cd ./packages/jaeger-ui && yarn build
   8 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn install --frozen-lockfile && cd ./packages/jaeger-ui && yarn build" did not complete successfully: exit code: 1
```

More details and reproducer is in https://github.com/jaegertracing/jaeger-ui/pull/2119

**Comment by pavolloffay** [comment]
https://github.com/rollup/rollup/pull/5346 is a similar issue

**Comment by pavolloffay** [comment]
The build on ppc64le passed. Note that #5346  is running into a similar issue.

**Comment by bnordland** [comment]
I ran into a similar issue on IBM i. I'm curious if it is an issue of Big Endian vs. Little Endian?
See: https://github.com/mdn/content/issues/25569
https://hacks.mozilla.org/2017/01/typedarray-or-dataview-understanding-byte-order/

**Comment by lukastaegert** [comment]
Ah, those are big endian systems? That would indeed be an interesting point to investigate as I was not able to test on such a system yet. So while I thought I handled endianness efficiently and correctly, I was never able to test it. Maybe it is possible to emulate such a system for debugging?

**Comment by pavolloffay** [comment]
It should be possible to emulate it even with docker buildx e.g. https://github.com/jaegertracing/jaeger-ui/pull/2119/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R1

**Comment by pavolloffay** [comment]
I am closing this. We were able to build the jaeger-ui with the native x390s https://github.com/jaegertracing/jaeger-ui/issues/2160

**Comment by scotroach** [comment]
## Confirmed: the root cause is big-endian byte-order in the WASM AST/hash buffers (minimal repro on IBM i / os400 ppc64 BE)

Following up on @bnordland's earlier comment — I can confirm this is a **big-endian** bug, and I have a minimal standalone repro that isolates it to the WASM buffer marshaling (no Vite, no bundling, no `xxhash` needed).

### Environment
- **Platform:** IBM i (`os400`), `ppc64`, **big-endian** (`os.endianness() === 'BE'`)
- **Node:** v24.14.1 (reproduces on v20/v22 too)
- **Package:** `@rollup/wasm-node@4.62.2` (aliased as `rollup`)

(Note: there is a native `linux-ppc64-gnu` and `linux-s390x-gnu` binding now, but IBM i is `os400`, not `linux`, so it falls back to the WASM build — which is where this breaks.)

### Symptom in real use
Running `vite`/`vitest` fails during SSR config transform with:

```
Error: Unknown node type: 1207959552
    at convertNode (node_modules/rollup/dist/es/shared/parseAst.js:2084:15)
    at convertProgram (node_modules/rollup/dist/es/shared/parseAst.js:1126:18)
    at parseAstAsync (node_modules/rollup/dist/es/shared/parseAst.js:2122:106)
```

`1207959552` is `0x48000000`. The expected value is `0x48` (= `72`). It's the same byte written in the opposite order — classic little-endian-on-big-endian.

### Minimal repro
```js
// on a big-endian host (os400/ppc64, s390x, etc.)
// `parse` returns the flat AST buffer the JS layer then walks in convertNode/convertProgram
const { parse } = require('@rollup/wasm-node/dist/native.js');
const ast = parse('const x = 1;');           // Uint8Array
const buf = Buffer.from(ast.buffer ?? ast);
console.log('first u32 LE:', buf.readUInt32LE(0)); // => 72         (0x48, correct)
console.log('first u32 BE:', buf.readUInt32BE(0)); // => 1207959552 (0x48000000, what convertNode reads on BE)
```

(Verified on real IBM i hardware: the buffer's leading node-type tag is written as `0x48` little-endian and read back as `1207959552` on this big-endian host — matching the `Unknown node type: 1207959552` thrown by `convertNode` in a real `vite`/`vitest` run.)

The WASM core writes the AST buffer (and the xxhash output reported in the s390x trace) as little-endian, but the JS consumer reads multi-byte integers in **host** byte order. On a BE host every multi-byte field is byte-swapped, so `convertNode` reads a garbage node-type tag and throws.

### Why this matters / scope
This is the single root cause behind the `s390x` "memory access out of bounds" report **and** the IBM i `Unknown node type` failures — it affects **all big-endian platforms** using the WASM build. Fixing the buffer reads to use explicit little-endian (`DataView.getUint32(offset, /* littleEndian */ true)` / `readUInt32LE`) rather than host-endian `TypedArray`/native-order reads would fix every BE platform at once, without needing a per-platform native binary.

You mentioned not having BE hardware to test on — `docker buildx --platform linux/s390x` reproduces it under emulation, and the standalone snippet above gives a fast pass/fail signal without a full build.

Happy to test patches on real IBM i hardware.
