### ISSUE TITLE
wrong module execute order when manualChunks exists

### ISSUE THREAD

**Issue by haijie-x** [rollup/rollup#5357]
### Rollup Version

4.9.6

### Operating System (or Browser)

nodejs

### Node Version (if applicable)

18.15.0

### Link To Reproduction

https://github.com/haijie-x/rollup-issue

### Expected Behaviour

result:
```
lib.js execute
main.js execute
common.js execute
a.js execute
b.js execute
```

### Actual Behaviour

![image](https://github.com/rollup/rollup/assets/98948357/84a2f223-23df-4d26-af02-dec7498ca7dd)
when customize manualChunks, like following
```javascript
manualChunks(id) {
  if (id.includes("common")) return "common";
},
```
![image](https://github.com/rollup/rollup/assets/98948357/4971df1a-95bb-4cbe-ba67-614be1a7494c)

`import lib from "lib";` in entry file will be compiled into `import './common.js'`, which lead to wrong module execute order.

```
lib.js execute
common.js execute
main.js execute
a.js execute
b.js execute
```

**Comment by lukastaegert** [comment]
Yes, that is known and expected at the moment, see https://rollupjs.org/configuration-options/#output-manualchunks:

> Be aware that manual chunks can change the behaviour of the application if side effects are triggered before the corresponding modules are actually used.

**Comment by haijie-x** [comment]
> Yes, that is known and expected at the moment, see https://rollupjs.org/configuration-options/#output-manualchunks:
> 
> > Be aware that manual chunks can change the behaviour of the application if side effects are triggered before the corresponding modules are actually used.

Thank you, i will close this issue.

**Comment by haijie-x** [comment]
Thank for your quick response , i will close this issue.

**Comment by Tofandel** [comment]
Is there a way to solve or workaround this like forcing an order with multiple manual chunks? If I try to split vue or a component library into a different chunk I get

B3dciENV.js:2940 Uncaught ReferenceError: Cannot access 'isFunction$1' before initialization, inside a `defineComponent` of another chunk

Because `isFunction$1` inside the vue chunk is declared as `const isFunction$1 = () ...`  while `defineComponent` is a function. Effectively, the function exists because it's been evaluated but the const doesn't because the script hasn't run yet
