### ISSUE TITLE
question: about the example in the readme

### ISSUE THREAD

**Issue by mikefills** [rollup/rollup#539]
In the readme it says that

> But because of the limitations of static analysis, and the dynamic nature of JavaScript, it can't do the same thing with code like this:

```
(function () {
  var obj = {
    foo: function () {
      console.log( 'this method was included!' );
    },

    bar: function () {
      console.log( 'so was this :-(' );
      this.baz();
    },

    baz: function () {
      console.log( 'and this :-(' );
    }
  };

  obj.foo();
})();
```

In this case a local object is defined with properties.
Why does the minifier include 'bar' and 'baz'? How is this different than the previous example where instead of properties  foo, bar, baz are functions?

**Comment by eventualbuddha** [comment]
@mikefills it is not possible to statically determine whether the properties of an object are used or not with 100% accuracy. It's possible to get close if you have a very simple example or follow some very particular conventions, but it's simply not safe to remove anything most of the time.

For example, imagine we had this:

```js
(function() {
  var obj = {
    foo: function() {
      this[window.methodToCall]();
    },

    bar: function() {
      console.log('bar called!');
    }
  };

  window.methodToCall = 'bar';
  obj.foo();
})();
```

Let's pretend that we do want to try to remove object properties. We can see that we can't remove `foo` because of the `obj.foo()` call, but what about `bar`? We see what appears to be a dynamic access on `this`, which we'd have to know `=== obj` inside the method, so we'd have to say everything is fair game since the value of `window.methodToCall` could be anything. You might say that we could see that we're setting it to `'bar'` by running `window.methodToCall = 'bar'` immediately before calling `foo`, but what if somewhere else I'd done this?

```js
Object.defineProperty(window, 'methodToCall', {
  get: function() { return 'NOPE'; },
  set: function(value) { /* ignore sets */ }
});
```

In the general case, I believe this problem is equivalent to the [halting problem](https://en.wikipedia.org/wiki/Halting_problem) and therefore cannot be solved properly without constraining the problem significantly.

**Comment by mikefills** [comment]
@eventualbuddha 
Thank you very much.
I was just referring to the 2nd example from readme, I don't understand how it would be hard to figure out what to exclude compared to the 1st example.

**Comment by eventualbuddha** [comment]
@mikefills you mean the code you pasted above, right? That's exactly what my explanation addresses. While it *might* be possible to statically analyze that example to determine what is needed and what isn't, but what about this example?

```js
(function() {
  var obj = {
    foo: function() {
      return this.bar;
    },

    bar: 99
  };

  obj.foo.call({ bar: 44 });
})();
```

How can you tell whether `bar: 99` should be included or not? What about `foo: 1` in the code below?

```js
(function() {
  var obj = {
    foo: 1
  };

  Object.prototype.bar = function() {
    return this.foo;
  };

  obj.bar();
})();
```
