### ISSUE TITLE
Add new module format for System.register

### ISSUE THREAD

**Issue by joeldenning** [rollup/rollup#543]
Not sure if this has been discussed before, but I'd love the option to export my module as [System.register format](https://github.com/ModuleLoader/es6-module-loader/blob/master/docs/system-register.md). What are your thoughts on why to do it / not do it, and also how easy it would be?

**Comment by Rich-Harris** [comment]
Custom output formats is definitely [something that's been discussed](https://github.com/rollup/rollup/issues/269#issuecomment-153867099), and System in particular (potentially as a built-in format). System is tricky though as I think it requires a little more code massaging than AMD and CommonJS etc. It's not a priority for me personally but I'd definitely be glad to see a PR for it!

@guybedford would have a clearer picture of the pros and cons – since JSPM can already translate everything to System, it might be redundant in this context, but perhaps not.

**Comment by Victorystick** [comment]
We've been tracking this in #83.
