### ISSUE TITLE
What is the smartest way to import globals?

### ISSUE THREAD

**Issue by philer** [rollup/rollup#556]
Before using rollup (or any other module manager) my modules were simple IIFEs. I would pass in any required globals like so (see [1] for why):
```JS
(function(win, $, undefined) {
  // do things
}(window, jQuery);
```
In rollup I'm now using the `format: "iife"` option and I'd like that IIFE to also pass in those globals in a similar manner.

What I've managed so far is using the `globals` option in my config like so:
```JS
  // ...
  globals: {
    jQuery: 'jQuery',
    window: 'window',
  },
  // ...
```
Now I can use `import $ from 'jQuery'` and `import win from 'window'`. However the output file contains some unnecessary lines at the top:
```JS
	win = 'default' in win ? win['default'] : win;
	$ = 'default' in $ ? $['default'] : $;
```
While inefficient this at least doesn't break. However when I do the same thing for `undefined` using something like `undefined: 'void 0'` things get weird since it tries to check `undefined` for a member named `'default'`
```JS
undefined = 'default' in undefined ? undefined['default'] : undefined;
```
which naturally results in a `TypeError: invalid 'in' operand undefined`.

So question (1) is there a way to prevent that line (I'm new to the whole import/export syntax)?
Or (2) is there an altogether better way of doing this?

---
[1] In case someone is wondering why I want to pass globals and especially `undefined` as arguments:
* For some reason it is possible to overwrite `undefined` as a variable name, so accessing the "global" `undefined` is not always safe.
* Since it's just a name inside the IIFE uglifiers can minify it.
* Shorter scope depth is slightly faster.

**Comment by eventualbuddha** [comment]
You can achieve essentially the same thing with the `intro` option:

```js
// rollup.config.js
export default {
  entry: 'index.js',
  format: 'iife',
  intro: 'var undefined;',
  globals: {
    jquery: 'jQuery',
    window: 'window'
  }
};

// index.js
import win from 'window';
import $ from 'jquery';

$(win);

// build.js
(function (win,$) {
	'use strict';

	win = 'default' in win ? win['default'] : win;
	$ = 'default' in $ ? $['default'] : $;

	var undefined;
	$(win);

}(window,jQuery));
```

I hope that answers your question!

**Comment by philer** [comment]
Thanks for your reply. I guess that'll work for undefined.

So I understand that means there is no way to get rid of the unnecessary lines for win and $? It's probably mostly a cosmetic concern but it still kinda irks me that this may cause hard-to-detect bugs in case the respective globals end up having a random `default` property for whatever reason.

**Comment by Victorystick** [comment]
@philer You could import `window` as a namespace to get rid of the `default` issue. jQuery, not so much.

```js
import * as window from 'window';
```

**Comment by DavidBabel** [comment]
seems like a good idea, but it broke unit tests

**Comment by unclechen** [comment]
@eventualbuddha 
I got this warning:
'window' is imported by src/action-core.js, but could not be resolved – treating it as an external dependency

my code is like:
```
// rollup.config.js
export default {
  entry: 'index.js',
  format: 'iife',
  globals: {
    window: 'window'
  }
};

// index.js
import win from 'window';
...

// build.js
(function (win) {
    'use strict';

    win = 'default' in win ? win['default'] : win;
    ...

}(window));
```

**Comment by ReiMcCl** [comment]
In the example provided, if "default" is defined within the user's window then "w" would be assigned to the associated default value rather than the global window object. So rather than an inconvenience, this is actually a breaking issue.

'w = w && w.hasOwnProperty('default') ? w['default'] : w;'

And unfortunately importing as a namespace prevents assignment to the window's properties.

`import * as w from 'window';`

If there was a method of disabling the assignment that occurs when doing a traditional "import w from 'window';" then that would be beneficial, however I haven't found one as of yet.

**Comment by guybedford** [comment]
For this specific use case it is probably advisable to make a special module - `window.js` containing `export default window`.

**Comment by ReiMcCl** [comment]
Hi @guybedford , thanks for the quick response.

From my understanding, importing window.js separately would change the structure of the output a bit, from window being passed to "w" in the IIFE to simply replacing all instances of a matching "w" variable with a direct reference to window. This might be due to my config though, which I have provided below:

`import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

export default {
    input: 'src/didom.js',
    output: {
      file: 'dist/didom.js',
      format: 'iife'
    },
    sourceMap: true,
    plugins: [
        resolve(),
        commonjs({
            include: 'node_modules/**'
        })
    ]
};`
