### ISSUE TITLE
@__NO_SIDE_EFFECTS doesn't work for some edge case, especially the returned value uses in someway.

### ISSUE THREAD

**Issue by yuzheng14** [rollup/rollup#5568]
### Rollup Version

v4.18.0

### Operating System (or Browser)

rollup repl

### Link To Reproduction

https://rollupjs.org/repl/?version=4.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRSRUUtU0hBS0lORyU1Q25pbXBvcnQlMjAnLiUyRm5vLXNpZGUtZWZmZWN0LmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2coNSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMiUyRiolNDBfX05PX1NJREVfRUZGRUNUUyolMkYlNUNuZnVuY3Rpb24lMjBhKCklMjAlN0IlN0QlNUNuJTVDbmNvbnN0JTIwYiUyMCUzRCUyMCUyRiolNDBfX1BVUkVfXyolMkZhKCklNUNuJTVDbmIuaW5zdGFsbCUyMCUzRCUyMDExMSUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJuby1zaWRlLWVmZmVjdC5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQSU3QiUyMmFubm90YXRpb25zJTIyJTNBdHJ1ZSU3RCU3RCU3RA==

### Expected Behaviour

```javascript
// TREE-SHAKING

console.log(5);

```

### Actual Behaviour

```javascript
/*@__NO_SIDE_EFFECTS*/
function a() {}

const b = /*@__PURE__*/a();

b.install = 111;

// TREE-SHAKING

console.log(5);

```

Even the function `a` has been annotated that don't have any side effects. But when `no-side-effect.js` represents following:

```javascript
const b = {}

b.install = 111
```

`b` will be tree-shaken. 

Most of time this maybe introduce a tiny overhead, but when in a vue components library which use install function excessively. For example:

```javascript
import Component from './Component.vue'

Component.install = function(Vue) {
  Vue.components(Component.name, Component)
}

export const { Component }

```

And when use this libray, even just import plain libray like `import 'vue-component-library'`, it will introduce almost entire content of it.

```javascript
// bundle of a file just `import 'vue-component-library`
import { openBlock, createElementBlock } from "vue";
const _export_sfc = (sfc, props) => {
  const target = sfc.__vccOpts || sfc;
  for (const [key, val] of props) {
    target[key] = val;
  }
  return target;
};
const _sfc_main = {};
function _sfc_render(_ctx, _cache) {
  return openBlock(), createElementBlock("div", null, "111");
}
const Component = /* @__PURE__ */ _export_sfc(_sfc_main, [["render", _sfc_render]]);
Component.install = function(Vue) {
  Vue.component(Component.name, Component);
};
```

The [Rollup official document](https://rollupjs.org/configuration-options/#pure) says `@__PURE__` means `Rollup will tree-shake i.e. remove the call unless the return value is used in some code that is not tree-shaken.`. But in this situation, `b` should be tree-shaken, and then the call of function `a` should also be tree-shaken.

**Comment by lukastaegert** [comment]
No, this is absolutely correct. The problem is the line

```
b.install = 111
```

This will throw an error because b is `undefined` as `a` has no return value. There is no annotation you can put on this line to make Rollup ignore the error.

You can fix it by making a actually return an empty object https://rollupjs.org/repl/?version=4.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRSRUUtU0hBS0lORyU1Q25pbXBvcnQlMjAnLiUyRm5vLXNpZGUtZWZmZWN0LmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2coNSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMiUyRiolNDBfX05PX1NJREVfRUZGRUNUUyolMkYlNUNuZnVuY3Rpb24lMjBhKCklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwJTdCJTdEJTVDbiU3RCU1Q24lNUNuY29uc3QlMjBiJTIwJTNEJTIwJTJGKiU0MF9fUFVSRV9fKiUyRmEoKSU1Q24lNUNuYi5pbnN0YWxsJTIwJTNEJTIwMTExJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMm5vLXNpZGUtZWZmZWN0LmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBJTdCJTIyYW5ub3RhdGlvbnMlMjIlM0F0cnVlJTdEJTdEJTdE

**Comment by yuzheng14** [comment]
> No, this is absolutely correct. The problem is the line
> 
> ```
> b.install = 111
> ```
> 
> This will throw an error because b is `undefined` as `a` has no return value. There is no annotation you can put on this line to make Rollup ignore the error.
> 
> You can fix it by making a actually return an empty object https://rollupjs.org/repl/?version=4.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRSRUUtU0hBS0lORyU1Q25pbXBvcnQlMjAnLiUyRm5vLXNpZGUtZWZmZWN0LmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2coNSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMiUyRiolNDBfX05PX1NJREVfRUZGRUNUUyolMkYlNUNuZnVuY3Rpb24lMjBhKCklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwJTdCJTdEJTVDbiU3RCU1Q24lNUNuY29uc3QlMjBiJTIwJTNEJTIwJTJGKiU0MF9fUFVSRV9fKiUyRmEoKSU1Q24lNUNuYi5pbnN0YWxsJTIwJTNEJTIwMTExJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMm5vLXNpZGUtZWZmZWN0LmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBJTdCJTIyYW5ub3RhdGlvbnMlMjIlM0F0cnVlJTdEJTdEJTdE

I known that I construct a wrong minimal reproducible set, then consider this example https://rollupjs.org/repl/?version=4.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRSRUUtU0hBS0lORyU1Q25pbXBvcnQlMjAnLiUyRm5vLXNpZGUtZWZmZWN0LmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2coNSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMG9wZW5CbG9jayUyQyUyMGNyZWF0ZUVsZW1lbnRCbG9jayUyMCU3RCUyMGZyb20lMjAlNUMlMjJ2dWUlNUMlMjIlM0IlNUNuJTJGKiU0MF9fTk9fU0lERV9FRkZFQ1RTKiUyRiU1Q25jb25zdCUyMF9leHBvcnRfc2ZjJTIwJTNEJTIwKHNmYyUyQyUyMHByb3BzKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHRhcmdldCUyMCUzRCUyMHNmYy5fX3ZjY09wdHMlMjAlN0MlN0MlMjBzZmMlM0IlNUNuJTIwJTIwZm9yJTIwKGNvbnN0JTIwJTVCa2V5JTJDJTIwdmFsJTVEJTIwb2YlMjBwcm9wcyklMjAlN0IlNUNuJTIwJTIwJTIwJTIwdGFyZ2V0JTVCa2V5JTVEJTIwJTNEJTIwdmFsJTNCJTVDbiUyMCUyMCU3RCU1Q24lMjAlMjByZXR1cm4lMjB0YXJnZXQlM0IlNUNuJTdEJTNCJTVDbmNvbnN0JTIwX3NmY19tYWluJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiUyRiolNDBfX05PX1NJREVfRUZGRUNUU19fKiUyRiU1Q25mdW5jdGlvbiUyMF9zZmNfcmVuZGVyKF9jdHglMkMlMjBfY2FjaGUpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMG9wZW5CbG9jaygpJTJDJTIwY3JlYXRlRWxlbWVudEJsb2NrKCU1QyUyMmRpdiU1QyUyMiUyQyUyMG51bGwlMkMlMjAlNUMlMjIxMTElNUMlMjIpJTNCJTVDbiU3RCU1Q25jb25zdCUyMENvbXBBJTIwJTNEJTIwJTJGKiUyMCU0MF9fUFVSRV9fJTIwKiUyRiUyMF9leHBvcnRfc2ZjKF9zZmNfbWFpbiUyQyUyMCU1QiU1QiU1QyUyMnJlbmRlciU1QyUyMiUyQyUyMF9zZmNfcmVuZGVyJTVEJTVEKSUzQiU1Q25Db21wQS5pbnN0YWxsJTIwJTNEJTIwZnVuY3Rpb24oVnVlKSUyMCU3QiU1Q24lMjAlMjBWdWUuY29tcG9uZW50KENvbXBBLm5hbWUlMkMlMjBDb21wQSklM0IlNUNuJTdEJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMm5vLXNpZGUtZWZmZWN0LmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBJTdCJTIyYW5ub3RhdGlvbnMlMjIlM0F0cnVlJTdEJTdEJTdE

The `no-side-effect.js` is a file compiled from a vue file

```vue
<script setup lang="ts"></script>

<template>
  <div>111</div>
</template>
```

In this case `Rollup` couldn't tree-shake `CompA` as well.

**Comment by lukastaegert** [comment]
The problem is again the same line. Unfortunately, Rollup does not manage to statically analyze the return value of `_export_sfc`, as it is basically returning its first parameter. There is some room for improvement,  but in any case this is very much at the limit of what Rollup can do. The best you can do for now is wrap it in a pure IIFE https://rollupjs.org/repl/?version=4.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRSRUUtU0hBS0lORyU1Q25pbXBvcnQlMjAnLiUyRm5vLXNpZGUtZWZmZWN0LmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2coNSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMG9wZW5CbG9jayUyQyUyMGNyZWF0ZUVsZW1lbnRCbG9jayUyMCU3RCUyMGZyb20lMjAlNUMlMjJ2dWUlNUMlMjIlM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQ29tcEElMjAlM0QlMjAlMkYqJTQwX19QVVJFX18qJTJGKCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwX2V4cG9ydF9zZmMlMjAlM0QlMjAoc2ZjJTJDJTIwcHJvcHMpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnN0JTIwdGFyZ2V0JTIwJTNEJTIwc2ZjLl9fdmNjT3B0cyUyMCU3QyU3QyUyMHNmYyUzQiU1Q24lMjAlMjAlMjAlMjBmb3IlMjAoY29uc3QlMjAlNUJrZXklMkMlMjB2YWwlNUQlMjBvZiUyMHByb3BzKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjB0YXJnZXQlNUJrZXklNUQlMjAlM0QlMjB2YWwlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMHRhcmdldCUzQiU1Q24lMjAlMjAlN0QlM0IlNUNuJTIwJTIwY29uc3QlMjBfc2ZjX21haW4lMjAlM0QlMjAlN0IlN0QlM0IlNUNuJTVDbiUyMCUyMGZ1bmN0aW9uJTIwX3NmY19yZW5kZXIoX2N0eCUyQyUyMF9jYWNoZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwb3BlbkJsb2NrKCklMkMlMjBjcmVhdGVFbGVtZW50QmxvY2soJTVDJTIyZGl2JTVDJTIyJTJDJTIwbnVsbCUyQyUyMCU1QyUyMjExMSU1QyUyMiklM0IlNUNuJTIwJTIwJTdEJTVDbiUyMCUyMGNvbnN0JTIwQ29tcEElMjAlM0QlMjBfZXhwb3J0X3NmYyhfc2ZjX21haW4lMkMlMjAlNUIlNUIlNUMlMjJyZW5kZXIlNUMlMjIlMkMlMjBfc2ZjX3JlbmRlciU1RCU1RCklM0IlNUNuJTIwJTIwQ29tcEEuaW5zdGFsbCUyMCUzRCUyMGZ1bmN0aW9uKFZ1ZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwVnVlLmNvbXBvbmVudChDb21wQS5uYW1lJTJDJTIwQ29tcEEpJTNCJTVDbiUyMCUyMCU3RCUzQiU1Q24lMjAlMjByZXR1cm4lMjBDb21wQSUzQiU1Q24lN0QpKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIybm8tc2lkZS1lZmZlY3QuanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0ElN0IlMjJhbm5vdGF0aW9ucyUyMiUzQXRydWUlN0QlN0QlN0Q=

**Comment by yuzheng14** [comment]
> The problem is again the same line. Unfortunately, Rollup does not manage to statically analyze the return value of `_export_sfc`, as it is basically returning its first parameter. There is some room for improvement, but in any case this is very much at the limit of what Rollup can do. The best you can do for now is wrap it in a pure IIFE https://rollupjs.org/repl/?version=4.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRSRUUtU0hBS0lORyU1Q25pbXBvcnQlMjAnLiUyRm5vLXNpZGUtZWZmZWN0LmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2coNSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMG9wZW5CbG9jayUyQyUyMGNyZWF0ZUVsZW1lbnRCbG9jayUyMCU3RCUyMGZyb20lMjAlNUMlMjJ2dWUlNUMlMjIlM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQ29tcEElMjAlM0QlMjAlMkYqJTQwX19QVVJFX18qJTJGKCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwX2V4cG9ydF9zZmMlMjAlM0QlMjAoc2ZjJTJDJTIwcHJvcHMpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnN0JTIwdGFyZ2V0JTIwJTNEJTIwc2ZjLl9fdmNjT3B0cyUyMCU3QyU3QyUyMHNmYyUzQiU1Q24lMjAlMjAlMjAlMjBmb3IlMjAoY29uc3QlMjAlNUJrZXklMkMlMjB2YWwlNUQlMjBvZiUyMHByb3BzKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjB0YXJnZXQlNUJrZXklNUQlMjAlM0QlMjB2YWwlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMHRhcmdldCUzQiU1Q24lMjAlMjAlN0QlM0IlNUNuJTIwJTIwY29uc3QlMjBfc2ZjX21haW4lMjAlM0QlMjAlN0IlN0QlM0IlNUNuJTVDbiUyMCUyMGZ1bmN0aW9uJTIwX3NmY19yZW5kZXIoX2N0eCUyQyUyMF9jYWNoZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwb3BlbkJsb2NrKCklMkMlMjBjcmVhdGVFbGVtZW50QmxvY2soJTVDJTIyZGl2JTVDJTIyJTJDJTIwbnVsbCUyQyUyMCU1QyUyMjExMSU1QyUyMiklM0IlNUNuJTIwJTIwJTdEJTVDbiUyMCUyMGNvbnN0JTIwQ29tcEElMjAlM0QlMjBfZXhwb3J0X3NmYyhfc2ZjX21haW4lMkMlMjAlNUIlNUIlNUMlMjJyZW5kZXIlNUMlMjIlMkMlMjBfc2ZjX3JlbmRlciU1RCU1RCklM0IlNUNuJTIwJTIwQ29tcEEuaW5zdGFsbCUyMCUzRCUyMGZ1bmN0aW9uKFZ1ZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwVnVlLmNvbXBvbmVudChDb21wQS5uYW1lJTJDJTIwQ29tcEEpJTNCJTVDbiUyMCUyMCU3RCUzQiU1Q24lMjAlMjByZXR1cm4lMjBDb21wQSUzQiU1Q24lN0QpKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIybm8tc2lkZS1lZmZlY3QuanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0ElN0IlMjJhbm5vdGF0aW9ucyUyMiUzQXRydWUlN0QlN0QlN0Q=

I realized. Thank you.
