### ISSUE TITLE
variable declerations being swallowed

### ISSUE THREAD

**Issue by calvinmetcalf** [rollup/rollup#568]
this file

``` js
var foo = 21;

var module = {exports: {}};

var exports = module.exports;

export {exports as default};

module.exports = foo * 2;

if (module.exports !== exports){exports = module.exports;}
```

gets turned into 

``` js
var foo = 21;

var module$1 = {exports: {}};

exports.default = module.exports;

module$1.exports = foo * 2;

if (module$1.exports !== exports$1){exports$1 = module$1.exports;}

export default exports$1;
```

I've even got the bizarre line 

``` js
var exports.exports$1 = module$1.exports;
```

to be generated once.

My guess is that this has to do with modifying the variable we export as default which (afaik) is totally legit to do in es6 modules.

**Comment by Rich-Harris** [comment]
Slightly simplified test [here](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22var%20module%20%3D%20%7Bexports%3A%20%7B%7D%7D%3B%5Cn%5Cnvar%20exports%20%3D%20module.exports%3B%5Cn%5Cnexport%20%7Bexports%20as%20default%7D%3B%5Cn%2F%2Fexport%20default%20exports%5Cn%5Cnexports%20%3D%20'x'%3B%22%7D%5D%7D). Looks like if you do

```js
export default exports;
```

rather than

```js
export { exports as default };
```

things start to work as expected? Either way it's a bug

**Comment by arxpoetica** [comment]
I'm importing a prebaked minified library (`happyjs`), like so:

```
import '../../../app/assets/javascripts/lib/happy.min.js';
```

It imports happy (get it?), but actually not, because it's stripping off a global var declared at the end of the minified lib. I'll bake a gist for comparison.

![image](https://cloud.githubusercontent.com/assets/111424/20078497/da98de76-a50e-11e6-98d8-0b953c104d0e.png)
(https://gist.github.com/arxpoetica/864719a797179f42129332e1e6c45b3b/revisions)

So it goes from:

```
...(this.jQuery||this.Zepto);var happy={USPhone:function(a){return/^\(?(\d{3})\)?[\- ]?\d{3}[\- ]?\d{4}$/.test(a)},date:function(a){return/^(?:0[1-9]|1[0-2])\/(?:0[1-9]|[12][0-9]|3[01])\/(?:\d{4})/.test(a)},email:function(a){return/^(?:\w+\.?\+?)*\w+@(?:\w+\.)+\w+$/.test(a)},minLength:function(a,b){return a.length>=b},maxLength:function(a,b){return a.length<=b},equal:function(a,b){return a==b}};
```

to:

```
...(window.jQuery||window.Zepto);
```

Is this the same problem/bug? Why is it stripping out a global var? (Am I not understanding Rollup?)

**Comment by arxpoetica** [comment]
I just realized. Is this an export problem? If I append `window.console.log(happy);` to the end of the prebundled, minified file, it starts working correctly. Does rollup only include code if it's been made modular somehow? This is a tricky concept (I would argue) and either I missed the documentation on what that means...or...?

**Comment by Rich-Harris** [comment]
I think the original issue is fixed now so will close this (correct me if I'm wrong) – @arxpoetica I think yours is a separate issue, it's expecting `happy.min.js` to have side-effects, which it doesn't (because any variable declarations are treated as being module-local, rather than applying to the global namespace). If it needs to be included in the bundle you'd need to turn it into a module (e.g. adding `export { something }` at the end) and import it as such (`import { something } from '...`)

**Comment by arxpoetica** [comment]
@Rich-Harris that is *really* helpful, thanks.
