### ISSUE TITLE
Support .mjs

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#573]
This is more of a heads-up than anything, and an opportunity to discuss some changes that are coming down the pike.

At the last Node Foundation CTC meeting, the committee [voted in favour](https://docs.google.com/document/d/143taqyrXGgOSlwR67lMGhYSm5-kwRznfEE-pOs2CaYU/view) of using file extensions to detect ES modules (as opposed to self-executing scripts). This is instead of other proposals such as adding metadata to package.json (`jsnext:main`, which [some folks on TC39 have suggested](https://github.com/jsforum/jsforum/issues/5#issuecomment-181493806) could become `module`), or less reliable solutions (discussion at https://github.com/nodejs/node-eps/issues/13). Thanks to @bmeck (who is close to the various discussions) for keeping us in the loop.

TC39 will be discussing this at their next meeting next week, and if this is the direction that the community ends up going in (which seems likely) tools like Rollup can help to anticipate and smooth over the transition.

The idea is that a package that wished to support both ES module and legacy environments could have an `index.js` file (presumably CommonJS or UMD) and an `index.jsm` file (ES module):

```js
// index.js
module.exports = {
  foo: require('./lib/foo'), // i.e. foo.js
  bar: require('./lib/bar')
};

// index.jsm
import foo from './lib/foo.jsm';
import bar from './lib/bar.jsm';

export { foo, bar };
```

Personally I think it's a great idea. While `jsnext:main` has been moderately successful, it's also caused a bit of confusion, and package.json metadata has other problems – not least the fact that it only applies to a module's entry point rather than to non-entry-point files. With this proposal it becomes easier for a library like (say) Lodash to support different environments without having multiple packages.

Needless to say `jsnext:main` support would continue (via rollup-plugin-node-resolve) for the forseeable future.

An aside: I haven't been able to contribute much to this project lately owing to 9-to-5 work and travel. Back soon hopefully :)

**Comment by bmeck** [comment]
It should be noted that we are still in final bikeshedding of the exact file extension. `.jsm` or `.m.js` are the most likely.

**Comment by eventualbuddha** [comment]
`.m.js` has the advantage of not needing explicit editor support for syntax highlighting. A minor advantage, but still :wink:

Also, @Rich-Harris, does this have implications for your policy of "always include the file extension in imports"?

**Comment by Rich-Harris** [comment]
> does this have implications for your policy of "always include the file extension in imports"?

I think it probably makes it *slightly* more important. But since a) it will take a while for people to start writing `.jsm` (or `.m.js`) files, and b) we don't want to create a whole lot of work for people who currently use extensionless imports as, we'd have to support all three for a while. 

Occurs to me that it would be fairly straightforward to create a utility that automated the process of adding `.js` to import statements, and eventually adding `.m.js`/`.jsm` and renaming files accordingly (and replacing `./foo` with `./foo/index.js[m]` along the way). Would be a valuable public service since people will probably otherwise have to do that manually when proper module loaders eventually appear.

**Comment by callumlocke** [comment]
Has there been any further update, or can we expect one soon?

**Comment by bmeck** [comment]
@callumlocke waiting on tc39 meeting notes to confirm (they are taking longer than normal), then should be a pretty fast follow.

**Comment by eventualbuddha** [comment]
The notes for 3/29-3/31 don't seem to include any mention of this. @bmeck, ideas?

**Comment by bmeck** [comment]
@eventualbuddha the meeting ended w/o discussion on the topic, this has pretty much left the Node CTC as the main discussion point. All indicators are still on the same path, CTC voted for file extension of `.mjs` due to concerns about `.jsm` as outlined in the [EP](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md). There have been counter proposals (many) since we merged this, we have not moved it to approved but it is the way forward and the new way to confirm is to wait on CTC to move the EP to approved status. This is a little bit of a setback time wise as scheduling was jumbled with so many proposals being presented after the EP was merged. We have reviewed the proposals and [as of yesterday](https://github.com/nodejs/node/issues/6567) are still seeing the file extension as the appropriate choice. More meetings will follow, but no clear reason why it would change at this point. Putting it under a flag if you want to support it prior to it being approved would be one course of action that could be taken.

**Comment by Rich-Harris** [comment]
Looks like this will be unnecessary, thanks to @bmeck and @jdalton's unambiguous grammar proposal 🎉  https://twitter.com/jdalton/status/750817391949389824

**Comment by eventualbuddha** [comment]
That's great! So for library authors targeting node versions that support this it seems simple: distribute an ES module with a `goal` set in the package.json (subject to change).

What about supporting old and new versions? There document didn't make any recommendations on that front that I saw.

**Comment by jdalton** [comment]
If you're package wishes to support older versions of Node (pre ES module) then you'd continue the current workflow of publishing transpiled code (cjs).

**Comment by Rich-Harris** [comment]
@jdalton so `jsnext:main` is still the only practical way to support both?

**Comment by jdalton** [comment]
I'm not familiar with `jsnext:main` in the context of rollup.

**Comment by jdalton** [comment]
OK, I [read up a bit](https://github.com/rollup/rollup#can-i-distribute-my-package-as-an-es6-module). You're saying that folks would continue to use CJS for the package but tools would be able to grab the ES module source to do transforms or bundles on. I think that's fine being tackled as it is in user land today since it's not branching execution for old and new enviros. Branching execution for old and new is something to be weary of because of inconsistencies in transpiled vs. built-in code paths/functionality.

**Comment by TrySound** [comment]
Ref https://github.com/rollup/rollup-plugin-node-resolve/pull/49
