### ISSUE TITLE
Using a scoped package name break UMD module generation

### ISSUE THREAD

**Issue by zackthehuman** [rollup/rollup#582]
I want to generate a UMD module where the name is a scoped package, e.g. `@something/modulename`. Doing so triggers an error a build time because the generated code is invalid:

```
factory((global.@something/modulename = {}) ... etc.
```

Would it be possible to detect this kind of situation an instead generate something like:

```
factory((global['@something/modulename'] = {}) ... etc.
```

This is a killer for me because we scope all of our internal modules.

**Comment by Rich-Harris** [comment]
Huh, I just replied to https://github.com/rollup/rollup/issues/584 suggesting that using an invalid identifier as a `moduleName` should cause an error to be thrown instead of generating bad code. But you're saying you actually want to create a property of `window` called `@something/modulename` rather than e.g. `window.something.modulename`?

**Comment by davidchase** [comment]
i believe babel umd-plugin strips the `@` and `/` characters so we have something like `@most/create` which becomes `global.mostCreate`

**Comment by christopherthielen** [comment]
I created a PR #1144 which allows arbitrary `moduleName` including `module-with-dashes`, yet still processes dot-notation `foo.bar.baz`.

---

The reason I want to allow dashes is because webpack UMD generates:

```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define("ui-router-visualizer", [], factory);
	else if(typeof exports === 'object')
		exports["ui-router-visualizer"] = factory();
	else
		root["ui-router-visualizer"] = factory();
```

I've published the library (built with webpack) for a while now, which sets `ui-router-visualizer` on the window.  I've also documented how to access via `window['ui-router-visualizer']` for my users in [various places](https://github.com/ui-router/visualizer#using-a-script-tag).

I'd like to switch to rollup, but I don't want to break existing users who still use `<script>` tags to load the library.
