### ISSUE TITLE
 How to resolve jquery dependency in bootstrap with rollup

### ISSUE THREAD

**Issue by mrbian** [rollup/rollup#592]
when I was using webpack,I used `require(expose?$=jquery!jquery)` plugin to expose jquery and then `require("bootstrap")`,
but I can not find a way to resolve this problem by rollup.
Is there anybody can give me a solution?

**Comment by Victorystick** [comment]
@mrbian I don't quite understand what you're trying to accomplish. I'm unfamiliar with the `require(expose?$=jquery!jquery)` incantation.

**Comment by TrySound** [comment]
@mrbian 
```
import jquery from 'jquery';
window.jQuery = jquery
```

**Comment by mrbian** [comment]
Sorry about my careless and thank you for your reply.

What I want to do is importing bootstrap and jquery in my project by rollup without writing script tag to include jquery.

So I write code like this in my **rollup.config.js**
```
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
export default {
    entry: 'main.js',
    dest: 'dist/bundle.js',
    format:'iife',
    plugins: [
        commonjs({
            namedExports: {
                'node_modules/jquery/dist/jquery.min.js': [ 'jquery' ],
                'node_modules/angular/angular.min.js' : ['angular'],
                'node_modules/bootstrap/dist/js/bootstrap.min.js' : ['bootstrap']
            }
        })
    ],
    globals: {
    },
    external: [
    ]
}
```
then I write these code in **main.js**
```
import jQuery from 'jquery';
var $ = jQuery;
$(body).html("hello rollup");
```
**this is ok but when I want to import bootstrap in my project**
```
import jQuery from 'jquery';
var $ = jQuery;
import('bootstrap');
```
I got an error in my chrome console
```
Uncaught ReferenceError: jQuery is not defined
```
Ooops! It seems that bootstrap cannot get jQuery.
I resolved the problem like this with expose plugin when I was using webpack.
I have tried to understand the wiki and do not find the way to resolve this.

**Comment by TrySound** [comment]
@mrbian Hm.. didn't know this syntax is allowed. `import('bootstrap');`
It's because bootstrap module trying to find global jQuery object which is loaded in local scope. Try `window.jQuery = jQuery` before all plugins.

**Comment by mrbian** [comment]
@TrySound  Thank you for your reply.I have updated my comment.
I write 
```
import jquery from "jquery";
window.jQuery = jquery;
import "bootstrap";
```
But I still got 
```
Uncaught ReferenceError: jQuery is not defined
```

**Comment by TrySound** [comment]
@mrbian Give me link to bootsrap script please.

**Comment by mrbian** [comment]
which kind of link?
Is it this?
```
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js
```
I got
```
affix.js:162  Uncaught ReferenceError: jQuery is not defined
```

**Comment by Victorystick** [comment]
@mrbian When you're doing `import jquery from 'jquery';` you aren't using a named export. You can remove that.

```diff
        commonjs({
            namedExports: {
-               'node_modules/jquery/dist/jquery.min.js': [ 'jquery' ],
                'node_modules/angular/angular.min.js' : ['angular'],
                'node_modules/bootstrap/dist/js/bootstrap.min.js' : ['bootstrap']
            }
        })
```

The problem is that both `import jquery...` and `import 'bootstrap';` are evaluated _before_  `window.jQuery = jquery`. That's one of the ways ES6 module semantics differs from CommonJS' `require`. One way to get around this is to instead do this:

```js
// main.js
import './jquery-global.js';
import 'bootstrap';

// jquery-global.js
import jquery from 'jquery';
window.jQuery = jquery;
```

That way you make sure that the `jQuery` global is defined before Bootstrap is loaded.

**Comment by mrbian** [comment]
@Victorystick  @TrySound  Thank for all of you.

**Comment by peterdenev** [comment]
I face the same problem and I've solved it with using [rollup-plugin-inject](https://github.com/rollup/rollup-plugin-inject) 

```javascript
inject({      
      include: '**/*.js',
      exclude: 'node_modules/**',
      jQuery: 'jquery',
})
```

**Comment by christianirack** [comment]
Testing whith this

import jquery from 'jquery'
window.jQuery = jquery
require('bootstrap')

I worked

**Comment by imudin** [comment]
@christianirack where did u you add `window.jQuery = jquery`? is it possible to add in one place and use it in other js files?

**Comment by sureshvv** [comment]
https://www.cnblogs.com/shenfanzui/p/13157978.html

**Comment by samypr100** [comment]
If you want to split your bundles and still make it work (e.g. jquery, bootstrap, vendor, etc.), you might encounter issues with jquery not defined when the vendor or other bundles load. This may happen if jquery suddendly gets bundled into a vendor chunk, or some other chunk and `window.jQuery = jquery;` doesn't happens in time.

To resolve that, one way is to make sure you have the `'jquery-global.js'` be part of a chunk that effectly loads before vendor using [manualchunks](https://rollupjs.org/configuration-options/#output-manualchunks). This chunk would load before due to the solution described in https://github.com/rollup/rollup/issues/592#issuecomment-205783255, but you'd still retain the ability to split out chunks however you'd like (e.g. `bootstrap` in it's own chunk).

```js
manualChunks(id) {
  if (id.includes(id.includes('node_modules/jquery/') || id.includes('src/jquery-global.js')) {
    return 'jquery';
  }
  // ...
}
```
