### ISSUE TITLE
Support default index.js when importing directories

### ISSUE THREAD

**Issue by martypdx** [rollup/rollup#599]
Not entirely sure what the ES module spec is, but most current transpilers eventually use `require` which allows defaulting to `index.js` when a directory is imported:

```
- foo
    - index.js
```

`import foo from './foo';`

rollup currently fails unless you use `'./foo/index'`

**Comment by Rich-Harris** [comment]
In a browser environment, file paths obviously have to be specific, otherwise you'll end up with a bunch of 404s. (The [spec](https://whatwg.github.io/loader/#browser-loader-prototype-%40%40resolve) isn't *totally* unambiguous, but that's what I've gathered from that and conversations with better-informed people.) We're actually thinking about enforcing the file extension as well, though there's apparently some conversation happening in the corridors of power about adding a `.jsm` extension for modules, so we're waiting for the dust to settle.

So, in the interests of avoiding nasty surprises when we get native loaders, Rollup makes as few assumptions as possible – the way to get the `foo/index.js` behaviour is to use [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve), which basically just wraps node-resolve.

**Comment by martypdx** [comment]
Seems about right. As long as it was intentional :grin: 

After another hour of coding the file got renamed to something specific anyway, so relevancy for me was short lived :D

> conversation happening in the corridors of power about adding a .jsm extension for modules,

Yes, I've been following that as well. Fun times ahead :tada:
