### ISSUE TITLE
Should load and  resolveId only works for current plugin?

### ISSUE THREAD

**Issue by differui** [rollup/rollup#617]
In #612 I wanna filter importees according to imporeeId with `"scoped!"` prefix.But I failed because `resolveId` method is public for all plugins.

Should `load` and `resolveId` only work for currnet plugin?I think:

1. More intuitive in this way.
2. Prevent affecting each other between plugins.

**Comment by Victorystick** [comment]
@differui The order is `resolveId -> load -> transform`. The idea is that plugins should be composable; so that one may resolve ids, another load an id, and a third transform it without being aware of the others. If your `resolveId` function removes the prefix, you've caused the problems yourself.

If you want the transforms of one plugin to _exclude_ certain ids, you'll need to set the plugin's `include` or `exclude` options. You'll just have to make sure that you can filter based on the _resolved ids_. You could try another file extension, like `*.scoped.scss` for scoped files, and tell the sass plugin to exclude such files.

Alternatively, you can leave the prefix intact and implement your own `load` function which loads those `"scope!"`d files.
