### ISSUE TITLE
Support for jsnext:main?

### ISSUE THREAD

**Issue by smebberson** [rollup/rollup#622]
Do you guys actually support `jsnext:main`?

I read about it on your wiki, so I removed the `entry` option from `rollup.config.js` and added `'jsnext:main': 'src/file.js'` and ran `rollup -c` again but I received an error.

Am I doing something wrong?

**Comment by Rich-Harris** [comment]
`jsnext:main` is an informal convention that allows packages in your `node_modules` folder to indicate the location of *their* entry files – so that if you have...

```js
import foo from 'foo';
```

...and `node_modules/foo/package.json` has a line like this...

```js
"jsnext:main": "dist/foo.es.js"
```

...then Rollup can resolve `foo` to `node_modules/foo/dist/foo.es.js` – but *only* if it knows how to resolve files in `node_modules`. That's where [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve) comes in – it teaches Rollup about `node_modules`:

```js
// rollup.config.js
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  entry: 'src/index.js',
  dest: 'bundle.js',
  format: 'cjs',
  plugins: [ nodeResolve({ jsnext: true }) ]
};
```

**Comment by Rich-Harris** [comment]
For the sake of completeness, should add that Node has settled on an official convention of using the `.mjs` extension to indicate that a file is an ES module, and in the future, this...

```js
// package.json
{
  ...
  "main": "dist/foo"
  ...
}
```

...will be basically equivalent to this:

```js
// package.json
{
  ...
  "main": "dist/foo.js",
  "jsnext:main": "dist/foo.mjs",
  ...
}
```

(Strictly speaking the `main` is unnecessary – if absent, is equivalent to `"main": "index"`. Omitting `main` in favour of a standard package structure is a convention that makes a lot of sense IMHO.)

Rollup and rollup-plugin-node-resolve don't support this yet, but #573 is the place to track it.

**Comment by TrySound** [comment]
@Rich-Harris `jsm` or `mjs`?

**Comment by Rich-Harris** [comment]
@TrySound `mjs` – `jsm` conflicted with something-or-other. Long threads [here](https://github.com/nodejs/node-eps/pull/3) and [here](https://github.com/nodejs/node-eps/issues/13) with a lot more detail

**Comment by smebberson** [comment]
After reading https://github.com/rollup/rollup/wiki/jsnext:main I was under the impression that because Rollup was es6 aware and I had included the `js:next` property in my `package.json` I wouldn't have to use `entry` in my `rollup.config.js`. I thought rollup would go and check for `js:next` due to absence of the `entry` parameter...

I guess I missed the point, or this is a case in which Rollup could be and isn't eating it's own dog food?

**Comment by Rich-Harris** [comment]
No, this is one of those situations where trying to be helpful (by saving people from including the `entry` part of the config) generally turns out to be extremely *un*helpful (a missing `entry` is more likely to be unintentional, and `jsnext:main` is as likely to refer to the *output* as to the input). It's always better to make these things explicit.

**Comment by smebberson** [comment]
@Rich-Harris, okay, thanks for your feedback. Much appreciated. I thought the point of `jsnext:main` was to point to the es6 input however (not the output):

> jsnext:main will point to a module that has ES2015 module syntax but otherwise only syntax features that node supports.

But I can swallow that. Thanks again.
