### ISSUE TITLE
new operator causes unwanted imports

### ISSUE THREAD

**Issue by acarabott** [rollup/rollup#623]
Hello, having a bit of a problem using the `new` operator for values I _don't_ want exported.

As you can see below, when I use the `new` operator on Image, it gets included in my `output.js`. This is also true for `const image = Image()` and `const image = new Image`;

I feel there's something I'm missing here... help appreciated.

`app.js`
````
import mod from './mod.js';
console.log(mod);
````

`mod.js`
````
export default {};

const number = 4; 

function getNumber() {
  return number;
}

const arrowNumber = () => { 
  return number;
};

const image = new Image(); 

function getImage() { 
  return image;
}

const arrowImage = () => { 
  return image;
};
````

`output.js`
````
'use strict';

var mod = {};

const image = new Image(); // bad :(

const arrowImage = () => { // bad :(
  return image;
};

console.log(mod);
//# sourceMappingURL=app.js.map
````

**Comment by eventualbuddha** [comment]
This is almost certainly due to rollup's side-effect detection. Calling `Image` either as a function or as a constructor is seen by rollup as an operation that could have required side-effects. While it's impossible to always determine whether a function has side-effects, it may be possible in some specific cases. https://github.com/rollup/rollup/issues/179 tracks that.
