### ISSUE TITLE
Module style for tree shaking.

### ISSUE THREAD

**Issue by backspaces** [rollup/rollup#645]
This is primarily a documentation issue, I think:

I've got a bunch of utilities, misc useful functions, that are in an object:

```
const util = {
  typeOf: (obj) => ({}).toString.call(obj).match(/\s(\w+)/)[1].toLowerCase(),
  isLittleEndian () {
    const d32 = new Uint32Array([0x01020304])
    return (new Uint8ClampedArray(d32.buffer))[0] === 4
  },
  error: (message) => { throw new Error(message) },
  identity: (o) => o,
  propFcn: (prop) => (o) => o[prop],
  ...//lots more
}
export default util
```

This does not appear to "tree shake". I can see how it would be a problem, with `this` internally and how the default style module is imported as a whole: `import util from './util.js'` Or I may have misused Rollup, I use the cli inside npm run scripts.

So do I need to restructure, tossing the util object and export each util individually? 
`export error: (message) => { throw new Error(message) },`

Classes have a similar problem: how can you remove individual methods?

Maybe a rollup best practices for module usage in the wiki?

**Comment by Victorystick** [comment]
Indeed. Rollup only does tree-shaking for functions and variables that use `import`/`export` syntax. You're correct in assuming that classes can't have their methods tree-shaken; see #349.

**Comment by Rich-Harris** [comment]
Will close this as there's no action that needs to be taken here (except getting smarter about removing unused methods of objects and classes, which is covered in other issues) — exporting functions individually is the way to make them tree-shakeable.

**Comment by Attrash-Islam** [comment]
I'd not recommend that behaviour of removing unused method of a class! In a real-world example at work we're working with old AngularJS 1.x code and new fresh Reactjs code (Some kind of migeration).

For AngularJS  controller I'm creating a class which contains method that the most of them is linked in the html template via ng- attributes, which means that they have "0 references" in the js files because we inject the whole class to the AngularJS eco-system.

This kind of method shaking will shake my whole app 😂
