### ISSUE TITLE
Export __esModule when bundling to CJS or UMD in named mode.

### ISSUE THREAD

**Issue by cameron-martin** [rollup/rollup#650]
When the `format` option is set to `'umd'` or `'cjs'` and the `exports` option is set to `'named'`, we should automatically export the `__esModule` property (with value `true`).

This means that a library compiled using rollup can be imported using an app which uses ES6 syntax for imports, then compiles to CommonJS using babel.

Can anyone see any downsides to doing this? If not, I'd be happy to submit a pull request.

**Comment by eventualbuddha** [comment]
We should do that. I've been meaning to for a long time.

**Comment by Rich-Harris** [comment]
This is enabled in 0.26.7 – thanks

**Comment by ericf** [comment]
I've started receiving some issues people ran into with because of this change. They were incorrectly importing the default export of React Intl which does not have a default export, then accessing a named export off of it.

- https://github.com/yahoo/react-intl/issues/499
- https://github.com/yahoo/react-intl/issues/503

Obviously the user's `import` statements are incorrect, but I just wanted to point this out since @cameron-martin asked about potential downsides.
