### ISSUE TITLE
Feature Request: CLI debug logging

### ISSUE THREAD

**Issue by fskreuz** [rollup/rollup#651]
I'm using nodemon to monitor my css and js compilation. node-sass logs info about initialization, config, changes etc. However, rollup doesn't print anything in the logs. The CLI works, just no indication that stuff happened.

A `--debug` would be nice to have. Since rollup uses stdout as a valid output, debug info might be embedded as a comment in the output, or have `--debug` require use of `--output` to free up stdout for logging info.

**Comment by Rich-Harris** [comment]
Agree, this is a good idea. Surely we could just print debugging info to `stderr` and not worry about `--output`? I think `--verbose` might be preferable to `--debug` (partly because you might just want to see the stats out of curiosity, not in a debugging context, and partly because for some odd reason Browserify uses `--debug` to mean 'sourcemaps, please', and it might cause confusion for people coming from Browserify-land).

**Comment by timdp** [comment]
I've been working on [rollup-timer](https://www.npmjs.com/package/rollup-timer), which does some of this.

Unfortunately, since there doesn't seem to be a way to hook into what Rollup does, my only option was to wrap the plugin API. Ideally, I think rollup would also export an EventEmitter that lets you track progress. The `rollup` function could continue to exist, but internally, it would, say, create a new `Rollerupper extends EventEmitter`.

**Comment by Rich-Harris** [comment]
Big 👍 to generating timing info. I think it should extend beyond plugins – it'd also be useful to know how long parsing is taking, for example, or tree-shaking (though I suppose I'm saying that with my author hat on rather than my user hat).

EventEmitter would be one way to go. Another option would be to add a `bundle.stats` (or whatever) object containing various timings (and perhaps other things). The disadvantage is that you have to wait until bundling is complete, but the advantage is that it's easier to group stuff together (e.g. the cumulative time spent on a particular transform).

**Comment by timdp** [comment]
Yeah, I'd definitely extend it. The project started out as a way to hunt down a slow plugin. In the end, my suspicion that Babel was the culprit was correct, but I also learned that Rollup itself consumed about 50% of the build time as well (unless rollup-timer is missing something).

It never hurts to add an observer pattern, I think. Even if you don't expose the events, you'll probably benefit from it in the code that generates `bundle.stats`, which would also be useful information.

**Comment by Spy-Seth** [comment]
As discuss with some on the gitter channel, I've been working on a similar tool last week: https://github.com/Spy-Seth/rollup-devtools

It's seems there is multiple initiative on this particular problem. We should try to works together on this subject.

**Comment by matheo** [comment]
Any good option ATM to have an idea of what's happening instead of the blue "unexpected token" of the death?
```
BUILD ERROR
Unexpected token
Error: Unexpected token
    at error (node_modules/rollup/dist/rollup.js:185:14)
    at Module.error (node_modules/rollup/dist/rollup.js:16526:3)
    at tryParse (node_modules/rollup/dist/rollup.js:16220:10)
    at new Module (node_modules/rollup/dist/rollup.js:16264:15)
    at load.catch.then.then.then.source (node_modules/rollup/dist/rollup.js:18189:20)
```
Thanks!

**Comment by timdp** [comment]
@matheo Is this using the CLI or the API? If it's using the API, try dumping the error object rather than the stack. There's usually metadata on the object such as the line number, which gets lost when you stringify.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
