### ISSUE TITLE
Allow for block format instead of IIFE for browserification

### ISSUE THREAD

**Issue by zbraniecki** [rollup/rollup#654]
All modern browsers support block syntax.
Instead of
```
(function () {
  'use strict';
  ...
}());
```

we could just do:

```
{
  ...
}
```

This would only require #653 to be fixed.

**Comment by eventualbuddha** [comment]
This might be suitable as an alternative to `iife`, but not a replacement because that would leak `var`s coming from e.g. babel or manually written, #653 notwithstanding. It would also not ensure that strict mode is used.

**Comment by divmgl** [comment]
-1, this makes no sense.

**Comment by zbraniecki** [comment]
@divmgl which part of my proposal you struggle to understand?

**Comment by btd** [comment]
That would be great if it will be possible to create own export format.

**Comment by Victorystick** [comment]
It's something we considered in the past, but haven't gotten around to as it hasn't been a highly requested feature.

**Comment by Rich-Harris** [comment]
Agree that it would be great to get custom export formats. Going to close this though – as @eventualbuddha points out it's a little more complicated because of top-level `var` declarations, and would be made more so if the bundle has exports or external imports. It would be a lot of work for very little payoff.

As an alternative, if you don't have exports or external imports, you could just generate an ES bundle and use `options.intro` and `options.outro` to add the enclosing curlies.

**Comment by btd** [comment]
I mostly agree with all your thoughts. It really need in very rare cases. For example I [switched should.js](https://github.com/shouldjs/should.js/blob/master/rollup.config.js) browser build some time ago to use rollup and I was need to customize UMD bundle, after some time I found intro/outro/footer/banner settings and used IIFE. It has covered all my needs. Result you can see in this [file](https://github.com/shouldjs/should.js/blob/master/should.js).

**Comment by zbraniecki** [comment]
Using intro/outro with the new `preferConst` option makes it *almost* work perfectly. The only missing piece is the ability to use `indent` in `es6` format to indent the block.
