### ISSUE TITLE
External exclusion duplicated import names

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup#659]
In the following test case, the import name `html` gets duplicated when it is imported from two externals in separate modules that are rolled up.

Example:

main.js
```javascript
import {html} from './template-a.jade';
import {component} from './component.js';

render(html);
render(component);
```

component.js
```javascript
import {html} from './template-b.jade';
export let component = html;
```

rollup.config.js
```javascript
import path from 'path';

export default {
  entry: 'main.js',
  external: [path.resolve('./template-a.jade'), path.resolve('./template-b.jade')]
}
```

This results in the Rolled-up output:

```javascript
import { html } from './template-a.jade';
import { html } from './template-b.jade';

let component = html$1;

render(html);
render(component);
```

when it should be:

```javascript
import { html } from './template-a.jade';
import { html$1 } from './template-b.jade';

let component = html$1;

render(html);
render(component);
```

**Comment by Rich-Harris** [comment]
Thanks – this is [fixed in 0.26.6](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22es6%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20%7B%20a%20%7D%20from%20'foo'%3B%5Cnimport%20'.%2Fother.js'%3B%5Cn%5Cnconsole.log(%20a%20)%3B%20%2F%2F%20foo%22%7D%2C%7B%22name%22%3A%22other.js%22%2C%22code%22%3A%22import%20%7B%20a%20%7D%20from%20'bar'%3B%5Cn%5Cnconsole.log(%20a%20)%3B%20%2F%2F%20bar%22%7D%5D%7D)

**Comment by guybedford** [comment]
Excellent, thank you!

**Comment by jonricaurte** [comment]
@Rich-Harris Thanks!
