### ISSUE TITLE
Cannot process empty file, module does not export default

### ISSUE THREAD

**Issue by unlight** [rollup/rollup#662]
Trying to build app vendors js file.
```js
    rollup({
        entry: 'dummy.js',
        plugins: [
            memory({
                contents: "require('@angular/common')"
            }),
            nodeResolve({
                // jsnext: true,
                main: true
            }),
            commonjs({
                ignoreGlobal: false, // Default: false
                sourceMap: false, // Default: true
            })
        ]
    })
```

Error: Module project\node_modules\@angular\common\src\directives\observable_list_diff.js does not export default (imported by project\node_modules\@angular\common\src\directives.js

File `observable_list_diff.js` looks as:
```
"use strict";
//# sourceMappingURL=observable_list_diff.js.map
```

**Comment by Rich-Harris** [comment]
Sorry for the long delay. It seems that the structure of `@angular/common` has changed – there's no `src/directives/observable_list_diff.js` any more – but it seems that we have a situation that in its simplest form looks like this:

```js
// main.js
require( 'foo' );

// node_modules/foo/index.js
var bar = require( './bar' );

// node_modules/foo/bar.js
/* crickets */
```

Is that correct? If so, because `bar` (analogous to `observable_list_diff`) isn't being processed by the commonjs plugin (because it's an empty file) and so isn't being given an `export default`. But since it doesn't *have* a default export, the error is correct in a way...

I think the only way to 'trick' it into working would be to add a transformer that injected a default export – something like this:

```js
var emptyModules = [
  'node_modules\@angular\common\src\directives\observable_list_diff.js'
].map( file => path.resolve( file ) );

// later...
plugins: [
  {
    transform ( code, id ) {
      if ( ~emptyModules.indexOf( id ) ) {
        return code + '\nexport default null';
      }
    },
    commonjs(...)
    ...
  }
]
```

Somewhat hacky but this is rather an unusual situation. I'll close this issue as I don't think there's a bug to be fixed as such, but let us know if you run into further problems!
