### ISSUE TITLE
Entry file in jsnext:main is not included in npm package

### ISSUE THREAD

**Issue by maxdavidson** [rollup/rollup#725]
Rollup specifies a jsnext:main field pointing to src/rollup.js, but this file is not included in the published npm package, as of v0.30.0.

The src directory was removed from the package.json files array in 1f97f4e4e228b22f962f2ad04220273673bbbcf5, but it should probably be added back.

**Comment by Rich-Harris** [comment]
Ah, whoops. `src/rollup.js` isn't actually correct because it contains ES2015 features – `jsnext:main` should point to a file that is ready to run in all target environments *except* for the fact that it uses `import` and `export` instead of `module.exports` or a UMD block/whatever. So if Rollup is to expose a `jsnext:main` we should update the build config to generate an ES module bundle (`dist/rollup.es.js` or `dist/rollup.jsm` or whatever – still waiting for TPTB to decide our collective future in that regard)

**Comment by maxdavidson** [comment]
You're right, there should be a build target for es modules. Setting `jsnext:main` to a `dist/rollup.jsm` might however break some build tools that don't recognize the `.jsm` extension. The safest approach is probably to just build a `dist/rollup.es.js` until native modules are ready.
