### ISSUE TITLE
Duplicate import declarations

### ISSUE THREAD

**Issue by ericf** [rollup/rollup#77]
When rolling up multiple files that reference an external module (React in this case) I ended up with the following invalid ES6 import statement:

```js
import { createElement, Component, createElement, isValidElement, Component, DOM, Component, DOM, Component, DOM, Component, DOM, Component, cloneElement, isValidElement, Component, Component, PropTypes, PropTypes, PropTypes, PropTypes, PropTypes, PropTypes, PropTypes, PropTypes } from 'react';
```

Note the duplicate import declarations… it appears these aren't being de-duped.

**Comment by Victorystick** [comment]
That ain't right. Thank you for raising the issue!

**Comment by yairEO** [comment]
I am using Gulp to bundle all files in a folder and generate some file which has X amount of `exports` (from each file in the folder), the reason is so I could do something like this:

    import * as controllers from 'controllers_bundle';

which will import all my controllers' functions so I won't have to manually write each import for each controller.

Anyway, when then gulp task combines the files, I get one big file which has many import declaration which repeat themselves since those controller files are mostly importing the same files themselves.

I then get a `Duplicate declaration` error on my bash console and my everything stops. I would think rollup would be smart enough to internally check if an imported file has in itself duplicate `import` declarations and remove them...

**Comment by eventualbuddha** [comment]
@yairEO that doesn't sound like the same issue as was fixed here. Could you open another issue with some sample code that reproduces the problem you're seeing?

**Comment by yairEO** [comment]
@eventualbuddha - sure, I will do that, hold on
