### ISSUE TITLE
Plugin API: Add AST support

### ISSUE THREAD

**Issue by GabrielRatener** [rollup/rollup#782]
Currently, when implementing the `load` function for a plugin, Rollup expects either a raw code string, or a code and map pair to be returned. Being able to return a JS AST would be more direct, as generating JS strings and then recompiling them is highly inefficient and unnecessary for many plugins. Also, the ESTree spec allows for location information to be stored in the AST, which would eliminate the need to resolve a chain of source mappings.

**Comment by Rich-Harris** [comment]
Rollup *can* in fact ingest an AST returned by a `load` or `transform` plugin (see for example [rollup-plugin-json](https://github.com/rollup/rollup-plugin-json/blob/master/src/index.js#L148), which generates a fake AST that prevents Rollup bothering to parse the actual JSON data), but it *also needs the code*, because unlike some tools it doesn't generate code from the AST. Instead, it uses the AST as a guide and manipulates the source code directly.

This approach is very simple and fast, but it does mean that if a plugin returns an AST, the `start` and `end` of each node have to line up exactly with the code returned by that plugin. That's rather complex and finicky, so the expectation is that plugin authors won't bother – hence the lack of documentation. It's easier, but slightly less efficient, for plugins to start from scratch and generate transformed code instead.

Do you have a specific loader/transformation pipeline in mind? Maybe we *can* use existing ASTs in your case.

**Comment by GabrielRatener** [comment]
OK, good to know, but I still think it makes sense to document this. In cases like [bizubee](https://github.com/bizubee/rollup-plugin-bizubee), the compiler can already produce a JS AST with source location info. So the simplest solution in that case would be to return the AST from `load` or `transform`, and let Rollup process it without requiring a separate source map, right?

**Comment by Rich-Harris** [comment]
What do you mean by source location info? Rollup only understands `start` and `end`, so it wouldn't know what the JS locations corresponded to in the original code.

Most likely (though there may be different requirements I'm not familiar with) you'd want to let `load` defer to the default loading process (i.e. the filesystem) and return an `{ ast, code, map }` object from `transform`.

TODO

* [ ] Document passing `ast` from `load`/`transform`

**Comment by GabrielRatener** [comment]
Having source location info just means having the `loc` [field](https://github.com/estree/estree/blob/master/spec.md#node-objects) set on AST nodes. Regardless, having an `{ast, code}` pair, where `ast` contains start and end data, seems like a fair use alternative to `{code, map}` for many plugins, so I'm glad this will be documented.

It does seem best in most cases for `load` to simply fetch a source string, and then let `transform` do the parsing. In that case, it seems `transform` could return `{ast, code}`, `{code, map}`, or if `ast` has no location info, `{ast, code, map}`.

**Comment by Rich-Harris** [comment]
Have finally [documented](https://github.com/rollup/rollup/wiki/Plugins#advanced-loaders-and-transformers) this, so I'll close the issue. The `loc` field on nodes is disregarded, only `start` and `end` are used, meaning it would be necessary to include a `map` if there was a discrepancy.
