### ISSUE TITLE
Tree shaking too aggressive?

### ISSUE THREAD

**Issue by piuccio** [rollup/rollup#786]
Hi, I'm trying to bundle this file with rollup `0.34.1`

_main.js_

``` js
import { Something } from './lib'

Something();
```

_something.js_

``` js
export function Something () {
   // do some magic in the brower
}
```

(Using an express middleware)

``` js
rollup.rollup({
    entry: 'main.js',
    plugins: [
        babel(),
        nodeResolve({
            jsnext: true,
            main: true,
            preferBuiltins: true
        }),
        commonjs()
    ],
    treeshake: true
})
.then(bundle => bundle.generate({ format: 'iife' }))
.then(result => {
    res.status(200)
    .type('application/javascript')
    .send(result.code);
})
.catch(next);
```

The output I get with **treeshake: true** is 

``` js
(function () {
    'use strict';



}());
```

an empty IIFE.

Using **treeshake: false**

``` js
(function () {
    'use strict';

    function Something() {
        // do some magic in the brower
    }

    Something();

}());
```

I've also tried using a `moduleName` but it didn't help.

Am I missing something? Is it normal that my main file gets shaken like that? Is there an option to disable tree shaking only on the main file and keep shaking all the imported libraries?

**Comment by Victorystick** [comment]
@piuccio If Rollup thinks that `Something` is free of side-effects, it'll tree-shake the call. So long as you're doing [something side-effectful](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22iife%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20%7B%20Something%20%7D%20from%20'.%2Flib'%5Cn%5CnSomething()%3B%22%7D%2C%7B%22name%22%3A%22lib.js%22%2C%22code%22%3A%22export%20function%20Something%20()%20%7B%5Cn%20%20%2F%2F%20do%20some%20magic%20in%20the%20brower%5Cn%20%20%2F%2F%20uncomment%20this%20line%3A%5Cn%20%20%2F%2F%20window.foo%20%3D%201%3B%5Cn%7D%22%7D%5D%7D) you should be fine. If you think Rollup mistakenly considers something side-effectful to be pure, please try to distill a minimal reproducing example.

**Comment by piuccio** [comment]
I see your point. The whole repo is [here](https://github.com/guardian/comment-count-widget)

`Something` is actually

```js
export function CommentCount ({ fail }) {
    return new Promise((resolve, reject) => {
        if (fail) {
            reject(new Error('Error loading comment count'));
        } else {
            const widgets = document.getElementsByTagName('comment-count');
            Array.from(widgets).forEach(fill);
            resolve();
        }
    });
}

function fill (element) {
    element.innerText = 42;
}
```

Iterating on DOM nodes to set the innerText is a side effect, I guess

**Comment by halfnibble** [comment]
I was just having the exact same issue. I made a gist to help out in cases where I really do need the function.
https://gist.github.com/halfnibble/13b279b9214ee2c4382f29cd4d6ca7dd

The code is simply:
```javascript
export var loadModule = function(module) {
    // Trick Rollup.js to keep JavaScript.
    let obj = {
        method: function() {}
    };
    obj.method(module);
};
```

Then, in your case:
```javascript
import { CommentCount } from './lib';
import { loadModule } from './loadModule';

loadModule(CommentCount);
```

For some reason, passing an otherwise eliminated object to an object's method keeps it from being **_treeshooked_** out. (Yes, I just made that term up).

**Comment by TimothyGu** [comment]
@Victorystick, where are side effects identified in the source code? I can take a look at this.

Rollup should recognize that `document` is not a global variable, and accessing any variables not controlled by Rollup can have a side effect.

**Comment by mingelz** [comment]
in my case:

```
const documentElement = document.documentElement;
documentElement.style.color = 'red';
```

the block is removed.

**Comment by code-tree** [comment]
**My situation:** I want to bundle SVG icons into my Angular2 app's JS

1. I use `gulp-plugin-string` to make the SVG icons globals in my entry file
2. I transform the global string variable to an SVG element in the Angular2 code

However, rollup tree-shakes the global as it thinks I never use it. I can't import it in the actual angular code because `ngc` can't understand the special SVG import.

How do I get rollup to not tree-shake the result of `gulp-plugin-string`, and keep it as a global variable?

**Comment by code-tree** [comment]
Ok, I figured out if I add the imported SVGs to `window` then all is good...

**Comment by timdp** [comment]
Here's a [super minimal example](http://rollupjs.org/?version=0.41.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMG1haW4lMjAlM0QlMjBmdW5jdGlvbiUyMCgpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKCd0ZXN0JyklNUNuJTdEJTVDbiU1Q25uZXclMjBQcm9taXNlKGZ1bmN0aW9uJTIwKHJlc29sdmUpJTIwJTdCJTVDbiUyMCUyMG1haW4oKSU1Q24lMjAlMjByZXNvbHZlKCklNUNuJTdEKSU1Q24lMjIlN0QlNUQlN0Q=) where Rollup thinks `Promise` is a pure function.

**Comment by kzc** [comment]
@timdp Here's the fix:
```patch
--- a/src/ast/nodes/shared/pureFunctions.js
+++ b/src/ast/nodes/shared/pureFunctions.js
@@ -26,7 +26,6 @@ simdTypes.forEach( t => {
        'ArrayBuffer', 'ArrayBuffer.isView',
        'DataView',
        'JSON.parse', 'JSON.stringify',
-       'Promise', 'Promise.all', 'Promise.race', 'Promise.reject', 'Promise.resolve',
        'Intl.Collator', 'Intl.Collator.supportedLocalesOf', 'Intl.DateTimeFormat', 'Intl.DateTimeFormat.supportedLocalesOf', 'Intl.NumberFormat', 'Intl.NumberFormat.supportedLocalesOf'
 
        // TODO properties of e.g. window...
```
for your failing test case:
```js
var main = function () {
  console.log('test')
}

new Promise(function (resolve) {
  main()
  resolve()
})
```
`Promise` and its methods should not be in the list of pure functions.

**Comment by kzc** [comment]
@Rich-Harris Any thoughts on the patch above? I think it's correct.

**Comment by Rich-Harris** [comment]
It's correct insofar as it fixes this case, but strictly speaking `Promise` and its methods *don't* have side-effects, it's just that their arguments might. For example this...

```js
var x = Promise.resolve( 42 );
```

...unambiguously *doesn't* have side-effects. What we really need to do is account for side-effects in arguments, in particular by assuming that function arguments are called. #1207 was an attempt in that direction but it had false positives.

I'm doing some experimentation at the moment into whether it's possible to get more accurate results by simulating what would actually happen if the code was run, and only bailing out when that gets too hard. Bear with me...

**Comment by kzc** [comment]
> strictly speaking Promise and its methods don't have side-effects, it's just that their arguments might.

But the argument to the Promise constructor is not a function call - it's a function expression.

A function expression (or arrow expression) is always side effect free - unless it is invoked. But in the case of the Promise constructor - the argument function expression is always guaranteed to be called, and as result can potentially have side effects.

If your rewrite involves special-casing the Promise constructor, sure, that can work.

**Comment by timdp** [comment]
@Rich-Harris Could we at least make the behavior configurable in the meantime? I'd rather make it a bit more conservative.

Also, I don't really understand why you'd want to strip out `new Promise(fn)` in particular. Can you give an example of a promise constructor that doesn't have any side effects?

**Comment by timdp** [comment]
Oh, wow, @kzc just made the exact same point. Sorry about the noise.

**Comment by Rich-Harris** [comment]
> A function expression (or arrow expression) is always side effect free - unless it is invoked

> the argument function expression is always guaranteed to be called, and as result can potentially have side effects

The key word here is 'potentially' — if the argument doesn't have side-effects, we don't want to include it unnecessarily. Since promises are *supposed* to represent eventual values (as opposed to 'work'), many (most?) arguments to `new Promise` don't have side-effects. Even given that most promises are created expressly to have effects at the end of a `then` chain, it's not too hard to think of counter-examples, e.g. an unused ponyfill for `document.ready`.

> If your rewrite involves special-casing the Promise constructor, sure, that can work.

It may do, because of `async` functions — there needs to be some way of modelling the return value. But my hope is that it will work regardless — if we simply assume that functions can do anything with their arguments, and we always simulate calling functions that are passed in, then we can flush out those side-effects with minimal false positives and no false negatives.

> Could we at least make the behavior configurable in the meantime? I'd rather make it a bit more conservative.

I'm sympathetic, am just trying to focus on this experiment while I have time to do so, because it potentially solves a lot of tree-shaking issues including this one. How big a problem is it at the moment?

**Comment by timdp** [comment]
> How big a problem is it at the moment?

Well, not huge, obviously, because there are several workarounds. It's just unexpected behavior. I somewhat pushed Rollup at our company to the point where we just rely on our own boilerplate Rollup-based build code for a lot of our products and projects. The more we use it, the bigger the impact of bugs like this one, so I'd rather have that boilerplate code producing valid code that's perhaps less optimal, than inadvertently remove too much code.

There's always a trade-off, of course, and I do understand and appreciate that you're improving the situation. However, in the short term, I'd rather not fork Rollup to have a temporary fix for my team, so that's why I suggested making the behavior configurable, which seemed like a relatively minor change.

**Comment by kzc** [comment]
I guess my main concern is just labelling the Promise constructor as "pure", when it's demonstrably not. But I'm eager to see the result of your experiment.
