### ISSUE TITLE
Give plugins bundle access?

### ISSUE THREAD

**Issue by skeggse** [rollup/rollup#803]
I've got a couple of places where I'd like to be able to call `resolveId` from a plugin. One such place is the handlebars.js plugin (see jibhaine/rollup-plugin-handlebars#2), and another is in rollup-plugin-root-import (see mixmaxhq/rollup-plugin-root-import#1).

In the former case, I'd like to be able to resolve the paths used to reference partials (handlebars imports), because handlebars uses its own mechanism for linking templates and partials. Handlebars generally works by providing a `registerPartial` method, and partial invocations use the internal map of partials. A more ideal solution would involve explicitly passing dependencies to each handlebars template, but that would break interoperability with conventional handlebars usage.

In the latter case, with root-import, I really only need access to the `entryId`, as that's what would enable cleaner default behavior, but a more general solution would involve exposing the ability to run `resolveId` from the plugin itself:

``` js
import {rollup} from 'rollup';
import rootImport from 'rollup-plugin-root-import';

// ideal usage
rollup.rollup({
  // absolute paths would be resolved relative to this
  entry: 'src/index.js'
  plugins: [rootImport]
}).then(...);

// current usage
rollup.rollup({
  entry: 'src/index.js',
  plugins: [
    rootImport({
      // currently needs this to resolve accurately
      root: `${__dirname}/src`
    })
  ]
}).then(...);
```

Without this functionality, `rootImport` would need to be explicitly passed its `root` 

Thoughts? Maybe there's a way to accomplish these goals without introducing weird coupling behavior?

**Comment by mstijak** [comment]
I would like to write a babel plugin which rewrites package imports to use src files instead of compiled (dist) files, similar to babel-plugin-lodash.
Bundle would provide access to `entryModule.exports` and `entryModule.exportsAll` mappings that could be used to generate a manifest file required for such a plugin.

**Comment by Rich-Harris** [comment]
Sorry for slow reply. Can you be more specific about what APIs you would need to accomplish these tasks?

FYI you can pass an `options` hook to intercept and manipulate options:

```js
// rollup.config.js
function logEntryFile () {
  return {
    name: 'a fairly useless plugin',
    options ( options ) {
      console.log( options.entry ); // logs 'src/index.js'
    }
  };
}

export default {
  entry: 'src/index.js',
  dest: 'bundle.js',
  format: 'iife',
  plugins: [ logEntryFile() ]
};
```

**Comment by mstijak** [comment]
@Rich-Harris 
In my case, I would like to get access to the instance of the Bundle class. 
Maybe it can be the second argument passed to the promise resolve function or a property of the result.
```
rollup(options).then((result, bundle) => {...})
```
I managed to solve my problem using `rollup-plugin-babel` and a custom Babel plugin, so it's fine if you decide not to make any changes.

**Comment by Rich-Harris** [comment]
@mstijak giving plugins access to internal implementation details is one of those things that sounds harmless at the time but almost always ends up being a mistake, because as soon as that happens you've basically made it part of the API, and a seemingly minor refactor in a patch release can have far-reaching breaking changes that are impossible to anticipate.

If we were to expose any additional functionality it would have to be done so explicitly, with documentation and tests.

**Comment by guybedford** [comment]
This has been opened up in https://github.com/rollup/rollup/pull/2208. Feedback welcome.
