### ISSUE TITLE
Export default binding

### ISSUE THREAD

**Issue by skeggse** [rollup/rollup#807]
As best I can tell, `export default` should export a binding, but in the following case, it does not:

```js
// value.js
let value = 4;
export function set(_value) {value = _value;}
export default value;

// main.js
import value, {set} from './value.js';
console.log(value);
set(2);
console.log(value);
```

As it produces

```js
'use strict';

let value = 4;
function set(_value) {value = _value;}
var value$1 = value;

console.log(value$1);
set(2);
console.log(value$1);
```

Which prints

```
4
4
```

instead of 

```
4
2
```

However, if I instead write `export {value as default};`, it functions as expected.

**Comment by Victorystick** [comment]
Thank you for this. I've been worrying about this scenario. Repro [here](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20value%2C%20%7Bset%7D%20from%20'.%2Fvalue.js'%3B%5Cnconsole.log(value)%3B%5Cnset(2)%3B%5Cnconsole.log(value)%3B%22%7D%2C%7B%22name%22%3A%22value.js%22%2C%22code%22%3A%22let%20value%20%3D%204%3B%5Cnexport%20function%20set(_value)%20%7Bvalue%20%3D%20_value%3B%7D%5Cnexport%20default%20value%3B%22%7D%5D%7D).

**Comment by Rich-Harris** [comment]
It's actually the other way around – `export default` should *never* export a live binding, because it's the only case where you're exporting an expression rather than a name (even if the expression *is* just a name).

In other words it's `export {value as default}` that's behaving incorrectly, so I'll close this in favour of https://github.com/rollup/rollup/issues/860.
