### ISSUE TITLE
Doesn't throw error message on invalid code

### ISSUE THREAD

**Issue by Kflash** [rollup/rollup#817]
I found that Rollup didn't throw errors where it should, and doesn't validate where it should.

```js
// no export statement - doesn't bundle and doesn't throw. Silenty ignored
const a = '123';
```
In the second example the first const is bundled. The other isn't. There are no errors or warnings. Maybe hint the end-dev about a error in the source code?

```js
// Equal const statement.
const a = 'abc';
const a = 'abc';
```

This is a few examples. There are more identical cases.

**Comment by TimothyGu** [comment]
For the first example, I don't see it as an error since you didn't actually try to import it, so rollup naturally just ignores that constant.

If you try to import, it [errors as expected](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20%7B%20a%20%7D%20from%20'.%2Fconsts.js'%3B%5Cn%5Cnconsole.log(a)%22%7D%2C%7B%22name%22%3A%22consts.js%22%2C%22code%22%3A%22%2F%2F%20Equal%20const%20statement.%5Cnconst%20a%20%3D%20'abc'%3B%5Cnconst%20a%20%3D%20'abc'%3B%22%7D%5D%7D): "Error: Module consts.js does not export a (imported by main.js)"

In the second case, indeed it's not valid ES2015 code. But rollup isn't a ECMAScript parser, nor a linter, nor a transpiler.

**Comment by TrySound** [comment]
Agree. Thanks

**Comment by Kflash** [comment]
@TrySound Take a look at this code lines as a few examples:

https://github.com/rollup/rollup/blob/master/src/ast/isReference.js#L17-L23

https://github.com/rollup/rollup/blob/master/src/ast/isReference.js#L9

So it's clear that Rollup does some kind of transpile/linting. Also some of the Issue tickets. 

So thinks like this has been fixed before if you look at the issue tracker.

But I guess this isn't a bug ?

**Comment by TrySound** [comment]
It's called static analysis. And your cases are not relevant for rollup. It's different responsibility.
