### ISSUE TITLE
Avoid creating a variable for exports

### ISSUE THREAD

**Issue by fregante** [rollup/rollup#826]
[rollupjs.org demo](https://rollupjs.org/repl?version=0.43.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMCgpJTIwJTdCJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

Input:

``` js
export default function () {}
```

Output:

``` js
function main () {}
export default main;
```

Desired output:

``` js
export default function () {}
```

---

Similarly, with named exports: [rollupjs.org demo](https://rollupjs.org/repl?version=0.43.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwYSUyMCgpJTIwJTdCJTdEJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwYiUyMCgpJTIwJTdCJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

Input:

``` js
export function a () {}
export function b () {}
```

Output:

``` js
function a () {}
function b () {}

export { a, b };
```

Desired output:

``` js
export function a () {}
export function b () {}
```

**Comment by bdwain** [comment]
Hi @guybedford is there any plan to implement this?

**Comment by lukastaegert** [comment]
Not at the moment, mostly because I am not sure the impact would warrant the rather high effort for this feature. Semantically the two versions are equivalent, so considering the linked issue, this would be mostly working around an (somewhat unfortunate but correct) implementation detail in Webpack and saving very few bytes.

Nevertheless, this is what might be doable and what would need to be done:
- At the moment, exports are created in the finalisers, which is a very nice, format independent way of handling it. If this were implemented, some exports would need to be excluded here based on the rendered format.
- Normal rendering would need to contain special code for ESM. This is not uncommon, there are already situations where there is special code for SystemJS.
- Between chunks, we only ever render named exports. Adding default exports here would cause a lot of friction. The situation might be different for external exports, but if the definition of the export ends up in a different chunk, there is not much that can be done. Thus this could only ever limited to entry chunks anyway.
- This would probably only be feasible for exported functions and classes. Other variable declarations can be split up rather dynamically depending on which variables are used in the current chunk and which are exported.

All in all, there is A LOT that needs to be done. Personally, I would rather invest my very time-limited efforts in some higher-impact features but would not want to discourage anyone from looking into this.

**Comment by lukastaegert** [comment]
Actually, in most situations it would not even save bytes but rather cost more bytes. I.e. if there are 5 separate exports, the five `export (default)` statements would be traded for a single `export` statement.

**Comment by lukastaegert** [comment]
My recommendation would be to rather look into something like https://github.com/speedskater/babel-plugin-rewire if mocking/spying is the issue at hand

**Comment by bdwain** [comment]
I think it could potentially save or cost a few bytes depending on if the average length of the export names was longer or shorter than `export`, since each extra export statement saves a repeat of the function name below. But the bytes seem mostly irrelevant to me since they'd be so small.

I also don't think non-entry chunks matter anyway, since you typically don't import from them directly as a library consumer (and this doesn't matter for apps)

I think the issue is not just limited to webpack, because webpack is just following the es modules spec. So it's really anything that follows the spec. 

I've also looked at rewire in the past but had trouble getting it working and it seems like just a much more complicated solution overall compared to spying on the module directly.

To me, there seems to be clear upside (spyability) with no clear downside (possibly a few extra bytes, though it could just as easily save bytes), so I think it would be good to do, though I understand if it's low priority. I don't know too much about rollup internals, but if I potentially did a PR, would you be open to it?

**Comment by lukastaegert** [comment]
Very much depends on how invasive the PR is. If you find a solution that does not break anything and only requires a few localized changes and no additional information passed around in central places I guess I would be open to it.

But my fear is any of the following:
- rendering of entry chunks diverges from rendering of other chunks it a way that the render methods of AST nodes now need to know in which chunk type they are located, weakening architectural encapsulation
- aggregating chunk exports for finalization becomes noticeably more complex

These are mainly future maintenance concerns, but I will be open to be convinced that this is not as important. And of course I do not want to discourage anyone from contributing to Rollup, on the contrary!

But what I see more is that your own goal—spyability—solely relies now on an unintended interaction between two tools, Rollup and Webpack, which may break again at any point. For instance Webpack may decide to use getters for their exports or mark them as non-configurable. Both options are totally spec compliant as mutating an import is actually forbidden in ESM. If I were you, I would rather try to figure out a way to solve my problem that is future proof.

Here an example how spying a top-level function could work using rollup-plugin-rewire and sinon:

```js
// index.js
export function testMe() {
  console.log('I do stuff');
}

export function callTestMe() {
  testMe();
}

// test.js
import {testMe, callTestMe, __RewireAPI__} from './index.js';

const testMeSpy = sinon.spy(testMe);
__RewireAPI__.__Rewire__('testMe', testMeSpy);
callTest();
assert(testSpy.calledOnce);
```

I did not check but my assumption would be that this should work even if you use CommonJS to write your tests.

**Comment by bdwain** [comment]
Thanks for taking the time to talk through it with me @lukastaegert!

I have seen rewire, but it's an extra babel transform that will slow down tests a lot and also be a plugin that's permanently required just to mock a module, which seems to me like a not ideal solution. It's also pretty awkward to work with relative to just spying on a module, so it's something I would like to avoid if possible.

I think there's a lot of desire to be able to mock modules, and I feel like unfortunately people have used the excuse that it's not compliant with the new module spec to just sweep the problem under the rug. But that ignores the fact that mocking modules was a common practice with commonjs modules, and there's nothing currently out there that does a good job of supporting that functionality or replacing it ([This comment/thread](https://github.com/standard-things/esm/issues/266#issuecomment-391046082) in particular did a good job of explaining how I feel on the topic). Most suggestions I see are to use dependency injection (which can get impractical in large apps) or exporting objects rather than individual functions. But having global mutable modules in my app kind of defeats the purpose of the es module loader. Jest module mocking seems to rely on using commonjs modules, so if I was to export a library with es modules (which is what I use rollup for), the only way to spy on it would be to transform my node modules with babel also, and not just my own code. This would slow down my tests a ton, so is a non-starter.

I may be misunderstanding how rollup works, but I don't think bullet point 1 is true. Why do non-entry chunks need be treated any differently? Can't all generated function exports just use the `export (default) function foo(){...}` syntax rather than the current syntax, regardless of whether it is an entry chunk or not? Since default exports are never used in non-entry chunks, it seems like there would be no need to make a distinction between entry and non-entry for this.

I also have to disagree with 

> But what I see more is that your own goal—spyability—solely relies now on an unintended interaction between two tools, Rollup and Webpack, which may break again at any point.

To me, the interaction between them is definitely intended. It seems like if rollup-built libraries exports functions in the way I'm asking, a spec-compliant bundler (not just webpack) would be able to allow spying on those functions, but not if it exports them in the way it currently does. Unfortunately, webpack 4 [changed its module system](https://github.com/webpack/webpack/issues/6979) to make this more difficult. I think it was a mistake (and lead to things like [this](https://github.com/standard-things/esm/issues/266)), but I view it as a separate issue from this one, because webpack could be replaced without replacing rollup. I was able to solve both issues independently by writing (very fragile) plugins, so rollup addressing this issue would make my rollup plugin unnecessary at least (and solve the issue for many other people as well).

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Comment by devsnek** [comment]
For CJS and UMD i'm seeing this pattern:

input:
```js
export const a = abc;
export const b = xyz;
```

output:
```js
const a = abc;
const b = xyz;
exports.a = a;
exports.b = b;
```

We're currently measuring our bundle in bytes, so being able to optimize this would be great.
