### ISSUE TITLE
Proposal: rollup.createProject

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#828]
``` js
// Pass path to config with defaults
const rollupProject = rollup.createProject('path/to/rollup.config.js');
gulp.task('script', () => {
  // Override defaults from config with some props in flatten way without bundle
  return rollupProject({
    entry: 'src/main.js',
    // Encapsulates bundle caching
    cache: false, // default: true
    dest: 'dist/bundle.js'
  });
});
```

This can be simpler for user and more consistently with rollup cli. Also now there is a sense in `rollup.rollup()` :)

/cc @rollup/collaborators

**Comment by TrySound** [comment]
Ref https://github.com/rollup/rollup/issues/761

**Comment by tnga** [comment]
assuming configurations are generally set in `rollup.config.js`, i thing setting rollup options in the task definitions is effectively useful for overwriting case. so if the rollup project's configurations are already set, it will be good to just do:
```js
gulp.task('script', () => {
  // Override defaults from config with some props in flatten way without bundle
  return rollupProject();
});
```

However i thing it will be better to have `rollup.assignProject()` or simply `rollup.project()` instead of `rollup.createProject()`, considering that, the presence of the `rollup.config.js` file is sufficient to consider a project as a *"rollup project"*

**Comment by Rich-Harris** [comment]
I'm going to close this issue, because I don't think it adds enough value to warrant the increased surface area. Since it's basically about making usage via Gulp slightly easier, and it doesn't add anything that can't be done as a separate package, I think the burden of creating conveniences like this should fall to the Gulp community.
