### ISSUE TITLE
circular live bindings not working as expected?

### ISSUE THREAD

**Issue by trusktr** [rollup/rollup#845]
For example, [these modules](http://goo.gl/PXXBKI) work in environments implemented with Babel, but the rollup.js code fails.  Is there some way to write these circular modules so that they work in any ES2015 module environment?

For reference, the `let A = A` and `let B = B` is required in Babel environments, as [pointed out](https://github.com/meteor/meteor/issues/7621#issuecomment-238992688) by @benjamn.

I'm looking for any ideas on whether there's a solution that should theoretically work in any ES6 environment, not just with Babel.

**Comment by trusktr** [comment]
I have the following, which I think should theoretically work in all ES2015 module systems: http://goo.gl/6zls2f

This is working in Babel-based projects (Meteor, Webpack, haven't tried Browserify). But, it fails in Rollup although I think it should theoretically work if bindings are "live". If you try the bundled code, it will fail because "C is not defined" in the first pair of conditional checks, although if the bindings were "live", then the check should not fail, but the resulting boolean should be false.

**Comment by trusktr** [comment]
To understand what I mean, just run `if (C) console.log(C)` in your console, and you'll get an error because "C is not defined". Had the bindings been "live", then C *would* be defined by the time it is first used.

**Comment by Rich-Harris** [comment]
Without having a working implementation to test against, it's hard to know for sure if Rollup behaves the same as native modules eventually will, but I *think* that Rollup is behaving according to spec here: https://github.com/rollup/rollup/pull/443.

Basically, as far as I can tell (and I'd welcome clarification from anyone who knows better), the spec says that if module `main` imports module `A`, module `A` must evaluate before module `main` (uncontroversial). If `A` imports `C`, `C` must evaluate before `A` – also uncontroversial. If `C` imports `A`, which is already at this stage in the process of evaluating, then `A` is `undefined` as far as `C` is concerned *while it's evaluating*.

If you open the console on [your initial example](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22%2F%2F%20---%20Entrypoint%5Cn%5Cnimport%20A%20from%20'.%2FA'%5Cnconsole.log('Entrypoint'%2C%20new%20A)%20%2F%2F%20runs%20the%20console.logs%20in%20the%20C%20constructor.%5Cn%22%7D%2C%7B%22name%22%3A%22A.js%22%2C%22code%22%3A%22%2F%2F%20---%20Module%20A%5Cn%5Cnimport%20C%20from%20'.%2FC'%5Cn%5Cnlet%20A%20%3D%20A%20%2F%2F%20%40benjamn's%20workaround%20applied%5Cn%5Cnexport%5Cnfunction%20setUpA(C)%20%7B%5Cn%5Cn%20%20%20%20A%20%3D%20class%20A%20extends%20C%20%7B%5Cn%20%20%20%20%20%20%20%20%2F%2F%20...%5Cn%20%20%20%20%7D%5Cn%5Cn%7D%5Cn%5Cnexport%20%7BA%20as%20default%7D%5Cn%22%7D%2C%7B%22name%22%3A%22B.js%22%2C%22code%22%3A%22%2F%2F%20---%20Module%20B%5Cn%5Cnimport%20C%20from%20'.%2FC'%5Cn%5Cnlet%20B%20%3D%20B%20%2F%2F%20%40benjamn's%20workaround%20applied%5Cn%5Cnexport%5Cnfunction%20setUpB(C)%20%7B%5Cn%5Cn%20%20%20%20B%20%3D%20class%20B%20extends%20C%20%7B%5Cn%20%20%20%20%20%20%20%20%2F%2F%20...%5Cn%20%20%20%20%7D%5Cn%5Cn%7D%5Cn%5Cnexport%20%7BB%20as%20default%7D%22%7D%2C%7B%22name%22%3A%22C.js%22%2C%22code%22%3A%22%2F%2F%20---%20Module%20C%5Cn%5Cnimport%20A%2C%20%7BsetUpA%7D%20from%20'.%2FA'%5Cnimport%20B%2C%20%7BsetUpB%7D%20from%20'.%2FB'%5Cn%5Cnlet%20C%20%3D%20class%20C%20%7B%5Cn%20%20%20%20constructor()%20%7B%5Cn%20%20%20%20%20%20%20%20%2F%2F%20this%20may%20run%20later%2C%20after%20all%20three%20modules%20are%20evaluated%2C%20or%5Cn%20%20%20%20%20%20%20%20%2F%2F%20possibly%20never.%5Cn%20%20%20%20%20%20%20%20console.log(A)%5Cn%20%20%20%20%20%20%20%20console.log(B)%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%5CnsetUpA(C)%5CnsetUpB(C)%5Cn%5Cnexport%20%7BC%20as%20default%7D%22%7D%5D%7D), you'll see a message like this:

<img width="518" alt="screen shot 2016-08-16 at 7 40 52 pm" src="https://cloud.githubusercontent.com/assets/1162160/17719800/42c0d6b2-63eb-11e6-8fc9-67463f2d66e1.png">

That's Rollup's way of telling you that we've encountered exactly that situation. A solution, as kludgy as it seems, is to import `C` from `main` before anything else gets imported – that way `C` is evaluated last (counter-intuitive I know!) meaning that `setUpA` and `setUpB` are able to run. [Here's an example](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22%2F%2F%20---%20Entrypoint%5Cn%5Cn%2F%2F%20open%20the%20console%20and%20try%20commenting%20this%20out%3A%5Cnimport%20'.%2FC'%5Cn%5Cnimport%20A%20from%20'.%2FA'%5Cnconsole.log('Entrypoint'%2C%20new%20A)%20%2F%2F%20runs%20the%20console.logs%20in%20the%20C%20constructor.%5Cn%22%7D%2C%7B%22name%22%3A%22A.js%22%2C%22code%22%3A%22%2F%2F%20---%20Module%20A%5Cn%5Cnimport%20C%20from%20'.%2FC'%5Cn%5Cnlet%20A%3B%5Cn%5Cnexport%5Cnfunction%20setUpA(C)%20%7B%5Cn%5Cn%20%20%20%20A%20%3D%20class%20A%20extends%20C%20%7B%5Cn%20%20%20%20%20%20%20%20%2F%2F%20...%5Cn%20%20%20%20%7D%5Cn%5Cn%7D%5Cn%5Cnexport%20%7BA%20as%20default%7D%5Cn%22%7D%2C%7B%22name%22%3A%22B.js%22%2C%22code%22%3A%22%2F%2F%20---%20Module%20B%5Cn%5Cnimport%20C%20from%20'.%2FC'%5Cn%5Cnlet%20B%3B%5Cn%5Cnexport%5Cnfunction%20setUpB(C)%20%7B%5Cn%5Cn%20%20%20%20B%20%3D%20class%20B%20extends%20C%20%7B%5Cn%20%20%20%20%20%20%20%20%2F%2F%20...%5Cn%20%20%20%20%7D%5Cn%5Cn%7D%5Cn%5Cnexport%20%7BB%20as%20default%7D%22%7D%2C%7B%22name%22%3A%22C.js%22%2C%22code%22%3A%22%2F%2F%20---%20Module%20C%5Cn%5Cnimport%20A%2C%20%7BsetUpA%7D%20from%20'.%2FA'%5Cnimport%20B%2C%20%7BsetUpB%7D%20from%20'.%2FB'%5Cn%5Cnlet%20C%20%3D%20class%20C%20%7B%5Cn%20%20%20%20constructor()%20%7B%5Cn%20%20%20%20%20%20%20%20%2F%2F%20this%20may%20run%20later%2C%20after%20all%20three%20modules%20are%20evaluated%2C%20or%5Cn%20%20%20%20%20%20%20%20%2F%2F%20possibly%20never.%5Cn%20%20%20%20%20%20%20%20console.log(A)%5Cn%20%20%20%20%20%20%20%20console.log(B)%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%5CnsetUpA(C)%5CnsetUpB(C)%5Cn%5Cnexport%20%7BC%20as%20default%7D%22%7D%5D%7D) – the bundle runs fine until you comment out the initial empty import.

Babel has to transpile ES modules to CommonJS, which has different semantics (e.g. `require` is imperative whereas `import` is declarative), so it's not totally unexpected that the behaviour will differ. For example it looks like `exports.default` is being [reassigned after the module initialises](http://babeljs.io/repl/#?evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2&experimental=true&loose=false&spec=false&code=%2F%2F%20---%20Module%20A%0A%0Aimport%20C%20from%20'.%2FC'%0A%0Alet%20A%20%3D%20A%20%2F%2F%20%40benjamn's%20workaround%20applied%0A%0Aexport%0Afunction%20setUpA(C)%20%7B%0A%0A%20%20%20%20A%20%3D%20class%20A%20extends%20C%20%7B%0A%20%20%20%20%20%20%20%20%2F%2F%20...%0A%20%20%20%20%7D%0A%0A%7D%0A%0Aexport%20%7BA%20as%20default%7D%0A), which I *think* is against spec (I could definitely be wrong though).

Hope this answer generated more light than heat!

**Comment by Rich-Harris** [comment]
> For example it looks like `exports.default` is being reassigned after the module initialises, which I *think* is against spec

Now that I think about it, Rollup is also behaving incorrectly here. `A` and `B` should be fixed, because they're default exports (default exports aren't supposed to be live). Rollup is apparently getting confused because you're doing `export {default as A}` rather than `export default A` – that's a bug. You can see what *should* happen [here](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22%2F%2F%20---%20Entrypoint%5Cn%5Cn%2F%2F%20open%20the%20console%20and%20try%20commenting%20this%20out%3A%5Cnimport%20'.%2FC'%5Cn%5Cnimport%20A%20from%20'.%2FA'%5Cnconsole.log('Entrypoint'%2C%20new%20A)%20%2F%2F%20runs%20the%20console.logs%20in%20the%20C%20constructor.%5Cn%22%7D%2C%7B%22name%22%3A%22A.js%22%2C%22code%22%3A%22%2F%2F%20---%20Module%20A%5Cn%5Cnimport%20C%20from%20'.%2FC'%5Cn%5Cnlet%20A%3B%5Cn%5Cnexport%5Cnfunction%20setUpA(C)%20%7B%5Cn%5Cn%20%20%20%20A%20%3D%20class%20A%20extends%20C%20%7B%5Cn%20%20%20%20%20%20%20%20%2F%2F%20...%5Cn%20%20%20%20%7D%5Cn%5Cn%7D%5Cn%5Cnexport%20default%20A%3B%5Cn%22%7D%2C%7B%22name%22%3A%22B.js%22%2C%22code%22%3A%22%2F%2F%20---%20Module%20B%5Cn%5Cnimport%20C%20from%20'.%2FC'%5Cn%5Cnlet%20B%3B%5Cn%5Cnexport%5Cnfunction%20setUpB(C)%20%7B%5Cn%5Cn%20%20%20%20B%20%3D%20class%20B%20extends%20C%20%7B%5Cn%20%20%20%20%20%20%20%20%2F%2F%20...%5Cn%20%20%20%20%7D%5Cn%5Cn%7D%5Cn%5Cnexport%20default%20B%3B%22%7D%2C%7B%22name%22%3A%22C.js%22%2C%22code%22%3A%22%2F%2F%20---%20Module%20C%5Cn%5Cnimport%20A%2C%20%7BsetUpA%7D%20from%20'.%2FA'%5Cnimport%20B%2C%20%7BsetUpB%7D%20from%20'.%2FB'%5Cn%5Cnlet%20C%20%3D%20class%20C%20%7B%5Cn%20%20%20%20constructor()%20%7B%5Cn%20%20%20%20%20%20%20%20%2F%2F%20this%20may%20run%20later%2C%20after%20all%20three%20modules%20are%20evaluated%2C%20or%5Cn%20%20%20%20%20%20%20%20%2F%2F%20possibly%20never.%5Cn%20%20%20%20%20%20%20%20console.log(A)%5Cn%20%20%20%20%20%20%20%20console.log(B)%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%5CnsetUpA(C)%5CnsetUpB(C)%5Cn%5Cnexport%20%7BC%20as%20default%7D%22%7D%5D%7D).

**Comment by Rich-Harris** [comment]
I'll close this as it doesn't look like anything is behaving incorrectly or that there's anything to be done here – reopen if that's not the case

**Comment by Victorystick** [comment]
It seems to me that you've just _introduced_ a bug rather than fixed one. Are you saying `default` should never be a live binding? As far as I understand, only `export default ...` gets special treatment. The spec treats all `export { x as y }` [the same](http://www.ecma-international.org/ecma-262/6.0/#sec-exports-static-semantics-exportentries). There is no special rule saying there shouldn't be a binding if the exported name is "default".

In this first example, there is no live binding. `foo` is neither a HoistableDeclaration nor a ClassDeclaration, meaning that it must be an AssignmentExpression which is evaluated and exported as the default.
```js
var foo = 0;
export default foo;
foo = 1;
```

Live binding. The variable `foo` is part of an ExportClause where the ExportName of the variable is "default"; nothing else has changed. It behaves just the same as if it had been `export { foo }`.
```js
var foo = 0;
export { foo as default };
foo = 1;
```

**Comment by trusktr** [comment]
I've made a simpler example that shows the problem. You'll get an undefined error if you try pasting the result in your console: https://goo.gl/O7FnxM

That should theoretically work in an ES2015 Module environment because the `var` statements are hoisted, and the `initA` function (which is also hoisted) is called before the `B` or `C` classes are defined so by the time when the `B` or `C` class definitions are evaluated the value of `A` should not be undefined.

However, in the compiled result, a new variable `A$1` is created and the `A` symbol is replaced in the B and C modules, so if one of the B or C modules is evaluated first, there will be an undefined error because the `initA` function is not setting the `A$1` variable, it is setting the `A` variable.

**Comment by trusktr** [comment]
@loganfsmyth (versed on ES2015 modules), can you verify this ?

**Comment by loganfsmyth** [comment]
Your analysis seems right, the B class should probably stay extending `A`, not `A$1`. This example seems potentially separate from the original issue reported here  though.

**Comment by trusktr** [comment]
True, it is separate. I originally posted

> I'm looking for any ideas on whether there's a solution that should theoretically work in any ES6 environment, not just with Babel.

So the new example shows the solution that I arrived at, but coincidentally still doesn't work in Rollup. I'm not sure about the original example though.

@loganfsmyth I believe you may have said (in an external conversation from here) that the things I'm doing in my original examples are only workarounds to how Babel compiles. 

Is the following example something that would work in a theoretical ES6 environment? Or would there be a temporal deadzone error? I think it should be a temporal deadzone error: http://goo.gl/6zls2f

**Comment by loganfsmyth** [comment]
Yes that would trigger a TDZ error.

**Comment by trusktr** [comment]
@loganfsmyth IIRC, you had helped me solve circular dependencies by showing me an "init function" approach. If true, do you remember where that discussion was?

**Comment by trusktr** [comment]
@loganfsmyth Ah, I think it was just this: https://esdiscuss.org/topic/how-to-solve-this-basic-es6-module-circular-dependency-problem#content-22
