### ISSUE TITLE
inconsistent case sensivity

### ISSUE THREAD

**Issue by aardgoose** [rollup/rollup#862]
Importing a module in two places using paths that are different only in case, but handled as case insensitive, results in two instances of the imported module in the resultant output. (Windows 10).
, rollup v  0.34.8

ie. file lookup is case insensitive 
ie. module instancing is case sensitive based on path name differences.

Eg.

**Module 1:**

import { Materials } from './materials/Materials.js';
...

**module 2:**

import { Materials } from './Materials/Materials.js';
...

**Resultant output file has** 

Materials and Materials$1 objects with expected breakage.

**Comment by snuggs** [comment]
I feel the lowest common denominator is POSIX compliance which states the following for all volume formats:

#### Linux and Derivatives _( ! OSX)_
  √ Files *MUST* be case sensitive. _(http://superuser.com/questions/431342/linux-both-case-sensitive-and-case-insensitive-and-always-inconvenient)_

#### Windows _(NTFS)_
  √ Files *MUST* be case sensitive _(https://support.microsoft.com/en-us/kb/100625)_

#### Windows _(VFAT | FAT32)_
  √ Files *MUST NOT* be case sensitive
![capture d ecran 2016-08-19 a 22 24 22](https://cloud.githubusercontent.com/assets/38223/17828300/8f027b3a-665b-11e6-8279-56dd90b92887.png)

#### OSX
  √ Files are *SHOULD* be case sensitive (but aren't).

![capture d ecran 2016-08-19 a 22 18 20](https://cloud.githubusercontent.com/assets/38223/17828256/b1aea5e2-665a-11e6-876c-da276dfb609e.png)

Therefore IMHO I feel like we should `throw` instead of returning a false positive regardless of the solution. "Failing" silently seems too flagrant. Your thoughts @aardgoose

**Comment by pmart123** [comment]
@snuggs I like the idea. From prior experience of being burned in similar situations, throwing the error is a nice gesture in comparison to the amount of potential time spent tracking something like this down.

**Comment by Rich-Harris** [comment]
I actually opened a PR for this yonks ago – https://github.com/rollup/rollup/pull/630 – but forgot about it. Just merged it, will cut a release soon. Thanks

**Comment by snuggs** [comment]
Well that's what i'm here for @Rich-Harris a little healthy nudge. Until can be more productive. Got a great thing going on here. 👍  #FACTS

**Comment by aardgoose** [comment]
Many thanks,  may save me some head scratching time in future.
