### ISSUE TITLE
Rollup not pruning unused `import *` variables when pruning source module

### ISSUE THREAD

**Issue by jvilk** [rollup/rollup#889]
I'm using Rollup v0.34.11. This one is rather hard to explain in words, so I will have the code do the talking! If you figure out a better title for the bug, feel free to rename.

`utils.js`:

```javascript
export const isWebWorker = typeof(importScripts) === 'function';
export const unused = true;
```

`main.js` (the entrypoint):

```javascript
import * as utils from './utils';

function unused() {
  // This is unreferenced code that Rollup correctly removes.
  // But it fails to remove `utils` with it!
  return utils;
}

console.log("Is Web Worker? " + utils.isWebWorker);
```

Resulting bundle (comments added):

```javascript
const isWebWorker = typeof(importScripts) === 'function';

// utils is no longer referenced anywhere at all! This is dead code!
var utils = Object.freeze({
        isWebWorker: isWebWorker,
        unused: unused$1  // <-- This variable no longer exists! Runtime error!
});

console.log("Is Web Worker? " + isWebWorker); // <-- utils used to be referenced here, but note how rollup pruned the module reference.
```

The hackfix workaround is to force that module to stay alive so rollup doesn't prune `unused`.

(This is a real problem; it occurred in a library I am attempting to convert to use Rollup.)

**Comment by Rich-Harris** [comment]
This is [fixed in 0.35](http://rollupjs.org/?shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwdXRpbHMlMjBmcm9tJTIwJy4lMkZ1dGlscyclM0IlNUNuJTVDbmZ1bmN0aW9uJTIwdW51c2VkKCklMjAlN0IlNUNuJTIwJTIwJTJGJTJGJTIwVGhpcyUyMGlzJTIwdW5yZWZlcmVuY2VkJTIwY29kZSUyMHRoYXQlMjBSb2xsdXAlMjBjb3JyZWN0bHklMjByZW1vdmVzLiU1Q24lMjAlMjAlMkYlMkYlMjBCdXQlMjBpdCUyMGZhaWxzJTIwdG8lMjByZW1vdmUlMjAlNjB1dGlscyU2MCUyMHdpdGglMjBpdCElNUNuJTIwJTIwcmV0dXJuJTIwdXRpbHMlM0IlNUNuJTdEJTVDbiU1Q25jb25zb2xlLmxvZyglNUMlMjJJcyUyMFdlYiUyMFdvcmtlciUzRiUyMCU1QyUyMiUyMCUyQiUyMHV0aWxzLmlzV2ViV29ya2VyKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ1dGlscy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGlzV2ViV29ya2VyJTIwJTNEJTIwdHlwZW9mKGltcG9ydFNjcmlwdHMpJTIwJTNEJTNEJTNEJTIwJ2Z1bmN0aW9uJyUzQiU1Q25leHBvcnQlMjBjb25zdCUyMHVudXNlZCUyMCUzRCUyMHRydWUlM0IlMjIlN0QlNUQlN0Q=) – thanks!
