### ISSUE TITLE
useStrict does not seem to work as expected

### ISSUE THREAD

**Issue by danbucholtz** [rollup/rollup#936]
I am applying the `useStrict` option in my `bundle.write` call as seen below:

```
return bundle.write({
  format: 'cjs',
  useStrict: false,
  dest: './dist/index.js'
});
```

Somewhere downstream in a transitive dependency, there is an `invalid number` that starts with a 0.  It is used for setting file permissions similar to `chmod`.

I cannot roll-up the package as a result.  I am unclear on what I can do here.

Thanks,
Dan

**Comment by eventualbuddha** [comment]
Can you share the output of the bundle?

**Comment by danbucholtz** [comment]
Yes. I'll give you a very minimized example test case shortly. Sound good?

**Comment by danbucholtz** [comment]
Here is the [sample repo](https://github.com/driftyco/ionic-app-generators/tree/rollup-strict-mode).

```
git clone git@github.com:driftyco/ionic-app-generators.git
git checkout rollup-strict-mode
npm install
npm run build
```

You'll see roll-up fail with the following error about strict mode:

`ERROR:  Error transforming /Users/dan/Dev/ionic-generators/node_modules/temp/lib/temp.js with 'commonjs' plugin: Invalid number (226:20) in /Users/dan/Dev/ionic-generators/node_modules/temp/lib/temp.js`

No bundle is actually written.

Unfortunately, this dependency is way downstream for me. Believe me, I'd love to get rid of it 😄 .

The `build` script is incredibly simple for this project.  See the roll-up config and usage of the `useStrict: false` variable here.
https://github.com/driftyco/ionic-app-generators/blob/rollup-strict-mode/build/build.js#L61

Thanks,
Dan

**Comment by Rich-Harris** [comment]
The `useStrict` option determines whether or not the `'use strict'` pragma should appear at the top of the generated bundle, *not* whether modules are assumed to be in strict mode. This is out of Rollup's control to a large extent – Acorn will only parse in strict mode if `sourceType` is `module`, and rightly so, since ES modules are *always* strict.

Since npm has a few CommonJS modules that rely on non-strict behaviour (generally for no good reason), including heavily-depended upon and long-since-abandoned packages like `temp`, this can be a problem. We *can* solve it though, by rewriting the module on the fly. [This commit](https://github.com/Rich-Harris/ionic-app-generators/commit/a63ecb5f360f869bb807842a240e7df82802997e) gets the build to work by doing that (and fixing a couple of other things that crop up afterwards).

Will close this issue but let us know if you run into further issues with it. Thanks for the sample repo
