### ISSUE TITLE
ES feature: trailing commas for function parameters

### ISSUE THREAD

**Issue by call-a3** [rollup/rollup#938]
A new proposal for ES is to support trailing commas on function parameters. This is already part of my default eslint config (I come from using webpack+babel as a transpiler for creating bundles that will be run in the browser). I'd like to keep the same syntax/style rules while switching to rollup for server functionality.

**Comment by GGAlanSmithee** [comment]
I might be misstaken, but isn't this just a matter of adding the [correct babel plugin](https://babeljs.io/docs/plugins/syntax-trailing-function-commas/)?

**Comment by call-a3** [comment]
Sure, but if I'm not mistaken, rollup doesn't use Babel by default, so I'd also have to set that up as well. I was hinting at maybe trying to get support for this syntax in the parser that rollup uses out of the box...

**Comment by Rich-Harris** [comment]
This is a JavaScript bundler – I'm afraid if you want to use made-up syntax you'll have to use [the appropriate transformer](https://github.com/rollup/rollup-plugin-babel) 😀

**Comment by tomkel** [comment]
Looks like rollup still doesn't support these... they have been in node since v8.

**Comment by MKRhere** [comment]
Since ES2017, trailing commas in function parameters is a feature of JavaScript, but Rollup still sees it as a syntax error. I'm afraid it's no longer `made-up syntax`, so is this issue re-openable?

**Comment by lukastaegert** [comment]
It has been well-supported since 2017: https://rollupjs.org/repl/?version=2.4.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIweChhJTJDKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZyhhJTJDKSU1Q24lN0QlNUNuJTVDbngoMSUyQyklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==
