### ISSUE TITLE
`this` set to `undefined`

### ISSUE THREAD

**Issue by snuggs** [rollup/rollup#942]
References https://github.com/rollup/rollup/issues/770

Was understanding about the setting to `undefined`. Does this happen when passing in a global scope or does it preserve `this`. The spec specifies a global object (no matter what) in the following link. Should we be congruent with it?  I do realize that the side effect of the environment is irrelevant to rollup/buble.  Should there be a default we should implement around the spec?

https://es5.github.io/#x15.1

Was getting the following message when rolling up. I don't think i mind the override to `undefined`. But feel could cause some nasty bugs. Am I overlooking something? 

Lastly the other day when doing the PR to upgrade to ASYNC-AWAIT I noticed there was some `undefined` being set in Acorn and it was complaining. Wonder if any relevance. Thanks in advance. /cc @Rich-Harris 

![capture d ecran 2016-09-15 a 08 27 42](https://cloud.githubusercontent.com/assets/38223/18549739/49b2169e-7b1e-11e6-827b-05196cbe16d9.png)

 
![capture d ecran 2016-09-15 a 03 44 52](https://cloud.githubusercontent.com/assets/38223/18549607/84bcb11e-7b1d-11e6-9793-738b3ce85fad.png)

![capture d ecran 2016-09-15 a 08 18 24](https://cloud.githubusercontent.com/assets/38223/18549535/193a4db6-7b1d-11e6-86de-2974f3c17908.png)

**Comment by Rich-Harris** [comment]
In the context of an ES module, `this` is `undefined` at the top level – so Rollup replaces references accordingly, to prevent broken code from working (otherwise it'll be harder for people to *stop* using Rollup when modules are natively supported). Since there are a few edge cases where it's necessary to control the meaning of `this, it can be controlled with `options.context` –  https://github.com/rollup/rollup/wiki/JavaScript-API#context

**Comment by snuggs** [comment]
AH I see splendid! So i can just use my `window` object from JSDom and call it a day. Just like this Issue. ;-) Thanks @Rich-Harris you're a gentleman and a scholar. :-D
