### ISSUE TITLE
Using `cache` breaks build after first time

### ISSUE THREAD

**Issue by thesbros** [rollup/rollup#952]
When using the `cache` parameter, the build will work fine the first time. For the subsequent builds, I get random errors about undefined functions:

```
node_modules/reflux-core/lib/createStore.js:33 Uncaught TypeError: Cannot read property 'init' of undefined
```

If I remove reflux-core, then it happens for something else, etc. etc. If I remove the `cache` parameter, it works but makes my builds take almost 3x longer.

Following is the config:

```
    let plugins = [
        nodeResolve({jsnext: true, browser: true}),
        babel({exclude: "node_modules/**"}),
        commonjs({
            sourceMap: true,
            exclude: ["node_modules/lodash-es/**", "node_modules/symbol-observable/**"]
        }),
        replace({
            "process.env.NODE_ENV": `"production"`
        })
    ];
    return rollup({
        entry: paths.scriptEntry,
        plugins: plugins,
        cache: cache
    }).then(b => {
        b.write({
            format: "iife",
            sourceMap: true,
            dest: paths.scriptOutput
        });

        cache = b;
    });
```

**Comment by Rich-Harris** [comment]
Afraid I'm having a hard time reproducing this – are you able to create a repo illustrating the issue? Thanks

**Comment by thesbros** [comment]
Sure: https://github.com/thesbros/repro

Steps to reproduce:

```
npm install
npm run build
Open `build/index.html` in browser.
Open console, see no errors.
Edit something. (e.g. remove a semicolon in app/scripts/index.js)
See TypeError in console.
```

**Comment by Rich-Harris** [comment]
Thanks for the repro. Looks like the issue is related to rollup-plugin-commonjs not being entirely stateless. Haven't quite nailed it down, but getting close.

There are two workarounds in the meantime:

1. Move [this block](https://github.com/thesbros/repro/blob/master/gulpfile.babel.js#L22-L40) out of the task, so that you're not reinstantiating the plugins from scratch on each build
2. Don't use Gulp. Just use `rollup -c -w` with `npm run` scripts. There's less overhead, fewer moving parts, and it works without any surprises. Demo here (`npm run dev` to start watching) https://github.com/Rich-Harris/repro

**Comment by thesbros** [comment]
Great, thanks. I'll do that workaround for now. My actual project has a lot more build tasks and that's why I use gulp. I have been thinking of switching to simple build scripts, so I will do that if I run into any other roadblocks.
