### ISSUE TITLE
IIFE with side effect involving prototype alias incorrectly dropped

### ISSUE THREAD

**Issue by kzc** [rollup/rollup#953]
```
$ node_modules/.bin/rollup --version
rollup version 0.35.12
```

See the line marked "side effect":

```
$ cat i2.js 
var V8Engine = (function() {
    function V8Engine() {}
    V8Engine.prototype.toString = function() { return 'V8'; };
    return V8Engine;
}());
var V6Engine = (function() {
    function V6Engine() {}
    V6Engine.prototype = V8Engine.prototype;                   // <-- alias
    V6Engine.prototype.toString = function() { return 'V6'; }; // <-- side effect
    return V6Engine;
}());
console.log(new V8Engine().toString());
```

Expected result:

```
$ node i2.js 
V6
```

Notice that the modified V6Engine IIFE with side effect was incorrectly dropped by `rollup`:

```
$ node_modules/.bin/rollup i2.js && echo
var V8Engine = (function() {
    function V8Engine() {}
    V8Engine.prototype.toString = function() { return 'V8'; };
    return V8Engine;
}());
console.log(new V8Engine().toString());
```

and produces the incorrect result:

```
$ node_modules/.bin/rollup i2.js | node
V8
```

**Comment by Rich-Harris** [comment]
Ah, yeah. I see what's going on here. [This code](https://github.com/rollup/rollup/blob/ad4ca750a59be6a710d322b9a7372dc631907c6a/src/ast/nodes/shared/isUsedByBundle.js), which determines whether the left-hand side of an assignment expression (or argument of an update expression) is used by the bundle, is bad. Regardless of whether the assignment is a true assignment (`foo = x`) or a mutation (`foo.bar = x`), it looks for the root of the expression (`foo`) and determines whether it could be used.

https://github.com/rollup/rollup/commit/94536ca2adfb017d4a74a51fade39d0a0282203a fixes it, but in a bad way – if it's a mutation, we try to figure out what the object being mutated is, and if we can't, assume the worst. That means that `unused.a = b` isn't included, but `Unused.prototype.toString = ...` *is*, incorrectly, because Rollup isn't (yet) smart enough to know what the value of `Unused.prototype` is, or (more relevantly) that it only 'belongs' to `Unused`.

Trying to think about the best way to think about this problem in a way that guarantees correctness but without being unduly conservative about effects. I think some concept of property 'ownership' might be the way forward (i.e. `V6Engine.prototype` could belong to either `V8Engine` or `V6Engine` because of `V6Engine.prototype = V8Engine.prototype`, so any mutations of that object are considered to have effects if *either* `V8Engine` or `V6Engine` is included. Am all ears if anyone is able to think about this more clearly than me...

**Comment by eventualbuddha** [comment]
I'm not sure whether the code you posted is a simplification, but this line strikes me as a bad idea:

```js
V6Engine.prototype = V8Engine.prototype;
```

Because you're simply creating a new reference to `V8Engine.prototype`, the subsequent assignment to `V6Engine.prototype.toString` also sets `V8Engine.prototype.toString`. I can see that you're expecting that behavior in `console.log(new V8Engine().toString())`, but… why?

**Comment by kzc** [comment]
It's valid javascript code that fails in rollup. There is no why.

**Comment by kzc** [comment]
Context: https://github.com/mishoo/UglifyJS2/issues/1261

**Comment by blacksonic** [comment]
Am i right that tree-shaking happens before transpiling with Babel for example? If so it ha a small impact i think.

**Comment by kzc** [comment]
It's much simpler to drop unused code in a higher level language before code generation. But rollup ought to have the ability to sort out side effects of mutated shared objects or at least err on the side of caution.

**Comment by Rich-Harris** [comment]
Yep, totally agree @kzc, it's a bug that needs fixing. I think the concept of 'ownership' is the right way to solve this problem (alternative would be to always err on the side of caution, which would mean including code unnecessarily). It's also a [regression](http://rollupjs.org/?version=0.34.13&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIydmFyJTIwVjhFbmdpbmUlMjAlM0QlMjAoZnVuY3Rpb24oKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBmdW5jdGlvbiUyMFY4RW5naW5lKCklMjAlN0IlN0QlNUNuJTIwJTIwJTIwJTIwVjhFbmdpbmUucHJvdG90eXBlLnRvU3RyaW5nJTIwJTNEJTIwZnVuY3Rpb24oKSUyMCU3QiUyMHJldHVybiUyMCdWOCclM0IlMjAlN0QlM0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwVjhFbmdpbmUlM0IlNUNuJTdEKCkpJTNCJTVDbnZhciUyMFY2RW5naW5lJTIwJTNEJTIwKGZ1bmN0aW9uKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwZnVuY3Rpb24lMjBWNkVuZ2luZSgpJTIwJTdCJTdEJTVDbiUyMCUyMCUyMCUyMFY2RW5naW5lLnByb3RvdHlwZSUyMCUzRCUyMFY4RW5naW5lLnByb3RvdHlwZSUzQiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyRiUyRiUyMCUzQy0tJTIwYWxpYXMlNUNuJTIwJTIwJTIwJTIwVjZFbmdpbmUucHJvdG90eXBlLnRvU3RyaW5nJTIwJTNEJTIwZnVuY3Rpb24oKSUyMCU3QiUyMHJldHVybiUyMCdWNiclM0IlMjAlN0QlM0IlMjAlMkYlMkYlMjAlM0MtLSUyMHNpZGUlMjBlZmZlY3QlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwVjZFbmdpbmUlM0IlNUNuJTdEKCkpJTNCJTVDbmNvbnNvbGUubG9nKG5ldyUyMFY4RW5naW5lKCkudG9TdHJpbmcoKSklM0IlMjIlN0QlNUQlN0Q=) (though on the positive side, that means it's definitely fixable in principle!) Unfortunately I don't have much time to work on open source this week so can't be much more use than that...

@blacksonic it can happen before or after – totally up to the developer. Typically you would transpile before bundling because that's quicker and you can use syntax that isn't real JavaScript (which Acorn, and therefore Rollup, won't parse).

**Comment by kzc** [comment]
Appears to be fixed by PR:

Rework treeshaking algorithm #1582

**Comment by lukastaegert** [comment]
You are indeed right, I just added the above example as a test.
