### ISSUE TITLE
Ignore/exclude some imports when generating dists with Rollup

### ISSUE THREAD

**Issue by Mevrael** [rollup/rollup#987]
Let say I have a library which is exporting some components and functions. Some of those components may be using other components.

Component 1:

```
export ...
```

Component 2:

```
import ... from `Component1`
import part from `component2/part`

export ...
```

What I need is to generate a dist versions could be included into browser from any CDN.

Setting `treeshake: false` allows to generate a dist file containing all the exported code and not an empty file...

but component 2 still includes component 1 and I want to ignore this import but still save imports of subcomponents/parts of component 2 and in result I want to have only 2 files: `component1.min.js` and `component2.min.js`.

Any ideas how it could be possible to ignore some imports on runtime?

**Comment by Victorystick** [comment]
Do you want to build one bundle per component? You'll have to invoke Rollup once per bundle you want to create, and you'll have to flag `Component1` as an external dependency of `Component2` if you don't want it to be included in in bundle. Then you'll manually have to make sure all components have their external dependencies satisfied at runtime; which is why I'm not sure what you mean by "ignore some imports on runtime".
