### ISSUE TITLE
Can rollup log unused dependencies?

### ISSUE THREAD

**Issue by ondras** [rollup/rollup#990]
As my ES6 codebase grows larger, unused (forgotten) dependencies start to occur. Rollup is apparently able to detect (and ignore) those, but it would be really nice to output some information about `import` statements that are apparently useless.

**Comment by tivac** [comment]
ESLint will catch these if you enable `no-unused-vars`.

![image](https://cloud.githubusercontent.com/assets/49545/18862640/f7e7a050-847c-11e6-9543-ab2da541718e.png)

**Comment by ondras** [comment]
Thanks for the info. Was just curious if rollup can dump this info (to stderr) as a part of its building proces.

**Comment by hzlmn** [comment]
Basically, I asked related question #940 . As I understand, there are some differences between DCE and Tree shaking.`rollup` start with nothing and add one by one only live nodes analysing your code. All that said, `rollup` do not touch "dead" code in any way, and i am not sure if its possible to get that unused pieces.

**Comment by ondras** [comment]
Hmm, interesting. But rollup is fully aware of all declared `import` statements, so it shall be able to mark those that are not used.

The issues with eslint's `no-unused-vars` is that it produces a lot of noise (I, for example, declare all my event handlers with the `e` argument, even if I do not access it.), so fishing for unused imports is somewhat tricky and unpleasant.

**Comment by Rich-Harris** [comment]
I'm going to close this, as this really *is* a linter's responsibility – even if Rollup does have the information to hand, it's still extra work that it has to do (and extra tests, and maintenance, etc) that is ultimately duplicating effort. In other situations we've decided against implementing things that are already done by ESLint, for the same reason.

> The issues with eslint's `no-unused-vars` is that it produces a lot of noise (I, for example, declare all my event handlers with the `e` argument, even if I do not access it

This is obviously a matter of taste to some degree, but I'd typically advise against that sort of thing – minifiers won't remove the unused arguments by default (because doing so would change the function arity) meaning extra bytes, and in extreme cases suboptimal mangling. But perhaps there's an ESLint plugin that distinguishes between imports and other types of declarations, or you could use the `no-unused-vars` rule's `argsIgnorePattern` option?

**Comment by ondras** [comment]
> But perhaps there's an ESLint plugin that distinguishes between imports and other types of declarations, or you could use the no-unused-vars rule's argsIgnorePattern option?

I am not aware of any. Manually cherry-picked the relevant lines from `no-unused-vars`. Thanks for your time on this!
