### ISSUE TITLE
Unwanted renaming of imported variable

### ISSUE THREAD

**Issue by grssam** [rollup/rollup#994]
Hi, in the [following example](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwQSUyMCU3RCUyMGZyb20lMjAnLiUyRkEuanMnJTNCJTVDbmltcG9ydCUyMCU3QiUyMEIlMkMlMjBDJTIwJTdEJTIwZnJvbSUyMCcuJTJGaW5kZXguanMnJTNCJTVDbnZhciUyMGElMjAlM0QlMjAlN0JiJTNBJTIwQS5iJTJDJTIwZCUzQSUyMEMlN0QlM0IlNUNuQi5mb29iYXIoYSklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyQi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBpc24ndCUyMHVzZWQlMjBhbnl3aGVyZSUyQyUyMHNvJTVDbiUyRiUyRiUyMFJvbGx1cCUyMGV4Y2x1ZGVzJTIwaXQlMjBmcm9tJTIwdGhlJTIwYnVuZGxlLi4uJTVDbmV4cG9ydCUyMHZhciUyMEIlMjAlM0QlMjAoZnVuY3Rpb24lMjAoKSUyMCU3QiU1Q24lNUN0JTVDbiUyMCUyMHJldHVybiUyMCU3QiU1Q24lMjAlMjAlMjAlMjBmb29iYXIlM0ElMjBmdW5jdGlvbigpJTdCJTdEJTVDbiUyMCUyMCU3RCU1Q24lN0QoKSklM0IlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjBmdW5jdGlvbiUyMGdldHMlMjBpbmNsdWRlZCU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGN1YmUlMjAoJTIweCUyMCklMjAlN0IlNUNuJTVDdCUyRiUyRiUyMHJld3JpdGUlMjB0aGlzJTIwYXMlMjAlNjBzcXVhcmUoJTIweCUyMCklMjAqJTIweCU2MCU1Q24lNUN0JTJGJTJGJTIwYW5kJTIwc2VlJTIwd2hhdCUyMGhhcHBlbnMhJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglMjAqJTIweCUzQiU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyQS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0JCJTdEJTIwZnJvbSUyMCcuJTJGaW5kZXguanMnJTNCJTVDbiU1Q25leHBvcnQlMjB2YXIlMjBBJTIwJTNEJTIwKGZ1bmN0aW9uKCklN0IlNUNuJTIwJTIwcmV0dXJuJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGIlM0ElMjA0MiU1Q24lMjAlMjAlN0QlNUNuJTdEKCkpJTNCJTVDbkIuZm9vYmFyKEEpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmluZGV4LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBmcm9tJTIwJy4lMkZCLmpzJyUzQiU1Q25leHBvcnQlMjAqJTIwZnJvbSUyMCcuJTJGQy5qcyclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyQy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0JCJTdEJTIwZnJvbSUyMCcuJTJGaW5kZXguanMnJTNCJTVDbiU1Q25leHBvcnQlMjB2YXIlMjBDJTIwJTNEJTIwKGZ1bmN0aW9uKCklN0IlNUNuJTIwJTIwcmV0dXJuJTIwRk9PQkFSJTNCJTVDbiU3RCgpKSUzQiU1Q25CLmZvb2JhcihDKSUzQiUyMiU3RCU1RCU3RA==), the import `C` is getting renamed to `C$$1`. Is there any reason behind this? This certainly not seem to collide with any other variable name in the final file.

NOTE: You might have to switch to `ES2015` output bundle type.

**Comment by Rich-Harris** [comment]
The code responsible for avoiding collisions between variable names doesn't take into account this edge case where modules indirectly import themselves, meaning that `C` is being renamed so that it doesn't conflict with... itself.

We could probably prevent that from happening, but since it's not actually causing code to break it's a low priority, so I'll close this. [Reduced test case here](http://rollupjs.org/?version=0.38.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwQSUyMCU3RCUyMGZyb20lMjAnLiUyRmluZGV4LmpzJyUzQiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwJTdCJTIweCUzQSUyMEElMjAlN0QlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyaW5kZXguanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwKiUyMGZyb20lMjAnLiUyRkEuanMnJTNCJTVDbmV4cG9ydCUyMGNvbnN0JTIwZm9vJTIwJTNEJTIwJ3doYXRldmVyJyUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJBLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGZvbyUyMCU3RCUyMGZyb20lMjAnLiUyRmluZGV4LmpzJyUzQiU1Q25leHBvcnQlMjB2YXIlMjBBJTIwJTNEJTIwJTdCJTdEJTNCJTIyJTdEJTVEJTdE) in case we ever need to revisit.
